import {Search,X} from 'lucide-react'
import {type ReactNode} from 'react'
import {TableRowActionMenu} from '../../shared/internal/TableRowActionMenu'
import {useModalA11y} from '../../shared/internal/useModalA11y'

export const PAGE_SIZE=8
export const statusLabel=(value:string)=>value.replaceAll('_',' ').replace(/(^|\s)\S/g,m=>m.toUpperCase())
export const pct=(a:number,b:number)=>b>0?(a/b)*100:0
export function Kpi({label,value,detail,icon}:{label:string;value:string|number;detail:string;icon:ReactNode}){return <article className="marketing-kpi"><span className="marketing-kpi-icon">{icon}</span><div><strong>{value}</strong><span>{label}</span><small>{detail}</small></div></article>}
export function Card({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="marketing-card"><header><h3>{title}</h3><p>{description}</p></header><div className="marketing-card-body">{children}</div></section>}
export function Filters({children}:{children:ReactNode}){return <div className="marketing-filters">{children}</div>}
export function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="marketing-search"><Search size={15}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
export function TableCard({title,description,count,children}:{title:string;description:string;count:number;children:ReactNode}){return <section className="marketing-table-card"><header><div><h3>{title}</h3><p>{description} · {count} registro(s)</p></div></header><div className="marketing-table-wrap">{children}</div></section>}
export function Status({value}:{value:string}){const key=value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('_','-').replaceAll(' ','-').toLowerCase();return <span className={`marketing-status ${key}`}>{statusLabel(value)}</span>}
export function ActionMenu({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){return <TableRowActionMenu label="registro" onView={onView} onEdit={onEdit} onDelete={onDelete}/>}
export function Empty({empty,text}:{empty:boolean;text:string}){return empty?<div className="marketing-empty">{text}</div>:null}
export function Pagination({page,total,onChange}:{page:number;total:number;onChange:(v:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(total<=PAGE_SIZE)return null;return <footer className="marketing-pagination"><span>Página {Math.min(page,pages)} de {pages}</span><div><button type="button" disabled={page<=1} onClick={()=>onChange(page-1)}>Anterior</button><button type="button" disabled={page>=pages} onClick={()=>onChange(page+1)}>Próxima</button></div></footer>}
export function Modal({title,subtitle,onClose,children,size='default'}:{title:string;subtitle:string;onClose:()=>void;children:ReactNode;size?:'default'|'wide'|'campaign'}){const dialogRef=useModalA11y(onClose);return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section ref={dialogRef} tabIndex={-1} className={`marketing-modal${size==='wide'?' marketing-modal-wide':size==='campaign'?' marketing-modal-campaign':''}`} role="dialog" aria-modal="true" aria-labelledby="marketing-modal-title"><header><div><span>Marketing</span><h2 id="marketing-modal-title">{title}</h2><p>{subtitle}</p></div><button type="button" className="marketing-icon-button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header>{children}</section></div>}
export function ModalFooter({onClose,label='Salvar'}:{onClose:()=>void;label?:string}){return <footer className="marketing-modal-footer"><button type="button" className="marketing-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="marketing-primary">{label}</button></footer>}
export function Field({label,value,onChange,type='text',wide=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;wide?:boolean}){return <label className={`marketing-field${wide?' wide':''}`}><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="marketing-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></label>}
export function CheckOptions({options,selected,onChange}:{options:string[];selected:string[];onChange:(v:string[])=>void}){return <div className="marketing-check-grid marketing-check-grid-wide">{options.map(x=><label key={x}><input type="checkbox" checked={selected.includes(x)} onChange={e=>onChange(e.target.checked?[...selected,x]:selected.filter(v=>v!==x))}/>{x}</label>)}</div>}
export function ViewModal({title,onClose,rows}:{title:string;onClose:()=>void;rows:[string,string][]}){return <Modal title={title} subtitle="Detalhes do registro" onClose={onClose}><div className="marketing-modal-body"><div className="marketing-view-grid">{rows.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></div><footer className="marketing-modal-footer"><button type="button" className="marketing-primary" onClick={onClose}>Fechar</button></footer></Modal>}
export const paginate=<T,>(items:T[],page:number)=>items.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)
export const shiftMonth=(value:string,delta:number)=>{const [y,m]=value.split('-').map(Number);const d=new Date(y,m-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
export const monthLabel=(value:string)=>{const [y,m]=value.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}
