import {BarChart3,CalendarDays,CheckCircle2,ChevronLeft,ChevronRight,ClipboardList,FileEdit,Gauge,ListChecks,Megaphone,MoreHorizontal,Plus,Search,Sparkles,Target,TrendingUp,Users,X} from 'lucide-react'
import {useEffect,useMemo,useState,type FormEvent,type ReactNode} from 'react'
import {Navigate,useLocation,useNavigate} from 'react-router-dom'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {compact,dateLabel,money,type BriefingStatus,type CampaignStatus,type ContentStatus,type MarketingBriefing,type MarketingCampaign,type MarketingContent,type MarketingSeed,type MarketingTab,type MarketingTask,type Priority,type TaskStatus} from './domain'
import {marketingRepository} from './repository'
import './marketing.css'

const load=()=>marketingRepository.snapshot()
const PAGE_SIZE=8
const statusLabel=(value:string)=>value.replaceAll('_',' ').replace(/(^|\s)\S/g,m=>m.toUpperCase())
const pct=(a:number,b:number)=>b>0?(a/b)*100:0
const MARKETING_ROUTES:Record<MarketingTab,string>={overview:'/app/marketing',campaigns:'/app/marketing/campanhas',calendar:'/app/marketing/calendario',tasks:'/app/marketing/tarefas',metrics:'/app/marketing/metricas',briefings:'/app/marketing/briefings',ai:'/app/marketing/ia-criativa'}
const tabFromPath=(path:string):MarketingTab|null=>path==='/app/marketing'||path==='/app/marketing/'?'overview':path==='/app/marketing/campanhas'?'campaigns':path==='/app/marketing/calendario'?'calendar':path==='/app/marketing/tarefas'?'tasks':path==='/app/marketing/metricas'?'metrics':path==='/app/marketing/briefings'?'briefings':path==='/app/marketing/ia-criativa'?'ai':null
const withoutMeta=<T extends {id?:string;createdAt?:string;updatedAt?:string}>(value:T)=>{const copy={...value};delete copy.id;delete copy.createdAt;delete copy.updatedAt;return copy as Omit<T,'id'|'createdAt'|'updatedAt'>}

export default function MarketingPage(){
 const location=useLocation(),navigate=useNavigate(),tab=tabFromPath(location.pathname)
 const [state,setState]=useState<MarketingSeed>(load)
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[period,setPeriod]=useState('2026-08'),[platform,setPlatform]=useState('all'),[page,setPage]=useState(1)
 const [campaignEditor,setCampaignEditor]=useState<MarketingCampaign|null|undefined>(undefined),[campaignView,setCampaignView]=useState<MarketingCampaign|null>(null)
 const [contentEditor,setContentEditor]=useState<MarketingContent|null|undefined>(undefined),[taskEditor,setTaskEditor]=useState<MarketingTask|null|undefined>(undefined),[taskView,setTaskView]=useState<MarketingTask|null>(null)
 const [briefingEditor,setBriefingEditor]=useState<MarketingBriefing|null|undefined>(undefined),[briefingView,setBriefingView]=useState<MarketingBriefing|null>(null)
 const refresh=()=>setState(load())
 useEffect(()=>{const fn=()=>refresh();window.addEventListener(marketingRepository.eventName,fn);return()=>window.removeEventListener(marketingRepository.eventName,fn)},[])
 useEffect(()=>{setQuery('');setStatus('all');setPage(1)},[tab])
 if(!tab)return <Navigate to="/app/marketing" replace/>
 const action=tab==='campaigns'?()=>setCampaignEditor(null):tab==='calendar'?()=>setContentEditor(null):tab==='tasks'?()=>setTaskEditor(null):tab==='briefings'?()=>setBriefingEditor(null):undefined
 const actionLabel=tab==='campaigns'?'Nova Campanha':tab==='calendar'?'Novo Conteúdo':tab==='tasks'?'Nova Tarefa':tab==='briefings'?'Novo Briefing':''
 const go=(next:MarketingTab)=>navigate(MARKETING_ROUTES[next])
 return <AdminShell area="marketing" items={CRM_WORKSPACE_NAV} header={{title:headerTitle(tab),description:headerDescription(tab)}} headerActions={action?[{label:actionLabel,icon:Plus,onClick:action}]:[]}>
  <section className="marketing-page">
   {tab==='overview'&&<Overview state={state} onNavigate={go}/>} 
   {tab==='campaigns'&&<Campaigns state={state} query={query} setQuery={setQuery} status={status} setStatus={setStatus} page={page} setPage={setPage} onView={setCampaignView} onEdit={setCampaignEditor}/>} 
   {tab==='calendar'&&<Calendar state={state} query={query} setQuery={setQuery} status={status} setStatus={setStatus} period={period} setPeriod={setPeriod} onEdit={setContentEditor}/>} 
   {tab==='tasks'&&<Tasks state={state} query={query} setQuery={setQuery} status={status} setStatus={setStatus} page={page} setPage={setPage} onView={setTaskView} onEdit={setTaskEditor}/>} 
   {tab==='metrics'&&<Metrics state={state} platform={platform} setPlatform={setPlatform} period={period} setPeriod={setPeriod}/>} 
   {tab==='briefings'&&<Briefings state={state} query={query} setQuery={setQuery} status={status} setStatus={setStatus} page={page} setPage={setPage} onView={setBriefingView} onEdit={setBriefingEditor}/>} 
   {tab==='ai'&&<AiCreative state={state}/>} 
  </section>
  {campaignEditor!==undefined&&<CampaignModal state={state} value={campaignEditor} onClose={()=>setCampaignEditor(undefined)}/>} 
  {campaignView&&<ViewModal title={campaignView.name} onClose={()=>setCampaignView(null)} rows={[['Contexto',campaignView.context],['Plataformas',campaignView.platforms.join(', ')],['Status',statusLabel(campaignView.status)],['Budget',money(campaignView.budget)],['Gasto',money(campaignView.spend)],['Cliques',compact(campaignView.clicks)],['Impressões',compact(campaignView.impressions)],['Conversões',compact(campaignView.conversions)],['Período',`${dateLabel(campaignView.startDate)} — ${dateLabel(campaignView.endDate)}`],['Responsável',campaignView.owner],['Observações',campaignView.notes||'—']]}/>} 
  {contentEditor!==undefined&&<ContentModal state={state} value={contentEditor} onClose={()=>setContentEditor(undefined)}/>} 
  {taskEditor!==undefined&&<TaskModal state={state} value={taskEditor} onClose={()=>setTaskEditor(undefined)}/>} 
  {taskView&&<ViewModal title={taskView.title} onClose={()=>setTaskView(null)} rows={[['Tipo',taskView.type],['Responsável',taskView.owner],['Setor',taskView.department],['Prazo',dateLabel(taskView.deadline)],['Status',statusLabel(taskView.status)],['Prioridade',statusLabel(taskView.priority)],['Contexto',taskView.context],['Classificação',taskView.classification],['Observações',taskView.notes||'—']]}/>} 
  {briefingEditor!==undefined&&<BriefingModal state={state} value={briefingEditor} onClose={()=>setBriefingEditor(undefined)}/>} 
  {briefingView&&<ViewModal title={briefingView.title} onClose={()=>setBriefingView(null)} rows={[['Tipo',briefingView.type],['Objetivo estratégico',briefingView.objective],['Contexto e necessidades',briefingView.context],['Público-alvo e personas',briefingView.audience],['Posicionamento',briefingView.positioning],['Tom de voz',briefingView.tone],['Responsáveis',briefingView.owners.join(', ')],['Prazo',dateLabel(briefingView.deadline)],['Canais',briefingView.channels.join(', ')],['Entregáveis',briefingView.deliverables.join(', ')],['Status',statusLabel(briefingView.status)],['Referências',briefingView.references||'—']]}/>} 
 </AdminShell>
}

function Overview({state,onNavigate}:{state:MarketingSeed;onNavigate:(v:MarketingTab)=>void}){const active=state.campaigns.filter(x=>x.status==='ativa').length,scheduled=state.contents.filter(x=>x.status==='agendado').length,pending=state.tasks.filter(x=>x.status!=='concluida').length,approvals=state.contents.filter(x=>x.approval==='pendente').length,published=state.contents.filter(x=>x.status==='publicado').length,deliveries=state.contents.filter(x=>x.publishDate>='2026-08-30').length,done=state.tasks.filter(x=>x.status==='concluida').length,performance=Math.round(pct(done,state.tasks.length));return <>
 <div className="marketing-kpis marketing-kpis-4"><Kpi label="Campanhas ativas" value={active} detail="em execução" icon={<Megaphone/>}/><Kpi label="Conteúdos programados" value={scheduled} detail="aguardando publicação" icon={<CalendarDays/>}/><Kpi label="Tarefas pendentes" value={pending} detail="demandas abertas" icon={<ListChecks/>}/><Kpi label="Aprovações pendentes" value={approvals} detail="conteúdos em revisão" icon={<CheckCircle2/>}/><Kpi label="Conteúdos publicados" value={published} detail="no período" icon={<FileEdit/>}/><Kpi label="Entregas próximas" value={deliveries} detail="próximos conteúdos" icon={<Target/>}/><Kpi label="Briefings abertos" value={state.briefings.filter(x=>x.status!=='arquivado').length} detail="estratégias ativas" icon={<ClipboardList/>}/><Kpi label="Performance do setor" value={`${performance}%`} detail="tarefas concluídas" icon={<Gauge/>}/></div>
 <div className="marketing-overview-grid"><Card title="Entregas próximas" description="Conteúdos a publicar"><div className="marketing-stack">{state.contents.filter(x=>x.status==='agendado'||x.status==='producao'||x.status==='revisao').slice(0,5).map(x=><div className="marketing-list-row" key={x.id}><div><strong>{x.title}</strong><small>{x.channels.join(' + ')} · {dateLabel(x.publishDate)} {x.publishTime}</small></div><Status value={x.status}/></div>)}</div></Card><Card title="Aprovações pendentes" description="Conteúdos aguardando aprovação"><div className="marketing-stack">{state.contents.filter(x=>x.approval==='pendente').map(x=><div className="marketing-list-row" key={x.id}><div><strong>{x.title}</strong><small>{x.owner}</small></div><Status value={x.approval}/></div>)}</div></Card><Card title="Atalhos rápidos" description="Ações operacionais"><div className="marketing-quick"><button type="button" onClick={()=>onNavigate('campaigns')}>Nova Campanha</button><button type="button" onClick={()=>onNavigate('calendar')}>Novo Conteúdo</button><button type="button" onClick={()=>onNavigate('tasks')}>Nova Tarefa</button><button type="button" onClick={()=>onNavigate('ai')}>IA Criativa</button></div></Card><Card title="Atividades recentes" description="Últimas movimentações"><div className="marketing-stack">{state.activities.map(x=><div className="marketing-activity" key={x.id}><strong>{x.label}</strong><span>{x.detail}</span></div>)}</div></Card></div>
 </>}

function Campaigns({state,query,setQuery,status,setStatus,page,setPage,onView,onEdit}:{state:MarketingSeed;query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;page:number;setPage:(v:number)=>void;onView:(v:MarketingCampaign)=>void;onEdit:(v:MarketingCampaign)=>void}){const rows=useMemo(()=>state.campaigns.filter(x=>(!query||`${x.name} ${x.description} ${x.context}`.toLowerCase().includes(query.toLowerCase()))&&(status==='all'||x.status===status)),[state.campaigns,query,status]),active=state.campaigns.filter(x=>x.status==='ativa'),budget=state.campaigns.reduce((s,x)=>s+x.budget,0),spend=state.campaigns.reduce((s,x)=>s+x.spend,0),clicks=state.campaigns.reduce((s,x)=>s+x.clicks,0),impressions=state.campaigns.reduce((s,x)=>s+x.impressions,0),paged=paginate(rows,page);return <>
 <div className="marketing-kpis marketing-kpis-5"><Kpi label="Campanhas Ativas" value={active.length} detail="em execução" icon={<Target/>}/><Kpi label="Budget Total" value={money(budget)} detail="investimento" icon={<Megaphone/>}/><Kpi label="Gasto Total" value={money(spend)} detail="executado" icon={<TrendingUp/>}/><Kpi label="Cliques" value={compact(clicks)} detail="total" icon={<Users/>}/><Kpi label="CTR Médio" value={`${pct(clicks,impressions).toFixed(1)}%`} detail="taxa de clique" icon={<BarChart3/>}/></div>
 <Filters><SearchBox value={query} onChange={v=>{setQuery(v);setPage(1)}} placeholder="Buscar por nome ou descrição..."/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todos os status</option>{['rascunho','agendada','ativa','pausada','concluida','cancelada'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></Filters>
 <TableCard title="Lista de Campanhas" description="Acompanhe campanhas, plataformas, investimento, status e performance" count={rows.length}><table className="marketing-table marketing-campaign-table"><thead><tr><th>Nome</th><th>Contexto</th><th>Plataforma</th><th>Status</th><th className="numeric">Budget</th><th className="numeric">Gasto</th><th className="numeric">Cliques</th><th className="actions">Ações</th></tr></thead><tbody>{paged.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.description}</small></td><td>{x.context}</td><td>{x.platforms.join(', ')}</td><td><Status value={x.status}/></td><td className="numeric">{money(x.budget)}</td><td className="numeric">{money(x.spend)}</td><td className="numeric">{compact(x.clicks)}</td><td className="actions"><ActionMenu onView={()=>onView(x)} onEdit={()=>onEdit(x)} onDelete={()=>marketingRepository.deleteCampaign(x.id)}/></td></tr>)}</tbody></table><Empty empty={!rows.length} text="Nenhuma campanha encontrada."/><Pagination page={page} total={rows.length} onChange={setPage}/></TableCard>
 </>}

function Calendar({state,query,setQuery,status,setStatus,period,setPeriod,onEdit}:{state:MarketingSeed;query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;period:string;setPeriod:(v:string)=>void;onEdit:(v:MarketingContent)=>void}){const rows=state.contents.filter(x=>(!query||`${x.title} ${x.artist} ${x.channels.join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(status==='all'||x.status===status)&&(!period||x.publishDate.startsWith(period))),scheduled=state.contents.filter(x=>x.status==='agendado').length,published=state.contents.filter(x=>x.status==='publicado').length,upcoming=state.contents.filter(x=>x.publishDate>='2026-08-30'&&x.publishDate<='2026-09-06').length;return <>
 <div className="marketing-kpis marketing-kpis-4"><Kpi label="Conteúdos" value={state.contents.length} detail="no total" icon={<CalendarDays/>}/><Kpi label="Agendados" value={scheduled} detail="aguardando publicação" icon={<CalendarDays/>}/><Kpi label="Publicados" value={published} detail="conteúdos publicados" icon={<CheckCircle2/>}/><Kpi label="Próximos 7 dias" value={upcoming} detail="na próxima semana" icon={<Target/>}/></div>
 <div className="marketing-period"><button type="button" onClick={()=>setPeriod(shiftMonth(period,-1))} aria-label="Mês anterior"><ChevronLeft size={15}/></button><input type="month" value={period} onChange={e=>setPeriod(e.target.value)} aria-label="Período do calendário"/><button type="button" onClick={()=>setPeriod(shiftMonth(period,1))} aria-label="Próximo mês"><ChevronRight size={15}/></button></div>
 <Filters><SearchBox value={query} onChange={setQuery} placeholder="Buscar conteúdo..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os status</option>{['ideia','producao','revisao','agendado','publicado','falhou','atrasado'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></Filters>
 <div className="marketing-calendar-grid">{rows.map(x=><article className="marketing-calendar-card" key={x.id}><div className="marketing-calendar-date"><strong>{new Date(`${x.publishDate}T12:00:00`).getDate()}</strong><span>{new Date(`${x.publishDate}T12:00:00`).toLocaleDateString('pt-BR',{month:'short'})}</span></div><div className="marketing-calendar-main"><div className="marketing-card-top"><div><strong>{x.title}</strong><small>{x.artist||x.context} · {x.publishTime}</small></div><ActionMenu onView={()=>onEdit(x)} onEdit={()=>onEdit(x)} onDelete={()=>marketingRepository.deleteContent(x.id)}/></div><p>{x.copy}</p><div className="marketing-tags">{x.channels.map(c=><span key={c}>{c}</span>)}<Status value={x.status}/><Status value={x.approval}/></div></div></article>)}</div><Empty empty={!rows.length} text="Nenhum conteúdo encontrado para o período."/>
 </>}

function Tasks({state,query,setQuery,status,setStatus,page,setPage,onView,onEdit}:{state:MarketingSeed;query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;page:number;setPage:(v:number)=>void;onView:(v:MarketingTask)=>void;onEdit:(v:MarketingTask)=>void}){const rows=state.tasks.filter(x=>(!query||`${x.title} ${x.type} ${x.owner} ${x.context}`.toLowerCase().includes(query.toLowerCase()))&&(status==='all'||x.status===status)),paged=paginate(rows,page);return <>
 <div className="marketing-kpis marketing-kpis-5"><Kpi label="Total de Tarefas" value={state.tasks.length} detail="demandas cadastradas" icon={<ListChecks/>}/><Kpi label="Concluídas" value={state.tasks.filter(x=>x.status==='concluida').length} detail="finalizadas" icon={<CheckCircle2/>}/><Kpi label="A Fazer" value={state.tasks.filter(x=>x.status==='a_fazer'||x.status==='backlog').length} detail="backlog e a fazer" icon={<CalendarDays/>}/><Kpi label="Em Andamento" value={state.tasks.filter(x=>x.status==='em_andamento').length} detail="em execução" icon={<MoreHorizontal/>}/><Kpi label="Revisão" value={state.tasks.filter(x=>x.status==='revisao').length} detail="em revisão" icon={<FileEdit/>}/></div>
 <Filters><SearchBox value={query} onChange={v=>{setQuery(v);setPage(1)}} placeholder="Buscar tarefa..."/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todos os status</option>{['backlog','a_fazer','em_andamento','revisao','concluida','bloqueada'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></Filters>
 <TableCard title="Lista de Tarefas" description="Acompanhe tarefas, tipos, responsáveis, prazos e status" count={rows.length}><table className="marketing-table"><thead><tr><th>Tarefa</th><th>Tipo</th><th>Responsável</th><th>Prazo</th><th>Prioridade</th><th>Status</th><th className="actions">Ações</th></tr></thead><tbody>{paged.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.context}</small></td><td>{x.type}</td><td>{x.owner}</td><td>{dateLabel(x.deadline)}</td><td><Status value={x.priority}/></td><td><Status value={x.status}/></td><td className="actions"><ActionMenu onView={()=>onView(x)} onEdit={()=>onEdit(x)} onDelete={()=>marketingRepository.deleteTask(x.id)}/></td></tr>)}</tbody></table><Empty empty={!rows.length} text="Nenhuma tarefa encontrada."/><Pagination page={page} total={rows.length} onChange={setPage}/></TableCard>
 </>}

function Metrics({state,platform,setPlatform,period,setPeriod}:{state:MarketingSeed;platform:string;setPlatform:(v:string)=>void;period:string;setPeriod:(v:string)=>void}){const rows=state.metrics.filter(x=>(platform==='all'||x.platform===platform)&&(!period||x.period===period)),base=platform==='all'?state.metrics.filter(x=>!period||x.period===period):rows,total=base.reduce((a,x)=>({reach:a.reach+x.reach,impressions:a.impressions+x.impressions,clicks:a.clicks+x.clicks,engagement:a.engagement+x.engagement,followers:a.followers+x.followers,conversions:a.conversions+x.conversions,spend:a.spend+x.spend,revenue:a.revenue+x.revenue}),{reach:0,impressions:0,clicks:0,engagement:0,followers:0,conversions:0,spend:0,revenue:0});return <>
 <Filters><select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">Visão consolidada</option>{state.metrics.map(x=>x.platform).filter((v,i,a)=>a.indexOf(v)===i).map(x=><option key={x}>{x}</option>)}</select><input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></Filters>
 <div className="marketing-kpis marketing-kpis-4"><Kpi label="Alcance" value={compact(total.reach)} detail="pessoas alcançadas" icon={<Users/>}/><Kpi label="Impressões" value={compact(total.impressions)} detail="exibições" icon={<BarChart3/>}/><Kpi label="Cliques" value={compact(total.clicks)} detail={`CTR ${pct(total.clicks,total.impressions).toFixed(2)}%`} icon={<Target/>}/><Kpi label="Conversões" value={compact(total.conversions)} detail="ações atribuídas" icon={<CheckCircle2/>}/><Kpi label="Engajamento" value={compact(total.engagement)} detail="interações" icon={<TrendingUp/>}/><Kpi label="Investimento" value={money(total.spend)} detail="mídia paga" icon={<Megaphone/>}/><Kpi label="Receita atribuída" value={money(total.revenue)} detail="conversões" icon={<Gauge/>}/><Kpi label="ROAS" value={total.spend?`${(total.revenue/total.spend).toFixed(2)}x`:'—'} detail="retorno sobre mídia" icon={<TrendingUp/>}/></div>
 <div className="marketing-analytics-grid"><Card title="Evolução consolidada" description="Performance agregada das plataformas monitoradas"><div className="marketing-bars">{base.map(x=><div key={x.id}><span>{x.platform}</span><div><i style={{width:`${Math.min(100,pct(x.impressions,Math.max(...base.map(y=>y.impressions),1)))}%`}}/></div><strong>{compact(x.impressions)}</strong></div>)}</div></Card><Card title="Resumo consolidado" description="Leitura rápida dos principais indicadores"><div className="marketing-summary"><p><span>CPC médio</span><strong>{total.clicks?money(total.spend/total.clicks):'—'}</strong></p><p><span>CPA médio</span><strong>{total.conversions?money(total.spend/total.conversions):'—'}</strong></p><p><span>Taxa de conversão</span><strong>{pct(total.conversions,total.clicks).toFixed(2)}%</strong></p><p><span>Retorno</span><strong>{money(total.revenue-total.spend)}</strong></p></div></Card></div>
 <TableCard title="Top Plataformas" description="Ranking de performance por plataforma" count={base.length}><table className="marketing-table"><thead><tr><th>Plataforma</th><th className="numeric">Alcance</th><th className="numeric">Impressões</th><th className="numeric">Cliques</th><th className="numeric">Conversões</th><th className="numeric">Investimento</th><th className="numeric">Receita</th><th className="numeric">ROAS</th></tr></thead><tbody>{base.map(x=><tr key={x.id}><td><strong>{x.platform}</strong></td><td className="numeric">{compact(x.reach)}</td><td className="numeric">{compact(x.impressions)}</td><td className="numeric">{compact(x.clicks)}</td><td className="numeric">{compact(x.conversions)}</td><td className="numeric">{money(x.spend)}</td><td className="numeric">{money(x.revenue)}</td><td className="numeric">{x.spend?(x.revenue/x.spend).toFixed(2):'—'}x</td></tr>)}</tbody></table><Empty empty={!base.length} text="Nenhuma métrica encontrada para o período."/></TableCard>
 </>}

function Briefings({state,query,setQuery,status,setStatus,page,setPage,onView,onEdit}:{state:MarketingSeed;query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;page:number;setPage:(v:number)=>void;onView:(v:MarketingBriefing)=>void;onEdit:(v:MarketingBriefing)=>void}){const rows=state.briefings.filter(x=>(!query||`${x.title} ${x.type} ${x.objective}`.toLowerCase().includes(query.toLowerCase()))&&(status==='all'||x.status===status)),paged=paginate(rows,page);return <>
 <div className="marketing-kpis marketing-kpis-4"><Kpi label="Briefings abertos" value={state.briefings.filter(x=>x.status!=='arquivado').length} detail="em acompanhamento" icon={<ClipboardList/>}/><Kpi label="Em revisão" value={state.briefings.filter(x=>x.status==='em_revisao').length} detail="aguardando validação" icon={<FileEdit/>}/><Kpi label="Aprovados" value={state.briefings.filter(x=>x.status==='aprovado').length} detail="prontos para execução" icon={<Target/>}/><Kpi label="Entregáveis planejados" value={state.briefings.reduce((s,x)=>s+x.deliverables.length,0)} detail="itens previstos" icon={<CheckCircle2/>}/></div>
 <Filters><SearchBox value={query} onChange={v=>{setQuery(v);setPage(1)}} placeholder="Buscar briefing..."/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todos os status</option>{['rascunho','em_revisao','aprovado','arquivado'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></Filters>
 <TableCard title="Lista de Briefings" description="Acompanhe briefings, tipos, objetivos, responsáveis e status" count={rows.length}><table className="marketing-table"><thead><tr><th>Briefing</th><th>Tipo</th><th>Responsáveis</th><th>Prazo</th><th>Entregáveis</th><th>Status</th><th className="actions">Ações</th></tr></thead><tbody>{paged.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>{x.objective}</small></td><td>{x.type}</td><td>{x.owners.join(', ')}</td><td>{dateLabel(x.deadline)}</td><td>{x.deliverables.length}</td><td><Status value={x.status}/></td><td className="actions"><ActionMenu onView={()=>onView(x)} onEdit={()=>onEdit(x)} onDelete={()=>marketingRepository.deleteBriefing(x.id)}/></td></tr>)}</tbody></table><Empty empty={!rows.length} text="Nenhum briefing encontrado."/><Pagination page={page} total={rows.length} onChange={setPage}/></TableCard>
 </>}

function AiCreative({state}:{state:MarketingSeed}){const [aiTab,setAiTab]=useState('ideas'),[objective,setObjective]=useState('Aumentar alcance e conversão do próximo lançamento'),[target,setTarget]=useState(state.campaigns[0]?.name??''),[result,setResult]=useState(''),[aiState,setAiState]=useState<'idle'|'loading'|'success'|'error'>('idle'),[error,setError]=useState('');const generate=()=>{if(!target||!objective.trim()){setError('Selecione um contexto e informe o objetivo antes de gerar.');setAiState('error');return}setError('');setAiState('loading');window.setTimeout(()=>{const text=aiTab==='pitching'?`Pitching sugerido para ${target}: narrativa clara, contexto artístico, diferenciais da faixa e evidências de audiência. Preparar versões para DSPs, imprensa e curadores independentes.`:aiTab==='trends'?`Tendências compatíveis com ${target}: vídeo vertical com narrativa curta, bastidores, prova social, conteúdo serializado e reaproveitamento dos melhores hooks entre plataformas.`:aiTab==='planning'?`Planejamento para ${target}: semana 1 aquecimento, semana 2 prova social e pré-save, semana 3 lançamento com mídia paga e creators, semana 4 sustentação com recortes de melhor retenção.`:`Ideias para ${target}: teaser de 8s, carrossel de história, bastidor de estúdio, desafio de refrão, vídeo reação, CTA de pre-save e versão acústica curta.`;setResult(text);marketingRepository.addAiHistory({kind:statusLabel(aiTab),title:`${statusLabel(aiTab)} — ${target}`,context:objective,result:text});setAiState('success')},250)};return <>
 <div className="marketing-ai-tabs" role="tablist" aria-label="Ferramentas da IA Criativa">{[['ideas','Ideias'],['planning','Planejamento'],['pitching','Pitching'],['trends','Tendências'],['analytics','Analytics'],['history','Histórico']].map(([id,label])=><button type="button" key={id} className={aiTab===id?'active':''} onClick={()=>{setAiTab(id);setError('');setAiState('idle')}} role="tab" aria-selected={aiTab===id}>{label}</button>)}</div>
 {aiTab==='history'?<Card title="Histórico da IA" description="Gerações salvas no módulo">{state.aiHistory.length?<div className="marketing-stack">{state.aiHistory.map(x=><div className="marketing-ai-history" key={x.id}><div><strong>{x.title}</strong><small>{new Date(x.createdAt).toLocaleString('pt-BR')} · {x.kind}</small></div><p>{x.result}</p></div>)}</div>:<Empty empty text="Nenhuma geração salva no histórico."/>}</Card>:aiTab==='analytics'?<div className="marketing-analytics-grid"><Card title="Diagnóstico de performance" description="Leitura consolidada do marketing"><div className="marketing-summary"><p><span>Melhores campanhas</span><strong>{[...state.campaigns].sort((a,b)=>b.clicks-a.clicks).slice(0,2).map(x=>x.name).join(' · ')||'Sem dados'}</strong></p><p><span>Melhores canais</span><strong>{[...state.metrics].sort((a,b)=>b.reach-a.reach).slice(0,2).map(x=>x.platform).join(' · ')||'Sem dados'}</strong></p><p><span>Direção sugerida</span><strong>Repetir formatos com maior retenção e CTA claro.</strong></p></div></Card><Card title="Próximas ações" description="Recomendações operacionais"><ul className="marketing-bullets"><li>Reaproveitar os melhores hooks em múltiplos canais.</li><li>Concentrar verba nos conjuntos com melhor conversão.</li><li>Transformar insights em tarefas com prazo e responsável.</li></ul></Card></div>:<div className="marketing-ai-workspace"><Card title="Music Intelligence Engine" description="Criação, planejamento, pitching e tendências"><div className="marketing-ai-form"><label><span>Contexto / campanha</span><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Selecione uma campanha</option>{state.campaigns.map(x=><option key={x.id}>{x.name}</option>)}</select></label><label><span>Objetivo</span><textarea value={objective} onChange={e=>setObjective(e.target.value)}/></label>{error&&<p className="marketing-form-error" role="alert">{error}</p>}<button type="button" className="marketing-primary" onClick={generate} disabled={aiState==='loading'}>{aiState==='loading'?'Gerando...':'Gerar análise'}</button></div></Card><Card title="Resultado" description="Saída simulada para validação operacional"><div className={`marketing-ai-result ${aiState}`}>{aiState==='loading'?'Processando contexto, dados de campanha e objetivo...':result||'Preencha o contexto e gere uma análise para visualizar o resultado.'}</div></Card></div>}
 </>}

function CampaignModal({state,value,onClose}:{state:MarketingSeed;value:MarketingCampaign|null;onClose:()=>void}){const [form,setForm]=useState(value?{...value}:{name:'',description:'',context:'',platforms:['Meta Ads'],status:'rascunho' as CampaignStatus,budget:0,spend:0,clicks:0,impressions:0,conversions:0,startDate:'',endDate:'',owner:state.owners[0]??'',notes:''}),[error,setError]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();if(!form.name.trim()){setError('Informe o nome da campanha.');return}if(!form.startDate||!form.endDate){setError('Informe o período completo da campanha.');return}if(form.endDate<form.startDate){setError('A data final não pode ser anterior à data inicial.');return}if(!form.platforms.length){setError('Selecione pelo menos uma plataforma.');return}marketingRepository.saveCampaign(withoutMeta(form as MarketingCampaign),value?.id);onClose()};return <Modal title={value?'Editar Campanha':'Nova Campanha'} subtitle="Planeje campanha, plataformas, investimento e período" onClose={onClose}><form onSubmit={submit} noValidate><div className="marketing-modal-body"><div className="marketing-form-grid"><Field label="Nome *" value={form.name} onChange={v=>{setForm({...form,name:v});setError('')}}/><Field label="Contexto" value={form.context} onChange={v=>setForm({...form,context:v})}/><Field label="Descrição" value={form.description} onChange={v=>setForm({...form,description:v})} wide/><SelectField label="Status" value={form.status} onChange={v=>setForm({...form,status:v as CampaignStatus})} options={['rascunho','agendada','ativa','pausada','concluida','cancelada']}/><SelectField label="Responsável" value={form.owner} onChange={v=>setForm({...form,owner:v})} options={state.owners}/><Field label="Budget" type="number" value={String(form.budget)} onChange={v=>setForm({...form,budget:Math.max(0,Number(v))})}/><Field label="Gasto" type="number" value={String(form.spend)} onChange={v=>setForm({...form,spend:Math.max(0,Number(v))})}/><Field label="Início *" type="date" value={form.startDate} onChange={v=>{setForm({...form,startDate:v});setError('')}}/><Field label="Fim *" type="date" value={form.endDate} onChange={v=>{setForm({...form,endDate:v});setError('')}}/><label className="marketing-field wide"><span>Plataformas</span><div className="marketing-check-grid">{state.platforms.map(p=><label key={p}><input type="checkbox" checked={form.platforms.includes(p)} onChange={e=>{setForm({...form,platforms:e.target.checked?[...form.platforms,p]:form.platforms.filter(x=>x!==p)});setError('')}}/>{p}</label>)}</div></label><Field label="Observações" value={form.notes} onChange={v=>setForm({...form,notes:v})} wide/></div>{error&&<p className="marketing-form-error" role="alert">{error}</p>}</div><ModalFooter onClose={onClose}/></form></Modal>}

function ContentModal({state,value,onClose}:{state:MarketingSeed;value:MarketingContent|null;onClose:()=>void}){const [form,setForm]=useState(value?{...value}:{title:'',context:'',artist:'',channels:['Instagram'],type:state.contentTypes[0]??'Post',publishDate:'',publishTime:'12:00',copy:'',campaign:'',hashtags:'',location:'',status:'ideia' as ContentStatus,approval:'pendente' as const,owner:state.owners[0]??''}),[error,setError]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();if(!form.title.trim()){setError('Informe o título do conteúdo.');return}if(!form.publishDate||!form.publishTime){setError('Informe data e horário de publicação.');return}if(!form.channels.length){setError('Selecione pelo menos uma plataforma.');return}marketingRepository.saveContent(withoutMeta(form as MarketingContent),value?.id);onClose()};return <Modal title={value?'Editar Conteúdo':'Novo Conteúdo'} subtitle="Programação de conteúdo multiplataforma" onClose={onClose}><form onSubmit={submit} noValidate><div className="marketing-modal-body"><div className="marketing-form-grid"><Field label="Título *" value={form.title} onChange={v=>{setForm({...form,title:v});setError('')}}/><Field label="Contexto" value={form.context} onChange={v=>setForm({...form,context:v})}/><Field label="Artista" value={form.artist} onChange={v=>setForm({...form,artist:v})}/><SelectField label="Tipo de conteúdo" value={form.type} onChange={v=>setForm({...form,type:v})} options={state.contentTypes}/><Field label="Data *" type="date" value={form.publishDate} onChange={v=>{setForm({...form,publishDate:v});setError('')}}/><Field label="Hora *" type="time" value={form.publishTime} onChange={v=>{setForm({...form,publishTime:v});setError('')}}/><SelectField label="Status" value={form.status} onChange={v=>setForm({...form,status:v as ContentStatus})} options={['ideia','producao','revisao','agendado','publicado','falhou','atrasado']}/><SelectField label="Responsável" value={form.owner} onChange={v=>setForm({...form,owner:v})} options={state.owners}/><Field label="Campanha relacionada" value={form.campaign} onChange={v=>setForm({...form,campaign:v})}/><Field label="Localização" value={form.location} onChange={v=>setForm({...form,location:v})}/><Field label="Hashtags" value={form.hashtags} onChange={v=>setForm({...form,hashtags:v})} wide/><label className="marketing-field wide"><span>Plataformas</span><div className="marketing-check-grid">{state.platforms.slice(0,4).map(p=><label key={p}><input type="checkbox" checked={form.channels.includes(p)} onChange={e=>{setForm({...form,channels:e.target.checked?[...form.channels,p]:form.channels.filter(x=>x!==p)});setError('')}}/>{p}</label>)}</div></label><label className="marketing-field wide"><span>Legenda / Copy</span><textarea value={form.copy} onChange={e=>setForm({...form,copy:e.target.value})}/></label></div>{error&&<p className="marketing-form-error" role="alert">{error}</p>}</div><ModalFooter onClose={onClose}/></form></Modal>}

function TaskModal({state,value,onClose}:{state:MarketingSeed;value:MarketingTask|null;onClose:()=>void}){const [form,setForm]=useState(value?{...value}:{title:'',type:state.taskTypes[0]??'Design',owner:state.owners[0]??'',department:state.departments[0]??'Marketing',deadline:'',status:'a_fazer' as TaskStatus,priority:'media' as Priority,context:'',classification:'',notes:''}),[error,setError]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();if(!form.title.trim()){setError('Informe o título da tarefa.');return}if(!form.deadline){setError('Informe o prazo da tarefa.');return}marketingRepository.saveTask(withoutMeta(form as MarketingTask),value?.id);onClose()};return <Modal title={value?'Editar Tarefa':'Nova Tarefa'} subtitle="Núcleo operacional de tarefas" onClose={onClose}><form onSubmit={submit} noValidate><div className="marketing-modal-body"><div className="marketing-form-grid"><Field label="Tarefa *" value={form.title} onChange={v=>{setForm({...form,title:v});setError('')}}/><SelectField label="Tipo" value={form.type} onChange={v=>setForm({...form,type:v})} options={state.taskTypes}/><SelectField label="Responsável" value={form.owner} onChange={v=>setForm({...form,owner:v})} options={state.owners}/><SelectField label="Setor" value={form.department} onChange={v=>setForm({...form,department:v})} options={state.departments}/><Field label="Prazo *" type="date" value={form.deadline} onChange={v=>{setForm({...form,deadline:v});setError('')}}/><SelectField label="Status" value={form.status} onChange={v=>setForm({...form,status:v as TaskStatus})} options={['backlog','a_fazer','em_andamento','revisao','concluida','bloqueada']}/><SelectField label="Prioridade" value={form.priority} onChange={v=>setForm({...form,priority:v as Priority})} options={['baixa','media','alta','urgente']}/><Field label="Contexto" value={form.context} onChange={v=>setForm({...form,context:v})}/><Field label="Classificação" value={form.classification} onChange={v=>setForm({...form,classification:v})}/><Field label="Observações" value={form.notes} onChange={v=>setForm({...form,notes:v})} wide/></div>{error&&<p className="marketing-form-error" role="alert">{error}</p>}</div><ModalFooter onClose={onClose}/></form></Modal>}

function BriefingModal({state,value,onClose}:{state:MarketingSeed;value:MarketingBriefing|null;onClose:()=>void}){const [form,setForm]=useState(value?{...value}:{title:'',type:state.briefingTypes[0]??'Campanha',objective:'',context:'',audience:'',positioning:'',tone:'',owners:[state.owners[0]??''],deadline:'',deliverables:[] as string[],channels:[] as string[],status:'rascunho' as BriefingStatus,references:''}),[error,setError]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();if(!form.title.trim()){setError('Informe o título do briefing.');return}if(!form.objective.trim()){setError('Informe o objetivo estratégico.');return}if(!form.owners.length){setError('Informe pelo menos um responsável.');return}marketingRepository.saveBriefing(withoutMeta(form as MarketingBriefing),value?.id);onClose()};return <Modal title={value?'Editar Briefing':'Novo Briefing'} subtitle="Origem estratégica dos projetos" onClose={onClose}><form onSubmit={submit} noValidate><div className="marketing-modal-body"><div className="marketing-form-grid"><Field label="Título *" value={form.title} onChange={v=>{setForm({...form,title:v});setError('')}}/><SelectField label="Tipo" value={form.type} onChange={v=>setForm({...form,type:v})} options={state.briefingTypes}/><Field label="Objetivo estratégico *" value={form.objective} onChange={v=>{setForm({...form,objective:v});setError('')}} wide/><Field label="Contexto e necessidades" value={form.context} onChange={v=>setForm({...form,context:v})} wide/><Field label="Público-alvo e personas" value={form.audience} onChange={v=>setForm({...form,audience:v})} wide/><Field label="Posicionamento" value={form.positioning} onChange={v=>setForm({...form,positioning:v})}/><Field label="Tom de voz" value={form.tone} onChange={v=>setForm({...form,tone:v})}/><Field label="Prazo" type="date" value={form.deadline} onChange={v=>setForm({...form,deadline:v})}/><SelectField label="Status" value={form.status} onChange={v=>setForm({...form,status:v as BriefingStatus})} options={['rascunho','em_revisao','aprovado','arquivado']}/><Field label="Responsáveis (separados por vírgula)" value={form.owners.join(', ')} onChange={v=>{setForm({...form,owners:v.split(',').map(x=>x.trim()).filter(Boolean)});setError('')}}/><Field label="Canais (separados por vírgula)" value={form.channels.join(', ')} onChange={v=>setForm({...form,channels:v.split(',').map(x=>x.trim()).filter(Boolean)})}/><Field label="Entregáveis (separados por vírgula)" value={form.deliverables.join(', ')} onChange={v=>setForm({...form,deliverables:v.split(',').map(x=>x.trim()).filter(Boolean)})} wide/><Field label="Referências" value={form.references} onChange={v=>setForm({...form,references:v})} wide/></div>{error&&<p className="marketing-form-error" role="alert">{error}</p>}</div><ModalFooter onClose={onClose}/></form></Modal>}

function Kpi({label,value,detail,icon}:{label:string;value:string|number;detail:string;icon:ReactNode}){return <article className="marketing-kpi"><span className="marketing-kpi-icon">{icon}</span><div><strong>{value}</strong><span>{label}</span><small>{detail}</small></div></article>}
function Card({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="marketing-card"><header><h3>{title}</h3><p>{description}</p></header><div className="marketing-card-body">{children}</div></section>}
function Filters({children}:{children:ReactNode}){return <div className="marketing-filters">{children}</div>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="marketing-search"><Search size={14}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function TableCard({title,description,count,children}:{title:string;description:string;count:number;children:ReactNode}){return <section className="marketing-table-card"><header><div><h3>{title}</h3><p>{description} · {count} registro(s)</p></div></header><div className="marketing-table-wrap">{children}</div></section>}
function Status({value}:{value:string}){const key=value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('_','-').replaceAll(' ','-').toLowerCase();return <span className={`marketing-status ${key}`}>{statusLabel(value)}</span>}
function ActionMenu({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);return <div className="marketing-menu"><button type="button" className="marketing-icon-button" onClick={()=>setOpen(v=>!v)} aria-label="Ações" aria-expanded={open}><MoreHorizontal size={16}/></button>{open&&<div className="marketing-menu-pop"><button type="button" onClick={()=>{setOpen(false);onView()}}>Visualizar</button><button type="button" onClick={()=>{setOpen(false);onEdit()}}>Editar</button><button type="button" className="danger" onClick={()=>{setOpen(false);onDelete()}}>Excluir</button></div>}</div>}
function Empty({empty,text}:{empty:boolean;text:string}){return empty?<div className="marketing-empty">{text}</div>:null}
function Pagination({page,total,onChange}:{page:number;total:number;onChange:(v:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(total<=PAGE_SIZE)return null;return <footer className="marketing-pagination"><span>Página {Math.min(page,pages)} de {pages}</span><div><button type="button" disabled={page<=1} onClick={()=>onChange(page-1)}>Anterior</button><button type="button" disabled={page>=pages} onClick={()=>onChange(page+1)}>Próxima</button></div></footer>}
function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:ReactNode}){useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[onClose]);return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="marketing-modal" role="dialog" aria-modal="true" aria-labelledby="marketing-modal-title"><header><div><span>Marketing</span><h2 id="marketing-modal-title">{title}</h2><p>{subtitle}</p></div><button type="button" className="marketing-icon-button" onClick={onClose} aria-label="Fechar"><X size={17}/></button></header>{children}</section></div>}
function ModalFooter({onClose}:{onClose:()=>void}){return <footer className="marketing-modal-footer"><button type="button" className="marketing-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="marketing-primary">Salvar</button></footer>}
function Field({label,value,onChange,type='text',wide=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;wide?:boolean}){return <label className={`marketing-field${wide?' wide':''}`}><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="marketing-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></label>}
function ViewModal({title,onClose,rows}:{title:string;onClose:()=>void;rows:[string,string][]}){return <Modal title={title} subtitle="Detalhes do registro" onClose={onClose}><div className="marketing-modal-body"><div className="marketing-view-grid">{rows.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></div><footer className="marketing-modal-footer"><button type="button" className="marketing-primary" onClick={onClose}>Fechar</button></footer></Modal>}
const paginate=<T,>(items:T[],page:number)=>items.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)
const shiftMonth=(value:string,delta:number)=>{const [y,m]=value.split('-').map(Number);const d=new Date(y,m-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const headerTitle=(tab:MarketingTab)=>tab==='overview'?'Marketing · Visão Geral':tab==='campaigns'?'Marketing · Campanhas':tab==='calendar'?'Marketing · Calendário':tab==='tasks'?'Marketing · Tarefas':tab==='metrics'?'Marketing · Métricas':tab==='briefings'?'Marketing · Briefings':'Marketing · IA Criativa'
const headerDescription=(tab:MarketingTab)=>tab==='overview'?'Cockpit operacional do setor de marketing':tab==='campaigns'?'Planeje, execute e monitore campanhas e tráfego pago':tab==='calendar'?'Programação e acompanhamento de conteúdos':tab==='tasks'?'Núcleo operacional de tarefas':tab==='metrics'?'Performance de marketing por plataforma':tab==='briefings'?'Origem estratégica dos projetos':'Criação, planejamento, pitching, tendências, métricas e histórico.'
