import {useEffect,useState} from 'react'
import {Navigate,useLocation} from 'react-router-dom'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import type {MarketingSeed,MarketingTab} from './domain'
import {marketingRepository} from './repository'
import {MarketingOverview} from './pages/MarketingOverview'
import {MarketingCampaigns} from './pages/MarketingCampaigns'
import {MarketingCalendar} from './pages/MarketingCalendar'
import {MarketingTasks} from './pages/MarketingTasks'
import {MarketingMetrics} from './pages/MarketingMetrics'
import {MarketingBriefings} from './pages/MarketingBriefings'
import {MarketingAiCreative} from './pages/MarketingAiCreative'
import './marketing.css'
import './marketing-reference.css'
const tabFromPath=(path:string):MarketingTab|null=>path==='/app/marketing'||path==='/app/marketing/'?'overview':path==='/app/marketing/campanhas'?'campaigns':path==='/app/marketing/calendario'?'calendar':path==='/app/marketing/tarefas'?'tasks':path==='/app/marketing/metricas'?'metrics':path==='/app/marketing/briefings'?'briefings':path==='/app/marketing/ia-criativa'?'ai':null
const title=(tab:MarketingTab)=>tab==='overview'?'Visão Geral':tab==='campaigns'?'Campanhas de Marketing':tab==='calendar'?'Marketing - Calendário de Conteúdo':tab==='tasks'?'Marketing · Tarefas':tab==='metrics'?'Métricas':tab==='briefings'?'Briefings':'IA Criativa'
const description=(tab:MarketingTab)=>tab==='overview'?'Cockpit operacional do setor de marketing':tab==='campaigns'?'Planeje, execute e monitore campanhas e tráfego pago':tab==='calendar'?'Programação de conteúdos':tab==='tasks'?'Núcleo operacional de tarefas':tab==='metrics'?'Performance de marketing por plataforma':tab==='briefings'?'Origem estratégica dos projetos':'Criação, perfil, pitching, tendências, métricas e histórico.'
export default function MarketingPage(){const location=useLocation(),tab=tabFromPath(location.pathname),[state,setState]=useState<MarketingSeed>(()=>marketingRepository.snapshot());useEffect(()=>{const refresh=()=>setState(marketingRepository.snapshot());window.addEventListener(marketingRepository.eventName,refresh);return()=>window.removeEventListener(marketingRepository.eventName,refresh)},[]);if(!tab)return <Navigate to="/app/marketing" replace/>;return <AdminShell area="marketing" items={CRM_WORKSPACE_NAV} header={{title:title(tab),description:description(tab)}}><section className="marketing-page">{tab==='overview'?<MarketingOverview state={state}/>:tab==='campaigns'?<MarketingCampaigns state={state}/>:tab==='calendar'?<MarketingCalendar state={state}/>:tab==='tasks'?<MarketingTasks state={state}/>:tab==='metrics'?<MarketingMetrics state={state}/>:tab==='briefings'?<MarketingBriefings state={state}/>:<MarketingAiCreative state={state}/>}</section></AdminShell>}
