import {AlertCircle,Clock,Download,ExternalLink,FileText,History,MailCheck,PenLine,Send,User,X} from 'lucide-react'
import {useMemo,useState} from 'react'
import {contractStatusOptions,optionLabel,signatureStatusOptions,type Contract,type ContractCategory} from '../domain'
import {formatCurrency,formatDate,formatDateTime} from '../format'
import {SendForSigningDialog} from './SendForSigningDialog'

type ViewTab='info'|'signature'|'document'|'versions'|'attachments'|'timeline'

export function ContractViewModal({contract,categories,onClose}:{contract:Contract;categories:ContractCategory[];onClose:()=>void}){
 const [signing,setSigning]=useState(false),[tab,setTab]=useState<ViewTab>('info')
 const category=categories.find(c=>c.id===contract.categoryId)?.name??'—',contractor=contract.parties.find(p=>p.role==='contractor')
 const expiry=useMemo(()=>{if(!contract.endDate)return null;const end=new Date(`${contract.endDate}T00:00:00`),today=new Date();today.setHours(0,0,0,0);const days=Math.ceil((end.getTime()-today.getTime())/86400000);return days>=0&&days<=30?days:null},[contract.endDate])
 const tabs:Array<[ViewTab,string]>=[['info','Informações'],['signature',`Assinatura${contract.signers.length?` (${contract.signers.length})`:''}`],['document','Arquivo'],['versions',`Versões${contract.document.versions.length?` (${contract.document.versions.length})`:''}`],['attachments',`Documentos${contract.attachments.length?` (${contract.attachments.length})`:''}`],['timeline','Histórico']]
 return <><div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="contracts-original-view" role="dialog" aria-modal="true" aria-label="Visualizar contrato">
  <button className="contracts-original-close" onClick={onClose} aria-label="Fechar"><X size={16}/></button>
  <header className="contracts-original-head"><div className="contracts-original-head-icon"><FileText size={20}/></div><div className="contracts-original-head-copy"><h2>{contract.title}</h2><div className="contracts-original-badges"><span className={`contracts-status status-${contract.status}`}>{optionLabel(contractStatusOptions,contract.status)}</span>{contract.signingProvider&&<span className="crm-badge muted">{contract.signingProvider}</span>}{expiry!==null&&<span className="contracts-original-warning"><AlertCircle size={12}/>Expira em {expiry}d</span>}</div></div></header>
  <nav className="contracts-original-tabs" role="tablist">{tabs.map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
  <div className="contracts-original-scroll">
   {tab==='info'&&<div className="contracts-original-content contracts-original-info"><div className="contracts-original-info-grid"><Info label="Cliente / Contratante" value={contractor?.name}/><Info label="Tipo" value={contract.type}/><Info label="Início" value={formatDate(contract.startDate)}/><Info label="Término" value={contract.endDate?formatDate(contract.endDate):'Indeterminado'}/><Info label="Valor" value={formatCurrency(contract.payment.amount,contract.payment.currency)}/><Info label="Categoria" value={category}/></div>{contract.description&&<div className="contracts-original-observations"><span>Observações</span><p>{contract.description}</p></div>}</div>}
   {tab==='signature'&&<div className="contracts-original-content contracts-original-signature">{contract.signers.length>0?<><div className="contracts-original-section-title"><strong>Signatários do Contrato</strong><span>{contract.signers.length} signatário(s)</span></div><div className="contracts-original-signer-list">{[...contract.signers].sort((a,b)=>a.order-b.order).map((signer,index)=><article key={signer.id}><div className="contracts-original-person-icon"><User size={14}/></div><div className="contracts-original-signer-copy"><strong>{signer.name}</strong><span><MailCheck size={12}/>{signer.email}</span></div><small>{signer.role||`Signatário ${index+1}`}</small></article>)}</div><div className="contracts-original-signing-card"><div><strong>Pronto para assinar?</strong><span>Envie o contrato para os {contract.signers.length} signatário(s) via plataforma de assinatura digital.</span></div><button className="crm-btn primary small" onClick={()=>setSigning(true)}><Send size={14}/>Enviar para Assinatura</button></div></>:<div className="contracts-original-empty"><div><PenLine size={32}/></div><strong>Nenhum signatário definido</strong><span>Adicione signatários no formulário do contrato.</span></div>}{contract.signingProvider&&<div className="contracts-original-process"><div className="contracts-original-section-title"><strong>Processo de Assinatura Digital</strong><span>{contract.signingProvider}</span></div><div className="contracts-original-process-card"><div className="contracts-original-head-icon"><PenLine size={17}/></div><div><strong>{contract.document.title||contract.title}</strong><span>{optionLabel(signatureStatusOptions,contract.signatureStatus)}</span></div></div></div>}</div>}
   {tab==='document'&&<div className="contracts-original-content">{contract.document.signedFileUrl?<div className="contracts-original-file-card"><div className="contracts-original-file-icon"><FileText size={32}/></div><div><strong>{contract.title}</strong><span>{contract.document.signedFileUrl}</span></div><a className="crm-btn primary" href={contract.document.signedFileUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Abrir PDF</a></div>:<div className="contracts-original-empty"><FileText size={48}/><strong>Nenhum arquivo vinculado</strong><span>Edite o contrato para adicionar a URL do PDF</span></div>}</div>}
   {tab==='versions'&&<div className="contracts-original-content">{contract.document.versions.length>0?<div className="contracts-original-version-list">{contract.document.versions.map((version,index)=><article key={version.id}><div className="contracts-original-circle"><History size={16}/></div><div><strong>Versão {version.version}{index===contract.document.versions.length-1&&<em>Atual</em>}</strong><span><Clock size={12}/>{formatDateTime(version.createdAt)}</span>{version.createdBy&&<span><User size={12}/>{version.createdBy}</span>}{version.notes&&<p>{version.notes}</p>}</div></article>)}</div>:<div className="contracts-original-empty"><History size={48}/><strong>Sem histórico de versões</strong><span>As versões do documento aparecerão aqui ao editar o arquivo</span></div>}</div>}
   {tab==='attachments'&&<div className="contracts-original-content">{contract.attachments.length>0?<div className="contracts-original-doc-list">{contract.attachments.map(a=><article key={a.id}><div className="contracts-original-circle"><FileText size={16}/></div><div><strong>{a.name}</strong><span>{Math.ceil(a.size/1024)} KB</span></div><a className="crm-btn secondary small" href={a.dataUrl} download={a.name}><Download size={13}/>Baixar</a></article>)}</div>:<div className="contracts-original-empty"><FileText size={48}/><strong>Nenhum documento anexado</strong><span>Edite o contrato para anexar documentos</span></div>}</div>}
   {tab==='timeline'&&<div className="contracts-original-content">{contract.timeline.length>0?<div className="contracts-original-timeline">{[...contract.timeline].reverse().map(item=><article key={item.id}><div className="contracts-original-circle"><History size={16}/></div><div><strong>{item.event}</strong><p>{item.description}</p><span>{item.actor} · {formatDateTime(item.createdAt)}</span></div></article>)}</div>:<div className="contracts-original-empty"><History size={48}/><strong>Sem histórico registrado</strong><span>Os eventos do contrato aparecerão aqui.</span></div>}</div>}
  </div>
  <footer className="contracts-original-foot">{contract.signers.length>0?<button className="crm-btn secondary small" onClick={()=>setSigning(true)}><Send size={14}/>Enviar para Assinatura</button>:<span/>}<button className="crm-btn secondary small" onClick={onClose}>Fechar</button></footer>
 </section></div>{signing&&<SendForSigningDialog contract={contract} onClose={()=>setSigning(false)}/>}</>
}
function Info({label,value}:{label:string;value?:string}){return <div className="contracts-original-info-item"><span>{label}</span><strong>{value||'—'}</strong></div>}
