import {Download,ExternalLink,FileText,History,PenLine,X} from 'lucide-react'
import {useState,type ReactNode} from 'react'
import {contractStatusOptions,optionLabel,signatureStatusOptions,type Contract,type ContractCategory} from '../domain'
import {formatCurrency,formatDate,formatDateTime} from '../format'
import {ContractA4Preview} from './ContractA4Preview'
import {SendForSigningDialog} from './SendForSigningDialog'

type ViewTab='info'|'signature'|'document'|'versions'|'attachments'|'timeline'

export function ContractViewModal({contract,categories,onClose,onEdit}:{contract:Contract;categories:ContractCategory[];onClose:()=>void;onEdit:()=>void}){
 const [signing,setSigning]=useState(false),[tab,setTab]=useState<ViewTab>('info')
 const category=categories.find(c=>c.id===contract.categoryId)?.name??'—',contractor=contract.parties.find(p=>p.role==='contractor'),contracted=contract.parties.find(p=>p.role==='contracted')
 const tabs:Array<[ViewTab,string]>=[['info','Informações'],['signature',`Assinatura${contract.signers.length?` (${contract.signers.length})`:''}`],['document','Documento'],['versions',`Versões${contract.document.versions.length?` (${contract.document.versions.length})`:''}`],['attachments',`Documentos${contract.attachments.length?` (${contract.attachments.length})`:''}`],['timeline','Timeline']]
 return <><div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="contracts-reference-view" role="dialog" aria-modal="true" aria-label="Visualizar contrato"><header className="contracts-reference-view-head"><div className="contracts-reference-view-icon"><FileText size={20}/></div><div className="contracts-reference-view-title"><h2>{contract.title}</h2><div><span className={`contracts-status status-${contract.status}`}>{optionLabel(contractStatusOptions,contract.status)}</span><span className="crm-badge muted">{contract.signingProvider??'Sem provider'}</span><span className="crm-badge muted">{contract.number||'Sem número'}</span></div></div><button className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><nav className="contracts-reference-tabs" role="tablist">{tabs.map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav><div className="contracts-reference-view-body">
  {tab==='info'&&<div className="contracts-info-grid"><Info title="Contrato"><Row k="Tipo" v={contract.type}/><Row k="Categoria" v={category}/><Row k="Status" v={optionLabel(contractStatusOptions,contract.status)}/><Row k="Número" v={contract.number}/></Info><Info title="Partes"><Row k="Contratante" v={contractor?.name}/><Row k="Contratada" v={contracted?.name}/><Row k="Representante" v={contractor?.representativeName||contracted?.representativeName}/></Info><Info title="Vigência"><Row k="Início" v={formatDate(contract.startDate)}/><Row k="Fim" v={formatDate(contract.endDate)}/><Row k="Duração" v={contract.duration}/></Info><Info title="Financeiro"><Row k="Valor" v={formatCurrency(contract.payment.amount,contract.payment.currency)}/><Row k="Forma" v={contract.payment.method}/><Row k="Periodicidade" v={contract.payment.periodicity}/><Row k="Parcelas" v={String(contract.payment.installments||'—')}/></Info><section className="contracts-reference-wide"><h3>Objeto / Descrição</h3><p>{contract.description||'Nenhuma descrição registrada.'}</p></section><Info title="Metadados"><Row k="Criado em" v={formatDateTime(contract.createdAt)}/><Row k="Atualizado em" v={formatDateTime(contract.updatedAt)}/></Info></div>}
  {tab==='signature'&&<div className="contracts-signature-tab"><div className="contracts-signature-summary"><div><span>Provider</span><strong>{contract.signingProvider??'Não configurado'}</strong></div><div><span>Status</span><strong>{optionLabel(signatureStatusOptions,contract.signatureStatus)}</strong></div><button className="crm-btn secondary" onClick={()=>setSigning(true)}><PenLine size={14}/>Enviar para assinatura</button></div>{contract.signers.length===0?<div className="contracts-reference-empty"><PenLine size={36}/><strong>Nenhum signatário configurado</strong><span>Edite o contrato para adicionar signatários antes do envio.</span></div>:<div className="contracts-signers-list">{[...contract.signers].sort((a,b)=>a.order-b.order).map(signer=><article key={signer.id}><i>{signer.order}</i><div><strong>{signer.name}</strong><span>{signer.email}</span></div><small>{optionLabel(signatureStatusOptions,signer.status)}</small></article>)}</div>}</div>}
  {tab==='document'&&<div className="contracts-document-tab"><ContractA4Preview document={contract.document}/>{contract.document.signedFileUrl&&<a className="crm-btn secondary contracts-download-link" href={contract.document.signedFileUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Abrir documento assinado</a>}</div>}
  {tab==='versions'&&(contract.document.versions.length===0?<div className="contracts-reference-empty"><History size={38}/><strong>Nenhuma versão anterior</strong><span>Versões serão preservadas quando documentos protegidos forem alterados.</span></div>:<div className="contracts-versions-list">{[...contract.document.versions].reverse().map(version=><article key={version.id}><div><strong>Versão {version.version}</strong><span>{version.notes||'Sem notas da versão'}</span></div><div><small>{version.createdBy}</small><small>{formatDateTime(version.createdAt)}</small></div></article>)}</div>)}
  {tab==='attachments'&&(contract.attachments.length===0?<div className="contracts-reference-empty"><FileText size={38}/><strong>Nenhum documento anexado</strong><span>Edite o contrato para anexar documentos relacionados.</span></div>:<div className="contracts-documents-list">{contract.attachments.map(a=><article key={a.id}><FileText size={18}/><div><strong>{a.name}</strong><span>{Math.ceil(a.size/1024)} KB</span></div><a className="crm-btn secondary small" href={a.dataUrl} download={a.name}><Download size={13}/>Baixar</a></article>)}</div>)}
  {tab==='timeline'&&(contract.timeline.length===0?<div className="contracts-reference-empty"><History size={38}/><strong>Nenhum evento registrado</strong></div>:<div className="contracts-reference-timeline">{[...contract.timeline].reverse().map(item=><article key={item.id}><span/><div><strong>{item.event}</strong><p>{item.description}</p><small>{item.actor} · {formatDateTime(item.createdAt)}</small></div></article>)}</div>)}
 </div><footer className="contracts-reference-view-foot"><div>{contract.signers.length>0&&<button className="crm-btn secondary" onClick={()=>setSigning(true)}><PenLine size={14}/>Enviar para Assinatura</button>}</div><div><button className="crm-btn secondary" onClick={onClose}>Fechar</button><button className="crm-btn primary" onClick={onEdit}>Editar</button></div></footer></section></div>{signing&&<SendForSigningDialog contract={contract} onClose={()=>setSigning(false)}/>}</>
}
function Info({title,children}:{title:string;children:ReactNode}){return <section className="contracts-reference-info"><h3>{title}</h3>{children}</section>}
function Row({k,v}:{k:string;v?:string}){return <div><span>{k}</span><strong>{v||'—'}</strong></div>}
