import {BarChart3,CheckCircle2,Globe2,MousePointer2,Target,TrendingUp,Users} from 'lucide-react'
import {useMemo,useState} from 'react'
import {compact,money,type MarketingSeed} from '../domain'
import {Card,Empty,Pagination,paginate,pct} from '../MarketingUi'
const PLATFORM_ORDER=['YouTube','TikTok','Instagram','Google Ads','Spotify Ads']
export function MarketingMetrics({state}:{state:MarketingSeed}){const [platform,setPlatform]=useState('all'),[period,setPeriod]=useState('2026-08'),[page,setPage]=useState(1);const platforms=PLATFORM_ORDER.filter(name=>state.metrics.some(x=>x.platform===name)),base=state.metrics.filter(x=>(platform==='all'||x.platform===platform)&&(!period||x.period===period)),total=base.reduce((a,x)=>({reach:a.reach+x.reach,impressions:a.impressions+x.impressions,clicks:a.clicks+x.clicks,engagement:a.engagement+x.engagement,followers:a.followers+x.followers,conversions:a.conversions+x.conversions,spend:a.spend+x.spend,revenue:a.revenue+x.revenue}),{reach:0,impressions:0,clicks:0,engagement:0,followers:0,conversions:0,spend:0,revenue:0}),max=Math.max(...base.map(x=>x.reach),1);const ranking=useMemo(()=>state.contents.filter(content=>platform==='all'||content.channels.includes(platform)).map((content,index)=>{const metric=base[index%Math.max(base.length,1)];return {id:content.id,title:content.title,artist:content.artist||content.campaign||content.context||'—',type:content.type,platform:content.channels.find(channel=>platform==='all'||channel===platform)||content.channels[0]||'—',value:metric?.reach??0,label:'Alcance'}}).sort((a,b)=>b.value-a.value),[state.contents,platform,base]),paged=paginate(ranking,page);return <>
<div className="marketing-platform-tabs marketing-platform-tabs-exact"><button type="button" className={platform==='all'?'active':''} onClick={()=>{setPlatform('all');setPage(1)}}><Globe2 size={14}/>Visão Geral</button>{platforms.map(name=><button type="button" key={name} className={platform===name?'active':''} onClick={()=>{setPlatform(name);setPage(1)}}><span className="marketing-platform-dot"/>{name}</button>)}</div>
<div className="marketing-metrics-period"><input type="month" value={period} onChange={e=>{setPeriod(e.target.value);setPage(1)}}/></div>
<div className="marketing-metric-strip marketing-metric-strip-exact">{[['Alcance',compact(total.reach),'pessoas alcançadas',Users],['Impressões',compact(total.impressions),'exibições',BarChart3],['Cliques',compact(total.clicks),`CTR ${pct(total.clicks,total.impressions).toFixed(2)}%`,MousePointer2],['Engajamento',compact(total.engagement),'interações',TrendingUp],['Conversões',compact(total.conversions),'ações atribuídas',CheckCircle2],['Seguidores',compact(total.followers),'base monitorada',Target]].map(([label,value,hint,Icon])=><article key={String(label)}><div><span>{String(label)}</span><strong>{String(value)}</strong><small>{String(hint)}</small></div><Icon size={16}/></article>)}</div>
<div className="marketing-analytics-grid marketing-analytics-reference"><Card title={platform==='all'?'Evolução consolidada':`${platform} · evolução`} description={platform==='all'?'Performance agregada das plataformas monitoradas':'Série simulada da plataforma selecionada'}><div className="marketing-performance-chart"><div className="marketing-chart-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0</span></div><div className="marketing-chart-columns">{base.map(x=><div key={x.id}><div className="marketing-chart-column-bar"><i style={{height:`${Math.max(8,Math.min(100,pct(x.reach,max)))}%`}}/></div><span>{x.platform}</span></div>)}</div></div></Card><Card title={platform==='all'?'Resumo consolidado':`Resumo · ${platform}`} description="Leitura rápida dos principais indicadores"><div className="marketing-summary marketing-summary-reference"><p><span>Audiência total</span><strong>{compact(total.followers)}</strong></p><p><span>Views totais/mês</span><strong>{compact(total.impressions)}</strong></p><p><span>Engajamento médio</span><strong>{compact(total.engagement)}</strong></p><p><span>Alcance total</span><strong>{compact(total.reach)}</strong></p><p><span>Cliques totais</span><strong>{compact(total.clicks)}</strong></p><p><span>CTR médio</span><strong>{pct(total.clicks,total.impressions).toFixed(2)}%</strong></p><p><span>Conversões totais</span><strong>{compact(total.conversions)}</strong></p><p><span>Investimento total</span><strong>{money(total.spend)}</strong></p></div></Card></div>
<section className="marketing-card marketing-ranking marketing-ranking-exact"><header><h3>{platform==='all'?'Top Conteúdos':`Ranking · ${platform}`}</h3><p>Ranking de performance por conteúdo, artista/campanha e plataforma</p></header><div className="marketing-card-body"><div className="marketing-ranking-header"><span>Posição</span><span>Conteúdo</span><span>Artista/Campanha</span><span>Resultado</span><span>Plataforma</span></div><div className="marketing-ranking-list marketing-content-ranking">{paged.map((item,index)=><article key={item.id}><span className="marketing-rank">{(page-1)*8+index+1}</span><div className="marketing-ranking-main"><strong>{item.title}</strong><small>{item.type}</small></div><div className="marketing-ranking-main"><strong>{item.artist}</strong></div><div><strong>{compact(item.value)}</strong><small>{item.label}</small></div><div><strong>{item.platform}</strong></div></article>)}</div><Empty empty={!ranking.length} text="Nenhum conteúdo encontrado para esta plataforma."/></div><Pagination page={page} total={ranking.length} onChange={setPage}/></section>
</>}
