import {BarChart3,CheckCircle2,MousePointer2,Target,TrendingUp,Users} from 'lucide-react'
import {useState} from 'react'
import {compact,money,type MarketingSeed} from '../domain'
import {Card,Empty,Pagination,paginate,pct} from '../MarketingUi'
export function MarketingMetrics({state}:{state:MarketingSeed}){const [platform,setPlatform]=useState('all'),[period,setPeriod]=useState('2026-08'),[page,setPage]=useState(1);const platforms=state.metrics.map(x=>x.platform).filter((v,i,a)=>a.indexOf(v)===i),base=state.metrics.filter(x=>(platform==='all'||x.platform===platform)&&(!period||x.period===period)),total=base.reduce((a,x)=>({reach:a.reach+x.reach,impressions:a.impressions+x.impressions,clicks:a.clicks+x.clicks,engagement:a.engagement+x.engagement,followers:a.followers+x.followers,conversions:a.conversions+x.conversions,spend:a.spend+x.spend,revenue:a.revenue+x.revenue}),{reach:0,impressions:0,clicks:0,engagement:0,followers:0,conversions:0,spend:0,revenue:0});const maxImpressions=Math.max(...base.map(x=>x.impressions),1),ranked=[...base].sort((a,b)=>b.reach-a.reach),paged=paginate(ranked,page);return <>
<div className="marketing-metrics-top"><div className="marketing-platform-tabs"><button type="button" className={platform==='all'?'active':''} onClick={()=>{setPlatform('all');setPage(1)}}><BarChart3 size={14}/>Visão Geral</button>{platforms.map(x=><button type="button" key={x} className={platform===x?'active':''} onClick={()=>{setPlatform(x);setPage(1)}}><span className="marketing-platform-dot"/>{x}</button>)}</div><input className="marketing-period-input" type="month" value={period} onChange={e=>{setPeriod(e.target.value);setPage(1)}}/></div>
<div className="marketing-metric-strip">{[['Alcance',compact(total.reach),'pessoas alcançadas',Users],['Impressões',compact(total.impressions),'exibições',BarChart3],['Cliques',compact(total.clicks),`CTR ${pct(total.clicks,total.impressions).toFixed(2)}%`,MousePointer2],['Engajamento',compact(total.engagement),'interações',TrendingUp],['Conversões',compact(total.conversions),'ações atribuídas',CheckCircle2],['Seguidores',compact(total.followers),'base monitorada',Target]].map(([label,value,hint,Icon])=><article key={String(label)}><div><span>{String(label)}</span><strong>{String(value)}</strong><small>{String(hint)}</small></div><Icon size={16}/></article>)}</div>
<div className="marketing-analytics-grid marketing-analytics-reference"><Card title={platform==='all'?'Evolução consolidada':`${platform} · evolução`} description={platform==='all'?'Performance agregada das plataformas monitoradas':'Série simulada da plataforma selecionada'}><div className="marketing-chart-shell"><div className="marketing-chart-scale"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0</span></div><div className="marketing-chart-bars">{base.map(x=><div key={x.id} className="marketing-chart-column"><div className="marketing-chart-bar"><i style={{height:`${Math.max(8,Math.min(100,pct(x.impressions,maxImpressions)))}%`}}/></div><span>{x.platform}</span></div>)}</div></div></Card><Card title={platform==='all'?'Resumo consolidado':`Resumo · ${platform}`} description="Leitura rápida dos principais indicadores"><div className="marketing-summary marketing-summary-reference"><p><span>CPC médio</span><strong>{total.clicks?money(total.spend/total.clicks):'—'}</strong></p><p><span>CPA médio</span><strong>{total.conversions?money(total.spend/total.conversions):'—'}</strong></p><p><span>Taxa de conversão</span><strong>{pct(total.conversions,total.clicks).toFixed(2)}%</strong></p><p><span>Investimento</span><strong>{money(total.spend)}</strong></p><p><span>Receita atribuída</span><strong>{money(total.revenue)}</strong></p><p><span>ROAS</span><strong>{total.spend?`${(total.revenue/total.spend).toFixed(2)}x`:'—'}</strong></p></div></Card></div>
<section className="marketing-card marketing-ranking"><header><h3>{platform==='all'?'Top Plataformas':`Ranking · ${platform}`}</h3><p>Ranking de performance por plataforma, investimento e retorno</p></header><div className="marketing-card-body"><div className="marketing-ranking-list">{paged.map((x,index)=><article key={x.id}><span className="marketing-rank">{String((page-1)*8+index+1).padStart(2,'0')}</span><div className="marketing-ranking-main"><strong>{x.platform}</strong><small>{compact(x.reach)} alcance · {compact(x.impressions)} impressões</small></div><div><small>CTR</small><strong>{pct(x.clicks,x.impressions).toFixed(2)}%</strong></div><div><small>Investimento</small><strong>{money(x.spend)}</strong></div><div><small>ROAS</small><strong>{x.spend?(x.revenue/x.spend).toFixed(2):'—'}x</strong></div></article>)}</div><Empty empty={!base.length} text="Nenhuma métrica encontrada para o período."/></div><Pagination page={page} total={ranked.length} onChange={setPage}/></section>
</>}
