import {portalLogo} from '../../../shared/branding/assets/brandAsset'
import type {CreativeBrandLayer,CreativeConfig,CreativeMediaSlot,CreativeTextLayer} from '../domain'
import type {CreativeFormat} from './formatRegistry'
const image=async(url:string)=>{const response=await fetch(url);if(!response.ok)throw new Error('Não foi possível carregar um asset do criativo.');const blob=await response.blob();return createImageBitmap(blob)}
function drawMedia(ctx:CanvasRenderingContext2D,source:ImageBitmap,slot:CreativeMediaSlot,x:number,y:number,width:number,height:number){const scaleBase=slot.fit==='contain'?Math.min(width/source.width,height/source.height):Math.max(width/source.width,height/source.height),scale=scaleBase*slot.zoom,drawW=source.width*scale,drawH=source.height*scale,freeX=width-drawW,freeY=height-drawH,dx=x+freeX*(slot.positionX/100),dy=y+freeY*(slot.positionY/100);ctx.save();ctx.beginPath();ctx.rect(x,y,width,height);ctx.clip();ctx.drawImage(source,dx,dy,drawW,drawH);ctx.restore()}
function wrapText(ctx:CanvasRenderingContext2D,value:string,maxWidth:number){const words=value.split(/\s+/),lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines}
function drawText(ctx:CanvasRenderingContext2D,layer:CreativeTextLayer,width:number,height:number){if(!layer.visible||!layer.text)return;const scale=width/1080,size=layer.fontSize*scale,x=width*layer.x/100,y=height*layer.y/100,maxWidth=width*layer.width/100;ctx.save();ctx.fillStyle=layer.color;ctx.font=`${layer.fontWeight} ${size}px ${layer.fontFamily}, Arial, sans-serif`;ctx.textAlign=layer.align;ctx.textBaseline='top';const anchor=layer.align==='center'?x+maxWidth/2:layer.align==='right'?x+maxWidth:x;for(const [index,line] of wrapText(ctx,layer.text,maxWidth).entries())ctx.fillText(line,anchor,y+index*size*layer.lineHeight,maxWidth);ctx.restore()}
async function drawBrand(ctx:CanvasRenderingContext2D,layer:CreativeBrandLayer|undefined,width:number,height:number){if(!layer?.visible)return;const url=layer.source==='global'?portalLogo:layer.url;if(!url)return;const source=await image(url);const targetW=width*layer.width/100,targetH=targetW*(source.height/source.width),rawX=width*layer.x/100,x=layer.align==='center'?rawX-targetW/2:layer.align==='right'?rawX-targetW:rawX,y=height*layer.y/100;ctx.save();ctx.globalAlpha=layer.opacity;ctx.drawImage(source,x,y,targetW,targetH);ctx.restore();source.close()}
export async function renderCreativeImage(creative:CreativeConfig,format:CreativeFormat){if(creative.mode!=='template'||!creative.primarySlot)throw new Error('Template incompleto.');const canvas=document.createElement('canvas');canvas.width=format.width;canvas.height=format.height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas indisponível.');ctx.fillStyle=creative.background||'#050505';ctx.fillRect(0,0,canvas.width,canvas.height);const mediaY=Math.round(canvas.height*.38),mediaH=canvas.height-mediaY,primary=await image(creative.primarySlot.url);if(creative.layout==='split'){if(!creative.secondarySlot)throw new Error('Mídia secundária obrigatória para Split.');const secondary=await image(creative.secondarySlot.url),half=canvas.width/2;drawMedia(ctx,primary,creative.primarySlot,0,mediaY,half,mediaH);drawMedia(ctx,secondary,creative.secondarySlot,half,mediaY,half,mediaH);secondary.close()}else drawMedia(ctx,primary,creative.primarySlot,0,mediaY,canvas.width,mediaH);primary.close();if(creative.headline)drawText(ctx,creative.headline,canvas.width,canvas.height);if(creative.subtitle)drawText(ctx,creative.subtitle,canvas.width,canvas.height);await drawBrand(ctx,creative.logo,canvas.width,canvas.height);await drawBrand(ctx,creative.watermark,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Falha ao gerar PNG.')),'image/png'));return new File([blob],`portal-lander-${Date.now()}.png`,{type:'image/png'})}
