import {useEffect,useState} from 'react'
import {Check,ExternalLink,Eye,Inbox,Newspaper,RefreshCw,X} from 'lucide-react'
import {Link,useNavigate} from 'react-router-dom'
import {AdminNotice,AdminShell} from '../../../shared/internal/AdminUi'
import {SITE_MANAGER_NAV} from '../../../shared/internal/adminNavigation'
import {listAdminEditorialPages} from '../../editorial/adminClient'
import type {EditorialPage} from '../../editorial/model'
import {convertImportCandidate,listImportCandidates,reviewImportCandidate,type ImportCandidate} from '../../editorial/editorialIngestionClient'

export default function ImportCandidatesPage(){
 const navigate=useNavigate(),[items,setItems]=useState<ImportCandidate[]>([]),[pages,setPages]=useState<EditorialPage[]>([]),[targetPageId,setTargetPageId]=useState(''),[status,setStatus]=useState('new'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [candidates,editorialPages]=await Promise.all([listImportCandidates(status),listAdminEditorialPages()]);const available=editorialPages.filter(page=>page.type==='editorial');setItems(candidates);setPages(available);setTargetPageId(current=>current&&available.some(page=>page.id===current)?current:'')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os candidatos.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[status])
 const action=async(item:ImportCandidate,kind:'review'|'approve'|'reject'|'ignore')=>{setBusy(item.id);setError('');try{await reviewImportCandidate(item.id,kind);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar o candidato.')}finally{setBusy('')}}
 const convert=async(item:ImportCandidate)=>{if(!targetPageId){setError('Selecione explicitamente a página editorial de destino antes de converter candidatos.');return}setBusy(item.id);setError('');try{const result=await convertImportCandidate(item.id,targetPageId);navigate(`/app/site/conteudos/${result.content.id}`)}catch(e){setError(e instanceof Error?e.message:'Não foi possível converter o candidato.')}finally{setBusy('')}}
 return <AdminShell area="cms" items={SITE_MANAGER_NAV} header={{title:'Candidatos editoriais',description:'Descobertas externas aguardam curadoria humana antes de virar rascunho.'}}>
  <div className="admin-toolbar"><div className="admin-toolbar-group"><Link className="button outline" to="/app/site/conteudos"><Newspaper size={15}/>Publicações</Link><Link className="button" to="/app/site/conteudos/importados"><Inbox size={15}/>Candidatos</Link><Link className="button outline" to="/app/settings/integracoes/editoriais"><RefreshCw size={15}/>Fontes</Link></div><div className="admin-toolbar-group"><label>Estado <select value={status} onChange={e=>setStatus(e.target.value)}><option value="new">Novos</option><option value="reviewing">Em revisão</option><option value="approved">Aprovados</option><option value="rejected">Rejeitados</option><option value="ignored">Ignorados</option><option value="converted">Convertidos</option></select></label><label>Página de destino <select value={targetPageId} onChange={e=>setTargetPageId(e.target.value)}><option value="">Selecione…</option>{pages.map(page=><option key={page.id} value={page.id}>{page.title}</option>)}</select></label></div></div>
  <AdminNotice title="Publicação continua manual" description="Aprovar um candidato não publica nada. A conversão cria somente um draft no CMS, mantendo a fonte externa como provenance e usando a página editorial escolhida acima."/>
  {loading&&<AdminNotice title="Carregando candidatos" description="Consultando a fila editorial persistida."/>}{error&&<AdminNotice title="Falha na operação" description={error}/>} 
  <div className="tableview-surface cms-tableview-surface"><section className="table-card"><table><thead><tr><th>Pauta</th><th>Fonte</th><th>Categoria</th><th>Relevância</th><th>Data</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><div className="table-primary"><span className="table-avatar"><Newspaper size={15}/></span><div><b>{item.title}</b><small>{item.description||'Sem snippet'}</small></div></div></td><td>{item.sourceName}<br/><a href={item.canonicalUrl} target="_blank" rel="noreferrer">Abrir origem <ExternalLink size={12}/></a></td><td>{item.suggestedCategory}</td><td>{item.relevanceScore}/100</td><td>{new Date(item.publishedAt||item.discoveredAt).toLocaleDateString('pt-BR')}</td><td><span className={`status ${item.status}`}>{item.status}</span></td><td><div className="admin-toolbar-group">{item.status==='new'&&<button className="button outline" type="button" disabled={busy===item.id} onClick={()=>void action(item,'review')}><Eye size={13}/>Revisar</button>}{['new','reviewing'].includes(item.status)&&<button className="button" type="button" disabled={busy===item.id} onClick={()=>void action(item,'approve')}><Check size={13}/>Aprovar</button>}{['new','reviewing','approved'].includes(item.status)&&<button className="button outline" type="button" disabled={busy===item.id} onClick={()=>void action(item,'ignore')}>Ignorar</button>}{item.status!=='converted'&&<button className="button outline" type="button" disabled={busy===item.id} onClick={()=>void action(item,'reject')}><X size={13}/>Rejeitar</button>}{item.status==='approved'&&<button className="button" type="button" disabled={busy===item.id||!targetPageId} onClick={()=>void convert(item)}>Converter em draft</button>}</div></td></tr>)}</tbody></table></section></div>
 </AdminShell>
}
