import type {ReactNode} from 'react'
import {PORTAL_ADVERTISING_INVENTORY} from '../../../shared/advertising/canonicalInventory'
import {portalLogo} from '../../../shared/branding/assets/brandAsset'
import type {MediaKitDraft,MediaKitResolvedMetric} from '../mediaKitDomain'

const PAGE_COUNT=9
const metricValue=(metric:MediaKitResolvedMetric)=>metric.value===null?'MÉTRICA NÃO DISPONÍVEL':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(metric.value)
const statusLabel=(metric:MediaKitResolvedMetric)=>metric.dataStatus==='SYNC_ERROR'?'ERRO DE SINCRONIZAÇÃO':metric.dataStatus==='STALE'?'DADO DESATUALIZADO':metric.dataStatus==='MANUAL'?'DADO MANUAL':metric.dataStatus==='UNAVAILABLE'?'NÃO DISPONÍVEL':metric.dataStatus

function Page({number,eyebrow,title,children,className=''}:{number:number;eyebrow:string;title:string;children:ReactNode;className?:string}){
  return <section className={`mk-page ${className}`.trim()} data-media-kit-page={number} aria-label={`Página ${number} de ${PAGE_COUNT}`}><header className="mk-page-header"><span>{eyebrow}</span><b>{String(number).padStart(2,'0')}</b></header><h2>{title}</h2>{children}<footer><span>PORTAL LANDER · MÍDIA KIT</span><span>{String(number).padStart(2,'0')}</span></footer></section>
}

function PreviewFrame({number,children}:{number:number;children:ReactNode}){
  return <div className="mk-preview-page-frame" data-preview-page={number}><div className="mk-preview-page-label">Página {number} de {PAGE_COUNT}</div>{children}</div>
}

export function MediaKitDocument({kit}:{kit:MediaKitDraft}){
 const metrics=kit.audience.snapshot.length?kit.audience.snapshot:kit.audience.metrics.map(binding=>({id:binding.id,label:binding.label,metricKey:binding.metricKey,value:null,unit:binding.unit,provider:binding.provider||null,providerAccountId:binding.providerAccountId||null,providerPropertyId:binding.providerPropertyId||null,periodStart:null,periodEnd:null,granularity:null,sourceType:'unavailable' as const,sourceReference:null,collectedAt:null,providerUpdatedAt:null,normalizedAt:null,freshnessStatus:'UNKNOWN' as const,dataStatus:'UNAVAILABLE' as const,syncId:null,provenance:{reason:'DRAFT_NOT_RESOLVED'},isEstimated:false,isManual:binding.sourceMode==='manual'}))
 return <main className="mk-document" aria-label="Preview do Mídia Kit">
  <PreviewFrame number={1}><section className="mk-page mk-cover" data-media-kit-page={1} aria-label={`Página 1 de ${PAGE_COUNT}`}><img src={portalLogo} alt="Portal Lander"/><div><span>MÍDIA · PUBLICIDADE · AUDIÊNCIA</span><h1>{kit.identity.title}</h1><strong>{kit.identity.subtitle} {kit.identity.versionLabel}</strong></div><footer><span>DOCUMENTO COMERCIAL VERSIONADO</span><span>01</span></footer></section></PreviewFrame>
  <PreviewFrame number={2}><Page number={2} eyebrow="SOBRE" title="SOBRE O PORTAL LANDER"><div className="mk-lead"><p>{kit.institutional.summary||'Apresentação institucional ainda não preenchida.'}</p><p>{kit.institutional.positioning||'Posicionamento comercial ainda não preenchido.'}</p></div><div className="mk-rule"/><p className="mk-note">Este documento preserva a identidade visual e os estados reais configurados no Portal Lander.</p></Page></PreviewFrame>
  <PreviewFrame number={3}><Page number={3} eyebrow="AUDIÊNCIA" title="NOSSA AUDIÊNCIA"><div className="mk-metric-grid">{metrics.length?metrics.map(metric=><article key={metric.id}><span>{metric.label}</span><strong>{metricValue(metric)}</strong><small>{statusLabel(metric)}</small><small>{metric.provider||metric.sourceType} · {metric.periodStart&&metric.periodEnd?`${new Date(metric.periodStart).toLocaleDateString('pt-BR')} — ${new Date(metric.periodEnd).toLocaleDateString('pt-BR')}`:'período indisponível'}</small></article>):<article><span>Audiência</span><strong>MÉTRICA NÃO DISPONÍVEL</strong><small>FONTE AINDA NÃO CONECTADA</small></article>}</div><p className="mk-note">Nenhuma ausência de dado é convertida em zero. Métricas publicadas são snapshots imutáveis com proveniência.</p></Page></PreviewFrame>
  <PreviewFrame number={4}><Page number={4} eyebrow="PUBLICIDADE" title="ONDE SUA MARCA APARECE"><div className="mk-placement-list">{PORTAL_ADVERTISING_INVENTORY.map(placement=>{const configured=kit.inventory.placements.find(item=>item.placementId===placement.id);return <article key={placement.id}><b>{placement.name}</b><p>{placement.description}</p><small>{placement.contexts.join(' · ')}</small><em>{configured?.commercialAvailability==='AVAILABLE'?'DISPONÍVEL COMERCIALMENTE':configured?.commercialAvailability==='UNAVAILABLE'?'INDISPONÍVEL':'DISPONIBILIDADE NÃO CONFIRMADA'}</em></article>})}</div></Page></PreviewFrame>
  <PreviewFrame number={5}><Page number={5} eyebrow="INVENTÁRIO" title="INVENTÁRIO PUBLICITÁRIO"><div className="mk-inventory-grid">{PORTAL_ADVERTISING_INVENTORY.map(placement=>{const configured=kit.inventory.placements.find(item=>item.placementId===placement.id);return <article key={placement.id}><span>{placement.id}</span><h3>{placement.name}</h3><p>Componente: {placement.component}</p><p>Status técnico: {placement.implementationStatus}</p><p>Status comercial: {configured?.commercialAvailability||'UNKNOWN'}</p>{configured?.notes&&<p>{configured.notes}</p>}</article>})}</div></Page></PreviewFrame>
  <PreviewFrame number={6}><Page number={6} eyebrow="EDITORIAL" title="CONTEÚDO EDITORIAL"><div className="mk-lead"><p>O Portal Lander possui arquitetura editorial com hero, metadados, corpo da matéria, tags, compartilhamento, conteúdos relacionados e módulos laterais.</p><p>Este Mídia Kit não declara formatos inline, interstitial, takeover, pre-roll ou mid-roll sem implementação comprovada.</p></div><div className="mk-editorial-diagram"><span>MATÉRIA</span><b>CONTEÚDO PRINCIPAL</b><span>PUBLICIDADE LATERAL</span><span>MAIS LIDAS</span><span>LANÇAMENTOS</span></div></Page></PreviewFrame>
  <PreviewFrame number={7}><Page number={7} eyebrow="NEWSLETTER" title="NEWSLETTER"><div className="mk-lead"><p>{kit.newsletter.enabled?(kit.newsletter.description||'Canal de newsletter incluído com base na infraestrutura existente do Portal.'):'Newsletter não incluída nesta versão do documento.'}</p></div><div className="mk-status-card"><strong>{kit.newsletter.enabled?'CANAL HABILITADO NO MÍDIA KIT':'CANAL NÃO INCLUÍDO'}</strong><p>Contagem de inscritos, open rate, CTR e entregas não são exibidos sem fonte real confirmada.</p></div></Page></PreviewFrame>
  <PreviewFrame number={8}><Page number={8} eyebrow="DIGITAL" title="PRESENÇA DIGITAL"><div className="mk-lead"><p>{kit.social.channelIds.length?`Canais confirmados: ${kit.social.channelIds.join(', ')}.`:'Nenhum canal social foi promovido a verdade comercial nesta versão.'}</p></div><div className="mk-status-card"><strong>PROVENIÊNCIA PRIMEIRO</strong><p>Tipos de provider suportados ou fixtures de desenvolvimento não são apresentados como canais ativos.</p></div></Page></PreviewFrame>
  <PreviewFrame number={9}><Page number={9} eyebrow="CONTATO" title="DISPONÍVEL AGORA / EXPANSÕES FUTURAS"><div className="mk-contact-grid"><article><span>CONTATO COMERCIAL</span><strong>{kit.commercial.name||'RESPONSÁVEL NÃO INFORMADO'}</strong><p>{kit.commercial.email||'E-mail não informado'}</p><p>{kit.commercial.phone||'Telefone não informado'}</p></article><article><span>CAPACIDADES ATUAIS</span>{kit.roadmap.currentCapabilities.length?kit.roadmap.currentCapabilities.map(item=><p key={item}>{item}</p>):<p>Nenhuma capacidade adicional declarada.</p>}</article><article><span>EXPANSÕES FUTURAS</span>{kit.roadmap.futureOpportunities.length?kit.roadmap.futureOpportunities.map(item=><p key={item}>{item}</p>):<p>Sem oportunidades futuras declaradas nesta versão.</p>}</article></div><p className="mk-note">O fluxo público /anuncie permanece em preparação até existir um canal comercial persistente real.</p></Page></PreviewFrame>
 </main>
}

export const MEDIA_KIT_PAGE_COUNT=PAGE_COUNT
