import {RotateCcw} from 'lucide-react'
import {useMemo,useState,type CSSProperties} from 'react'
import {useParams} from 'react-router-dom'
import {homeReadModel,type HomeStory} from '../../../pages/home/models/homeReadModel'
import {editorialReadModel} from '../../editorial/repository'
import {AdminShell} from '../../../shared/internal/AdminUi'
import {publicSiteReadModel} from '../../../shared/data/publicSiteReadModel'
import {SITE_MANAGER_NAV} from '../../../shared/internal/adminNavigation'
import {SectionEditorField as Field,SectionEditorSaveBar,SectionEditorSummaryCard,SectionEditorTabButton as Tab,SectionViewportSwitch,type SectionEditorTabId as EditorTab} from '../components/SectionEditorUi'
import {SectionMediaField} from '../components/SectionMediaField'
import {sitePageRepository} from '../pageRepository'
import {EDITORIAL_PAGE_SECTION_DEFINITIONS,HOME_SECTION_DEFINITIONS,SPECIAL_PAGE_SECTION_DEFINITIONS,defaultSectionConfiguration,heroTextPadding,readSectionConfiguration,resetSectionConfiguration,writeSectionConfiguration,type SectionConfiguration,type SectionDefinition,type SectionHeroViewport} from '../sectionConfiguration'
import '../../../pages/home/styles/home-official-sections.css'
import '../../../styles/section-configuration-editor.css'
import '../../../styles/section-editor-workbench.css'
import '../../../styles/editorial-listing-layout.css'

type PreviewViewport=SectionHeroViewport
type PaddingElement='Kicker'|'Title'|'Description'
type PaddingAxis='X'|'Y'
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value))
const viewportLabel=(viewport:PreviewViewport)=>viewport==='desktop'?'Desktop':viewport==='tablet'?'Tablet':'Mobile'
const viewportSuffix=(viewport:PreviewViewport)=>viewport==='desktop'?'Desktop':viewport==='tablet'?'Tablet':'Mobile'
const paddingKey=(element:PaddingElement,axis:PaddingAxis,viewport:PreviewViewport)=>`hero${element}Padding${axis}${viewportSuffix(viewport)}` as keyof SectionConfiguration
function SectionHead({title,linkLabel}:{title:string;linkLabel?:string}){return <div className="pl-section-head"><h2>{title}</h2>{linkLabel&&<span>{linkLabel}</span>}</div>}
function ImageThumb({src,badge}:{src:string;badge?:string}){return <div className="pl-thumb has-image" style={{backgroundImage:`linear-gradient(180deg,transparent 55%,rgba(0,0,0,.72)),url(${src})`}}>{badge&&<span className="pl-badge">{badge}</span>}</div>}
function StoryCard({item}:{item:HomeStory}){return <article className="pl-card"><ImageThumb src={item.image} badge={item.category}/><div className="pl-card-body"><h3>{item.title}</h3><div className="pl-meta"><span>{item.meta}</span><span>◉ {item.views}</span></div></div></article>}
function PaddingControl({label,x,y,onX,onY}:{label:string;x:number;y:number;onX:(value:number)=>void;onY:(value:number)=>void}){return <div className="section-config-padding-card"><strong>{label}</strong><div className="section-config-two"><Field label={`Horizontal (X) · ${x}px`}><input type="number" min="0" max="240" step="1" value={x} onChange={event=>onX(clamp(Number(event.target.value)||0,0,240))}/></Field><Field label={`Vertical (Y) · ${y}px`}><input type="number" min="0" max="240" step="1" value={y} onChange={event=>onY(clamp(Number(event.target.value)||0,0,240))}/></Field></div></div>}

function StandardPreview({definition,config,viewport='desktop'}:{definition:SectionDefinition;config:SectionConfiguration;viewport?:PreviewViewport}){
  const limit=Math.max(1,Math.min(12,config.itemLimit||1)),columns=Math.max(1,Math.min(4,config.columns||1))
  const commonStyle={background:config.background,color:config.textColor,textAlign:config.textAlign as 'left'|'center'|'right'}
  const heroHeight=viewport==='desktop'?config.heroHeightDesktop:viewport==='tablet'?config.heroHeightTablet:config.heroHeightMobile
  const padding=heroTextPadding(config,viewport)
  const heroHeightStyle={height:`${heroHeight}px`,minHeight:`${heroHeight}px`,maxHeight:`${heroHeight}px`} as CSSProperties
  const kickerStyle={color:config.accentColor,padding:`${padding.kicker.y}px ${padding.kicker.x}px`} as CSSProperties
  const titleStyle={padding:`${padding.title.y}px ${padding.title.x}px`} as CSSProperties
  const descriptionStyle={padding:`${padding.description.y}px ${padding.description.x}px`} as CSSProperties
  if(!config.active)return <div className="section-preview-disabled">Esta seção está oculta. Ative-a no painel à esquerda para visualizar o resultado.</div>
  if(definition.kind==='featured')return <section className="pl-section official-em-destaque section-preview-real" style={commonStyle}><SectionHead title={config.title} linkLabel={config.linkLabel}/><div className="pl-card-grid" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{homeReadModel.featuredStories.slice(0,limit).map(story=><StoryCard key={story.title} item={story}/>)}</div></section>
  if(definition.kind==='latest')return <section className="pl-section official-ultimas-noticias section-preview-real" style={commonStyle}><SectionHead title={config.title} linkLabel={config.linkLabel}/><div className="pl-latest-grid" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{homeReadModel.latestStories.slice(0,limit).map(story=><StoryCard key={story.title} item={story}/>)}</div></section>
  if(definition.kind==='ranking')return <section className="pl-most official-mais-lidas section-preview-real" style={commonStyle}><SectionHead title={config.title}/>{homeReadModel.mostRead.slice(0,limit).map((item,index)=><div className="pl-ranked" key={item}><strong>{String(index+1).padStart(2,'0')}</strong><div><h4>{item}</h4><small>Há {index+3} horas</small></div></div>)}</section>
  if(definition.kind==='trending')return <section className="pl-trending official-em-alta section-preview-real" style={commonStyle}><SectionHead title={config.title} linkLabel={config.linkLabel}/><div className="pl-trending-list">{homeReadModel.mostRead.slice(0,limit).map((item,index)=><div className="pl-trending-item" key={item}><span className="pl-trending-rank">{String(index+1).padStart(2,'0')}</span><div><strong>{item}</strong><small>Há {index+3} horas</small></div></div>)}</div></section>
  if(definition.kind==='agenda')return <section className="pl-agenda official-agenda section-preview-real" style={commonStyle}><SectionHead title={config.title}/>{homeReadModel.agenda.slice(0,limit).map(item=><div className="pl-agenda-item" key={item.title}><div><strong>{item.day}</strong><span>{item.month}</span></div><div><b>{item.title}</b><small>{item.place}</small></div></div>)}</section>
  if(definition.kind==='ad')return <section className="section-preview-ad"><div className="editorial-advertising-card" style={{background:config.background,color:config.textColor}}>{config.imageUrl?<img className="editorial-advertising-image" src={config.imageUrl} alt="Preview da publicidade"/>:<div className="editorial-advertising-placeholder">CARREGUE A ARTE DA PUBLICIDADE</div>}<div className="editorial-advertising-copy">{config.eyebrow&&<small style={{color:config.accentColor}}>{config.eyebrow}</small>}{config.title&&<strong>{config.title}</strong>}{config.description&&<p>{config.description}</p>}{config.linkLabel&&<span className="editorial-advertising-link" style={{borderColor:config.accentColor,color:config.accentColor}}>{config.linkLabel}</span>}</div></div></section>
  if(definition.kind==='cta')return <section className="section-preview-cta" style={commonStyle}>{config.imageUrl&&<img src={config.imageUrl} alt=""/>}<div><small style={{color:config.accentColor}}>{config.eyebrow}</small><h2>{config.title}</h2>{config.description&&<p>{config.description}</p>}{config.linkLabel&&<span className="section-preview-cta-button" style={{background:config.accentColor}}>{config.linkLabel}</span>}</div></section>
  if(definition.kind==='editorial')return <section className="section-preview-editorial" style={commonStyle}><div className="section-preview-editorial-head"><div><small>NOTÍCIAS</small><h2>{config.title}</h2><p>{config.description}</p></div></div><div className="section-preview-editorial-grid" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{homeReadModel.stories.slice(0,Math.min(limit,6)).map(story=><StoryCard key={story.title} item={story}/>)}</div></section>
  if(definition.kind==='standard-hero')return <section className={`public-standard-page-hero section-preview-special pl-responsive-hero preview-${viewport}`} style={{...commonStyle,...heroHeightStyle,...(config.imageUrl?{backgroundImage:`linear-gradient(rgba(0,0,0,.48),rgba(0,0,0,.48)),url(${config.imageUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:{})}}><div className="public-shell"><div className="news-page-intro-copy"><span style={kickerStyle}>{config.eyebrow}</span><h1 style={titleStyle}>{config.title}</h1><p style={descriptionStyle}>{config.description}</p></div></div></section>
  if(definition.kind==='body')return <section className="public-shell article-shell section-preview-special-body" style={commonStyle}><article className="article-content">{config.eyebrow&&<span style={{color:config.accentColor}}>{config.eyebrow}</span>}<h2>{config.title}</h2><p>{config.description}</p></article></section>
  if(definition.kind==='channels'){const channels=publicSiteReadModel.socialChannels().slice(0,limit);return <section className="public-shell pl-page section-preview-special-body" style={commonStyle}><div className="pl-page-hero"><div className="news-page-intro-copy"><h2>{config.title}</h2><p>{config.description}</p></div></div><div className="news-reference-grid editorial-listing-grid" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{channels.map(channel=><article className="pl-card news-reference-card" key={channel.id}><div className="pl-card-body news-reference-card-body"><h3>{channel.label}</h3><p>{channel.network.toUpperCase()}</p></div></article>)}</div></section>}
  if(definition.kind==='guidelines'){const guidelines=publicSiteReadModel.collaborationGuidelines().slice(0,limit);return <section className="public-shell colabore-content section-preview-special-body" style={commonStyle}><div className="colabore-guidelines"><div className="colabore-guidelines-copy"><span style={{color:config.accentColor}}>{config.eyebrow}</span><h2>{config.title}</h2><p>{config.description}</p></div>{guidelines.map(item=><div className="colabore-guideline" key={item.id}><b>{String(item.order).padStart(2,'0')}</b><span>{item.title}</span></div>)}</div></section>}
  if(definition.kind==='form')return <section className="section-preview-form" style={commonStyle}><div><small style={{color:config.accentColor}}>FORMULÁRIO</small><h2>{config.title}</h2><p>{config.description}</p></div><div className="section-preview-form-fields"><label>Nome<input disabled placeholder="Seu nome"/></label><label>E-mail<input disabled placeholder="seu@email.com"/></label><label>Mensagem<textarea disabled rows={4}/></label><button type="button" disabled>ENVIAR MATERIAL</button></div></section>
  return <section className="section-preview-custom" style={commonStyle}>{config.imageUrl&&<img src={config.imageUrl} alt=""/>}<div><small style={{color:config.accentColor}}>{config.eyebrow}</small><h2>{config.title}</h2>{config.description&&<p>{config.description}</p>}</div></section>
}

export function SectionConfigurationPage(){
  const {pageId='home',sectionId=''}=useParams()
  const page=editorialReadModel.pages.find(item=>item.id===pageId),localPage=sitePageRepository.listDraftPages().find(item=>item.id===pageId)
  const homeDefinition=HOME_SECTION_DEFINITIONS.find(item=>item.id===sectionId),editorialDefinition=EDITORIAL_PAGE_SECTION_DEFINITIONS.find(item=>item.id===sectionId),specialDefinition=Object.values(SPECIAL_PAGE_SECTION_DEFINITIONS).flat().find(item=>item.id===sectionId),custom=sitePageRepository.listSections()[pageId]?.find(item=>item.id===sectionId)
  const definition:SectionDefinition=homeDefinition??editorialDefinition??specialDefinition??{id:sectionId,name:custom?.name||'Seção personalizada',summary:custom?`Seção própria configurável de ${custom.name}.`:'Seção configurável da página.',kind:'custom'}
  const configOwnerId=sectionId==='editorial-template'?'editorial-template':pageId
  const fallback=useMemo<Partial<SectionConfiguration>|undefined>(()=>sectionId==='editorial-hero'?{title:(page?.title||localPage?.title||'Página').toUpperCase(),description:page?.description||'',eyebrow:'AGORA NO PORTAL'}:undefined,[sectionId,page?.title,page?.description,localPage?.title])
  const configName=sectionId==='editorial-hero'?(page?.title||localPage?.title||definition.name):definition.name
  const initial=()=>readSectionConfiguration(configOwnerId,sectionId,configName,fallback)
  const [config,setConfig]=useState<SectionConfiguration>(initial),[persisted,setPersisted]=useState<SectionConfiguration>(initial),[previewViewport,setPreviewViewport]=useState<PreviewViewport>('desktop'),[tab,setTab]=useState<EditorTab>('content'),[saved,setSaved]=useState(false)
  const patch=(next:Partial<SectionConfiguration>)=>{setConfig(current=>({...current,...next}));setSaved(false)}
  const save=()=>{writeSectionConfiguration(configOwnerId,sectionId,config);setPersisted(config);setSaved(true)}
  const discard=()=>{setConfig(persisted);setSaved(false)}
  const reset=()=>{resetSectionConfiguration(configOwnerId,sectionId);setConfig(defaultSectionConfiguration(sectionId,configName,fallback));setSaved(false)}
  const dirty=JSON.stringify(config)!==JSON.stringify(persisted)
  const listKind=['featured','ranking','latest','trending','agenda','channels','guidelines','editorial'].includes(definition.kind),linkKind=['featured','ranking','latest','trending','agenda','ad','cta','custom'].includes(definition.kind),imageKind=['ad','cta','standard-hero','body','custom'].includes(definition.kind),responsiveHeroKind=definition.kind==='standard-hero'
  const currentPadding=heroTextPadding(config,previewViewport);const patchPadding=(element:PaddingElement,axis:PaddingAxis,value:number)=>patch({[paddingKey(element,axis,previewViewport)]:value} as Partial<SectionConfiguration>)
  return <AdminShell area="cms" items={SITE_MANAGER_NAV} header={{title:`Configurar seção: ${definition.name}`,description:`Configure ${definition.name} no painel rolável à esquerda e acompanhe o preview fixo à direita.`,backTo:'/app/site/paginas',backLabel:'Páginas'}}>
    <div className="section-editor-workbench"><div className="section-editor-rail"><SectionEditorSummaryCard eyebrow={definition.name.toUpperCase()} description={definition.summary} active={config.active} onActiveChange={active=>patch({active})}/><div className="section-editor-tabs"><Tab active={tab==='content'} label="Conteúdo" onClick={()=>setTab('content')}/><Tab active={tab==='appearance'} label="Aparência" onClick={()=>setTab('appearance')}/><Tab active={tab==='behavior'} label="Comportamento" onClick={()=>setTab('behavior')}/></div><section className="section-editor-card section-editor-detail">
      {tab==='content'&&<><div className="section-editor-card-head"><h3>Conteúdo</h3><p>Edite somente os campos funcionais desta seção.</p></div><div className="section-config-fields"><Field label="Título"><input value={config.title} onChange={event=>patch({title:event.target.value})}/></Field><Field label="Chamada / kicker"><input value={config.eyebrow} onChange={event=>patch({eyebrow:event.target.value})} placeholder="Opcional"/></Field><Field label="Descrição"><textarea rows={4} value={config.description} onChange={event=>patch({description:event.target.value})} placeholder="Texto opcional da seção"/></Field>{linkKind&&<div className="section-config-two"><Field label="Texto do botão / link"><input value={config.linkLabel} onChange={event=>patch({linkLabel:event.target.value})}/></Field><Field label="Destino"><input value={config.linkUrl} onChange={event=>patch({linkUrl:event.target.value})} placeholder="/noticias"/></Field></div>}{imageKind&&<SectionMediaField value={config.imageUrl} onChange={imageUrl=>patch({imageUrl})} label={definition.kind==='ad'?'Arte da publicidade':'Imagem / mídia'}/>} {listKind&&<div className="section-config-two"><Field label="Quantidade de itens"><input type="number" min="1" max="12" value={config.itemLimit} onChange={event=>patch({itemLimit:Number(event.target.value)||1})}/></Field><Field label="Colunas"><select value={config.columns} onChange={event=>patch({columns:Number(event.target.value)})}><option value="1">1 coluna</option><option value="2">2 colunas</option><option value="3">3 colunas</option><option value="4">4 colunas</option></select></Field></div>}</div></>}
      {tab==='appearance'&&<><div className="section-editor-card-head"><h3>Aparência{responsiveHeroKind?` · ${viewportLabel(previewViewport)}`:''}</h3><p>Tipografia, campos e tokens seguem o padrão canônico do módulo.</p></div><div className="section-config-fields">{responsiveHeroKind&&<><div className="section-config-responsive-heights"><strong>Altura da Hero por dispositivo</strong><div className="section-config-three"><Field label="Desktop (px)"><input type="number" min="240" max="900" step="10" value={config.heroHeightDesktop} onFocus={()=>setPreviewViewport('desktop')} onChange={event=>patch({heroHeightDesktop:clamp(Number(event.target.value)||420,240,900)})}/></Field><Field label="Tablet (px)"><input type="number" min="220" max="800" step="10" value={config.heroHeightTablet} onFocus={()=>setPreviewViewport('tablet')} onChange={event=>patch({heroHeightTablet:clamp(Number(event.target.value)||340,220,800)})}/></Field><Field label="Mobile (px)"><input type="number" min="200" max="700" step="10" value={config.heroHeightMobile} onFocus={()=>setPreviewViewport('mobile')} onChange={event=>patch({heroHeightMobile:clamp(Number(event.target.value)||280,200,700)})}/></Field></div></div><div className="section-config-responsive-padding"><strong>Padding dos textos · {viewportLabel(previewViewport)}</strong><PaddingControl label="Chamada / kicker" x={currentPadding.kicker.x} y={currentPadding.kicker.y} onX={value=>patchPadding('Kicker','X',value)} onY={value=>patchPadding('Kicker','Y',value)}/><PaddingControl label="Título" x={currentPadding.title.x} y={currentPadding.title.y} onX={value=>patchPadding('Title','X',value)} onY={value=>patchPadding('Title','Y',value)}/><PaddingControl label="Descrição" x={currentPadding.description.x} y={currentPadding.description.y} onX={value=>patchPadding('Description','X',value)} onY={value=>patchPadding('Description','Y',value)}/></div></>}<Field label="Alinhamento"><select value={config.textAlign} onChange={event=>patch({textAlign:event.target.value as SectionConfiguration['textAlign']})}><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></Field><div className="section-config-colors"><Field label="Fundo"><input type="color" value={config.background} onChange={event=>patch({background:event.target.value})}/></Field><Field label="Texto"><input type="color" value={config.textColor} onChange={event=>patch({textColor:event.target.value})}/></Field><Field label="Destaque"><input type="color" value={config.accentColor} onChange={event=>patch({accentColor:event.target.value})}/></Field></div></div></>}
      {tab==='behavior'&&<><div className="section-editor-card-head"><h3>Comportamento</h3><p>Estado e responsividade usam o mesmo contexto de dispositivo do preview.</p></div><div className="section-config-fields"><div className="section-editor-rule"><strong>Viewport ativo</strong><p>{viewportLabel(previewViewport)}. O preview usa a largura canônica do dispositivo selecionado.</p><span className="section-editor-device-badge">{viewportLabel(previewViewport)}</span></div></div></>}
    </section><div className="section-editor-actions"><button type="button" className="button outline" onClick={reset}><RotateCcw size={15}/> Restaurar padrão</button></div>{saved&&<div className="section-config-success">Configuração salva com sucesso.</div>}</div>
    <section className="section-editor-preview"><div className="section-editor-preview-head"><div><h2>Preview da seção</h2><p>{viewportLabel(previewViewport)} · edição em tempo real · alterações refletidas antes de salvar.</p></div><SectionViewportSwitch viewport={previewViewport} onChange={setPreviewViewport}/></div><div className="section-editor-preview-canvas section-config-preview-frame responsive-device-preview"><div className={`section-preview-device-canvas ${previewViewport}`}><StandardPreview definition={definition} config={config} viewport={previewViewport}/></div></div></section></div>
    <SectionEditorSaveBar dirty={dirty} saved={saved} onDiscard={discard} onSave={save} dirtyText="O rascunho permanece separado do estado salvo até confirmar." cleanText="O estado salvo continua sendo usado pela versão pública."/>
  </AdminShell>
}
