import {CalendarDays,ChevronLeft,ChevronRight,DollarSign,FileText,MoreHorizontal,Palmtree,Plus,Search,Trash2,Upload,UserCheck,UserX,Users,X} from 'lucide-react'
import {useMemo,useState,type FormEvent,type ReactNode} from 'react'
import {AdminShell} from '../../shared/internal/AdminUi'
import {UNIFIED_ADMIN_NAV} from '../../shared/internal/adminNavigation'
import {dateLabel,money,type ContractType,type Employee,type EmployeeStatus,type LeaveEntry,type LeaveStatus,type PayrollEntry,type PayrollStatus,type RhSeed} from './domain'
import {useDeleteEmployees,useDeleteLeaves,useDeletePayroll,useDeleteRhDocument,useRhState,useSaveEmployee,useSaveLeave,useSavePayroll} from './hooks'
import './rh.css'

type Tab='employees'|'payroll'|'leaves'|'documents'
type EmployeeEditor=Employee|null|undefined
type PayrollEditor=PayrollEntry|null|undefined
type LeaveEditor=LeaveEntry|null|undefined
const PAGE_SIZE=10
const EMPTY:RhSeed={employees:[],payroll:[],leaves:[],documents:[],departments:['Administrativo','Comercial','Financeiro','Marketing','Operações','Tecnologia'],documentTypes:['Contrato de Trabalho','Documento Pessoal','Atestado','Comprovante','Certificado','Outro'],leaveTypes:['férias','atestado','licença médica','licença maternidade/paternidade','falta justificada','afastamento']}
const statusLabel=(value:string)=>value?value.charAt(0).toUpperCase()+value.slice(1):'—'
const monthLabel=(value:string)=>{if(!value)return '—';const [y,m]=value.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}
const paginate=<T,>(items:T[],page:number)=>items.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)

export default function RHPage(){
 const stateQuery=useRhState(),state=stateQuery.data??EMPTY
 const saveEmployee=useSaveEmployee(),deleteEmployees=useDeleteEmployees(),savePayroll=useSavePayroll(),deletePayroll=useDeletePayroll(),saveLeave=useSaveLeave(),deleteLeaves=useDeleteLeaves(),deleteDocument=useDeleteRhDocument()
 const [tab,setTab]=useState<Tab>('employees'),[employeeEditor,setEmployeeEditor]=useState<EmployeeEditor>(undefined),[employeeView,setEmployeeView]=useState<Employee|null>(null),[payrollEditor,setPayrollEditor]=useState<PayrollEditor>(undefined),[payrollView,setPayrollView]=useState<PayrollEntry|null>(null),[leaveEditor,setLeaveEditor]=useState<LeaveEditor>(undefined),[leaveView,setLeaveView]=useState<LeaveEntry|null>(null)
 const [employeeSearch,setEmployeeSearch]=useState(''),[employeeStatus,setEmployeeStatus]=useState('all'),[department,setDepartment]=useState('all'),[payrollSearch,setPayrollSearch]=useState(''),[payrollMonth,setPayrollMonth]=useState(''),[payrollStatus,setPayrollStatus]=useState('all'),[leaveSearch,setLeaveSearch]=useState(''),[leaveStatus,setLeaveStatus]=useState('all'),[documentEmployee,setDocumentEmployee]=useState('')
 const [employeePage,setEmployeePage]=useState(1),[payrollPage,setPayrollPage]=useState(1),[leavePage,setLeavePage]=useState(1),[selectedEmployees,setSelectedEmployees]=useState<string[]>([]),[selectedPayroll,setSelectedPayroll]=useState<string[]>([]),[selectedLeaves,setSelectedLeaves]=useState<string[]>([])
 const employeeNames=useMemo(()=>new Map(state.employees.map(item=>[item.id,item.name])),[state.employees])
 const counts={total:state.employees.length,active:state.employees.filter(x=>x.status==='ativo').length,vacation:state.employees.filter(x=>x.status==='férias').length,away:state.employees.filter(x=>x.status==='afastado').length}
 const employees=useMemo(()=>state.employees.filter(x=>(!employeeSearch||[x.name,x.email,x.role,x.cpf].some(v=>v.toLowerCase().includes(employeeSearch.toLowerCase())))&&(employeeStatus==='all'||x.status===employeeStatus)&&(department==='all'||x.department===department)),[state.employees,employeeSearch,employeeStatus,department])
 const payroll=useMemo(()=>state.payroll.filter(x=>(!payrollSearch||[employeeNames.get(x.employeeId)||'',x.referenceMonth].some(v=>v.toLowerCase().includes(payrollSearch.toLowerCase())))&&(!payrollMonth||x.referenceMonth===payrollMonth)&&(payrollStatus==='all'||x.status===payrollStatus)),[state.payroll,employeeNames,payrollSearch,payrollMonth,payrollStatus])
 const leaves=useMemo(()=>state.leaves.filter(x=>(!leaveSearch||[employeeNames.get(x.employeeId)||'',x.type].some(v=>v.toLowerCase().includes(leaveSearch.toLowerCase())))&&(leaveStatus==='all'||x.status===leaveStatus)),[state.leaves,employeeNames,leaveSearch,leaveStatus])
 const docs=state.documents.filter(x=>x.employeeId===documentEmployee)
 const newAction=tab==='employees'?()=>setEmployeeEditor(null):tab==='payroll'?()=>setPayrollEditor(null):tab==='leaves'?()=>setLeaveEditor(null):undefined
 const newLabel=tab==='employees'?'Novo Funcionário':tab==='payroll'?'Novo Registro':tab==='leaves'?'Nova Férias/Ausência':''
 const error=[stateQuery.error,saveEmployee.error,deleteEmployees.error,savePayroll.error,deletePayroll.error,saveLeave.error,deleteLeaves.error,deleteDocument.error].find(Boolean)
 return <AdminShell area="rh" items={UNIFIED_ADMIN_NAV} header={{title:'Recursos Humanos',description:'Gestão de funcionários, folha de pagamento, férias e documentos'}} headerActions={newAction?[{label:newLabel,icon:Plus,onClick:newAction}]:[]}>
  <section className="rh-page">
   {stateQuery.isLoading&&<div className="rh-empty-card"><strong>Carregando Recursos Humanos…</strong></div>}
   {stateQuery.isError&&<div className="rh-empty-card"><strong>RH indisponível</strong><p>{stateQuery.error instanceof Error?stateQuery.error.message:'Não foi possível carregar os dados.'}</p><button className="button outline" onClick={()=>void stateQuery.refetch()}>Tentar novamente</button></div>}
   {error&&!stateQuery.isError&&<div className="rh-empty-card"><strong>Não foi possível concluir a última ação.</strong><p>{error instanceof Error?error.message:'Erro desconhecido.'}</p></div>}
   {!stateQuery.isError&&<>
    <div className="rh-kpis"><Kpi icon={<Users/>} label="Total de Funcionários" value={counts.total} detail="cadastros da equipe"/><Kpi icon={<UserCheck/>} label="Ativos" value={counts.active} detail="em atividade"/><Kpi icon={<Palmtree/>} label="Em Férias" value={counts.vacation} detail="afastamento por férias"/><Kpi icon={<UserX/>} label="Afastados" value={counts.away} detail="afastamentos ativos"/></div>
    <div className="rh-tabs" role="tablist"><TabButton active={tab==='employees'} onClick={()=>setTab('employees')} icon={<Users/>}>Funcionários</TabButton><TabButton active={tab==='payroll'} onClick={()=>setTab('payroll')} icon={<DollarSign/>}>Folha de Pagamento</TabButton><TabButton active={tab==='leaves'} onClick={()=>setTab('leaves')} icon={<CalendarDays/>}>Férias e Ausências</TabButton><TabButton active={tab==='documents'} onClick={()=>setTab('documents')} icon={<FileText/>}>Documentos</TabButton></div>
    {tab==='employees'&&<><div className="rh-filters"><SearchBox value={employeeSearch} onChange={v=>{setEmployeeSearch(v);setEmployeePage(1)}} placeholder="Buscar por nome, email, cargo, CPF..."/><select value={employeeStatus} onChange={e=>{setEmployeeStatus(e.target.value);setEmployeePage(1)}}><option value="all">Todos os status</option>{['ativo','inativo','férias','afastado','desligado'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select><select value={department} onChange={e=>{setDepartment(e.target.value);setEmployeePage(1)}}><option value="all">Todos os setores</option>{state.departments.map(x=><option key={x}>{x}</option>)}</select></div><TableCard title="Lista de Funcionários" description="Acompanhe funcionários, cargos, setores, vínculo, salário, status e usuário associado." count={employees.length} selectedCount={selectedEmployees.length} onBulkDelete={()=>void deleteEmployees.mutateAsync(selectedEmployees).then(()=>setSelectedEmployees([]))}><table className="rh-table"><thead><tr><CheckHead checked={paginate(employees,employeePage).length>0&&paginate(employees,employeePage).every(x=>selectedEmployees.includes(x.id))} onChange={checked=>setSelectedEmployees(checked?Array.from(new Set([...selectedEmployees,...paginate(employees,employeePage).map(x=>x.id)])):selectedEmployees.filter(id=>!paginate(employees,employeePage).some(x=>x.id===id)))}/><th>Nome</th><th>Cargo</th><th>Setor</th><th>Tipo</th><th className="numeric">Salário</th><th>Status</th><th>Usuário</th><th>Ações</th></tr></thead><tbody>{paginate(employees,employeePage).map(x=><tr key={x.id}><CheckCell checked={selectedEmployees.includes(x.id)} onChange={()=>setSelectedEmployees(selectedEmployees.includes(x.id)?selectedEmployees.filter(id=>id!==x.id):[...selectedEmployees,x.id])}/><td><strong>{x.name}</strong><small>{x.email}</small></td><td>{x.role||'—'}</td><td>{x.department||'—'}</td><td>{x.contractType}</td><td className="numeric">{money(x.baseSalary)}</td><td><Status value={x.status}/></td><td>{x.linkedUser||'—'}</td><td><RowActions onView={()=>setEmployeeView(x)} onEdit={()=>setEmployeeEditor(x)} onDelete={()=>void deleteEmployees.mutateAsync([x.id])}/></td></tr>)}</tbody></table><EmptyRows empty={!employees.length} text="Nenhum funcionário encontrado."/><Pagination page={employeePage} total={employees.length} onChange={setEmployeePage}/></TableCard></>}
    {tab==='payroll'&&<><div className="rh-filters"><input type="month" value={payrollMonth} onChange={e=>{setPayrollMonth(e.target.value);setPayrollPage(1)}}/><SearchBox value={payrollSearch} onChange={v=>{setPayrollSearch(v);setPayrollPage(1)}} placeholder="Buscar por funcionário ou mês..."/><select value={payrollStatus} onChange={e=>{setPayrollStatus(e.target.value);setPayrollPage(1)}}><option value="all">Todos os status</option>{['pendente','processado','pago','cancelado'].map(x=><option key={x}>{x}</option>)}</select></div><TableCard title="Folha de Pagamento" description="Acompanhe salários, descontos, bônus, valores líquidos, status e datas de pagamento." count={payroll.length} selectedCount={selectedPayroll.length} onBulkDelete={()=>void deletePayroll.mutateAsync(selectedPayroll).then(()=>setSelectedPayroll([]))}><table className="rh-table"><thead><tr><CheckHead checked={paginate(payroll,payrollPage).length>0&&paginate(payroll,payrollPage).every(x=>selectedPayroll.includes(x.id))} onChange={checked=>setSelectedPayroll(checked?Array.from(new Set([...selectedPayroll,...paginate(payroll,payrollPage).map(x=>x.id)])):selectedPayroll.filter(id=>!paginate(payroll,payrollPage).some(x=>x.id===id)))}/><th>Funcionário</th><th>Mês Ref.</th><th className="numeric">Bruto</th><th className="numeric">Descontos</th><th className="numeric">Bônus</th><th className="numeric">Líquido</th><th>Pagamento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{paginate(payroll,payrollPage).map(x=><tr key={x.id}><CheckCell checked={selectedPayroll.includes(x.id)} onChange={()=>setSelectedPayroll(selectedPayroll.includes(x.id)?selectedPayroll.filter(id=>id!==x.id):[...selectedPayroll,x.id])}/><td><strong>{employeeNames.get(x.employeeId)||'Funcionário não encontrado'}</strong></td><td>{monthLabel(x.referenceMonth)}</td><td className="numeric">{money(x.grossSalary)}</td><td className="numeric negative">{money(x.discounts)}</td><td className="numeric positive">{money(x.bonus)}</td><td className="numeric"><strong>{money(x.netSalary)}</strong></td><td>{dateLabel(x.paymentDate)}</td><td><Status value={x.status}/></td><td><RowActions onView={()=>setPayrollView(x)} onEdit={()=>setPayrollEditor(x)} onDelete={()=>void deletePayroll.mutateAsync([x.id])}/></td></tr>)}</tbody></table><EmptyRows empty={!payroll.length} text="Nenhum registro de pagamento encontrado."/><Pagination page={payrollPage} total={payroll.length} onChange={setPayrollPage}/></TableCard></>}
    {tab==='leaves'&&<><div className="rh-filters"><SearchBox value={leaveSearch} onChange={v=>{setLeaveSearch(v);setLeavePage(1)}} placeholder="Buscar por funcionário ou tipo..."/><select value={leaveStatus} onChange={e=>{setLeaveStatus(e.target.value);setLeavePage(1)}}><option value="all">Todos os status</option>{['pendente','aprovado','rejeitado','em andamento','concluído'].map(x=><option key={x}>{x}</option>)}</select></div><TableCard title="Férias e Ausências" description="Acompanhe solicitações de férias, ausências, períodos, quantidade de dias e status de aprovação." count={leaves.length} selectedCount={selectedLeaves.length} onBulkDelete={()=>void deleteLeaves.mutateAsync(selectedLeaves).then(()=>setSelectedLeaves([]))}><table className="rh-table"><thead><tr><CheckHead checked={paginate(leaves,leavePage).length>0&&paginate(leaves,leavePage).every(x=>selectedLeaves.includes(x.id))} onChange={checked=>setSelectedLeaves(checked?Array.from(new Set([...selectedLeaves,...paginate(leaves,leavePage).map(x=>x.id)])):selectedLeaves.filter(id=>!paginate(leaves,leavePage).some(x=>x.id===id)))}/><th>Funcionário</th><th>Tipo</th><th>Início</th><th>Fim</th><th className="numeric">Dias</th><th>Status</th><th>Ações</th></tr></thead><tbody>{paginate(leaves,leavePage).map(x=><tr key={x.id}><CheckCell checked={selectedLeaves.includes(x.id)} onChange={()=>setSelectedLeaves(selectedLeaves.includes(x.id)?selectedLeaves.filter(id=>id!==x.id):[...selectedLeaves,x.id])}/><td><strong>{employeeNames.get(x.employeeId)||'Funcionário não encontrado'}</strong></td><td>{statusLabel(x.type)}</td><td>{dateLabel(x.startDate)}</td><td>{dateLabel(x.endDate)}</td><td className="numeric">{x.days}</td><td><Status value={x.status}/></td><td><RowActions onView={()=>setLeaveView(x)} onEdit={()=>setLeaveEditor(x)} onDelete={()=>void deleteLeaves.mutateAsync([x.id])}/></td></tr>)}</tbody></table><EmptyRows empty={!leaves.length} text="Nenhum registro de férias/ausência encontrado."/><Pagination page={leavePage} total={leaves.length} onChange={setLeavePage}/></TableCard></>}
    {tab==='documents'&&<section className="rh-docs"><div className="rh-doc-selector"><label><span>Funcionário</span><select value={documentEmployee} onChange={e=>setDocumentEmployee(e.target.value)}><option value="">Selecione um funcionário</option>{state.employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>{!documentEmployee?<div className="rh-empty-card"><FileText/><strong>Selecione um funcionário</strong><p>Escolha um funcionário acima para visualizar seus documentos.</p></div>:<><section className="rh-upload-card"><h3>Enviar Novo Documento</h3><button className="rh-upload-zone" disabled title="Storage persistente de documentos ainda não configurado"><Upload/><strong>Upload de documentos ainda não disponível neste ambiente.</strong><span>Nenhum arquivo ou metadata fictícia será salvo.</span></button></section><TableCard title="Documentos" description="Documentos previamente persistidos no domínio de RH." count={docs.length}><table className="rh-table"><thead><tr><th>Tipo</th><th>Arquivo</th><th>Descrição</th><th>Data</th><th>Ações</th></tr></thead><tbody>{docs.map(x=><tr key={x.id}><td><Status value={x.type}/></td><td><strong>{x.fileName}</strong></td><td>{x.description||'—'}</td><td>{new Date(x.createdAt).toLocaleDateString('pt-BR')}</td><td><button className="rh-icon negative" onClick={()=>void deleteDocument.mutateAsync(x.id)} title="Excluir"><Trash2 size={15}/></button></td></tr>)}</tbody></table><EmptyRows empty={!docs.length} text="Nenhum documento persistido para este funcionário."/></TableCard></>}</section>}
   </>}
  </section>
  {employeeEditor!==undefined&&<EmployeeModal value={employeeEditor} state={state} busy={saveEmployee.isPending} onClose={()=>setEmployeeEditor(undefined)} onSave={async(value,id)=>{await saveEmployee.mutateAsync({value,id});setEmployeeEditor(undefined)}}/>}
  {payrollEditor!==undefined&&<PayrollModal value={payrollEditor} state={state} busy={savePayroll.isPending} onClose={()=>setPayrollEditor(undefined)} onSave={async(value,id)=>{await savePayroll.mutateAsync({value,id});setPayrollEditor(undefined)}}/>}
  {leaveEditor!==undefined&&<LeaveModal value={leaveEditor} state={state} busy={saveLeave.isPending} onClose={()=>setLeaveEditor(undefined)} onSave={async(value,id)=>{await saveLeave.mutateAsync({value,id});setLeaveEditor(undefined)}}/>}
  {employeeView&&<ViewModal title="Funcionário" onClose={()=>setEmployeeView(null)} rows={[['Nome',employeeView.name],['E-mail',employeeView.email||'—'],['Cargo',employeeView.role||'—'],['Setor',employeeView.department||'—'],['Contrato',employeeView.contractType],['Admissão',dateLabel(employeeView.admissionDate)],['Salário',money(employeeView.baseSalary)],['Status',statusLabel(employeeView.status)],['Telefone',employeeView.phone||'—'],['CPF',employeeView.cpf||'—']]}/>} 
  {payrollView&&<ViewModal title="Registro de Pagamento" onClose={()=>setPayrollView(null)} rows={[['Funcionário',employeeNames.get(payrollView.employeeId)||'—'],['Mês',monthLabel(payrollView.referenceMonth)],['Bruto',money(payrollView.grossSalary)],['Descontos',money(payrollView.discounts)],['Bônus',money(payrollView.bonus)],['Líquido',money(payrollView.netSalary)],['Pagamento',dateLabel(payrollView.paymentDate)],['Status',statusLabel(payrollView.status)]]}/>} 
  {leaveView&&<ViewModal title="Férias / Ausência" onClose={()=>setLeaveView(null)} rows={[['Funcionário',employeeNames.get(leaveView.employeeId)||'—'],['Tipo',statusLabel(leaveView.type)],['Início',dateLabel(leaveView.startDate)],['Fim',dateLabel(leaveView.endDate)],['Dias',String(leaveView.days)],['Status',statusLabel(leaveView.status)],['Aprovado por',leaveView.approvedByDisplayName||leaveView.approvedBy||'—'],['Aprovado em',leaveView.approvedAt?new Date(leaveView.approvedAt).toLocaleString('pt-BR'):'—']]}/>} 
 </AdminShell>
}

function Kpi({icon,label,value,detail}:{icon:ReactNode;label:string;value:number;detail:string}){return <article className="rh-kpi"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{detail}</em></div></article>}
function TabButton({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:ReactNode;children:ReactNode}){return <button role="tab" aria-selected={active} className={active?'active':''} onClick={onClick}>{icon}{children}</button>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}){return <label className="rh-search"><Search size={15}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Status({value}:{value:string}){return <span className={`rh-status ${value.toLowerCase().replaceAll(' ','-')}`}>{statusLabel(value)}</span>}
function CheckHead({checked,onChange}:{checked:boolean;onChange:(checked:boolean)=>void}){return <th className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} aria-label="Selecionar página"/></th>}
function CheckCell({checked,onChange}:{checked:boolean;onChange:()=>void}){return <td className="check"><input type="checkbox" checked={checked} onChange={onChange} aria-label="Selecionar registro"/></td>}
function RowActions({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){return <div className="rh-row-actions"><button onClick={onView} title="Visualizar"><MoreHorizontal size={15}/></button><button onClick={onEdit}>Editar</button><button className="negative" onClick={onDelete} title="Excluir"><Trash2 size={14}/></button></div>}
function EmptyRows({empty,text}:{empty:boolean;text:string}){return empty?<div className="rh-empty-inline">{text}</div>:null}
function TableCard({title,description,count,selectedCount=0,onBulkDelete,children}:{title:string;description:string;count:number;selectedCount?:number;onBulkDelete?:()=>void;children:ReactNode}){return <section className="rh-table-card"><header><div><h3>{title}</h3><p>{description}</p></div><div><span>{count} registro{count===1?'':'s'}</span>{selectedCount>0&&onBulkDelete&&<button className="button outline" onClick={onBulkDelete}><Trash2 size={13}/>Excluir {selectedCount}</button>}</div></header><div className="rh-table-scroll">{children}</div></section>}
function Pagination({page,total,onChange}:{page:number;total:number;onChange:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(pages<=1)return null;return <div className="rh-pagination"><button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={15}/></button><span>Página {page} de {pages}</span><button disabled={page>=pages} onClick={()=>onChange(page+1)}><ChevronRight size={15}/></button></div>}
function Modal({title,onClose,children,footer}:{title:string;onClose:()=>void;children:ReactNode;footer?:ReactNode}){return <div className="rh-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="rh-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button onClick={onClose} aria-label="Fechar"><X/></button></header><div className="rh-modal-body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>}
function ViewModal({title,onClose,rows}:{title:string;onClose:()=>void;rows:[string,string][]}){return <Modal title={title} onClose={onClose}><dl className="rh-view-list">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Modal>}

function EmployeeModal({value,state,busy,onClose,onSave}:{value:Employee|null;state:RhSeed;busy:boolean;onClose:()=>void;onSave:(value:Omit<Employee,'id'|'createdAt'|'updatedAt'>,id?:string)=>Promise<void>}){
 const [form,setForm]=useState(()=>({name:value?.name??'',email:value?.email??'',cpf:value?.cpf??'',rg:value?.rg??'',birthDate:value?.birthDate??'',phone:value?.phone??'',address:value?.address??'',role:value?.role??'',department:value?.department??state.departments[0]??'',contractType:(value?.contractType??'CLT') as ContractType,admissionDate:value?.admissionDate??'',baseSalary:value?.baseSalary??0,status:(value?.status??'ativo') as EmployeeStatus,linkedUser:value?.linkedUser??'',notes:value?.notes??''}))
 const set=<K extends keyof typeof form>(key:K,next:(typeof form)[K])=>setForm(current=>({...current,[key]:next}))
 const submit=(e:FormEvent)=>{e.preventDefault();void onSave(form,value?.id)}
 return <Modal title={value?'Editar Funcionário':'Novo Funcionário'} onClose={onClose} footer={<><button className="button outline" onClick={onClose}>Cancelar</button><button className="button dark" disabled={busy||!form.name.trim()} form="rh-employee-form" type="submit">Salvar</button></>}><form id="rh-employee-form" className="rh-form-grid" onSubmit={submit}><Field label="Nome *"><input required value={form.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="E-mail"><input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="CPF"><input value={form.cpf} onChange={e=>set('cpf',e.target.value)}/></Field><Field label="RG"><input value={form.rg} onChange={e=>set('rg',e.target.value)}/></Field><Field label="Nascimento"><input type="date" value={form.birthDate} onChange={e=>set('birthDate',e.target.value)}/></Field><Field label="Telefone"><input value={form.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Cargo"><input value={form.role} onChange={e=>set('role',e.target.value)}/></Field><Field label="Setor"><select value={form.department} onChange={e=>set('department',e.target.value)}>{state.departments.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Contrato"><select value={form.contractType} onChange={e=>set('contractType',e.target.value as ContractType)}>{['CLT','PJ','Estágio','Temporário','Autônomo'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Admissão"><input type="date" value={form.admissionDate} onChange={e=>set('admissionDate',e.target.value)}/></Field><Field label="Salário base"><input type="number" min="0" step="0.01" value={form.baseSalary} onChange={e=>set('baseSalary',Number(e.target.value))}/></Field><Field label="Status"><select value={form.status} onChange={e=>set('status',e.target.value as EmployeeStatus)}>{['ativo','inativo','férias','afastado','desligado'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Usuário associado"><input value={form.linkedUser} onChange={e=>set('linkedUser',e.target.value)}/></Field><Field label="Endereço" wide><input value={form.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="Observações" wide><textarea rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field></form></Modal>
}
function PayrollModal({value,state,busy,onClose,onSave}:{value:PayrollEntry|null;state:RhSeed;busy:boolean;onClose:()=>void;onSave:(value:Omit<PayrollEntry,'id'|'createdAt'|'updatedAt'|'netSalary'>,id?:string)=>Promise<void>}){
 const [form,setForm]=useState(()=>({employeeId:value?.employeeId??state.employees[0]?.id??'',referenceMonth:value?.referenceMonth??'',grossSalary:value?.grossSalary??0,discounts:value?.discounts??0,bonus:value?.bonus??0,paymentDate:value?.paymentDate??'',status:(value?.status??'pendente') as PayrollStatus,notes:value?.notes??''}));const set=<K extends keyof typeof form>(key:K,next:(typeof form)[K])=>setForm(current=>({...current,[key]:next}));const net=Math.max(0,form.grossSalary-form.discounts+form.bonus)
 return <Modal title={value?'Editar Pagamento':'Novo Registro de Pagamento'} onClose={onClose} footer={<><button className="button outline" onClick={onClose}>Cancelar</button><button className="button dark" disabled={busy||!form.employeeId||!form.referenceMonth} form="rh-payroll-form" type="submit">Salvar</button></>}><form id="rh-payroll-form" className="rh-form-grid" onSubmit={e=>{e.preventDefault();void onSave(form,value?.id)}}><Field label="Funcionário *" wide><select required value={form.employeeId} onChange={e=>set('employeeId',e.target.value)}><option value="">Selecione</option>{state.employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Mês de referência *"><input required type="month" value={form.referenceMonth} onChange={e=>set('referenceMonth',e.target.value)}/></Field><Field label="Status"><select value={form.status} onChange={e=>set('status',e.target.value as PayrollStatus)}>{['pendente','processado','pago','cancelado'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Salário bruto"><input type="number" min="0" step="0.01" value={form.grossSalary} onChange={e=>set('grossSalary',Number(e.target.value))}/></Field><Field label="Descontos"><input type="number" min="0" step="0.01" value={form.discounts} onChange={e=>set('discounts',Number(e.target.value))}/></Field><Field label="Bônus"><input type="number" min="0" step="0.01" value={form.bonus} onChange={e=>set('bonus',Number(e.target.value))}/></Field><Field label="Líquido"><input disabled value={money(net)}/></Field><Field label="Data de pagamento"><input type="date" value={form.paymentDate} onChange={e=>set('paymentDate',e.target.value)}/></Field><Field label="Observações" wide><textarea rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field></form></Modal>
}
function LeaveModal({value,state,busy,onClose,onSave}:{value:LeaveEntry|null;state:RhSeed;busy:boolean;onClose:()=>void;onSave:(value:Omit<LeaveEntry,'id'|'createdAt'|'updatedAt'|'days'|'approvedBy'|'approvedByUserId'|'approvedByDisplayName'|'approvedAt'>,id?:string)=>Promise<void>}){
 const [form,setForm]=useState(()=>({employeeId:value?.employeeId??state.employees[0]?.id??'',type:value?.type??state.leaveTypes[0]??'',startDate:value?.startDate??'',endDate:value?.endDate??'',status:(value?.status??'pendente') as LeaveStatus,notes:value?.notes??''}));const set=<K extends keyof typeof form>(key:K,next:(typeof form)[K])=>setForm(current=>({...current,[key]:next}))
 return <Modal title={value?'Editar Férias / Ausência':'Nova Férias / Ausência'} onClose={onClose} footer={<><button className="button outline" onClick={onClose}>Cancelar</button><button className="button dark" disabled={busy||!form.employeeId||!form.startDate||!form.endDate} form="rh-leave-form" type="submit">Salvar</button></>}><form id="rh-leave-form" className="rh-form-grid" onSubmit={e=>{e.preventDefault();void onSave(form,value?.id)}}><Field label="Funcionário *" wide><select required value={form.employeeId} onChange={e=>set('employeeId',e.target.value)}><option value="">Selecione</option>{state.employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Tipo"><select value={form.type} onChange={e=>set('type',e.target.value)}>{state.leaveTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={e=>set('status',e.target.value as LeaveStatus)}>{['pendente','aprovado','rejeitado','em andamento','concluído'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Início"><input required type="date" value={form.startDate} onChange={e=>set('startDate',e.target.value)}/></Field><Field label="Fim"><input required type="date" value={form.endDate} onChange={e=>set('endDate',e.target.value)}/></Field>{value?.status==='aprovado'&&<Field label="Aprovação" wide><input disabled value={`${value.approvedByDisplayName||value.approvedBy||'Usuário autenticado'}${value.approvedAt?` · ${new Date(value.approvedAt).toLocaleString('pt-BR')}`:''}`}/></Field>}<Field label="Observações" wide><textarea rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field></form></Modal>
}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={wide?'wide':''}><span>{label}</span>{children}</label>}
