import {AlertCircle,CalendarDays,ChevronLeft,ChevronRight,DollarSign,FileText,MoreHorizontal,Palmtree,Plus,Search,Trash2,Upload,UserCheck,UserX,Users,X} from 'lucide-react'
import {useEffect,useMemo,useRef,useState,type ChangeEvent,type FormEvent,type ReactNode} from 'react'
import {AdminShell} from '../../shared/internal/AdminUi'
import {UNIFIED_ADMIN_NAV} from '../../shared/internal/adminNavigation'
import {dateLabel,money,type ContractType,type Employee,type EmployeeStatus,type LeaveEntry,type LeaveStatus,type PayrollEntry,type PayrollStatus,type RhSeed} from './domain'
import {rhRepository} from './repository'
import './rh.css'

type Tab='employees'|'payroll'|'leaves'|'documents'
type EmployeeEditor=Employee|null|undefined
type PayrollEditor=PayrollEntry|null|undefined
type LeaveEditor=LeaveEntry|null|undefined
const load=()=>rhRepository.snapshot()
const statusLabel=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1)
const monthLabel=(value:string)=>{if(!value)return '—';const [y,m]=value.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}
const PAGE_SIZE=10

export default function RHPage(){
 const [state,setState]=useState<RhSeed>(load),[tab,setTab]=useState<Tab>('employees'),[employeeEditor,setEmployeeEditor]=useState<EmployeeEditor>(undefined),[employeeView,setEmployeeView]=useState<Employee|null>(null),[payrollEditor,setPayrollEditor]=useState<PayrollEditor>(undefined),[payrollView,setPayrollView]=useState<PayrollEntry|null>(null),[leaveEditor,setLeaveEditor]=useState<LeaveEditor>(undefined),[leaveView,setLeaveView]=useState<LeaveEntry|null>(null)
 const [employeeSearch,setEmployeeSearch]=useState(''),[employeeStatus,setEmployeeStatus]=useState('all'),[department,setDepartment]=useState('all'),[payrollSearch,setPayrollSearch]=useState(''),[payrollMonth,setPayrollMonth]=useState(''),[payrollStatus,setPayrollStatus]=useState('all'),[leaveSearch,setLeaveSearch]=useState(''),[leaveStatus,setLeaveStatus]=useState('all'),[documentEmployee,setDocumentEmployee]=useState(''),[documentType,setDocumentType]=useState(''),[documentDescription,setDocumentDescription]=useState('')
 const [employeePage,setEmployeePage]=useState(1),[payrollPage,setPayrollPage]=useState(1),[leavePage,setLeavePage]=useState(1),[selectedEmployees,setSelectedEmployees]=useState<string[]>([]),[selectedPayroll,setSelectedPayroll]=useState<string[]>([]),[selectedLeaves,setSelectedLeaves]=useState<string[]>([]),fileRef=useRef<HTMLInputElement>(null)
 const refresh=()=>setState(load())
 useEffect(()=>{const fn=()=>refresh();window.addEventListener(rhRepository.eventName,fn);return()=>window.removeEventListener(rhRepository.eventName,fn)},[])
 const employeeName=(id:string)=>state.employees.find(x=>x.id===id)?.name??'Funcionário não encontrado'
 const counts={total:state.employees.length,active:state.employees.filter(x=>x.status==='ativo').length,vacation:state.employees.filter(x=>x.status==='férias').length,away:state.employees.filter(x=>x.status==='afastado').length}
 const employees=useMemo(()=>state.employees.filter(x=>(!employeeSearch||[x.name,x.email,x.role,x.cpf].some(v=>v.toLowerCase().includes(employeeSearch.toLowerCase())))&&(employeeStatus==='all'||x.status===employeeStatus)&&(department==='all'||x.department===department)),[state.employees,employeeSearch,employeeStatus,department])
 const payroll=useMemo(()=>state.payroll.filter(x=>(!payrollSearch||[employeeName(x.employeeId),x.referenceMonth].some(v=>v.toLowerCase().includes(payrollSearch.toLowerCase())))&&(!payrollMonth||x.referenceMonth===payrollMonth)&&(payrollStatus==='all'||x.status===payrollStatus)),[state.payroll,state.employees,payrollSearch,payrollMonth,payrollStatus])
 const leaves=useMemo(()=>state.leaves.filter(x=>(!leaveSearch||[employeeName(x.employeeId),x.type].some(v=>v.toLowerCase().includes(leaveSearch.toLowerCase())))&&(leaveStatus==='all'||x.status===leaveStatus)),[state.leaves,state.employees,leaveSearch,leaveStatus])
 const paginate=<T,>(items:T[],page:number)=>items.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)
 const docs=state.documents.filter(x=>x.employeeId===documentEmployee)
 const newAction=tab==='employees'?()=>setEmployeeEditor(null):tab==='payroll'?()=>setPayrollEditor(null):tab==='leaves'?()=>setLeaveEditor(null):undefined
 const newLabel=tab==='employees'?'Novo Funcionário':tab==='payroll'?'Novo Registro':tab==='leaves'?'Nova Férias/Ausência':''
 return <AdminShell area="rh" items={UNIFIED_ADMIN_NAV} header={{title:'Recursos Humanos',description:'Gestão de funcionários, folha de pagamento, férias e documentos'}} headerActions={newAction?[{label:newLabel,icon:Plus,onClick:newAction}]:[]}>
  <section className="rh-page">
   <div className="rh-kpis"><Kpi icon={<Users/>} label="Total de Funcionários" value={counts.total} detail="cadastros da equipe"/><Kpi icon={<UserCheck/>} label="Ativos" value={counts.active} detail="em atividade"/><Kpi icon={<Palmtree/>} label="Em Férias" value={counts.vacation} detail="afastamento por férias"/><Kpi icon={<UserX/>} label="Afastados" value={counts.away} detail="afastamentos ativos"/></div>
   <div className="rh-tabs" role="tablist"><TabButton active={tab==='employees'} onClick={()=>setTab('employees')} icon={<Users/>}>Funcionários</TabButton><TabButton active={tab==='payroll'} onClick={()=>setTab('payroll')} icon={<DollarSign/>}>Folha de Pagamento</TabButton><TabButton active={tab==='leaves'} onClick={()=>setTab('leaves')} icon={<CalendarDays/>}>Férias e Ausências</TabButton><TabButton active={tab==='documents'} onClick={()=>setTab('documents')} icon={<FileText/>}>Documentos</TabButton></div>
   {tab==='employees'&&<><div className="rh-filters"><SearchBox value={employeeSearch} onChange={v=>{setEmployeeSearch(v);setEmployeePage(1)}} placeholder="Buscar por nome, email, cargo, CPF..."/><select value={employeeStatus} onChange={e=>{setEmployeeStatus(e.target.value);setEmployeePage(1)}}><option value="all">Todos os status</option>{['ativo','inativo','férias','afastado','desligado'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select><select value={department} onChange={e=>{setDepartment(e.target.value);setEmployeePage(1)}}><option value="all">Todos os setores</option>{state.departments.map(x=><option key={x}>{x}</option>)}</select></div><TableCard title="Lista de Funcionários" description="Acompanhe funcionários, cargos, setores, vínculo, salário, status e usuário associado." count={employees.length} selectedCount={selectedEmployees.length} onBulkDelete={()=>{rhRepository.deleteEmployees(selectedEmployees);setSelectedEmployees([])}}><table className="rh-table"><thead><tr><CheckHead checked={paginate(employees,employeePage).length>0&&paginate(employees,employeePage).every(x=>selectedEmployees.includes(x.id))} onChange={checked=>setSelectedEmployees(checked?Array.from(new Set([...selectedEmployees,...paginate(employees,employeePage).map(x=>x.id)])):selectedEmployees.filter(id=>!paginate(employees,employeePage).some(x=>x.id===id)))}/><th>Nome</th><th>Cargo</th><th>Setor</th><th>Tipo</th><th className="numeric">Salário</th><th>Status</th><th>Usuário</th><th>Ações</th></tr></thead><tbody>{paginate(employees,employeePage).map(x=><tr key={x.id}><CheckCell checked={selectedEmployees.includes(x.id)} onChange={()=>setSelectedEmployees(selectedEmployees.includes(x.id)?selectedEmployees.filter(id=>id!==x.id):[...selectedEmployees,x.id])}/><td><strong>{x.name}</strong><small>{x.email}</small></td><td>{x.role||'—'}</td><td>{x.department||'—'}</td><td>{x.contractType}</td><td className="numeric">{money(x.baseSalary)}</td><td><Status value={x.status}/></td><td>{x.linkedUser||'—'}</td><td><RowActions onView={()=>setEmployeeView(x)} onEdit={()=>setEmployeeEditor(x)} onDelete={()=>rhRepository.deleteEmployees([x.id])}/></td></tr>)}</tbody></table><EmptyRows empty={!employees.length} text="Nenhum funcionário encontrado."/><Pagination page={employeePage} total={employees.length} onChange={setEmployeePage}/></TableCard></>}
   {tab==='payroll'&&<><div className="rh-filters"><input type="month" value={payrollMonth} onChange={e=>{setPayrollMonth(e.target.value);setPayrollPage(1)}}/><SearchBox value={payrollSearch} onChange={v=>{setPayrollSearch(v);setPayrollPage(1)}} placeholder="Buscar por funcionário ou mês..."/><select value={payrollStatus} onChange={e=>{setPayrollStatus(e.target.value);setPayrollPage(1)}}><option value="all">Todos os status</option>{['pendente','processado','pago','cancelado'].map(x=><option key={x}>{x}</option>)}</select></div><TableCard title="Folha de Pagamento" description="Acompanhe salários, descontos, bônus, valores líquidos, status e datas de pagamento." count={payroll.length} selectedCount={selectedPayroll.length} onBulkDelete={()=>{rhRepository.deletePayroll(selectedPayroll);setSelectedPayroll([])}}><table className="rh-table"><thead><tr><CheckHead checked={paginate(payroll,payrollPage).length>0&&paginate(payroll,payrollPage).every(x=>selectedPayroll.includes(x.id))} onChange={checked=>setSelectedPayroll(checked?Array.from(new Set([...selectedPayroll,...paginate(payroll,payrollPage).map(x=>x.id)])):selectedPayroll.filter(id=>!paginate(payroll,payrollPage).some(x=>x.id===id)))}/><th>Funcionário</th><th>Mês Ref.</th><th className="numeric">Bruto</th><th className="numeric">Descontos</th><th className="numeric">Bônus</th><th className="numeric">Líquido</th><th>Pagamento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{paginate(payroll,payrollPage).map(x=><tr key={x.id}><CheckCell checked={selectedPayroll.includes(x.id)} onChange={()=>setSelectedPayroll(selectedPayroll.includes(x.id)?selectedPayroll.filter(id=>id!==x.id):[...selectedPayroll,x.id])}/><td><strong>{employeeName(x.employeeId)}</strong></td><td>{monthLabel(x.referenceMonth)}</td><td className="numeric">{money(x.grossSalary)}</td><td className="numeric negative">{money(x.discounts)}</td><td className="numeric positive">{money(x.bonus)}</td><td className="numeric"><strong>{money(x.netSalary)}</strong></td><td>{dateLabel(x.paymentDate)}</td><td><Status value={x.status}/></td><td><RowActions onView={()=>setPayrollView(x)} onEdit={()=>setPayrollEditor(x)} onDelete={()=>rhRepository.deletePayroll([x.id])}/></td></tr>)}</tbody></table><EmptyRows empty={!payroll.length} text="Nenhum registro de pagamento encontrado."/><Pagination page={payrollPage} total={payroll.length} onChange={setPayrollPage}/></TableCard></>}
   {tab==='leaves'&&<><div className="rh-filters"><SearchBox value={leaveSearch} onChange={v=>{setLeaveSearch(v);setLeavePage(1)}} placeholder="Buscar por funcionário ou tipo..."/><select value={leaveStatus} onChange={e=>{setLeaveStatus(e.target.value);setLeavePage(1)}}><option value="all">Todos os status</option>{['pendente','aprovado','rejeitado','em andamento','concluído'].map(x=><option key={x}>{x}</option>)}</select></div><TableCard title="Férias e Ausências" description="Acompanhe solicitações de férias, ausências, períodos, quantidade de dias e status de aprovação." count={leaves.length} selectedCount={selectedLeaves.length} onBulkDelete={()=>{rhRepository.deleteLeaves(selectedLeaves);setSelectedLeaves([])}}><table className="rh-table"><thead><tr><CheckHead checked={paginate(leaves,leavePage).length>0&&paginate(leaves,leavePage).every(x=>selectedLeaves.includes(x.id))} onChange={checked=>setSelectedLeaves(checked?Array.from(new Set([...selectedLeaves,...paginate(leaves,leavePage).map(x=>x.id)])):selectedLeaves.filter(id=>!paginate(leaves,leavePage).some(x=>x.id===id)))}/><th>Funcionário</th><th>Tipo</th><th>Início</th><th>Fim</th><th className="numeric">Dias</th><th>Status</th><th>Ações</th></tr></thead><tbody>{paginate(leaves,leavePage).map(x=><tr key={x.id}><CheckCell checked={selectedLeaves.includes(x.id)} onChange={()=>setSelectedLeaves(selectedLeaves.includes(x.id)?selectedLeaves.filter(id=>id!==x.id):[...selectedLeaves,x.id])}/><td><strong>{employeeName(x.employeeId)}</strong></td><td>{statusLabel(x.type)}</td><td>{dateLabel(x.startDate)}</td><td>{dateLabel(x.endDate)}</td><td className="numeric">{x.days}</td><td><Status value={x.status}/></td><td><RowActions onView={()=>setLeaveView(x)} onEdit={()=>setLeaveEditor(x)} onDelete={()=>rhRepository.deleteLeaves([x.id])}/></td></tr>)}</tbody></table><EmptyRows empty={!leaves.length} text="Nenhum registro de férias/ausência encontrado."/><Pagination page={leavePage} total={leaves.length} onChange={setLeavePage}/></TableCard></>}
   {tab==='documents'&&<section className="rh-docs"><div className="rh-doc-selector"><label><span>Funcionário</span><select value={documentEmployee} onChange={e=>setDocumentEmployee(e.target.value)}><option value="">Selecione um funcionário</option>{state.employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>{!documentEmployee?<div className="rh-empty-card"><FileText/><strong>Selecione um funcionário</strong><p>Escolha um funcionário acima para visualizar e gerenciar seus documentos.</p></div>:<><section className="rh-upload-card"><h3>Enviar Novo Documento</h3><div className="rh-form-grid"><label><span>Tipo de Documento</span><select value={documentType} onChange={e=>setDocumentType(e.target.value)}><option value="">Selecione o tipo</option>{state.documentTypes.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Descrição</span><input value={documentDescription} onChange={e=>setDocumentDescription(e.target.value)} placeholder="Descrição opcional do documento"/></label></div><input ref={fileRef} hidden type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={e=>uploadDocuments(e,documentEmployee,documentType,documentDescription,()=>{setDocumentDescription('');setDocumentType('');e.currentTarget.value=''})}/><button className="rh-upload-zone" onClick={()=>fileRef.current?.click()}><Upload/><strong>Selecionar arquivos</strong><span>PDF, JPG, PNG, DOC ou DOCX · até 10 MB por arquivo</span></button></section><TableCard title="Documentos" description="Acompanhe documentos de funcionários, tipos, anexos e registros." count={docs.length}><table className="rh-table"><thead><tr><th>Tipo</th><th>Arquivo</th><th>Descrição</th><th>Data</th><th>Ações</th></tr></thead><tbody>{docs.map(x=><tr key={x.id}><td><Status value={x.type}/></td><td><strong>{x.fileName}</strong></td><td>{x.description||'—'}</td><td>{new Date(x.createdAt).toLocaleDateString('pt-BR')}</td><td><button className="rh-icon negative" onClick={()=>rhRepository.deleteDocument(x.id)} title="Excluir"><Trash2 size={15}/></button></td></tr>)}</tbody></table><EmptyRows empty={!docs.length} text="Nenhum documento encontrado para este funcionário."/></TableCard></>}</section>}
  </section>
  {employeeEditor!==undefined&&<EmployeeModal value={employeeEditor} state={state} onClose={()=>setEmployeeEditor(undefined)}/>} {employeeView&&<ViewModal title="Funcionário" onClose={()=>setEmployeeView(null)} rows={[["Nome",employeeView.name],["Email",employeeView.email],["Cargo",employeeView.role],["Setor",employeeView.department],["Tipo de Contrato",employeeView.contractType],["Admissão",dateLabel(employeeView.admissionDate)],["Salário Base",money(employeeView.baseSalary)],["Status",statusLabel(employeeView.status)],["Usuário Vinculado",employeeView.linkedUser||'—'],["Observações",employeeView.notes||'—']]}/>} 
  {payrollEditor!==undefined&&<PayrollModal value={payrollEditor} state={state} onClose={()=>setPayrollEditor(undefined)}/>} {payrollView&&<ViewModal title="Registro de Pagamento" onClose={()=>setPayrollView(null)} rows={[["Funcionário",employeeName(payrollView.employeeId)],["Mês de Referência",monthLabel(payrollView.referenceMonth)],["Salário Bruto",money(payrollView.grossSalary)],["Descontos",money(payrollView.discounts)],["Bônus",money(payrollView.bonus)],["Salário Líquido",money(payrollView.netSalary)],["Data de Pagamento",dateLabel(payrollView.paymentDate)],["Status",statusLabel(payrollView.status)],["Observações",payrollView.notes||'—']]}/>} 
  {leaveEditor!==undefined&&<LeaveModal value={leaveEditor} state={state} onClose={()=>setLeaveEditor(undefined)}/>} {leaveView&&<ViewModal title="Férias/Ausência" onClose={()=>setLeaveView(null)} rows={[["Funcionário",employeeName(leaveView.employeeId)],["Tipo",statusLabel(leaveView.type)],["Data de Início",dateLabel(leaveView.startDate)],["Data de Fim",dateLabel(leaveView.endDate)],["Dias",String(leaveView.days)],["Status",statusLabel(leaveView.status)],["Aprovado por",leaveView.approvedBy||'—'],["Observações",leaveView.notes||'—']]}/>} 
 </AdminShell>
}

function Kpi({icon,label,value,detail}:{icon:ReactNode;label:string;value:number;detail:string}){return <div className="rh-kpi"><span className="rh-kpi-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p></div></div>}
function TabButton({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:ReactNode;children:ReactNode}){return <button className={active?'active':''} role="tab" aria-selected={active} onClick={onClick}>{icon}{children}</button>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="rh-search"><Search size={15}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function TableCard({title,description,count,selectedCount=0,onBulkDelete,children}:{title:string;description:string;count:number;selectedCount?:number;onBulkDelete?:()=>void;children:ReactNode}){return <section className="rh-table-card"><header><div><h3>{title}</h3><p>{description} · {count} registro(s)</p></div>{selectedCount>0&&onBulkDelete&&<button className="rh-danger-button" onClick={onBulkDelete}><Trash2 size={14}/>Excluir ({selectedCount})</button>}</header><div className="rh-table-wrap">{children}</div></section>}
function CheckHead({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void}){return <th className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} aria-label="Selecionar todos os registros exibidos"/></th>}
function CheckCell({checked,onChange}:{checked:boolean;onChange:()=>void}){return <td className="check"><input type="checkbox" checked={checked} onChange={onChange}/></td>}
function Status({value}:{value:string}){const key=value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll(' ','-').toLowerCase();return <span className={`rh-status ${key}`}>{statusLabel(value)}</span>}
function RowActions({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);return <div className="rh-menu"><button className="rh-icon" onClick={()=>setOpen(v=>!v)} aria-label="Ações"><MoreHorizontal size={17}/></button>{open&&<div className="rh-menu-pop"><button onClick={()=>{setOpen(false);onView()}}>Visualizar</button><button onClick={()=>{setOpen(false);onEdit()}}>Editar</button><button className="danger" onClick={()=>{setOpen(false);onDelete()}}>Excluir</button></div>}</div>}
function EmptyRows({empty,text}:{empty:boolean;text:string}){return empty?<div className="rh-empty-row"><AlertCircle size={18}/>{text}</div>:null}
function Pagination({page,total,onChange}:{page:number;total:number;onChange:(p:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(total<=PAGE_SIZE)return null;return <footer className="rh-pagination"><span>Página {Math.min(page,pages)} de {pages}</span><div><button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={14}/>Anterior</button><button disabled={page>=pages} onClick={()=>onChange(page+1)}>Próxima<ChevronRight size={14}/></button></div></footer>}

function EmployeeModal({value,state,onClose}:{value:Employee|null;state:RhSeed;onClose:()=>void}){const blank={name:'',email:'',cpf:'',rg:'',birthDate:'',phone:'',address:'',role:'',department:state.departments[0]??'',contractType:'CLT' as ContractType,admissionDate:'',baseSalary:0,status:'ativo' as EmployeeStatus,linkedUser:'',notes:''},[form,setForm]=useState(value?{name:value.name,email:value.email,cpf:value.cpf,rg:value.rg,birthDate:value.birthDate,phone:value.phone,address:value.address,role:value.role,department:value.department,contractType:value.contractType,admissionDate:value.admissionDate,baseSalary:value.baseSalary,status:value.status,linkedUser:value.linkedUser,notes:value.notes}:blank);const submit=(e:FormEvent)=>{e.preventDefault();if(form.name.trim().length<2)return;rhRepository.saveEmployee(form,value?.id);onClose()};return <Modal title={value?'Editar Funcionário':'Novo Funcionário'} subtitle={value?'Atualize os dados do funcionário':'Cadastre um novo integrante da equipe'} onClose={onClose}><form onSubmit={submit}><div className="rh-modal-body"><h4>Dados Pessoais</h4><div className="rh-form-grid"><Field label="Nome Completo *" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="CPF" value={form.cpf} onChange={v=>setForm({...form,cpf:v})}/><Field label="RG" value={form.rg} onChange={v=>setForm({...form,rg:v})}/><Field label="Data de Nascimento" type="date" value={form.birthDate} onChange={v=>setForm({...form,birthDate:v})}/><Field label="Telefone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="Endereço" value={form.address} onChange={v=>setForm({...form,address:v})} wide/></div><h4>Dados Profissionais</h4><div className="rh-form-grid"><Field label="Cargo" value={form.role} onChange={v=>setForm({...form,role:v})}/><SelectField label="Setor" value={form.department} onChange={v=>setForm({...form,department:v})} options={state.departments}/><SelectField label="Tipo de Contrato" value={form.contractType} onChange={v=>setForm({...form,contractType:v as ContractType})} options={['CLT','PJ','Estágio','Temporário','Autônomo']}/><Field label="Data de Admissão" type="date" value={form.admissionDate} onChange={v=>setForm({...form,admissionDate:v})}/><Field label="Salário Base" type="number" value={String(form.baseSalary||'')} onChange={v=>setForm({...form,baseSalary:Math.max(0,Number(v))})}/><SelectField label="Status" value={form.status} onChange={v=>setForm({...form,status:v as EmployeeStatus})} options={['ativo','inativo','férias','afastado','desligado']}/><Field label="Usuário Vinculado" value={form.linkedUser} onChange={v=>setForm({...form,linkedUser:v})}/><Field label="Observações" value={form.notes} onChange={v=>setForm({...form,notes:v})} wide/></div></div><ModalFooter onClose={onClose}/></form></Modal>}
function PayrollModal({value,state,onClose}:{value:PayrollEntry|null;state:RhSeed;onClose:()=>void}){const blank={employeeId:state.employees[0]?.id??'',referenceMonth:new Date().toISOString().slice(0,7),grossSalary:0,discounts:0,bonus:0,paymentDate:'',status:'pendente' as PayrollStatus,notes:''},[form,setForm]=useState(value?{employeeId:value.employeeId,referenceMonth:value.referenceMonth,grossSalary:value.grossSalary,discounts:value.discounts,bonus:value.bonus,paymentDate:value.paymentDate,status:value.status,notes:value.notes}:blank);const net=Math.max(0,form.grossSalary-form.discounts+form.bonus),submit=(e:FormEvent)=>{e.preventDefault();if(!form.employeeId||!form.referenceMonth)return;rhRepository.savePayroll(form,value?.id);onClose()};return <Modal title={value?'Editar Registro de Pagamento':'Novo Registro de Pagamento'} subtitle="Preencha os dados da folha de pagamento" onClose={onClose}><form onSubmit={submit}><div className="rh-modal-body"><div className="rh-form-grid"><SelectField label="Funcionário *" value={form.employeeId} onChange={v=>setForm({...form,employeeId:v})} options={state.employees.map(x=>x.id)} labels={Object.fromEntries(state.employees.map(x=>[x.id,x.name]))}/><Field label="Mês de Referência *" type="month" value={form.referenceMonth} onChange={v=>setForm({...form,referenceMonth:v})}/><Field label="Salário Bruto" type="number" value={String(form.grossSalary||'')} onChange={v=>setForm({...form,grossSalary:Math.max(0,Number(v))})}/><Field label="Descontos" type="number" value={String(form.discounts||'')} onChange={v=>setForm({...form,discounts:Math.max(0,Number(v))})}/><Field label="Bônus" type="number" value={String(form.bonus||'')} onChange={v=>setForm({...form,bonus:Math.max(0,Number(v))})}/><label className="rh-field"><span>Salário Líquido</span><input readOnly value={money(net)}/></label><Field label="Data de Pagamento" type="date" value={form.paymentDate} onChange={v=>setForm({...form,paymentDate:v})}/><SelectField label="Status" value={form.status} onChange={v=>setForm({...form,status:v as PayrollStatus})} options={['pendente','processado','pago','cancelado']}/><Field label="Observações" value={form.notes} onChange={v=>setForm({...form,notes:v})} wide/></div></div><ModalFooter onClose={onClose}/></form></Modal>}
function LeaveModal({value,state,onClose}:{value:LeaveEntry|null;state:RhSeed;onClose:()=>void}){const blank={employeeId:state.employees[0]?.id??'',type:state.leaveTypes[0]??'férias',startDate:'',endDate:'',status:'pendente' as LeaveStatus,approvedBy:'',notes:''},[form,setForm]=useState(value?{employeeId:value.employeeId,type:value.type,startDate:value.startDate,endDate:value.endDate,status:value.status,approvedBy:value.approvedBy,notes:value.notes}:blank);const submit=(e:FormEvent)=>{e.preventDefault();if(!form.employeeId||!form.startDate||!form.endDate||form.endDate<form.startDate)return;rhRepository.saveLeave(form,value?.id);onClose()};return <Modal title={value?'Editar Férias/Ausência':'Nova Férias/Ausência'} subtitle="Registre férias ou ausência do funcionário" onClose={onClose}><form onSubmit={submit}><div className="rh-modal-body"><div className="rh-form-grid"><SelectField label="Funcionário *" value={form.employeeId} onChange={v=>setForm({...form,employeeId:v})} options={state.employees.map(x=>x.id)} labels={Object.fromEntries(state.employees.map(x=>[x.id,x.name]))}/><SelectField label="Tipo de Ausência *" value={form.type} onChange={v=>setForm({...form,type:v})} options={state.leaveTypes}/><Field label="Data de Início *" type="date" value={form.startDate} onChange={v=>setForm({...form,startDate:v})}/><Field label="Data de Fim *" type="date" value={form.endDate} onChange={v=>setForm({...form,endDate:v})}/><SelectField label="Status" value={form.status} onChange={v=>setForm({...form,status:v as LeaveStatus})} options={['pendente','aprovado','rejeitado','em andamento','concluído']}/><Field label="Aprovado por" value={form.approvedBy} onChange={v=>setForm({...form,approvedBy:v})}/><Field label="Observações" value={form.notes} onChange={v=>setForm({...form,notes:v})} wide/></div></div><ModalFooter onClose={onClose}/></form></Modal>}
function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:ReactNode}){return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="rh-modal" role="dialog" aria-modal="true"><header><div><span>Recursos Humanos</span><h2>{title}</h2><p>{subtitle}</p></div><button className="rh-icon" onClick={onClose}><X size={18}/></button></header>{children}</section></div>}
function ModalFooter({onClose}:{onClose:()=>void}){return <footer className="rh-modal-footer"><button type="button" className="rh-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="rh-primary">Salvar</button></footer>}
function Field({label,value,onChange,type='text',wide=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;wide?:boolean}){return <label className={`rh-field${wide?' wide':''}`}><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SelectField({label,value,onChange,options,labels}:{label:string;value:string;onChange:(v:string)=>void;options:string[];labels?:Record<string,string>}){return <label className="rh-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{labels?.[x]??statusLabel(x)}</option>)}</select></label>}
function ViewModal({title,onClose,rows}:{title:string;onClose:()=>void;rows:[string,string][]}){return <Modal title={`Visualizar ${title}`} subtitle="Detalhes do registro" onClose={onClose}><div className="rh-modal-body"><div className="rh-view-grid">{rows.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></div><footer className="rh-modal-footer"><button className="rh-primary" onClick={onClose}>Fechar</button></footer></Modal>}
function uploadDocuments(e:ChangeEvent<HTMLInputElement>,employeeId:string,type:string,description:string,done:()=>void){const files=Array.from(e.target.files??[]);files.filter(file=>file.size<=10*1024*1024).forEach(file=>rhRepository.addDocument({employeeId,type:type||'Outro',fileName:file.name,fileUrl:'#',description}));done()}
