export type SettingsTab='empresa'|'identidade_site'|'automacoes'|'seguranca'|'integracoes'|'usuarios'
export interface SettingsCompany{legalName:string;tradeName:string;cnpj:string;address:string;phone:string;responsible:string;slug:string;logoUrl:string}
export interface SettingsAutomation{id:string;title:string;description:string;enabled:boolean;email:boolean;push:boolean;sms:boolean;frequency?:string;preferredTime?:string}
export interface SettingsIntegration{id:string;name:string;category:string;description:string;status:'connected'|'available'|'external'|'unavailable';logo:string;actionLabel:string}
export interface SettingsUser{id:string;name:string;email:string;role:string;phone:string;createdAt:string;status:'ativo'|'inativo'|'pendente'}
export interface SettingsRole{id:string;slug:string;name:string;description:string;archived:boolean;system:boolean;permissions:string[]}
export interface SettingsInvite{id:string;email:string;role:string;status:'pendente'}
export interface SettingsAudit{id:string;createdAt:string;userId:string;actorRole:string;action:string;entity:string;entityId:string;method:string;path:string;ip:string;correlationId:string;before:Record<string,unknown>|null;after:Record<string,unknown>|null;diff:Record<string,{from:unknown;to:unknown}>|null}
export interface SettingsSession{id:string;isCurrent:boolean;createdAt:string;lastSeenAt:string;expiresAt:string;userAgent:string}
export interface SettingsSecurity{passwordChange:boolean;twoFactor:boolean;sessionList:boolean;revokeOtherSessions:boolean;deleteAccount:boolean;sessions:SettingsSession[]}
export interface SettingsRuntime{automation:boolean;userInvites:boolean;roleMutation:boolean;userRemoval:boolean;companyLogoUpload:boolean;websiteEmbed:boolean}
export interface SettingsSeed{company:SettingsCompany;automations:SettingsAutomation[];integrations:SettingsIntegration[];users:SettingsUser[];roles:SettingsRole[];invites:SettingsInvite[];audit:SettingsAudit[];security?:SettingsSecurity;runtime?:SettingsRuntime;meta?:{version:number;updatedAt:string}}
