import {useEffect,useMemo,useState} from 'react'
import {RefreshCw,Save,Plus} from 'lucide-react'
import {contentIngestionClient,type EditorialProviderStatus,type EditorialSource,type EditorialSourceProvider} from '../editorial/contentIngestionClient'

const emptySource={name:'',provider:'rss' as EditorialSourceProvider,sourceType:'news',category:'Mercado Musical',country:'BR',language:'pt-BR',url:'',feedUrl:'',enabled:false,syncFrequencyMinutes:60,configuration:{minRelevanceScore:15}}

export function IntegrationSourcesPanel(){
 const [sources,setSources]=useState<EditorialSource[]>([]),[providers,setProviders]=useState<Record<string,EditorialProviderStatus>>({}),[draft,setDraft]=useState(emptySource),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const load=async()=>{setError('');try{const [sourceRows,status]=await Promise.all([contentIngestionClient.listSources(),contentIngestionClient.providerStatus()]);setSources(sourceRows);setProviders(status.providers)}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível carregar as fontes editoriais.')}}
 useEffect(()=>{void load()},[])
 const grouped=useMemo(()=>Object.entries(providers),[providers])
 const create=async()=>{setBusy('create');setError('');try{await contentIngestionClient.createSource(draft);setDraft(emptySource);await load()}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível criar a fonte.')}finally{setBusy('')}}
 const patch=(id:string,changes:Partial<EditorialSource>)=>setSources(current=>current.map(item=>item.id===id?{...item,...changes}:item))
 const save=async(source:EditorialSource)=>{setBusy(source.id);setError('');try{await contentIngestionClient.updateSource(source.id,source);await load()}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível salvar a fonte.')}finally{setBusy('')}}
 const sync=async(source:EditorialSource)=>{setBusy(`sync:${source.id}`);setError('');try{await contentIngestionClient.syncSource(source.id);await load()}catch(caught){setError(caught instanceof Error?caught.message:'A sincronização falhou.')}finally{setBusy('')}}
 return <div className="settings-stack">
  <section className="settings-card"><header><div><h2>Descoberta editorial</h2><p>Fontes externas alimentam candidatos para curadoria. Nada é publicado automaticamente.</p></div></header><div className="settings-card-body">
   {error&&<p role="alert" className="settings-modal-note">{error}</p>}
   <div className="settings-integration-groups"><section><h3>Status dos providers</h3><div className="settings-integration-list">{grouped.map(([name,status])=><article key={name}><div className="settings-integration-logo">{name.slice(0,2).toUpperCase()}</div><div className="settings-integration-copy"><strong>{name}</strong><p>{status.reused?'Integração existente reaproveitada':status.configured===false?'Configuração pendente no backend/fonte':'Disponível'}{typeof status.enabled==='number'?` • ${status.enabled} ativa(s)`:''}</p></div><span className={`settings-status ${status.configured===false?'':'connected'}`}>{status.configured===false?'Pendente':'OK'}</span></article>)}</div></section></div>
  </div></section>
  <section className="settings-card"><header><div><h2>Adicionar fonte RSS / Atom</h2><p>Cadastre feeds legítimos. URLs privadas, localhost e protocolos inseguros são bloqueados pelo backend.</p></div></header><div className="settings-card-body"><div className="settings-grid"><label className="settings-field"><span>Nome</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="settings-field"><span>Feed URL</span><input value={draft.feedUrl} onChange={e=>setDraft({...draft,feedUrl:e.target.value})} placeholder="https://fonte.example/feed.xml"/></label><label className="settings-field"><span>Categoria</span><input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label className="settings-field"><span>Frequência (min)</span><input type="number" min={15} value={draft.syncFrequencyMinutes} onChange={e=>setDraft({...draft,syncFrequencyMinutes:Number(e.target.value)||60})}/></label></div><div className="settings-actions left"><button type="button" className="settings-primary" onClick={()=>void create()} disabled={!draft.name||!draft.feedUrl||busy==='create'}><Plus size={14}/>Adicionar desativada</button></div></div></section>
  <section className="settings-card"><header><div><h2>Fontes configuradas</h2><p>ECAD, Pro-Música Brasil, UBC, ABRAMUS e IFPI permanecem desativadas até que um feed RSS/Atom legítimo seja informado.</p></div></header><div className="settings-card-body"><div className="settings-integration-list">{sources.map(source=><article key={source.id}><div className="settings-integration-logo">{source.provider==='official_source'?'OF':source.provider.slice(0,2).toUpperCase()}</div><div className="settings-integration-copy"><strong>{source.name}</strong><p>{source.provider} • {source.category||'Sem categoria'} • {source.lastStatus}{source.lastSyncAt?` • ${new Date(source.lastSyncAt).toLocaleString('pt-BR')}`:''}</p><label className="settings-field"><span>Feed URL</span><input value={source.feedUrl} disabled={!['rss','official_source'].includes(source.provider)} onChange={e=>patch(source.id,{feedUrl:e.target.value,enabled:false})} placeholder={source.provider==='official_source'?'Informe apenas se houver feed legítimo':'https://...'}/></label>{source.lastError&&<small>{source.lastError}</small>}</div><div className="settings-role-actions"><label className="settings-channel-card"><span>Ativa</span><input type="checkbox" checked={source.enabled} disabled={source.provider==='youtube'&&providers.youtube?.configured===false||(['rss','official_source'].includes(source.provider)&&!source.feedUrl)} onChange={e=>patch(source.id,{enabled:e.target.checked})}/></label><button type="button" className="settings-outline" onClick={()=>void save(source)} disabled={busy===source.id}><Save size={14}/>Salvar</button><button type="button" className="settings-outline" onClick={()=>void sync(source)} disabled={!source.enabled||busy===`sync:${source.id}`}><RefreshCw size={14}/>Sincronizar</button></div></article>)}</div></div></section>
 </div>
}
