import {addDays,dateISO,monthName,sameDay,startOfWeek,timeHHMM} from '../date'
import type {AgendaEvent,AgendaParticipant,AgendaViewMode} from '../domain'

type Props={view:AgendaViewMode;referenceDate:Date;events:AgendaEvent[];participants:AgendaParticipant[];onSelect:(event:AgendaEvent)=>void}
const weekdays=['SEG','TER','QUA','QUI','SEX','SÁB','DOM']
const statusClass=(status:string)=>`agenda-event-chip status-${status}`
const participantSummary=(event:AgendaEvent,participants:AgendaParticipant[])=>event.participantIds.map(id=>participants.find(item=>item.id===id)?.label).filter(Boolean).join(', ')
const eventsForDay=(events:AgendaEvent[],date:Date)=>events.filter(event=>sameDay(new Date(event.startsAt),date)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))
function EventChip({event,participants,onSelect,compact=false}:{event:AgendaEvent;participants:AgendaParticipant[];onSelect:(event:AgendaEvent)=>void;compact?:boolean}){const start=new Date(event.startsAt);return <button type="button" className={statusClass(event.status)} onClick={()=>onSelect(event)} title={`${event.title}${participantSummary(event,participants)?` · ${participantSummary(event,participants)}`:''}`}><span>{timeHHMM(start)}</span><strong>{event.title}</strong>{!compact&&participantSummary(event,participants)&&<small>{participantSummary(event,participants)}</small>}</button>}
function MonthGrid({month,events,participants,onSelect,mini=false}:{month:Date;events:AgendaEvent[];participants:AgendaParticipant[];onSelect:(event:AgendaEvent)=>void;mini?:boolean}){const first=new Date(month.getFullYear(),month.getMonth(),1),gridStart=startOfWeek(first),days=Array.from({length:42},(_,index)=>addDays(gridStart,index));return <div className={mini?'agenda-mini-month-grid':'agenda-month-grid'}>{weekdays.map(day=><div className="agenda-calendar-weekday" key={day}>{day}</div>)}{days.map(day=>{const inMonth=day.getMonth()===month.getMonth(),dayEvents=eventsForDay(events,day);return <div key={dateISO(day)} className={`agenda-calendar-day${inMonth?'':' outside'}${sameDay(day,new Date())?' today':''}`}><span className="agenda-day-number">{day.getDate()}</span>{!mini&&<div className="agenda-day-events">{dayEvents.slice(0,3).map(event=><EventChip key={event.id} event={event} participants={participants} onSelect={onSelect} compact/>)}{dayEvents.length>3&&<span className="agenda-more-events">+{dayEvents.length-3} evento(s)</span>}</div>}{mini&&dayEvents.length>0&&<span className="agenda-mini-event-dot" aria-label={`${dayEvents.length} evento(s)`}/>}</div>})}</div>}
export default function AgendaCalendar({view,referenceDate,events,participants,onSelect}:Props){
 if(view==='dia'){const dayEvents=eventsForDay(events,referenceDate),hours=Array.from({length:14},(_,index)=>index+7);return <section className="agenda-calendar-card agenda-day-view"><header><strong>{referenceDate.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</strong><span>{dayEvents.length} evento(s)</span></header><div className="agenda-day-timeline">{hours.map(hour=>{const slotEvents=dayEvents.filter(event=>new Date(event.startsAt).getHours()===hour);return <div className="agenda-hour-row" key={hour}><time>{String(hour).padStart(2,'0')}:00</time><div>{slotEvents.map(event=><EventChip key={event.id} event={event} participants={participants} onSelect={onSelect}/>)}</div></div>})}</div></section>}
 if(view==='semana'){const start=startOfWeek(referenceDate),days=Array.from({length:7},(_,index)=>addDays(start,index));return <section className="agenda-calendar-card agenda-week-view"><div className="agenda-week-grid">{days.map(day=>{const dayEvents=eventsForDay(events,day);return <div key={dateISO(day)} className={`agenda-week-column${sameDay(day,new Date())?' today':''}`}><header><span>{day.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','').toUpperCase()}</span><strong>{day.getDate()}</strong></header><div>{dayEvents.length?dayEvents.map(event=><EventChip key={event.id} event={event} participants={participants} onSelect={onSelect}/>):<p className="agenda-no-events">Sem eventos</p>}</div></div>})}</div></section>}
 if(view==='ano'){const months=Array.from({length:12},(_,index)=>new Date(referenceDate.getFullYear(),index,1));return <section className="agenda-year-view">{months.map(month=><article className="agenda-mini-month" key={month.getMonth()}><h3>{monthName(month)}</h3><MonthGrid month={month} events={events} participants={participants} onSelect={onSelect} mini/></article>)}</section>}
 return <section className="agenda-calendar-card"><MonthGrid month={new Date(referenceDate.getFullYear(),referenceDate.getMonth(),1)} events={events} participants={participants} onSelect={onSelect}/></section>
}
