import {beforeEach,describe,expect,it} from 'vitest'
import {contractTypeOptions,type Contract} from './domain'
import {contractCategoriesMock,contractVariablesMock} from './mocks'
import {parseContractText} from './semanticParser'
import {extractPlaceholders,resolveDocument} from './variables'
import {formatCurrency} from './format'
import {contractsRepository} from './repository'
import {signingProviders} from './signing'
import {contractSchema,signerSchema} from './schema'

const forbidden=['Artista','Gravadora','Fonograma','ISRC','ISWC','MusicWork','Contrato de Gravação','Distribuição Fonográfica','Licenciamento de Fonograma']
class MemoryStorage{private data=new Map<string,string>();get length(){return this.data.size}clear(){this.data.clear()}getItem(key:string){return this.data.get(key)??null}key(index:number){return Array.from(this.data.keys())[index]??null}removeItem(key:string){this.data.delete(key)}setItem(key:string,value:string){this.data.set(key,value)}}
const party=(id:string,role:'contractor'|'contracted',crmContactId?:string)=>({id,source:crmContactId?'crm' as const:'manual' as const,entityType:'company' as const,crmContactId,role,name:role==='contractor'?'Empresa Exemplo':'Portal Lander',tradeName:'',document:'',rg:'',email:'',phone:'',nationality:'',occupation:'',maritalStatus:'',address:'',city:'',state:'',representativeName:'',representativeDocument:'',representativeRole:'',representativeEmail:''})
const contractInput=(crmContactId?:string):Omit<Contract,'id'|'createdAt'|'updatedAt'|'timeline'>=>({title:'Contrato Comercial',number:'PL-001',type:'Publicidade',categoryId:'category_1',status:'draft',startDate:'2026-08-30',endDate:'2026-09-30',duration:'30 dias',description:'Campanha institucional',internalNotes:'',payment:{amount:12000,currency:'BRL',periodicity:'única',method:'Pix',installments:1,dueDay:10,finePercent:2,interestPercent:1,notes:''},parties:[party('a','contractor',crmContactId),party('b','contracted')],variableValues:{},document:{id:'doc',title:'Documento principal',contentHtml:'<p>Versão 1</p>',headerHtml:'',footerHtml:'',status:'not_sent',versions:[]},signers:[],attachments:[],signatureStatus:'not_sent'})

describe('contracts Portal Lander domain',()=>{
 beforeEach(()=>Object.defineProperty(globalThis,'localStorage',{value:new MemoryStorage(),configurable:true}))
 it('contains commercial contract types without forbidden domain',()=>{const serialized=JSON.stringify(contractTypeOptions);for(const term of forbidden)expect(serialized).not.toContain(term);expect(contractTypeOptions).toContain('Publieditorial');expect(contractTypeOptions).toContain('Campanha Publicitária');expect(contractTypeOptions).toContain('Divulgação de Lançamento')})
 it('ships administrable categories and Portal Lander variables',()=>{expect(contractCategoriesMock.some(item=>item.name==='Publicidade')).toBe(true);expect(contractVariablesMock.some(v=>v.key==='{{CONTRATANTE.NAME}}')).toBe(true);expect(contractVariablesMock.some(v=>v.key==='{{CAMPAIGN.NAME}}')).toBe(true);expect(contractVariablesMock.some(v=>v.key==='{{CONTENT.TITLE}}')).toBe(true);expect(contractVariablesMock.some(v=>v.key==='{{SIGNATURE.CONTRATADA}}')).toBe(true)})
 it('resolves placeholders and reports missing values',()=>{const result=resolveDocument({headerHtml:'',contentHtml:'Olá {{CONTRATANTE.NAME}} — {{PAYMENT.AMOUNT}}',footerHtml:''},{'{{CONTRATANTE.NAME}}':'Empresa Exemplo'});expect(result.contentHtml).toContain('Empresa Exemplo');expect(result.missing).toEqual(['{{PAYMENT.AMOUNT}}'])})
 it('extracts semantic business data',()=>{const parsed=parseContractText('Contrato de publicidade no valor de R$ 12.000,00 em 3 parcelas. E-mail contato@exemplo.com. Rua Exemplo 100. Cláusula de confidencialidade, vigência e rescisão.');expect(parsed.variables.some(v=>v.placeholder==='{{PAYMENT.AMOUNT}}')).toBe(true);expect(parsed.variables.some(v=>v.placeholder==='{{PAYMENT.INSTALLMENTS}}')).toBe(true);expect(parsed.variables.some(v=>v.placeholder==='{{CONTRATANTE.ADDRESS}}')).toBe(true);expect(parsed.clauseTypes).toContain('confidencialidade');expect(parsed.clauseTypes).toContain('vigencia');expect(parsed.clauseTypes).toContain('rescisao')})
 it('validates contract and signer structures',()=>{expect(contractSchema.safeParse(contractInput()).success).toBe(true);expect(signerSchema.safeParse({name:'Responsável',email:'responsavel@example.com',required:true}).success).toBe(true)})
 it('keeps signing providers explicitly unconfigured in frontend',()=>{expect(signingProviders.autentique.configured).toBe(false);expect(signingProviders.clicksign.configured).toBe(false);expect(signingProviders.docusign.configured).toBe(false)})
 it('creates and updates contracts through the repository boundary',async()=>{const created=await contractsRepository.createContract(contractInput());expect((await contractsRepository.listContracts())).toHaveLength(1);const updated=await contractsRepository.updateContract(created.id,{title:'Contrato Atualizado'});expect(updated.title).toBe('Contrato Atualizado');expect(updated.timeline.at(-1)?.event).toBe('updated')})
 it('links contracts to CRM contacts by reference',async()=>{await contractsRepository.createContract(contractInput('contact_123'));const linked=await contractsRepository.listContractsByCrmContact('contact_123');expect(linked).toHaveLength(1);expect(linked[0].parties[0].crmContactId).toBe('contact_123')})
 it('preserves document history when a protected contract document changes',async()=>{const created=await contractsRepository.createContract({...contractInput(),status:'partially_signed'});const updated=await contractsRepository.updateContract(created.id,{document:{...created.document,contentHtml:'<p>Versão 2</p>'}});expect(updated.document.versions).toHaveLength(1);expect(updated.document.versions[0].contentHtml).toContain('Versão 1');expect(updated.timeline.some(item=>item.event==='document_updated')).toBe(true)})
 it('records important business changes in the timeline',async()=>{const created=await contractsRepository.createContract(contractInput());const updated=await contractsRepository.updateContract(created.id,{status:'in_review',payment:{...created.payment,amount:15000}});expect(updated.timeline.some(item=>item.event==='status_changed')).toBe(true);expect(updated.timeline.some(item=>item.event==='payment_updated')).toBe(true)})
 it('formats BRL centrally',()=>expect(formatCurrency(12000,'BRL')).toContain('12.000,00'))
 it('extracts unique placeholders',()=>expect(extractPlaceholders('{{CONTRACT.TITLE}} {{CONTRACT.TITLE}}')).toEqual(['{{CONTRACT.TITLE}}']))
})
