import {contractCategoriesMock,contractTemplatesMock,contractVariablesMock,contractsMockRecords} from './mocks'
import {newId,type Contract,type ContractCategory,type ContractsState,type ContractTemplate,type ContractTimelineEntry,type ContractVariable} from './domain'
const STORAGE_KEY='portal-lander:contracts:v1'
const now=()=>new Date().toISOString()
const initial=():ContractsState=>({contracts:[...contractsMockRecords] as Contract[],templates:structuredClone(contractTemplatesMock),categories:structuredClone(contractCategoriesMock),variables:structuredClone(contractVariablesMock)})
const read=():ContractsState=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return initial();const parsed=JSON.parse(raw) as Partial<ContractsState>;return {contracts:parsed.contracts??initial().contracts,templates:parsed.templates??initial().templates,categories:parsed.categories?.length?parsed.categories:initial().categories,variables:parsed.variables?.length?parsed.variables:initial().variables}}catch{return initial()}}
const write=(state:ContractsState)=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state))
const timeline=(event:string,description:string):ContractTimelineEntry=>({id:newId('timeline'),event,description,createdAt:now(),actor:'Administrador'})
const changed=(a:unknown,b:unknown)=>JSON.stringify(a)!==JSON.stringify(b)
const updateEvents=(current:Contract,patch:Partial<Contract>)=>{const events:ContractTimelineEntry[]=[];if(patch.status&&patch.status!==current.status)events.push(timeline('status_changed',`Status alterado de ${current.status} para ${patch.status}`));if(patch.document&&changed(patch.document,current.document))events.push(timeline('document_updated','Documento principal atualizado'));if(patch.parties&&changed(patch.parties,current.parties))events.push(timeline('parties_updated','Partes do contrato atualizadas'));if((patch.startDate!==undefined&&patch.startDate!==current.startDate)||(patch.endDate!==undefined&&patch.endDate!==current.endDate)||(patch.duration!==undefined&&patch.duration!==current.duration))events.push(timeline('term_updated','Vigência do contrato atualizada'));if(patch.payment&&changed(patch.payment,current.payment))events.push(timeline('payment_updated','Condições financeiras atualizadas'));if(patch.signers&&changed(patch.signers,current.signers))events.push(timeline('signers_updated','Signatários atualizados'));if(patch.attachments&&changed(patch.attachments,current.attachments))events.push(timeline('attachments_updated','Documentos ou anexos atualizados'));return events.length?events:[timeline('updated','Contrato atualizado')]}
export const contractsRepository={
 listContracts:async()=>read().contracts,
 getContract:async(id:string)=>read().contracts.find(item=>item.id===id),
 listContractsByCrmContact:async(contactId:string)=>read().contracts.filter(contract=>contract.parties.some(p=>p.crmContactId===contactId)),
 createContract:async(input:Omit<Contract,'id'|'createdAt'|'updatedAt'|'timeline'>)=>{const state=read(),stamp=now();const contract:Contract={...input,id:newId('contract'),createdAt:stamp,updatedAt:stamp,timeline:[timeline('created','Contrato criado')]};state.contracts.unshift(contract);write(state);return contract},
 updateContract:async(id:string,patch:Partial<Contract>)=>{const state=read(),index=state.contracts.findIndex(item=>item.id===id);if(index<0)throw new Error('Contrato não encontrado.');const current=state.contracts[index];let document=patch.document??current.document;const protectedDocument=['partially_signed','signed','active'].includes(current.status);if(protectedDocument&&patch.document&&patch.document.contentHtml!==current.document.contentHtml){const previous={id:newId('version'),version:current.document.versions.length+1,contentHtml:current.document.contentHtml,createdAt:now(),createdBy:'Administrador',notes:'Versão preservada antes de alteração de documento protegido',provider:current.document.provider,externalId:current.document.externalId,fileUrl:current.document.signedFileUrl};document={...patch.document,versions:[...current.document.versions,previous]}}const events=updateEvents(current,{...patch,document});const updated:Contract={...current,...patch,document,updatedAt:now(),timeline:[...current.timeline,...events]};state.contracts[index]=updated;write(state);return updated},
 deleteContract:async(id:string)=>{const state=read();state.contracts=state.contracts.filter(item=>item.id!==id);write(state)},
 bulkDeleteContracts:async(ids:string[])=>{const set=new Set(ids),state=read();state.contracts=state.contracts.filter(item=>!set.has(item.id));write(state)},
 listTemplates:async()=>read().templates,
 saveTemplate:async(input:Omit<ContractTemplate,'id'|'createdAt'|'updatedAt'> & {id?:string})=>{const state=read(),stamp=now();if(input.id){const index=state.templates.findIndex(x=>x.id===input.id);if(index<0)throw new Error('Template não encontrado.');state.templates[index]={...state.templates[index],...input,id:input.id,updatedAt:stamp};write(state);return state.templates[index]}const item:ContractTemplate={...input,id:newId('template'),createdAt:stamp,updatedAt:stamp};state.templates.unshift(item);write(state);return item},
 deleteTemplate:async(id:string)=>{const state=read();state.templates=state.templates.filter(x=>x.id!==id);write(state)},
 listCategories:async()=>read().categories,
 saveCategory:async(input:Omit<ContractCategory,'id'|'createdAt'|'updatedAt'> & {id?:string})=>{const state=read(),stamp=now();if(input.id){const index=state.categories.findIndex(x=>x.id===input.id);if(index<0)throw new Error('Categoria não encontrada.');state.categories[index]={...state.categories[index],...input,id:input.id,updatedAt:stamp};write(state);return state.categories[index]}const item:ContractCategory={...input,id:newId('category'),createdAt:stamp,updatedAt:stamp};state.categories.push(item);write(state);return item},
 deleteCategory:async(id:string)=>{const state=read();if(state.contracts.some(x=>x.categoryId===id)||state.templates.some(x=>x.categoryId===id))throw new Error('Categoria em uso e não pode ser excluída.');state.categories=state.categories.filter(x=>x.id!==id);write(state)},
 listVariables:async()=>read().variables,
 saveVariable:async(input:Omit<ContractVariable,'id'|'createdAt'|'updatedAt'> & {id?:string})=>{const state=read(),stamp=now();if(input.id){const index=state.variables.findIndex(x=>x.id===input.id);if(index<0)throw new Error('Variável não encontrada.');state.variables[index]={...state.variables[index],...input,id:input.id,updatedAt:stamp};write(state);return state.variables[index]}const item:ContractVariable={...input,id:newId('variable'),createdAt:stamp,updatedAt:stamp};state.variables.push(item);write(state);return item},
 deleteVariable:async(id:string)=>{const state=read();state.variables=state.variables.filter(x=>x.id!==id);write(state)},
}
