import {FileUp,SearchCheck,X} from 'lucide-react'
import {useMemo,useState} from 'react'
import {parseContractText} from '../semanticParser'

const asHtml=(value:string)=>value.trim().startsWith('<')?value:value.split(/\n{2,}/).map(block=>`<p>${block.replace(/\n/g,'<br/>')}</p>`).join('\n')

export function ContractImportWorkspace({initial='',onClose,onApply}:{initial?:string;onClose:()=>void;onApply:(contentHtml:string)=>void}){
 const [text,setText]=useState(initial),[error,setError]=useState('')
 const parsed=useMemo(()=>parseContractText(text),[text])
 const importFile=async(file?:File)=>{if(!file)return;try{if(file.size>2*1024*1024)throw new Error('O arquivo excede 2 MB.');setText(await file.text());setError('')}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível importar o arquivo.')}}
 return <div className="crm-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="crm-modal crm-modal-lg contracts-import-modal" role="dialog" aria-modal="true" aria-label="Importar contrato"><header className="crm-modal-head"><div><h2>Importar e analisar contrato</h2><p>Workspace adaptado para contratos empresariais, comerciais, publicitários, editoriais e de serviços do Portal Lander.</p></div><button className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><div className="crm-modal-body contracts-import-workspace">{error&&<div className="crm-error" role="alert">{error}</div>}<div className="contracts-import-toolbar"><label className="crm-btn secondary"><FileUp size={14}/>Importar TXT/HTML<input hidden type="file" accept=".txt,.html,.htm,text/plain,text/html" onChange={event=>void importFile(event.target.files?.[0])}/></label><span className="crm-badge muted"><SearchCheck size={12}/> {parsed.variables.length} variável(is) detectada(s)</span><span className="crm-badge muted">{parsed.clauseTypes.length} contexto(s)</span></div><div className="contracts-import-grid"><label>Conteúdo importado<textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Cole ou importe o conteúdo do contrato para analisar CPF/CNPJ, e-mails, valores, datas, obrigações, confidencialidade, publicidade, eventos e assinaturas."/></label><aside className="contracts-import-analysis"><section><h4>Variáveis detectadas</h4>{parsed.variables.length===0?<div className="crm-empty-mini">Nenhuma variável detectada.</div>:<div className="contracts-import-findings">{parsed.variables.map((item,index)=><div key={`${item.placeholder}-${index}`}><span><strong>{item.context}</strong><br/><small>{item.originalText}</small></span><code>{item.placeholder}</code></div>)}</div>}</section><section><h4>Contextos contratuais</h4>{parsed.clauseTypes.length===0?<div className="crm-empty-mini">Nenhum contexto específico detectado.</div>:<div className="contracts-clause-tags">{parsed.clauseTypes.map(item=><span key={item}>{item.replace(/_/g,' ')}</span>)}</div>}</section></aside></div></div><footer className="crm-modal-foot"><button className="crm-btn secondary" onClick={onClose}>Cancelar</button><button className="crm-btn primary" disabled={!text.trim()} onClick={()=>{onApply(asHtml(text));onClose()}}>Aplicar ao documento</button></footer></section></div>
}
