import {AlertCircle,CheckCircle2,Clock,ExternalLink,FileText,History,MailCheck,PenLine,User,X} from 'lucide-react'
import {useMemo,useState,type ReactNode} from 'react'
import {contractStatusOptions,optionLabel,partyEntityTypeOptions,partySourceOptions,signatureStatusOptions,type Contract,type ContractCategory,type ContractParty,type ContractSigner} from '../domain'
import {formatCurrency,formatDate,formatDateTime} from '../format'
import {ContractA4Preview} from './ContractA4Preview'

type ViewTab='info'|'parties'|'payment'|'signature'|'document'|'versions'|'attachments'|'timeline'
const signerRoleLabel:Record<ContractSigner['role'],string>={contractor:'Contratante',contracted:'Contratada',legal_representative:'Representante legal',witness:'Testemunha',other:'Outro'}
const partyRoleLabel:Record<ContractParty['role'],string>={contractor:'Contratante',contracted:'Contratada',other:'Outra parte'}
const viewStyles={summary:{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:1,background:'#e9e9e9',border:'1px solid #e9e9e9',borderRadius:10,overflow:'hidden',marginBottom:22} as const,summaryItem:{background:'#fff',padding:'13px 15px',minWidth:0} as const,summaryLabel:{display:'block',fontSize:9,fontWeight:800,letterSpacing:'.06em',textTransform:'uppercase',color:'#888',marginBottom:5} as const,summaryValue:{display:'block',fontSize:12,fontWeight:800,color:'#222',overflowWrap:'anywhere'} as const,section:{padding:'16px 0 2px',borderTop:'1px solid #ededed'} as const,party:{display:'grid',gridTemplateColumns:'36px minmax(0,1fr)',gap:14,padding:'16px',border:'1px solid #ececec',borderRadius:10,background:'#fff'} as const}

export function ContractViewModal({contract,categories,onClose}:{contract:Contract;categories:ContractCategory[];onClose:()=>void}){
 const [tab,setTab]=useState<ViewTab>('info')
 const category=categories.find(c=>c.id===contract.categoryId)?.name??'—'
 const contractor=contract.parties.find(p=>p.role==='contractor')
 const signedAt=contract.timeline.find(item=>/assinado/i.test(item.event))?.createdAt
 const expiry=useMemo(()=>{if(!contract.endDate)return null;const end=new Date(contract.endDate);const today=new Date();today.setHours(0,0,0,0);const in30=new Date(today);in30.setDate(in30.getDate()+30);if(end<today||end>in30)return null;return Math.ceil((end.getTime()-today.getTime())/86400000)},[contract.endDate])
 const tabs:Array<[ViewTab,string]>=[['info','Informações'],['parties',`Partes (${contract.parties.length})`],['payment','Pagamento'],['signature',`Assinatura${contract.signers.length?` (${contract.signers.length})`:''}`],['document','Documento'],['versions',`Versões${contract.document.versions.length?` (${contract.document.versions.length})`:''}`],['attachments',`Anexos${contract.attachments.length?` (${contract.attachments.length})`:''}`],['timeline','Histórico']]
 return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}>
  <section className="contracts-original-dialog" role="dialog" aria-modal="true" aria-label="Visualizar contrato">
   <header className="contracts-original-header"><div className="contracts-original-header-row"><div className="contracts-original-header-icon"><FileText size={20}/></div><div className="contracts-original-title-wrap"><h2>{contract.title||'Contrato sem título'}</h2><div className="contracts-original-badges"><span className={`contracts-status status-${contract.status}`}>{optionLabel(contractStatusOptions,contract.status)}</span><span className="contracts-original-outline-badge">{category}</span><span className="contracts-original-outline-badge">{optionLabel(signatureStatusOptions,contract.signatureStatus)}</span>{contract.signingProvider&&<span className="contracts-original-outline-badge">{contract.signingProvider}</span>}{expiry!==null&&<span className="contracts-original-warning-badge"><AlertCircle size={12}/>Expira em {expiry}d</span>}</div></div></div><button className="contracts-original-close" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header>
   <div className="contracts-original-tabs-shell"><nav className="contracts-original-tabs" role="tablist" aria-label="Seções do contrato">{tabs.map(([key,label])=><button key={key} type="button" role="tab" aria-selected={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav><div className="contracts-original-scroll">
    {tab==='info'&&<section className="contracts-original-tab-content contracts-original-info-tab"><div style={viewStyles.summary}><Summary label="Contratante" value={contractor?.name}/><Summary label="Vigência" value={`${formatDate(contract.startDate)} — ${contract.endDate?formatDate(contract.endDate):'Indeterminado'}`}/><Summary label="Valor" value={formatCurrency(contract.payment.amount,contract.payment.currency)}/><Summary label="Assinatura" value={optionLabel(signatureStatusOptions,contract.signatureStatus)}/></div><SectionTitle>Identificação</SectionTitle><div className="contracts-original-info-grid"><InfoItem label="Título" value={contract.title}/><InfoItem label="Número / Código" value={contract.number}/><InfoItem label="Tipo" value={contract.type}/><InfoItem label="Categoria" value={category}/><InfoItem label="Status" value={optionLabel(contractStatusOptions,contract.status)}/><InfoItem label="Cliente / Contratante" value={contractor?.name}/></div><div style={viewStyles.section}><SectionTitle>Vigência e contexto</SectionTitle><div className="contracts-original-info-grid"><InfoItem label="Data de início" value={formatDate(contract.startDate)}/><InfoItem label="Data de término" value={contract.endDate?formatDate(contract.endDate):'Indeterminado'}/><InfoItem label="Duração" value={contract.duration}/><InfoItem label="Valor" value={formatCurrency(contract.payment.amount,contract.payment.currency)}/><InfoItem label="Status da assinatura" value={optionLabel(signatureStatusOptions,contract.signatureStatus)}/><InfoItem label="Assinado em" value={signedAt?formatDateTime(signedAt):'—'}/></div></div><ReadBlock label="Descrição / Observações" value={contract.description}/><ReadBlock label="Notas internas" value={contract.internalNotes}/><div style={viewStyles.section}><SectionTitle>Variáveis do contrato</SectionTitle>{Object.keys(contract.variableValues).length>0?<div className="contracts-original-info-grid">{Object.entries(contract.variableValues).map(([key,value])=><InfoItem key={key} label={key} value={value}/>)}</div>:<EmptyText>Nenhuma variável preenchida.</EmptyText>}</div><div style={viewStyles.section}><SectionTitle>Metadados</SectionTitle><div className="contracts-original-info-grid"><InfoItem label="ID do contrato" value={contract.id}/><InfoItem label="Criado em" value={formatDateTime(contract.createdAt)}/><InfoItem label="Atualizado em" value={formatDateTime(contract.updatedAt)}/></div></div></section>}
    {tab==='parties'&&<section className="contracts-original-tab-content"><SectionTitle>Partes do contrato ({contract.parties.length})</SectionTitle>{contract.parties.length>0?<div className="contracts-original-list versions">{contract.parties.map((party,index)=><article style={viewStyles.party} key={party.id}><div className="contracts-original-history-icon"><User size={16}/></div><div style={{width:'100%'}}><div className="contracts-original-version-title"><strong>{party.name||`Parte ${index+1}`}</strong><span className="contracts-original-outline-badge">{partyRoleLabel[party.role]}</span></div><ReadGrid><InfoItem label="Papel" value={partyRoleLabel[party.role]}/><InfoItem label="Origem" value={optionLabel(partySourceOptions,party.source)}/><InfoItem label="Tipo" value={optionLabel(partyEntityTypeOptions,party.entityType)}/><InfoItem label="Contato CRM" value={party.crmContactId}/><InfoItem label={party.entityType==='company'?'Razão Social':'Nome completo'} value={party.name}/><InfoItem label="Nome Fantasia" value={party.tradeName}/><InfoItem label={party.entityType==='company'?'CNPJ':'CPF'} value={party.document}/><InfoItem label="RG" value={party.rg}/><InfoItem label="E-mail" value={party.email}/><InfoItem label="Telefone" value={party.phone}/><InfoItem label="Nacionalidade" value={party.nationality}/><InfoItem label="Profissão" value={party.occupation}/><InfoItem label="Estado civil" value={party.maritalStatus}/><InfoItem label="Endereço" value={party.address}/><InfoItem label="Cidade" value={party.city}/><InfoItem label="Estado" value={party.state}/><InfoItem label="Representante legal" value={party.representativeName}/><InfoItem label="CPF do representante" value={party.representativeDocument}/><InfoItem label="Cargo / Função" value={party.representativeRole}/><InfoItem label="E-mail do representante" value={party.representativeEmail}/></ReadGrid></div></article>)}</div>:<EmptyText>Nenhuma parte cadastrada.</EmptyText>}</section>}
    {tab==='payment'&&<section className="contracts-original-tab-content contracts-original-info-tab"><div style={viewStyles.summary}><Summary label="Valor" value={formatCurrency(contract.payment.amount,contract.payment.currency)}/><Summary label="Moeda" value={contract.payment.currency}/><Summary label="Periodicidade" value={contract.payment.periodicity}/><Summary label="Forma de pagamento" value={contract.payment.method}/></div><SectionTitle>Condições de pagamento</SectionTitle><div className="contracts-original-info-grid"><InfoItem label="Valor" value={formatCurrency(contract.payment.amount,contract.payment.currency)}/><InfoItem label="Moeda" value={contract.payment.currency}/><InfoItem label="Periodicidade" value={contract.payment.periodicity}/><InfoItem label="Forma de pagamento" value={contract.payment.method}/><InfoItem label="Parcelas" value={String(contract.payment.installments||'—')}/><InfoItem label="Dia de vencimento" value={String(contract.payment.dueDay||'—')}/><InfoItem label="Multa" value={contract.payment.finePercent!==''?`${contract.payment.finePercent}%`:'—'}/><InfoItem label="Juros" value={contract.payment.interestPercent!==''?`${contract.payment.interestPercent}%`:'—'}/></div><ReadBlock label="Observações de pagamento" value={contract.payment.notes}/></section>}
    {tab==='signature'&&<section className="contracts-original-tab-content contracts-original-signature-tab"><div style={viewStyles.summary}><Summary label="Status" value={optionLabel(signatureStatusOptions,contract.signatureStatus)}/><Summary label="Provedor" value={contract.signingProvider}/><Summary label="Signatários" value={String(contract.signers.length)}/><Summary label="Documento" value={contract.document.title}/></div><SectionTitle>Processo de assinatura digital</SectionTitle><div className="contracts-original-info-grid"><InfoItem label="Status" value={optionLabel(signatureStatusOptions,contract.signatureStatus)}/><InfoItem label="Provedor" value={contract.signingProvider}/><InfoItem label="ID externo" value={contract.document.externalId}/><InfoItem label="Documento" value={contract.document.title}/></div>{contract.signers.length>0?<><div style={viewStyles.section}><SectionTitle>Signatários ({contract.signers.length})</SectionTitle><div className="contracts-original-list">{[...contract.signers].sort((a,b)=>a.order-b.order).map(signer=><article className="contracts-original-row-card" key={signer.id}><div className="contracts-original-avatar">{signer.status==='signed'?<CheckCircle2 size={14}/>:<User size={14}/>}</div><div className="contracts-original-row-copy"><strong>{signer.name||'Signatário sem nome'}</strong><span><MailCheck size={12}/>{signer.email||'—'}</span><span>Documento: {signer.document||'—'} · Ordem: {signer.order} · {signer.required?'Obrigatório':'Opcional'}</span>{signer.partyId&&<span>Parte vinculada: {contract.parties.find(p=>p.id===signer.partyId)?.name||signer.partyId}</span>}</div><div className="contracts-original-signer-status"><span className="contracts-original-outline-badge">{signerRoleLabel[signer.role]}</span><span className="contracts-original-outline-badge">{optionLabel(signatureStatusOptions,signer.status)}</span></div></article>)}</div></div></>:<div className="contracts-original-empty"><div><PenLine size={32}/></div><strong>Nenhum signatário definido</strong><span>Este contrato não possui signatários configurados.</span></div>}</section>}
    {tab==='document'&&<section className="contracts-original-tab-content"><SectionTitle>Documento principal</SectionTitle><div className="contracts-original-info-grid"><InfoItem label="ID do documento" value={contract.document.id}/><InfoItem label="Título" value={contract.document.title}/><InfoItem label="Status" value={optionLabel(signatureStatusOptions,contract.document.status)}/><InfoItem label="Provedor" value={contract.document.provider}/><InfoItem label="ID externo" value={contract.document.externalId}/><InfoItem label="Versões" value={String(contract.document.versions.length)}/></div>{contract.document.signedFileUrl&&<article className="contracts-original-file-card"><div className="contracts-original-file-icon"><FileText size={32}/></div><div><strong>Arquivo assinado</strong><code>{contract.document.signedFileUrl}</code></div><a className="crm-btn secondary" href={contract.document.signedFileUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>Abrir PDF</a></article>}<div style={viewStyles.section}><SectionTitle>Pré-visualização do conteúdo</SectionTitle><ContractA4Preview document={contract.document}/></div></section>}
    {tab==='versions'&&<section className="contracts-original-tab-content">{contract.document.versions.length>0?<div className="contracts-original-list versions">{contract.document.versions.map((version,index)=><article className="contracts-original-version-card" key={version.id}><div className="contracts-original-history-icon"><History size={16}/></div><div><div className="contracts-original-version-title"><strong>Versão {version.version}</strong>{index===contract.document.versions.length-1&&<span className="contracts-original-current-badge">Atual</span>}</div><span><Clock size={12}/>{formatDateTime(version.createdAt)}</span><span><User size={12}/>{version.createdBy||'—'}</span><span>Provedor: {version.provider||'—'} · ID externo: {version.externalId||'—'}</span>{version.notes&&<p>{version.notes}</p>}</div>{version.fileUrl&&<a className="crm-btn secondary small" href={version.fileUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={12}/>Abrir arquivo</a>}</article>)}</div>:<div className="contracts-original-empty plain"><History size={48}/><strong>Sem histórico de versões</strong><span>Nenhuma versão registrada para este documento.</span></div>}</section>}
    {tab==='attachments'&&<section className="contracts-original-tab-content">{contract.attachments.length>0?<div className="contracts-original-list versions">{contract.attachments.map(attachment=><article className="contracts-original-version-card" key={attachment.id}><div className="contracts-original-history-icon"><FileText size={16}/></div><div><strong>{attachment.name}</strong><span>Tipo: {attachment.type||'—'}</span><span>Tamanho: {attachment.size>0?`${Math.round(attachment.size/1024)} KB`:'—'}</span><span>Adicionado em: {formatDateTime(attachment.createdAt)}</span></div><a className="crm-btn secondary small" href={attachment.dataUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={12}/>Abrir</a></article>)}</div>:<div className="contracts-original-empty plain"><FileText size={48}/><strong>Nenhum documento anexado</strong><span>Este contrato não possui anexos.</span></div>}</section>}
    {tab==='timeline'&&<section className="contracts-original-tab-content">{contract.timeline.length>0?<div className="contracts-original-list versions">{[...contract.timeline].reverse().map(item=><article className="contracts-original-version-card" key={item.id}><div className="contracts-original-history-icon"><History size={16}/></div><div><strong>{item.event}</strong><span><Clock size={12}/>{formatDateTime(item.createdAt)}</span><span><User size={12}/>{item.actor||'—'}</span>{item.description&&<p>{item.description}</p>}</div></article>)}</div>:<div className="contracts-original-empty plain"><History size={48}/><strong>Sem histórico registrado</strong><span>Este contrato ainda não possui eventos registrados.</span></div>}</section>}
   </div></div><footer className="contracts-original-footer"><span/><button className="crm-btn secondary small" onClick={onClose}>Fechar</button></footer>
  </section>
 </div>
}
function Summary({label,value}:{label:string;value?:string}){return <div style={viewStyles.summaryItem}><span style={viewStyles.summaryLabel}>{label}</span><strong style={viewStyles.summaryValue}>{value||'—'}</strong></div>}
function SectionTitle({children}:{children:ReactNode}){return <p className="contracts-original-section-title" style={{marginTop:18}}>{children}</p>}
function ReadGrid({children}:{children:ReactNode}){return <div className="contracts-original-info-grid" style={{marginTop:12}}>{children}</div>}
function InfoItem({label,value}:{label:string;value?:string}){return <div><p className="contracts-original-field-label">{label}</p><p className="contracts-original-field-value">{value||'—'}</p></div>}
function ReadBlock({label,value}:{label:string;value?:string}){return <div className="contracts-original-observations"><p className="contracts-original-field-label">{label}</p><div style={{whiteSpace:'pre-wrap'}}>{value||'—'}</div></div>}
function EmptyText({children}:{children:ReactNode}){return <div className="contracts-original-empty plain"><span>{children}</span></div>}
