import {FileText,MoreHorizontal,Plus,Save,Search,X} from 'lucide-react'
import {useMemo,useRef,useState} from 'react'
import type {ContractCategory,ContractTemplate,ContractVariable} from '../domain'
import {extractPlaceholders} from '../variables'
import {ContractA4Preview} from './ContractA4Preview'

type SortDirection='asc'|'desc'
type TemplateSortKey='name'|'category'|'variables'|'status'
type SortState={key:TemplateSortKey;direction:SortDirection}|null
const compare=(a:string|number,b:string|number,direction:SortDirection)=>{const result=typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b),'pt-BR',{numeric:true,sensitivity:'base'});return direction==='asc'?result:-result}

export function TemplatesPanel({templates,categories,variables,creating,onCreatingChange,onSave,onDelete}:{templates:ContractTemplate[];categories:ContractCategory[];variables:ContractVariable[];creating:boolean;onCreatingChange:(open:boolean)=>void;onSave:(value:Omit<ContractTemplate,'id'|'createdAt'|'updatedAt'> & {id?:string})=>Promise<unknown>;onDelete:(id:string)=>Promise<unknown>}){
 const [editing,setEditing]=useState<ContractTemplate|undefined>(),[viewing,setViewing]=useState<ContractTemplate|undefined>(),[selected,setSelected]=useState<string[]>([]),[sort,setSort]=useState<SortState>(null)
 const sorted=useMemo(()=>{if(!sort)return templates;const value=(template:ContractTemplate):string|number=>sort.key==='name'?template.name:sort.key==='category'?(categories.find(c=>c.id===template.categoryId)?.name??''):sort.key==='variables'?template.variableKeys.length:(template.active?'Ativo':'Inativo');return [...templates].sort((a,b)=>compare(value(a),value(b),sort.direction))},[templates,categories,sort])
 const allSelected=sorted.length>0&&sorted.every(template=>selected.includes(template.id))
 const toggleAll=(checked:boolean)=>setSelected(checked?sorted.map(template=>template.id):[])
 return <section className="contracts-registry"><header><div><h2>Templates</h2><p>Modelos reutilizáveis com conteúdo, header, footer e variáveis.</p></div></header>{templates.length===0?<div className="contracts-empty"><FileText size={28}/><strong>Nenhum template cadastrado.</strong><button className="crm-btn primary" onClick={()=>onCreatingChange(true)}>Novo Template</button></div>:<div className="contracts-registry-table"><div className="contracts-registry-row head" style={registryRowStyle}><span style={checkboxCellStyle}><input style={checkboxStyle} type="checkbox" aria-label="Selecionar todos os templates exibidos" checked={allSelected} onChange={event=>toggleAll(event.target.checked)}/></span><span><SortHeader label="Nome" column="name" sort={sort} onSort={setSort}/></span><span><SortHeader label="Categoria" column="category" sort={sort} onSort={setSort}/></span><span><SortHeader label="Variáveis" column="variables" sort={sort} onSort={setSort}/></span><span><SortHeader label="Status" column="status" sort={sort} onSort={setSort}/></span><span>Ações</span></div>{sorted.map(t=><div className="contracts-registry-row" style={registryRowStyle} key={t.id}><span style={checkboxCellStyle}><input style={checkboxStyle} type="checkbox" aria-label={`Selecionar ${t.name}`} checked={selected.includes(t.id)} onChange={()=>setSelected(selected.includes(t.id)?selected.filter(id=>id!==t.id):[...selected,t.id])}/></span><strong>{t.name}</strong><span>{categories.find(c=>c.id===t.categoryId)?.name??'—'}</span><span>{t.variableKeys.length}</span><span>{t.active?'Ativo':'Inativo'}</span><TemplateActions onView={()=>setViewing(t)} onEdit={()=>setEditing(t)} onDuplicate={()=>void onSave({...t,id:undefined,name:`${t.name} — cópia`,variableKeys:[...t.variableKeys]})} onDelete={()=>confirm(`Excluir o template ${t.name}?`)&&void onDelete(t.id)}/></div>)}</div>}{(creating||editing)&&<TemplateWorkspace initial={editing} categories={categories} variables={variables} onClose={()=>{onCreatingChange(false);setEditing(undefined)}} onSave={async value=>{await onSave(value);onCreatingChange(false);setEditing(undefined)}}/>}{viewing&&<TemplateView template={viewing} category={categories.find(c=>c.id===viewing.categoryId)} onClose={()=>setViewing(undefined)}/>}</section>
}

function SortHeader({label,column,sort,onSort}:{label:string;column:TemplateSortKey;sort:SortState;onSort:(state:NonNullable<SortState>)=>void}){const direction=sort?.key===column?sort.direction:null;const buttonStyle=(active:boolean)=>({width:14,height:20,padding:0,border:'none',background:'transparent',color:active?'#111':'#aaa',fontSize:13,fontWeight:active?900:700,lineHeight:1,cursor:'pointer',opacity:active?1:.55} as const);return <div className="crm-sort-header"><span>{label}</span><div role="group" aria-label={`Ordenar ${label}`} style={{display:'inline-flex',alignItems:'center',gap:0}}><button type="button" style={buttonStyle(direction==='asc')} aria-label={`${label}: ordem crescente`} aria-pressed={direction==='asc'} onClick={()=>onSort({key:column,direction:'asc'})}>↑</button><button type="button" style={buttonStyle(direction==='desc')} aria-label={`${label}: ordem decrescente`} aria-pressed={direction==='desc'} onClick={()=>onSort({key:column,direction:'desc'})}>↓</button></div></div>}
function TemplateActions({onView,onEdit,onDuplicate,onDelete}:{onView:()=>void;onEdit:()=>void;onDuplicate:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);return <div className="crm-row-actions" style={actionCellStyle}><button className="crm-icon-btn" aria-label="Ações" onClick={()=>setOpen(value=>!value)}><MoreHorizontal size={16}/></button>{open&&<div className="crm-row-menu"><button onClick={()=>{setOpen(false);onView()}}>Ver</button><button onClick={()=>{setOpen(false);onEdit()}}>Editar</button><button onClick={()=>{setOpen(false);onDuplicate()}}>Duplicar</button><button className="danger" onClick={()=>{setOpen(false);onDelete()}}>Excluir</button></div>}</div>}
const registryRowStyle={gridTemplateColumns:'44px minmax(180px,1.5fr) minmax(140px,1fr) minmax(100px,.65fr) minmax(90px,.65fr) 72px',alignItems:'center'}
const checkboxCellStyle={width:44,minWidth:44,display:'flex',alignItems:'center',justifyContent:'center'}
const checkboxStyle={width:15,height:15,margin:0}
const actionCellStyle={width:'100%',display:'flex',alignItems:'center',justifyContent:'flex-start'}

type WorkspaceTab='template'|'variables'|'categories'|'preview'
function TemplateWorkspace({initial,categories,variables,onClose,onSave}:{initial?:ContractTemplate;categories:ContractCategory[];variables:ContractVariable[];onClose:()=>void;onSave:(value:Omit<ContractTemplate,'id'|'createdAt'|'updatedAt'> & {id?:string})=>Promise<void>}){
 const [name,setName]=useState(initial?.name??''),[categoryId,setCategoryId]=useState(initial?.categoryId??''),[contentHtml,setContent]=useState(initial?.contentHtml??''),[headerHtml,setHeader]=useState(initial?.headerHtml??''),[footerHtml,setFooter]=useState(initial?.footerHtml??''),[active,setActive]=useState(initial?.active??true),[tab,setTab]=useState<WorkspaceTab>('template'),[search,setSearch]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const textareaRef=useRef<HTMLTextAreaElement>(null)
 const keys=extractPlaceholders(`${headerHtml}\n${contentHtml}\n${footerHtml}`)
 const filtered=useMemo(()=>variables.filter(v=>!search.trim()||`${v.name} ${v.key} ${v.group}`.toLowerCase().includes(search.trim().toLowerCase())),[variables,search])
 const groups=useMemo(()=>Array.from(new Set(filtered.map(v=>v.group))),[filtered])
 const insertVariable=(key:string)=>{const el=textareaRef.current;if(!el){setContent(v=>`${v}${v?'\n':''}${key}`);return}const start=el.selectionStart,end=el.selectionEnd;setContent(value=>value.slice(0,start)+key+value.slice(end));requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start+key.length,start+key.length)})}
 const save=async()=>{if(!name.trim()||!categoryId){setError('Informe nome e categoria.');return}setSaving(true);setError('');try{await onSave({id:initial?.id,name:name.trim(),categoryId,description:initial?.description??'',contentHtml,headerHtml,footerHtml,variableKeys:keys,active})}finally{setSaving(false)}}
 return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="contracts-template-workspace" role="dialog" aria-modal="true" aria-label={initial?'Editar Template de Contrato':'Novo Template de Contrato'}>
   <header className="contracts-template-workspace-head"><div><h2>{initial?'Editar Template de Contrato':'Novo Template de Contrato'}</h2><p>{initial?'Edite o conteúdo e as configurações do template.':'Crie templates reutilizáveis para geração automática de contratos.'}</p></div><button className="contracts-template-workspace-close" onClick={onClose} aria-label="Fechar"><X size={18}/></button><nav className="contracts-template-workspace-tabs">{([['template','Template'],['variables','Variáveis'],['categories','Categorias'],['preview','Preview']] as const).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav></header>
   <div className="contracts-template-workspace-body">
    {tab==='template'&&<div className="contracts-template-workspace-template"><main className="contracts-template-workspace-main"><section className="contracts-template-workspace-basics"><div><span>Informações Básicas</span><label>Nome do Template<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex: Contrato de Prestação de Serviços"/></label><label>Categoria do Template<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Selecionar categoria…</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div><div><span>Identidade Visual do Documento</span><label>Cabeçalho<textarea rows={3} value={headerHtml} onChange={e=>setHeader(e.target.value)} placeholder="Conteúdo do cabeçalho"/></label><label>Rodapé<textarea rows={3} value={footerHtml} onChange={e=>setFooter(e.target.value)} placeholder="Conteúdo do rodapé"/></label></div></section><section className="contracts-template-workspace-editor"><div><span>Conteúdo do Contrato</span><small>{keys.length} variável(is) detectada(s)</small></div><textarea ref={textareaRef} value={contentHtml} onChange={e=>setContent(e.target.value)} placeholder={'Escreva o conteúdo do contrato…\n\nUse {{GRUPO.CAMPO}} para inserir variáveis dinâmicas,\nou clique no [+] no painel de variáveis à direita.'}/></section></main><aside className="contracts-template-workspace-vars"><header><strong>Variáveis do Registro</strong><label><Search size={13}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar variáveis…"/></label></header><div className="contracts-template-workspace-varscroll">{groups.length===0?<p>Nenhuma variável encontrada.</p>:groups.map(group=><section key={group}><h4>{group}</h4>{filtered.filter(v=>v.group===group).map(v=><div key={v.id}><span><code>{v.key}</code><small>{v.name}</small></span><button onClick={()=>insertVariable(v.key)} title={`Inserir ${v.key}`}><Plus size={14}/></button></div>)}</section>)}</div></aside></div>}
    {tab==='variables'&&<div className="contracts-template-registry-tab"><header><h3>Variáveis</h3><p>Placeholders disponíveis para templates e documentos.</p></header><div>{variables.map(v=><article key={v.id}><div><strong>{v.name}</strong><code>{v.key}</code><small>{v.group} · {v.type}</small></div><span>{v.required?'Obrigatória':'Opcional'}</span></article>)}</div></div>}
    {tab==='categories'&&<div className="contracts-template-registry-tab"><header><h3>Categorias</h3><p>Classificação disponível para os templates.</p></header><div>{[...categories].sort((a,b)=>a.order-b.order).map(c=><article key={c.id}><div><strong>{c.name}</strong><small>{c.description||'Sem descrição'}</small></div><span>{c.active?'Ativa':'Inativa'}</span></article>)}</div></div>}
    {tab==='preview'&&<div className="contracts-template-workspace-preview"><ContractA4Preview document={{contentHtml,headerHtml,footerHtml}}/></div>}
   </div>
   <footer className="contracts-template-workspace-foot"><div><label className="contracts-check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Template ativo</label>{error&&<span className="crm-error-inline">{error}</span>}</div><div><button className="crm-btn secondary" onClick={onClose}>Cancelar</button><button className="crm-btn primary" disabled={saving} onClick={()=>void save()}><Save size={14}/>{saving?'Salvando…':'Salvar Template'}</button></div></footer>
  </section></div>
}

function TemplateView({template,category,onClose}:{template:ContractTemplate;category?:ContractCategory;onClose:()=>void}){return <div className="crm-modal-backdrop"><section className="crm-modal crm-modal-lg contracts-template-modal"><header className="crm-modal-head"><div><div className="crm-badge-row"><span className="crm-badge">{category?.name??'Sem categoria'}</span><span className="crm-badge muted">{template.active?'Ativo':'Inativo'}</span></div><h2>{template.name}</h2><p>{template.description}</p></div><button className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><div className="crm-modal-body"><div className="contracts-template-vars"><strong>Variáveis</strong><div>{template.variableKeys.map(k=><span key={k}>{k}</span>)}</div></div><ContractA4Preview document={{contentHtml:template.contentHtml,headerHtml:template.headerHtml,footerHtml:template.footerHtml}}/></div><footer className="crm-modal-foot"><button className="crm-btn secondary" onClick={onClose}>Fechar</button></footer></section></div>}
