import {ArrowDownLeft,ArrowLeftRight,ArrowUpRight,Download,FileText,Plus,Scale,Search,X} from 'lucide-react'
import {useMemo,useState,type FormEvent,type ReactNode} from 'react'
import {useNavigate} from 'react-router-dom'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {invoiceStatusOptions,invoiceTypeOptions,money,uid,type FinanceInvoice,type InvoiceStatus,type InvoiceType} from './domain'
import {financeRepository} from './repository'

const dateLabel=(value:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—'

export default function FinanceInvoicesPage(){
 const navigate=useNavigate()
 const [invoices,setInvoices]=useState(financeRepository.listInvoices),[invoiceModal,setInvoiceModal]=useState<FinanceInvoice|null|undefined>(undefined),[search,setSearch]=useState(''),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[page,setPage]=useState(1)
 const updateInvoices=(next:FinanceInvoice[])=>{setInvoices(next);financeRepository.saveInvoices(next)}
 const filtered=useMemo(()=>invoices.filter(x=>(!search||[x.number,x.party,x.document].some(v=>v.toLowerCase().includes(search.toLowerCase())))&&(type==='all'||x.type===type)&&(status==='all'||x.status===status)&&(!start||x.issueDate>=start)&&(!end||x.issueDate<=end)),[invoices,search,type,status,start,end])
 const pages=Math.max(1,Math.ceil(filtered.length/10)),items=filtered.slice((Math.min(page,pages)-1)*10,Math.min(page,pages)*10)
 const outputs=invoices.filter(x=>x.type==='saida'),inputs=invoices.filter(x=>x.type==='entrada'),outValue=outputs.reduce((s,x)=>s+x.amount,0),inValue=inputs.reduce((s,x)=>s+x.amount,0),balance=outValue-inValue
 return <AdminShell area="finance" items={CRM_WORKSPACE_NAV} header={{title:'Notas Fiscais',description:'Registro e controle de notas fiscais de entrada e saída'}} headerActions={[{label:'Financeiro',variant:'secondary',icon:ArrowLeftRight,onClick:()=>navigate('/app/finance')},{label:'Registrar Nota',icon:Plus,onClick:()=>setInvoiceModal(null)}]}>
  <section className="finance-page">
   <div className="finance-kpis finance-invoice-six">
    <Kpi title="Total" value={String(invoices.length)} icon={<FileText/>}/><Kpi title="Saídas" value={String(outputs.length)} icon={<ArrowUpRight/>}/><Kpi title="Entradas" value={String(inputs.length)} icon={<ArrowDownLeft/>}/><Kpi title="Valor Saídas" value={money(outValue)} icon={<ArrowUpRight/>}/><Kpi title="Valor Entradas" value={money(-inValue)} icon={<ArrowDownLeft/>}/><Kpi title="Saldo" value={`${balance>=0?'+':''}${money(balance)}`} icon={<Scale/>}/>
   </div>
   <div className="finance-filters"><input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(1)}}/><input type="date" value={end} onChange={e=>{setEnd(e.target.value);setPage(1)}}/><label className="finance-search"><Search size={15}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar por número, cliente ou fornecedor…"/></label><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="all">Todas</option>{invoiceTypeOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todos</option>{invoiceStatusOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
   <section className="finance-table-card"><header><div><h3>Lista de Notas Fiscais</h3><p>Registro de notas de entrada e saída · {filtered.length} registro(s)</p></div></header><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th></th><th>Número</th><th>Tipo</th><th>Cliente / Fornecedor</th><th>Valor</th><th>Data Emissão</th><th>Status</th><th>PDF</th><th>Ações</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><input type="checkbox"/></td><td><strong>{x.number}/{x.series}</strong></td><td>{x.type==='saida'?'Saída':'Entrada'}</td><td>{x.party}<small className="finance-cell-sub">{x.document}</small></td><td>{money(x.amount)}</td><td>{dateLabel(x.issueDate)}</td><td><span className={`finance-status ${x.status}`}>{x.status[0].toUpperCase()+x.status.slice(1)}</span></td><td>{x.pdfUrl?<button className="crm-icon-btn" onClick={()=>window.open(x.pdfUrl,'_blank')}><Download size={15}/></button>:'—'}</td><td>•••</td></tr>)}</tbody></table></div><footer className="finance-pagination"><span>Página {Math.min(page,pages)} de {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></footer></section>
  </section>
  {invoiceModal!==undefined&&<InvoiceModal initial={invoiceModal} onClose={()=>setInvoiceModal(undefined)} onSave={value=>{const now=new Date().toISOString();const next=value.id?invoices.map(item=>item.id===value.id?{...value,updatedAt:now}:item):[{...value,id:uid('nf'),createdAt:now,updatedAt:now},...invoices];updateInvoices(next);setInvoiceModal(undefined)}}/>}
 </AdminShell>
}

function InvoiceModal({initial,onClose,onSave}:{initial:FinanceInvoice|null;onClose:()=>void;onSave:(x:FinanceInvoice)=>void}){
 const now=new Date().toISOString(),blank:FinanceInvoice={id:'',number:'',series:'001',type:'saida',party:'',document:'',issueDate:new Date().toISOString().slice(0,10),dueDate:'',amount:0,status:'pendente',description:'',pdfUrl:'',createdAt:now,updatedAt:now}
 const [form,setForm]=useState(initial?{...initial}:blank)
 const save=(event:FormEvent)=>{event.preventDefault();if(!form.number.trim()||!form.party.trim()||form.amount<=0)return;onSave(form)}
 return <div className="crm-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="finance-modal wide" role="dialog" aria-modal="true" aria-label={initial?'Editar Nota Fiscal':'Registrar Nota Fiscal'}><header><div><span>Financeiro</span><h2>{initial?'Editar Nota Fiscal':'Registrar Nota Fiscal'}</h2></div><button className="crm-icon-btn" type="button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><form onSubmit={save}><div className="finance-modal-body"><section className="finance-form-section"><h3>Dados da Nota</h3><div className="finance-form-grid"><SelectField label="Tipo" value={form.type} onChange={value=>setForm(current=>({...current,type:value as InvoiceType}))} options={invoiceTypeOptions}/><Field label="Número" value={form.number} onChange={value=>setForm(current=>({...current,number:value}))}/><Field label="Série" value={form.series} onChange={value=>setForm(current=>({...current,series:value}))}/><Field label={form.type==='saida'?'Cliente':'Fornecedor'} value={form.party} onChange={value=>setForm(current=>({...current,party:value}))}/><Field label="CPF / CNPJ" value={form.document} onChange={value=>setForm(current=>({...current,document:value}))}/><Field label="Valor" type="number" value={String(form.amount||'')} onChange={value=>setForm(current=>({...current,amount:Number(value)}))}/><Field label="Data de Emissão" type="date" value={form.issueDate} onChange={value=>setForm(current=>({...current,issueDate:value}))}/><Field label="Vencimento" type="date" value={form.dueDate} onChange={value=>setForm(current=>({...current,dueDate:value}))}/><SelectField label="Status" value={form.status} onChange={value=>setForm(current=>({...current,status:value as InvoiceStatus}))} options={invoiceStatusOptions}/></div><label className="finance-field wide"><span>Descrição / Serviço</span><textarea rows={4} value={form.description} onChange={event=>setForm(current=>({...current,description:event.target.value}))}/></label><Field label="URL do PDF" value={form.pdfUrl} onChange={value=>setForm(current=>({...current,pdfUrl:value}))}/></section></div><footer className="finance-modal-foot"><button type="button" className="crm-btn secondary" onClick={onClose}>Cancelar</button><button className="crm-btn primary" type="submit">{initial?'Salvar Alterações':'Registrar Nota'}</button></footer></form></section></div>
}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="finance-field"><span>{label}</span><input type={type} value={value} onChange={event=>onChange(event.target.value)}/></label>}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:readonly (readonly [string,string])[]}){return <label className="finance-field"><span>{label}</span><select value={value} onChange={event=>onChange(event.target.value)}>{options.map(([key,labelText])=><option key={key} value={key}>{labelText}</option>)}</select></label>}
function Kpi({title,value,icon}:{title:string;value:string;icon:ReactNode}){return <article className="finance-kpi"><div><span>{title}</span><strong>{value}</strong></div><i>{icon}</i></article>}
