import {BookOpen,DollarSign,Search,TrendingDown,TrendingUp} from 'lucide-react'
import {useMemo,useState,type ReactNode} from 'react'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {money,type FinanceTransaction} from './domain'
import {financeRepository} from './repository'

type SortDirection='asc'|'desc'
type ResultSortKey='name'|'revenue'|'expense'|'result'|'share'
type SortState={key:ResultSortKey;direction:SortDirection}|null
const compare=(a:string|number,b:string|number,direction:SortDirection)=>{const result=typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b),'pt-BR',{numeric:true,sensitivity:'base'});return direction==='asc'?result:-result}
const filterControlStyle={flex:'0 0 auto'} as const
const searchStyle={flex:'1 1 320px',minWidth:0,width:'auto'} as const
const tableHeaderStyle={textAlign:'left' as const,verticalAlign:'middle' as const}
const tableCellStyle={textAlign:'left' as const,verticalAlign:'middle' as const}
const categoryCellContentStyle={display:'block',width:'100%',margin:0,textAlign:'left' as const}

export default function FinanceAccountingPage(){
 const [transactions]=useState(financeRepository.listTransactions),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[start,setStart]=useState(''),[end,setEnd]=useState('')
 const paid=useMemo(()=>transactions.filter(x=>x.status==='pago'&&(!start||x.date>=start)&&(!end||x.date<=end)&&(!search||[x.description,x.category,x.counterparty,x.contractRef].some(v=>v.toLowerCase().includes(search.toLowerCase())))&&(filter==='all'||filter==='revenue'&&x.type==='receita'||filter==='expenses'&&x.type==='despesa'||filter==='profit')),[transactions,start,end,search,filter])
 const revenues=paid.filter(x=>x.type==='receita'),expenses=paid.filter(x=>x.type==='despesa'),rev=revenues.reduce((s,x)=>s+x.amount,0),exp=expenses.reduce((s,x)=>s+x.amount,0),profit=rev-exp,margin=rev?profit/rev*100:0
 const categoryRows=group(paid,x=>x.category)
 return <AdminShell area="finance" items={CRM_WORKSPACE_NAV} header={{title:'Contabilidade',description:'Demonstrativos e visão contábil gerencial'}}>
  <section className="finance-page">
   <div className="finance-kpis accounting-original-kpis"><Kpi title="Receita Total" value={money(rev)} icon={<TrendingUp/>}/><Kpi title="Despesa Total" value={money(-exp)} icon={<TrendingDown/>}/><Kpi title="Lucro Líquido" value={money(profit)} icon={<DollarSign/>}/><Kpi title="Margem Líquida" value={`${margin.toFixed(1)}%`} icon={<BookOpen/>}/></div>
   <div className="finance-filters"><input style={filterControlStyle} type="date" value={start} onChange={e=>setStart(e.target.value)}/><input style={filterControlStyle} type="date" value={end} onChange={e=>setEnd(e.target.value)}/><label className="finance-search" style={searchStyle}><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por descrição ou categoria…"/></label><select style={filterControlStyle} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="revenue">Receitas</option><option value="expenses">Despesas</option><option value="profit">Lucro</option></select></div>
   <ResultTable title="Demonstrativo de Resultado" description="Receitas e despesas por categoria no período" firstColumn="Categoria" rows={categoryRows} totalRevenue={rev}/>
  </section>
 </AdminShell>
}
function group(items:FinanceTransaction[],key:(x:FinanceTransaction)=>string){const out:Record<string,{revenue:number;expense:number}>={};for(const x of items){const name=key(x);out[name]??={revenue:0,expense:0};out[name][x.type==='receita'?'revenue':'expense']+=x.amount}return Object.entries(out).map(([name,value])=>({name,...value}))}
function ResultTable({title,description,firstColumn,rows,totalRevenue}:{title:string;description:string;firstColumn:string;rows:{name:string;revenue:number;expense:number}[];totalRevenue:number}){const [sort,setSort]=useState<SortState>(null);const sorted=useMemo(()=>{if(!sort)return rows;const value=(x:{name:string;revenue:number;expense:number}):string|number=>sort.key==='name'?x.name:sort.key==='revenue'?x.revenue:sort.key==='expense'?x.expense:sort.key==='result'?x.revenue-x.expense:(totalRevenue?x.revenue/totalRevenue:0);return [...rows].sort((a,b)=>compare(value(a),value(b),sort.direction))},[rows,sort,totalRevenue]);return <section className="finance-table-card"><header><div><h3>{title}</h3><p>{description} · {rows.length} registro(s)</p></div></header><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th style={tableHeaderStyle}><SortHeader label={firstColumn} column="name" sort={sort} onSort={setSort}/></th><th style={tableHeaderStyle}><SortHeader label="Receitas" column="revenue" sort={sort} onSort={setSort}/></th><th style={tableHeaderStyle}><SortHeader label="Despesas" column="expense" sort={sort} onSort={setSort}/></th><th style={tableHeaderStyle}><SortHeader label="Resultado" column="result" sort={sort} onSort={setSort}/></th><th style={tableHeaderStyle}><SortHeader label="% Receita" column="share" sort={sort} onSort={setSort}/></th></tr></thead><tbody>{sorted.map(x=><tr key={x.name}><td style={tableCellStyle}><strong style={categoryCellContentStyle}>{x.name}</strong></td><td className="positive" style={tableCellStyle}>{money(x.revenue)}</td><td className="negative" style={tableCellStyle}>{money(-x.expense)}</td><td style={tableCellStyle}>{money(x.revenue-x.expense)}</td><td style={tableCellStyle}>{totalRevenue?`${(x.revenue/totalRevenue*100).toFixed(1)}%`:'0.0%'}</td></tr>)}</tbody></table></div></section>}
function SortHeader({label,column,sort,onSort}:{label:string;column:ResultSortKey;sort:SortState;onSort:(state:NonNullable<SortState>)=>void}){const direction=sort?.key===column?sort.direction:null;const buttonStyle=(active:boolean)=>({width:14,height:20,padding:0,border:'none',background:'transparent',color:active?'#111':'#aaa',fontSize:13,fontWeight:active?900:700,lineHeight:1,cursor:'pointer',opacity:active?1:.55} as const);return <div className="crm-sort-header" style={{justifyContent:'flex-start'}}><span>{label}</span><div role="group" aria-label={`Ordenar ${label}`} style={{display:'inline-flex',alignItems:'center',gap:0}}><button type="button" style={buttonStyle(direction==='asc')} aria-label={`${label}: ordem crescente`} aria-pressed={direction==='asc'} onClick={()=>onSort({key:column,direction:'asc'})}>↑</button><button type="button" style={buttonStyle(direction==='desc')} aria-label={`${label}: ordem decrescente`} aria-pressed={direction==='desc'} onClick={()=>onSort({key:column,direction:'desc'})}>↓</button></div></div>}
function Kpi({title,value,icon}:{title:string;value:string;icon:ReactNode}){return <article className="finance-kpi"><div><span>{title}</span><strong>{value}</strong></div><i>{icon}</i></article>}
