import {ArrowDownLeft,ArrowLeftRight,ArrowUpRight,Download,FileText,MoreHorizontal,Plus,Scale,Search,Trash2,X} from 'lucide-react'
import {useMemo,useState,type FormEvent,type ReactNode} from 'react'
import {useNavigate} from 'react-router-dom'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {invoiceStatusOptions,invoiceTypeOptions,money,uid,type FinanceInvoice,type InvoiceStatus,type InvoiceType} from './domain'
import {financeRepository} from './repository'

type SortDirection='asc'|'desc'
type InvoiceSortKey='number'|'type'|'party'|'amount'|'issueDate'|'status'
type SortState={key:InvoiceSortKey;direction:SortDirection}|null
const writeInvoices=(items:FinanceInvoice[])=>financeRepository.saveInvoices(items)
const dateLabel=(value:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const compare=(a:string|number,b:string|number,direction:SortDirection)=>{const result=typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b),'pt-BR',{numeric:true,sensitivity:'base'});return direction==='asc'?result:-result}
const checkboxCellStyle={width:44,minWidth:44,textAlign:'center' as const,paddingLeft:0,paddingRight:0}
const checkboxStyle={width:15,height:15,margin:'0 auto',display:'block'}
const filterLayout={display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10} as const
const searchStyle={gridColumn:'1 / -1',width:'100%',minWidth:0} as const

export default function FinanceInvoicesPage(){
 const navigate=useNavigate()
 const [invoices,setInvoices]=useState(financeRepository.listInvoices),[invoiceModal,setInvoiceModal]=useState<FinanceInvoice|null|undefined>(undefined),[viewing,setViewing]=useState<FinanceInvoice|null>(null),[selected,setSelected]=useState<string[]>([]),[sort,setSort]=useState<SortState>(null),[search,setSearch]=useState(''),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[page,setPage]=useState(1)
 const updateInvoices=(next:FinanceInvoice[])=>{setInvoices(next);writeInvoices(next)}
 const filtered=useMemo(()=>invoices.filter(x=>{const q=search.trim().toLowerCase();return(!q||[x.number,x.series,x.party,x.document,x.accessKey,x.operationNature,x.cfop].some(v=>String(v??'').toLowerCase().includes(q)))&&(type==='all'||x.type===type)&&(status==='all'||x.status===status)&&(!start||x.issueDate>=start)&&(!end||x.issueDate<=end)}),[invoices,search,type,status,start,end])
 const sorted=useMemo(()=>{if(!sort)return filtered;const value=(x:FinanceInvoice):string|number=>sort.key==='number'?`${x.number} ${x.series}`:sort.key==='type'?(x.type==='saida'?'Saída':'Entrada'):sort.key==='party'?`${x.party} ${x.document}`:sort.key==='amount'?x.amount:sort.key==='issueDate'?x.issueDate:x.status;return [...filtered].sort((a,b)=>compare(value(a),value(b),sort.direction))},[filtered,sort])
 const pages=Math.max(1,Math.ceil(sorted.length/10)),items=sorted.slice((Math.min(page,pages)-1)*10,Math.min(page,pages)*10)
 const outputs=invoices.filter(x=>x.type==='saida'),inputs=invoices.filter(x=>x.type==='entrada'),outValue=outputs.reduce((s,x)=>s+x.amount,0),inValue=inputs.reduce((s,x)=>s+x.amount,0),balance=outValue-inValue
 const allVisible=items.length>0&&items.every(x=>selected.includes(x.id))
 const toggleAllVisible=(checked:boolean)=>setSelected(current=>checked?Array.from(new Set([...current,...items.map(x=>x.id)])):current.filter(id=>!items.some(x=>x.id===id)))
 return <AdminShell area="finance" items={CRM_WORKSPACE_NAV} header={{title:'Notas Fiscais',description:'Registro e controle de notas fiscais de entrada e saída'}} headerActions={[{label:'Financeiro',variant:'secondary',icon:ArrowLeftRight,onClick:()=>navigate('/app/finance')},{label:'Registrar Nota',icon:Plus,onClick:()=>setInvoiceModal(null)}]}>
  <section className="finance-page">
   <div className="finance-kpis finance-invoice-six"><Kpi title="Total" value={String(invoices.length)} icon={<FileText/>}/><Kpi title="Saídas" value={String(outputs.length)} icon={<ArrowUpRight/>}/><Kpi title="Entradas" value={String(inputs.length)} icon={<ArrowDownLeft/>}/><Kpi title="Valor Saídas" value={money(outValue)} icon={<ArrowUpRight/>}/><Kpi title="Valor Entradas" value={money(-inValue)} icon={<ArrowDownLeft/>}/><Kpi title="Saldo" value={`${balance>=0?'+':''}${money(balance)}`} icon={<Scale/>}/></div>
   <div className="finance-filters" style={filterLayout}><label className="finance-search" style={searchStyle}><Search size={15}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar por número, série, cliente, fornecedor, CPF/CNPJ, chave de acesso, natureza ou CFOP…"/></label><input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(1)}}/><input type="date" value={end} onChange={e=>{setEnd(e.target.value);setPage(1)}}/><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="all">Todas</option>{invoiceTypeOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todos</option>{invoiceStatusOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
   <section className="finance-table-card"><header><div><h3>Lista de Notas Fiscais</h3><p>Registro de notas de entrada e saída · {filtered.length} registro(s)</p></div>{selected.length>0&&<button className="crm-btn danger small" onClick={()=>{updateInvoices(invoices.filter(x=>!selected.includes(x.id)));setSelected([])}}><Trash2 size={14}/>Excluir ({selected.length})</button>}</header><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th style={checkboxCellStyle}><input style={checkboxStyle} type="checkbox" aria-label="Selecionar todas as notas exibidas" checked={allVisible} onChange={e=>toggleAllVisible(e.target.checked)}/></th><th><SortHeader label="Número" column="number" sort={sort} onSort={s=>{setSort(s);setPage(1)}}/></th><th><SortHeader label="Tipo" column="type" sort={sort} onSort={s=>{setSort(s);setPage(1)}}/></th><th><SortHeader label="Cliente / Fornecedor" column="party" sort={sort} onSort={s=>{setSort(s);setPage(1)}}/></th><th><SortHeader label="Valor" column="amount" sort={sort} onSort={s=>{setSort(s);setPage(1)}}/></th><th><SortHeader label="Data Emissão" column="issueDate" sort={sort} onSort={s=>{setSort(s);setPage(1)}}/></th><th><SortHeader label="Status" column="status" sort={sort} onSort={s=>{setSort(s);setPage(1)}}/></th><th>PDF</th><th>Ações</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td style={checkboxCellStyle}><input style={checkboxStyle} type="checkbox" aria-label={`Selecionar nota ${x.number}`} checked={selected.includes(x.id)} onChange={()=>setSelected(selected.includes(x.id)?selected.filter(id=>id!==x.id):[...selected,x.id])}/></td><td><button className="finance-link" onClick={()=>setViewing(x)}><strong>{x.number}/{x.series}</strong></button></td><td>{x.type==='saida'?'Saída':'Entrada'}</td><td>{x.party}<small className="finance-cell-sub">{x.document}</small></td><td>{money(x.amount)}</td><td>{dateLabel(x.issueDate)}</td><td><span className={`finance-status ${x.status}`}>{invoiceStatusLabel(x.status)}</span></td><td>{x.pdfUrl?<button className="crm-icon-btn" onClick={()=>window.open(x.pdfUrl,'_blank')} aria-label={`Abrir PDF da nota ${x.number}`}><Download size={15}/></button>:'—'}</td><td><RowMenu onView={()=>setViewing(x)} onEdit={()=>setInvoiceModal(x)} onDelete={()=>updateInvoices(invoices.filter(item=>item.id!==x.id))}/></td></tr>)}</tbody></table></div><footer className="finance-pagination"><span>Página {Math.min(page,pages)} de {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></footer></section>
  </section>
  {invoiceModal!==undefined&&<InvoiceModal initial={invoiceModal} onClose={()=>setInvoiceModal(undefined)} onSave={value=>{const now=new Date().toISOString();const next=value.id?invoices.map(item=>item.id===value.id?{...value,updatedAt:now}:item):[{...value,id:uid('nf'),createdAt:now,updatedAt:now},...invoices];updateInvoices(next);setInvoiceModal(undefined)}}/>}
  {viewing&&<InvoiceView value={viewing} onClose={()=>setViewing(null)}/>} 
 </AdminShell>
}

function InvoiceModal({initial,onClose,onSave}:{initial:FinanceInvoice|null;onClose:()=>void;onSave:(x:FinanceInvoice)=>void}){
 const now=new Date().toISOString(),blank:FinanceInvoice={id:'',number:'',series:'001',model:'55',accessKey:'',type:'saida',operationNature:'',cfop:'',party:'',document:'',stateRegistration:'',municipalRegistration:'',email:'',phone:'',address:'',city:'',state:'',zipCode:'',issueDate:new Date().toISOString().slice(0,10),entryExitDate:'',dueDate:'',productsAmount:0,freightAmount:0,insuranceAmount:0,discountAmount:0,otherExpenses:0,amount:0,icmsBase:0,icmsAmount:0,ipiAmount:0,pisAmount:0,cofinsAmount:0,issAmount:0,paymentMethod:'',paymentCondition:'',status:'pendente',description:'',additionalInfo:'',pdfUrl:'',xmlUrl:'',createdAt:now,updatedAt:now}
 const [form,setForm]=useState<FinanceInvoice>(initial?{...blank,...initial}:blank)
 const set=(patch:Partial<FinanceInvoice>)=>setForm(current=>({...current,...patch}))
 const save=(event:FormEvent)=>{event.preventDefault();if(!form.number.trim()||!form.party.trim()||form.amount<=0)return;onSave(form)}
 return <div className="crm-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="finance-modal wide" role="dialog" aria-modal="true" aria-label={initial?'Editar Nota Fiscal':'Registrar Nota Fiscal'}><header><div><span>Financeiro</span><h2>{initial?'Editar Nota Fiscal':'Registrar Nota Fiscal'}</h2></div><button className="crm-icon-btn" type="button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><form onSubmit={save}><div className="finance-modal-body">
  <FormSection title="Identificação fiscal"><div className="finance-form-grid"><SelectField label="Tipo" value={form.type} onChange={value=>set({type:value as InvoiceType})} options={invoiceTypeOptions}/><Field label="Modelo" value={form.model??''} onChange={value=>set({model:value})}/><Field label="Número" value={form.number} onChange={value=>set({number:value})}/><Field label="Série" value={form.series} onChange={value=>set({series:value})}/><Field label="Chave de Acesso" value={form.accessKey??''} onChange={value=>set({accessKey:value})}/><SelectField label="Status" value={form.status} onChange={value=>set({status:value as InvoiceStatus})} options={invoiceStatusOptions}/></div></FormSection>
  <FormSection title="Operação"><div className="finance-form-grid"><Field label="Natureza da Operação" value={form.operationNature??''} onChange={value=>set({operationNature:value})}/><Field label="CFOP" value={form.cfop??''} onChange={value=>set({cfop:value})}/><Field label="Data de Emissão" type="date" value={form.issueDate} onChange={value=>set({issueDate:value})}/><Field label="Data de Entrada / Saída" type="date" value={form.entryExitDate??''} onChange={value=>set({entryExitDate:value})}/><Field label="Vencimento" type="date" value={form.dueDate} onChange={value=>set({dueDate:value})}/></div></FormSection>
  <FormSection title={form.type==='saida'?'Destinatário / Cliente':'Emitente / Fornecedor'}><div className="finance-form-grid"><Field label={form.type==='saida'?'Cliente':'Fornecedor'} value={form.party} onChange={value=>set({party:value})}/><Field label="CPF / CNPJ" value={form.document} onChange={value=>set({document:value})}/><Field label="Inscrição Estadual" value={form.stateRegistration??''} onChange={value=>set({stateRegistration:value})}/><Field label="Inscrição Municipal" value={form.municipalRegistration??''} onChange={value=>set({municipalRegistration:value})}/><Field label="E-mail" value={form.email??''} onChange={value=>set({email:value})}/><Field label="Telefone" value={form.phone??''} onChange={value=>set({phone:value})}/><Field label="Endereço" value={form.address??''} onChange={value=>set({address:value})}/><Field label="Cidade" value={form.city??''} onChange={value=>set({city:value})}/><Field label="UF" value={form.state??''} onChange={value=>set({state:value})}/><Field label="CEP" value={form.zipCode??''} onChange={value=>set({zipCode:value})}/></div></FormSection>
  <FormSection title="Valores da nota"><div className="finance-form-grid"><NumberField label="Produtos / Serviços" value={form.productsAmount} onChange={value=>set({productsAmount:value})}/><NumberField label="Frete" value={form.freightAmount} onChange={value=>set({freightAmount:value})}/><NumberField label="Seguro" value={form.insuranceAmount} onChange={value=>set({insuranceAmount:value})}/><NumberField label="Desconto" value={form.discountAmount} onChange={value=>set({discountAmount:value})}/><NumberField label="Outras Despesas" value={form.otherExpenses} onChange={value=>set({otherExpenses:value})}/><NumberField label="Valor Total" value={form.amount} onChange={value=>set({amount:value})}/></div></FormSection>
  <FormSection title="Tributos"><div className="finance-form-grid"><NumberField label="Base de Cálculo ICMS" value={form.icmsBase} onChange={value=>set({icmsBase:value})}/><NumberField label="ICMS" value={form.icmsAmount} onChange={value=>set({icmsAmount:value})}/><NumberField label="IPI" value={form.ipiAmount} onChange={value=>set({ipiAmount:value})}/><NumberField label="PIS" value={form.pisAmount} onChange={value=>set({pisAmount:value})}/><NumberField label="COFINS" value={form.cofinsAmount} onChange={value=>set({cofinsAmount:value})}/><NumberField label="ISS" value={form.issAmount} onChange={value=>set({issAmount:value})}/></div></FormSection>
  <FormSection title="Pagamento e documentos"><div className="finance-form-grid"><Field label="Forma de Pagamento" value={form.paymentMethod??''} onChange={value=>set({paymentMethod:value})}/><Field label="Condição de Pagamento" value={form.paymentCondition??''} onChange={value=>set({paymentCondition:value})}/><Field label="URL do PDF / DANFE" value={form.pdfUrl} onChange={value=>set({pdfUrl:value})}/><Field label="URL do XML" value={form.xmlUrl??''} onChange={value=>set({xmlUrl:value})}/></div></FormSection>
  <FormSection title="Descrição e informações complementares"><TextAreaField label="Descrição / Produtos / Serviços" value={form.description} onChange={value=>set({description:value})}/><TextAreaField label="Informações Adicionais" value={form.additionalInfo??''} onChange={value=>set({additionalInfo:value})}/></FormSection>
 </div><footer className="finance-modal-foot"><button type="button" className="crm-btn secondary" onClick={onClose}>Cancelar</button><button className="crm-btn primary" type="submit">{initial?'Salvar Alterações':'Registrar Nota'}</button></footer></form></section></div>
}

function InvoiceView({value,onClose}:{value:FinanceInvoice;onClose:()=>void}){return <div className="crm-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="finance-modal wide" role="dialog" aria-modal="true" aria-label="Visualizar nota fiscal"><header><div><span>Financeiro · Visualização</span><h2>Nota {value.number}/{value.series}</h2></div><button className="crm-icon-btn" type="button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><div className="finance-modal-body">
 <FormSection title="Identificação fiscal"><InfoGrid items={[["Tipo",value.type==='saida'?'Saída':'Entrada'],['Modelo',value.model??'—'],['Número',value.number],['Série',value.series],['Chave de Acesso',value.accessKey??'—'],['Status',invoiceStatusLabel(value.status)]]}/></FormSection>
 <FormSection title="Operação"><InfoGrid items={[["Natureza da Operação",value.operationNature??'—'],['CFOP',value.cfop??'—'],['Data de Emissão',dateLabel(value.issueDate)],['Data de Entrada / Saída',dateLabel(value.entryExitDate??'')],['Vencimento',dateLabel(value.dueDate)]]}/></FormSection>
 <FormSection title={value.type==='saida'?'Destinatário / Cliente':'Emitente / Fornecedor'}><InfoGrid items={[[value.type==='saida'?'Cliente':'Fornecedor',value.party],['CPF / CNPJ',value.document],['Inscrição Estadual',value.stateRegistration??'—'],['Inscrição Municipal',value.municipalRegistration??'—'],['E-mail',value.email??'—'],['Telefone',value.phone??'—'],['Endereço',value.address??'—'],['Cidade',value.city??'—'],['UF',value.state??'—'],['CEP',value.zipCode??'—']]}/></FormSection>
 <FormSection title="Valores da nota"><InfoGrid items={[["Produtos / Serviços",money(value.productsAmount??0)],['Frete',money(value.freightAmount??0)],['Seguro',money(value.insuranceAmount??0)],['Desconto',money(value.discountAmount??0)],['Outras Despesas',money(value.otherExpenses??0)],['Valor Total',money(value.amount)]]}/></FormSection>
 <FormSection title="Tributos"><InfoGrid items={[["Base de Cálculo ICMS",money(value.icmsBase??0)],['ICMS',money(value.icmsAmount??0)],['IPI',money(value.ipiAmount??0)],['PIS',money(value.pisAmount??0)],['COFINS',money(value.cofinsAmount??0)],['ISS',money(value.issAmount??0)]]}/></FormSection>
 <FormSection title="Pagamento e documentos"><InfoGrid items={[["Forma de Pagamento",value.paymentMethod??'—'],['Condição de Pagamento',value.paymentCondition??'—']]}/><div className="finance-view-grid"><DocumentLink label="PDF / DANFE" url={value.pdfUrl}/><DocumentLink label="XML" url={value.xmlUrl??''}/></div></FormSection>
 <FormSection title="Descrição / Produtos / Serviços"><p className="finance-view-notes">{value.description||'—'}</p></FormSection><FormSection title="Informações adicionais"><p className="finance-view-notes">{value.additionalInfo||'—'}</p></FormSection>
 <FormSection title="Auditoria / Metadados"><InfoGrid items={[["Criado em",new Date(value.createdAt).toLocaleString('pt-BR')],['Atualizado em',new Date(value.updatedAt).toLocaleString('pt-BR')],['ID',value.id]]}/></FormSection>
 </div><footer className="finance-modal-foot"><button className="crm-btn secondary" onClick={onClose}>Fechar</button></footer></section></div>}

function SortHeader({label,column,sort,onSort}:{label:string;column:InvoiceSortKey;sort:SortState;onSort:(state:NonNullable<SortState>)=>void}){const direction=sort?.key===column?sort.direction:null;const buttonStyle=(active:boolean)=>({width:14,height:20,padding:0,border:'none',background:'transparent',color:active?'#111':'#aaa',fontSize:13,fontWeight:active?900:700,lineHeight:1,cursor:'pointer',opacity:active?1:.55} as const);return <div className="crm-sort-header"><span>{label}</span><div role="group" aria-label={`Ordenar ${label}`} style={{display:'inline-flex',alignItems:'center',gap:0}}><button type="button" style={buttonStyle(direction==='asc')} aria-label={`${label}: ordem crescente`} aria-pressed={direction==='asc'} onClick={()=>onSort({key:column,direction:'asc'})}>↑</button><button type="button" style={buttonStyle(direction==='desc')} aria-label={`${label}: ordem decrescente`} aria-pressed={direction==='desc'} onClick={()=>onSort({key:column,direction:'desc'})}>↓</button></div></div>}
function RowMenu({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);return <div className="crm-row-actions"><button className="crm-icon-btn" onClick={()=>setOpen(v=>!v)} aria-label="Ações"><MoreHorizontal size={16}/></button>{open&&<div className="crm-row-menu"><button onClick={()=>{setOpen(false);onView()}}>Visualizar</button><button onClick={()=>{setOpen(false);onEdit()}}>Editar</button><button className="danger" onClick={()=>{setOpen(false);onDelete()}}>Excluir</button></div>}</div>}
function FormSection({title,children}:{title:string;children:ReactNode}){return <section className="finance-form-section"><h3>{title}</h3>{children}</section>}
function InfoGrid({items}:{items:[string,string][]}){return <div className="finance-view-grid">{items.map(([label,value])=><Info key={label} label={label} value={value}/>)}</div>}
function Info({label,value}:{label:string;value:string}){return <div className="finance-info"><span>{label}</span><strong>{value||'—'}</strong></div>}
function DocumentLink({label,url}:{label:string;url:string}){return <div className="finance-info"><span>{label}</span><strong>{url?<a href={url} target="_blank" rel="noopener noreferrer">Abrir documento</a>:'—'}</strong></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="finance-field"><span>{label}</span><input type={type} value={value} onChange={event=>onChange(event.target.value)}/></label>}
function NumberField({label,value,onChange}:{label:string;value:number|undefined;onChange:(value:number)=>void}){return <label className="finance-field"><span>{label}</span><input type="number" min="0" step="0.01" value={value??''} onChange={event=>onChange(Number(event.target.value))}/></label>}
function TextAreaField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="finance-field wide"><span>{label}</span><textarea rows={4} value={value} onChange={event=>onChange(event.target.value)}/></label>}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:readonly (readonly [string,string])[]}){return <label className="finance-field"><span>{label}</span><select value={value} onChange={event=>onChange(event.target.value)}>{options.map(([key,labelText])=><option key={key} value={key}>{labelText}</option>)}</select></label>}
function Kpi({title,value,icon}:{title:string;value:string;icon:ReactNode}){return <article className="finance-kpi"><div><span>{title}</span><strong>{value}</strong></div><i>{icon}</i></article>}
const invoiceStatusLabel=(status:InvoiceStatus)=>invoiceStatusOptions.find(([key])=>key===status)?.[1]??status
