import {Plus,Trash2} from 'lucide-react'
import {useState} from 'react'
import type {ContractCategory} from '../domain'

export function CategoriesPanel({categories,onSave,onDelete}:{categories:ContractCategory[];onSave:(value:Omit<ContractCategory,'id'|'createdAt'|'updatedAt'> & {id?:string})=>Promise<unknown>;onDelete:(id:string)=>Promise<unknown>}){
 const [editing,setEditing]=useState<ContractCategory|undefined>(),[name,setName]=useState(''),[description,setDescription]=useState(''),[order,setOrder]=useState(categories.length+1),[active,setActive]=useState(true),[error,setError]=useState('')
 const reset=()=>{setEditing(undefined);setName('');setDescription('');setOrder(categories.length+1);setActive(true);setError('')}
 const submit=async()=>{if(!name.trim()){setError('Informe o nome da categoria.');return}if(!Number.isFinite(order)||order<1){setError('Informe uma ordem válida.');return}await onSave({id:editing?.id,name:name.trim(),description:description.trim(),active,order});reset()}
 const startEdit=(category:ContractCategory)=>{setEditing(category);setName(category.name);setDescription(category.description);setOrder(category.order);setActive(category.active);setError('')}
 return <section className="contracts-registry"><header><div><h2>Categorias</h2><p>Classificação administrável dos contratos e templates.</p></div></header><div className="contracts-inline-editor contracts-category-editor">{error&&<div className="crm-error">{error}</div>}<label>Nome<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Descrição<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Ordem<input type="number" min="1" value={order} onChange={e=>setOrder(Math.max(1,Number(e.target.value)||1))}/></label><label className="contracts-check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Ativa</label><button className="crm-btn primary" onClick={submit}><Plus size={14}/>{editing?'Salvar':'Adicionar'}</button>{editing&&<button className="crm-btn secondary" onClick={reset}>Cancelar</button>}</div>{categories.length===0?<div className="contracts-empty"><strong>Nenhuma categoria cadastrada.</strong></div>:<div className="contracts-registry-table"><div className="contracts-registry-row head"><span>Nome</span><span>Descrição</span><span>Ordem</span><span>Status</span><span>Ações</span></div>{[...categories].sort((a,b)=>a.order-b.order).map(c=><div className="contracts-registry-row" key={c.id}><strong>{c.name}</strong><span>{c.description||'—'}</span><span>{c.order}</span><button className={`contracts-toggle ${c.active?'active':''}`} onClick={()=>void onSave({...c,id:c.id,active:!c.active})}>{c.active?'Ativa':'Inativa'}</button><div><button className="crm-btn secondary small" onClick={()=>startEdit(c)}>Editar</button><button className="crm-icon-btn" onClick={()=>confirm(`Excluir a categoria ${c.name}?`)&&void onDelete(c.id)} aria-label={`Excluir ${c.name}`}><Trash2 size={14}/></button></div></div>)}</div>}</section>
}
