import {useEffect,useState} from 'react'
import {FileUp,X} from 'lucide-react'
import {integrationProviderClient} from '../../settings/integrationProviderClient'
import type {Contract} from '../domain'

type SentResult={externalId:string;provider:'autentique'}

export function SendForSigningDialog({contract,onClose,onSent}:{contract:Contract;onClose:()=>void;onSent?:(result:SentResult)=>Promise<void>|void}){
 const orderedSigners=[...contract.signers].sort((a,b)=>a.order-b.order)
 const [configured,setConfigured]=useState(false),[loadingState,setLoadingState]=useState(true),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 useEffect(()=>{let active=true;void integrationProviderClient.runtime().then(result=>{if(active)setConfigured(Boolean(result.providers.autentique?.configured))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Não foi possível consultar o estado do Autentique.')}).finally(()=>{if(active)setLoadingState(false)});return()=>{active=false}},[])
 const invalidSigners=orderedSigners.filter(s=>!s.email.trim())
 const send=async()=>{if(!configured||!file||busy||invalidSigners.length)return;setBusy(true);setError('');setSuccess('');try{const result=await integrationProviderClient.createAutentiqueDocument({name:contract.title||contract.document.title,signers:orderedSigners.map(s=>({name:s.name,email:s.email,order:s.order})),file});await onSent?.({externalId:result.externalId,provider:'autentique'});setSuccess(`Documento enviado ao Autentique. ID externo: ${result.externalId}`)}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao enviar o documento ao Autentique.')}finally{setBusy(false)}}
 return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target&&!busy)onClose()}}><section className="crm-modal contracts-signing-dialog" role="dialog" aria-modal="true" aria-label="Enviar para assinatura"><header className="crm-modal-head"><div><h2>Enviar para assinatura</h2><p>O envio só é confirmado depois que o Autentique retornar um identificador real do documento.</p></div><button className="crm-icon-btn" onClick={onClose} aria-label="Fechar" disabled={busy}><X size={18}/></button></header><div className="crm-modal-body contracts-signing-body"><section><h3>Documento</h3><strong>{contract.title}</strong><span>{contract.signers.length} signatário(s) configurado(s)</span></section><section><h3>Provider</h3><div className="contracts-provider"><strong>Autentique</strong><span>{loadingState?'Verificando backend...':configured?'Backend configurado':'Credenciais não configuradas'}</span></div></section><section><h3>PDF final</h3><label className="contracts-provider"><span><FileUp size={16}/>Selecionar PDF para assinatura</span><input type="file" accept="application/pdf,.pdf" onChange={event=>{setFile(event.target.files?.[0]??null);setError('');setSuccess('')}}/></label>{file&&<small>{file.name} · {Math.max(1,Math.ceil(file.size/1024))} KB</small>}</section><section><h3>Ordem de assinatura</h3>{orderedSigners.length===0?<div className="crm-empty-mini">Nenhum signatário configurado.</div>:orderedSigners.map(s=><div className="contracts-signer-line" key={s.id}><span>{s.order}</span><strong>{s.name}</strong><small>{s.email||'E-mail ausente'}</small></div>)}</section>{invalidSigners.length>0&&<div className="crm-error">Todos os signatários precisam possuir e-mail antes do envio.</div>}{!loadingState&&!configured&&<div className="crm-error">Configure AUTENTIQUE_API_TOKEN no backend antes de enviar contratos.</div>}{error&&<div className="crm-error">{error}</div>}{success&&<div className="crm-success">{success}</div>}</div><footer className="crm-modal-foot"><button className="crm-btn secondary" onClick={onClose} disabled={busy}>Fechar</button><button className="crm-btn primary" disabled={busy||loadingState||!configured||!file||orderedSigners.length===0||invalidSigners.length>0||Boolean(success)} onClick={()=>void send()}>{busy?'Enviando...':'Enviar ao Autentique'}</button></footer></section></div>
}
