import {Plus,Trash2} from 'lucide-react'
import {useMemo,useState} from 'react'
import type {ContractVariable,VariableGroup} from '../domain'

const groups:VariableGroup[]=['CONTRATANTE','CONTRATADA','CONTRACT','PAYMENT','SERVICE','CAMPAIGN','EVENT','CONTENT','SIGNATURE','GENERAL']
const variableTypes:ContractVariable['type'][]=['text','number','date','currency','email']

export function VariablesPanel({variables,onSave,onDelete}:{variables:ContractVariable[];onSave:(value:Omit<ContractVariable,'id'|'createdAt'|'updatedAt'> & {id?:string})=>Promise<unknown>;onDelete:(id:string)=>Promise<unknown>}){
 const [editing,setEditing]=useState<ContractVariable|undefined>(),[group,setGroup]=useState<VariableGroup>('GENERAL'),[name,setName]=useState(''),[field,setField]=useState(''),[description,setDescription]=useState(''),[type,setType]=useState<ContractVariable['type']>('text'),[defaultValue,setDefaultValue]=useState(''),[filter,setFilter]=useState('all'),[required,setRequired]=useState(false),[active,setActive]=useState(true),[error,setError]=useState('')
 const visible=useMemo(()=>variables.filter(v=>filter==='all'||v.group===filter),[variables,filter])
 const reset=()=>{setEditing(undefined);setGroup('GENERAL');setName('');setField('');setDescription('');setType('text');setDefaultValue('');setRequired(false);setActive(true);setError('')}
 const startEdit=(variable:ContractVariable)=>{setEditing(variable);setGroup(variable.group);setName(variable.name);setField(variable.key.replace(/^\{\{[A-Z][A-Z0-9_]*\./,'').replace(/\}\}$/,''));setDescription(variable.description);setType(variable.type);setDefaultValue(variable.defaultValue);setRequired(variable.required);setActive(variable.active);setError('')}
 const submit=async()=>{const normalized=field.trim().toUpperCase().replace(/[^A-Z0-9_]+/g,'_').replace(/^_+|_+$/g,'');if(!name.trim()||!normalized){setError('Informe nome e campo.');return}const key=`{{${group}.${normalized}}}`;const duplicate=variables.find(v=>v.key===key&&v.id!==editing?.id);if(duplicate){setError('Já existe uma variável com esta key.');return}await onSave({id:editing?.id,name:name.trim(),key,group,description:description.trim(),type,required,defaultValue,active});reset()}
 return <section className="contracts-registry"><header><div><h2>Variáveis</h2><p>Registry de placeholders disponíveis para templates e documentos.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os grupos</option>{groups.map(g=><option key={g}>{g}</option>)}</select></header><div className="contracts-variable-editor contracts-variable-editor-full">{error&&<div className="crm-error">{error}</div>}<label>Grupo<select value={group} onChange={e=>setGroup(e.target.value as VariableGroup)}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex: Nome da campanha"/></label><label>Campo<input value={field} onChange={e=>setField(e.target.value)} placeholder="Ex: NAME"/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value as ContractVariable['type'])}>{variableTypes.map(item=><option key={item} value={item}>{item}</option>)}</select></label><label className="contracts-variable-description">Descrição<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Valor default<input value={defaultValue} onChange={e=>setDefaultValue(e.target.value)}/></label><label className="contracts-check"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>Obrigatória</label><label className="contracts-check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Ativa</label><button className="crm-btn primary" onClick={submit}><Plus size={14}/>{editing?'Salvar':'Adicionar'}</button>{editing&&<button className="crm-btn secondary" onClick={reset}>Cancelar</button>}</div>{visible.length===0?<div className="contracts-empty"><strong>Nenhuma variável cadastrada.</strong></div>:<div className="contracts-variable-groups">{groups.filter(g=>filter==='all'||g===filter).map(g=>{const list=visible.filter(v=>v.group===g);if(!list.length)return null;return <section key={g}><h3>{g}</h3>{list.map(v=><div className="contracts-variable-row contracts-variable-row-full" key={v.id}><div><strong>{v.name}</strong><code>{v.key}</code><small>{v.description||'Sem descrição'} · {v.type}{v.defaultValue?` · default: ${v.defaultValue}`:''}</small></div><span>{v.required?'Obrigatória':'Opcional'}</span><button className={`contracts-toggle ${v.active?'active':''}`} onClick={()=>void onSave({...v,id:v.id,active:!v.active})}>{v.active?'Ativa':'Inativa'}</button><div className="contracts-variable-actions"><button className="crm-btn secondary small" onClick={()=>startEdit(v)}>Editar</button><button className="crm-icon-btn" onClick={()=>confirm(`Excluir ${v.name}?`)&&void onDelete(v.id)} aria-label={`Excluir ${v.name}`}><Trash2 size={14}/></button></div></div>)}</section>})}</div>}</section>
}
