import { AlertTriangle, FileText, Globe2, Search } from 'lucide-react'
import { editorialReadModel } from '../repository'

function PersistenceNotice(){return <div className="admin-notice"><AlertTriangle size={18}/><div><strong>Persistência editorial ainda indisponível</strong><p>Este frontend não possui backend, banco ou API editorial. Criação, edição, publicação e exclusão permanecem bloqueadas para não simular sucesso com localStorage ou memória.</p></div></div>}
function AdminHeader({title,description,action}:{title:string,description:string,action:string}){return <div className="admin-page-header"><div className="admin-page-header-copy"><span className="admin-breadcrumb">Gerenciador do Site / {title}</span><h1>{title}</h1><p>{description}</p></div><div className="admin-header-actions"><button className="button dark" disabled title="Requer backend editorial">{action}</button></div></div>}
function Toolbar({placeholder,count}:{placeholder:string,count:number}){return <div className="admin-toolbar"><div className="admin-toolbar-group"><div className="searchbox"><Search size={17}/><input placeholder={placeholder}/></div><button className="admin-filter" type="button">Todos os status</button></div><span className="admin-breadcrumb">{count} registros</span></div>}

export function EditorialPagesAdmin(){
  const pages=editorialReadModel.pages
  return <><AdminHeader title="Páginas" description="Estrutura editorial, navegação, publicação e relacionamento entre páginas do portal." action="Nova página"/><PersistenceNotice/><Toolbar placeholder="Buscar por título ou slug..." count={pages.length}/><section className="table-card"><table><thead><tr><th>Página</th><th>Tipo</th><th>Slug</th><th>Status</th><th>Menu</th><th>Posição</th><th>Parent</th><th>Conteúdos</th><th>Atualização</th></tr></thead><tbody>{pages.map(page=><tr key={page.id}><td><div className="table-primary"><span className="table-avatar"><Globe2 size={15}/></span><div><b>{page.title}</b><small>{page.navigationLabel}</small></div></div></td><td>{page.type}</td><td>/{page.slug}</td><td><span className={`status ${page.status}`}>{page.status}</span></td><td>{page.showInMainMenu?'Visível':'Oculta'}</td><td>{page.menuOrder}</td><td>{page.parentId?editorialReadModel.getPageById(page.parentId)?.title||page.parentId:'—'}</td><td>{editorialReadModel.countContents(page.id)}</td><td>{new Date(page.updatedAt).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></section></>
}

export function EditorialContentsAdmin(){
  const contents=editorialReadModel.contents
  return <><AdminHeader title="Conteúdos" description="Gerencie todos os conteúdos editoriais por uma única estrutura, independentemente da página ou categoria." action="Novo conteúdo"/><PersistenceNotice/><Toolbar placeholder="Buscar conteúdo, autor ou slug..." count={contents.length}/><section className="table-card"><table><thead><tr><th>Conteúdo</th><th>Página</th><th>Slug</th><th>Status</th><th>Autor</th><th>Atualização</th></tr></thead><tbody>{contents.map(content=><tr key={content.id}><td><div className="table-primary"><span className="table-avatar"><FileText size={15}/></span><div><b>{content.title}</b><small>{content.summary}</small></div></div></td><td>{editorialReadModel.getPageById(content.pageId)?.title||content.pageId}</td><td>{content.slug}</td><td><span className={`status ${content.status}`}>{content.status}</span></td><td>{content.author}</td><td>{new Date(content.updatedAt).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></section></>
}
