import {ArrowDownLeft,ArrowLeftRight,ArrowUpRight,Download,FileText,MoreHorizontal,Plus,Scale,Search,X} from 'lucide-react'
import {useMemo,useState,type FormEvent,type ReactNode} from 'react'
import {useNavigate} from 'react-router-dom'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {money,uid,type FinanceInvoice,type InvoiceStatus,type InvoiceType} from './domain'
import InvoiceRegisterModal from './InvoiceRegisterModal'
import {financeInvoicesMock} from './mocks'

const STORAGE='portal-lander:finance:invoices'
const readInvoices=():FinanceInvoice[]=>{try{const raw=localStorage.getItem(STORAGE);return raw?JSON.parse(raw) as FinanceInvoice[]:structuredClone(financeInvoicesMock)}catch{return structuredClone(financeInvoicesMock)}}
const writeInvoices=(items:FinanceInvoice[])=>localStorage.setItem(STORAGE,JSON.stringify(items))
const dateLabel=(value:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const statusLabel=(value:InvoiceStatus)=>value[0].toUpperCase()+value.slice(1)

export default function FinanceInvoicesPage(){
 const navigate=useNavigate()
 const [invoices,setInvoices]=useState(readInvoices),[search,setSearch]=useState(''),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[page,setPage]=useState(1),[viewing,setViewing]=useState<FinanceInvoice|null>(null),[editing,setEditing]=useState<FinanceInvoice|null>(null),[creating,setCreating]=useState(false)
 const update=(next:FinanceInvoice[])=>{setInvoices(next);writeInvoices(next)}
 const filtered=useMemo(()=>invoices.filter(x=>(!search||[x.number,x.party,x.document].some(v=>v.toLowerCase().includes(search.toLowerCase())))&&(type==='all'||x.type===type)&&(status==='all'||x.status===status)&&(!start||x.issueDate>=start)&&(!end||x.issueDate<=end)),[invoices,search,type,status,start,end])
 const pages=Math.max(1,Math.ceil(filtered.length/10)),items=filtered.slice((Math.min(page,pages)-1)*10,Math.min(page,pages)*10)
 const outputs=invoices.filter(x=>x.type==='saida'),inputs=invoices.filter(x=>x.type==='entrada'),outValue=outputs.reduce((s,x)=>s+x.amount,0),inValue=inputs.reduce((s,x)=>s+x.amount,0),balance=outValue-inValue
 return <AdminShell area="finance" items={CRM_WORKSPACE_NAV} header={{title:'Notas Fiscais',description:'Registro e controle de notas fiscais de entrada e saída'}} headerActions={[{label:'Financeiro',variant:'secondary',icon:ArrowLeftRight,className:'finance-header-action',onClick:()=>navigate('/app/finance')},{label:'Registrar Nota',icon:Plus,className:'finance-header-action',onClick:()=>setCreating(true)}]}>
  <section className="finance-page">
   <div className="finance-kpis finance-invoice-six">
    <Kpi title="Total" value={String(invoices.length)} icon={<FileText/>}/><Kpi title="Saídas" value={String(outputs.length)} icon={<ArrowUpRight/>}/><Kpi title="Entradas" value={String(inputs.length)} icon={<ArrowDownLeft/>}/><Kpi title="Valor Saídas" value={money(outValue)} icon={<ArrowUpRight/>}/><Kpi title="Valor Entradas" value={money(-inValue)} icon={<ArrowDownLeft/>}/><Kpi title="Saldo" value={`${balance>=0?'+':''}${money(balance)}`} icon={<Scale/>}/>
   </div>
   <div className="finance-filters"><input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(1)}}/><input type="date" value={end} onChange={e=>{setEnd(e.target.value);setPage(1)}}/><label className="finance-search"><Search size={15}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar por número, cliente ou fornecedor…"/></label><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="all">Todas</option><option value="saida">Saída</option><option value="entrada">Entrada</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todos</option><option value="emitida">Emitida</option><option value="pendente">Pendente</option><option value="paga">Paga</option><option value="cancelada">Cancelada</option></select></div>
   <section className="finance-table-card"><header><div><h3>Lista de Notas Fiscais</h3><p>Registro de notas de entrada e saída · {filtered.length} registro(s)</p></div></header><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th></th><th>Número</th><th>Tipo</th><th>Cliente / Fornecedor</th><th>Valor</th><th>Data Emissão</th><th>Status</th><th>PDF</th><th>Ações</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><input type="checkbox"/></td><td><strong>{x.number}/{x.series}</strong></td><td>{x.type==='saida'?'Saída':'Entrada'}</td><td>{x.party}<small className="finance-cell-sub">{x.document}</small></td><td>{money(x.amount)}</td><td>{dateLabel(x.issueDate)}</td><td><span className={`finance-status ${x.status}`}>{statusLabel(x.status)}</span></td><td>{x.pdfUrl?<button className="crm-icon-btn" onClick={()=>window.open(x.pdfUrl,'_blank')} aria-label={`Abrir PDF da nota ${x.number}`}><Download size={15}/></button>:'—'}</td><td><RowMenu onView={()=>setViewing(x)} onEdit={()=>setEditing(x)} onDelete={()=>{if(confirm(`Excluir a nota ${x.number}/${x.series}?`))update(invoices.filter(item=>item.id!==x.id))}}/></td></tr>)}</tbody></table></div><footer className="finance-pagination"><span>Página {Math.min(page,pages)} de {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></footer></section>
  </section>
  {creating&&<InvoiceRegisterModal onClose={()=>setCreating(false)} onSave={value=>{const stamp=new Date().toISOString();update([{...value,id:uid('nf'),createdAt:stamp,updatedAt:stamp},...invoices]);setCreating(false)}}/>}
  {viewing&&<InvoiceView invoice={viewing} onClose={()=>setViewing(null)} onEdit={()=>{setEditing(viewing);setViewing(null)}}/>}
  {editing&&<InvoiceEditModal invoice={editing} onClose={()=>setEditing(null)} onSave={value=>{update(invoices.map(item=>item.id===value.id?value:item));setEditing(null)}}/>}
 </AdminShell>
}

function RowMenu({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);return <div className="crm-row-actions"><button type="button" className="crm-icon-btn" onClick={()=>setOpen(value=>!value)} aria-label="Ações" aria-expanded={open}><MoreHorizontal size={16}/></button>{open&&<div className="crm-row-menu"><button type="button" onClick={()=>{setOpen(false);onView()}}>Ver</button><button type="button" onClick={()=>{setOpen(false);onEdit()}}>Editar</button><button type="button" className="danger" onClick={()=>{setOpen(false);onDelete()}}>Excluir</button></div>}</div>}

function InvoiceView({invoice,onClose,onEdit}:{invoice:FinanceInvoice;onClose:()=>void;onEdit:()=>void}){return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="finance-modal" role="dialog" aria-modal="true" aria-label={`Nota fiscal ${invoice.number}`}><header><div><span>Nota Fiscal</span><h2>{invoice.number}/{invoice.series}</h2></div><button type="button" className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><div className="finance-modal-body"><div className="finance-form-grid"><ViewField label="Tipo" value={invoice.type==='saida'?'Saída':'Entrada'}/><ViewField label="Cliente / Fornecedor" value={invoice.party}/><ViewField label="Documento" value={invoice.document}/><ViewField label="Valor" value={money(invoice.amount)}/><ViewField label="Data de emissão" value={dateLabel(invoice.issueDate)}/><ViewField label="Vencimento" value={dateLabel(invoice.dueDate)}/><ViewField label="Status" value={statusLabel(invoice.status)}/><ViewField label="Descrição" value={invoice.description||'—'}/></div>{invoice.pdfUrl&&<button type="button" className="crm-btn secondary" onClick={()=>window.open(invoice.pdfUrl,'_blank')}><Download size={14}/>Abrir PDF</button>}</div><footer className="finance-modal-foot"><button type="button" className="crm-btn secondary" onClick={onClose}>Fechar</button><button type="button" className="crm-btn primary" onClick={onEdit}>Editar</button></footer></section></div>}

function InvoiceEditModal({invoice,onClose,onSave}:{invoice:FinanceInvoice;onClose:()=>void;onSave:(value:FinanceInvoice)=>void}){const [form,setForm]=useState({...invoice});const submit=(event:FormEvent)=>{event.preventDefault();if(!form.number.trim()||!form.party.trim()||form.amount<=0)return;onSave({...form,updatedAt:new Date().toISOString()})};return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="finance-modal wide" role="dialog" aria-modal="true" aria-label={`Editar nota fiscal ${invoice.number}`}><header><div><span>Nota Fiscal</span><h2>Editar Nota Fiscal</h2></div><button type="button" className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><form onSubmit={submit}><div className="finance-modal-body"><div className="finance-form-grid"><Field label="Número" value={form.number} onChange={value=>setForm(current=>({...current,number:value}))}/><Field label="Série" value={form.series} onChange={value=>setForm(current=>({...current,series:value}))}/><SelectField label="Tipo" value={form.type} options={[['saida','Saída'],['entrada','Entrada']]} onChange={value=>setForm(current=>({...current,type:value as InvoiceType}))}/><Field label="Cliente / Fornecedor" value={form.party} onChange={value=>setForm(current=>({...current,party:value}))}/><Field label="Documento" value={form.document} onChange={value=>setForm(current=>({...current,document:value}))}/><Field label="Valor" type="number" value={String(form.amount||'')} onChange={value=>setForm(current=>({...current,amount:Number(value)}))}/><Field label="Data de emissão" type="date" value={form.issueDate} onChange={value=>setForm(current=>({...current,issueDate:value}))}/><Field label="Vencimento" type="date" value={form.dueDate} onChange={value=>setForm(current=>({...current,dueDate:value}))}/><SelectField label="Status" value={form.status} options={[['emitida','Emitida'],['pendente','Pendente'],['paga','Paga'],['cancelada','Cancelada']]} onChange={value=>setForm(current=>({...current,status:value as InvoiceStatus}))}/><Field label="PDF / URL" value={form.pdfUrl} onChange={value=>setForm(current=>({...current,pdfUrl:value}))}/></div><label className="finance-field wide"><span>Descrição</span><textarea rows={4} value={form.description} onChange={e=>setForm(current=>({...current,description:e.target.value}))}/></label></div><footer className="finance-modal-foot"><button type="button" className="crm-btn secondary" onClick={onClose}>Cancelar</button><button type="submit" className="crm-btn primary">Salvar Alterações</button></footer></form></section></div>}

function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="finance-field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:readonly (readonly [string,string])[];onChange:(value:string)=>void}){return <label className="finance-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([option,labelText])=><option key={option} value={option}>{labelText}</option>)}</select></label>}
function ViewField({label,value}:{label:string;value:string}){return <div className="finance-field"><span>{label}</span><strong>{value}</strong></div>}
function Kpi({title,value,icon}:{title:string;value:string;icon:ReactNode}){return <article className="finance-kpi"><div><span>{title}</span><strong>{value}</strong></div><i>{icon}</i></article>}
