import {FileText,MoreHorizontal,Plus,Search,Tags,Trash2,TrendingDown,TrendingUp,Upload,X,DollarSign} from 'lucide-react'
import {useMemo,useRef,useState,type ChangeEvent,type FormEvent,type ReactNode} from 'react'
import {useNavigate} from 'react-router-dom'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {financeCategories,money,uid,type FinancePaymentType,type FinanceStatus,type FinanceTransaction,type FinanceTransactionType} from './domain'
import {financeTransactionsMock} from './mocks'

const STORAGE='portal-lander:finance:transactions'
const read=():FinanceTransaction[]=>{try{const raw=localStorage.getItem(STORAGE);return raw?JSON.parse(raw) as FinanceTransaction[]:structuredClone(financeTransactionsMock)}catch{return structuredClone(financeTransactionsMock)}}
const write=(items:FinanceTransaction[])=>localStorage.setItem(STORAGE,JSON.stringify(items))
const dateLabel=(value:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—'

export default function FinanceMainPage(){
 const navigate=useNavigate(),ofxRef=useRef<HTMLInputElement>(null)
 const [transactions,setTransactions]=useState(read),[editing,setEditing]=useState<FinanceTransaction|null|undefined>(undefined),[viewing,setViewing]=useState<FinanceTransaction|null>(null)
 const [search,setSearch]=useState(''),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[category,setCategory]=useState('all'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<string[]>([])
 const update=(next:FinanceTransaction[])=>{setTransactions(next);write(next)}
 const filtered=useMemo(()=>transactions.filter(x=>(!search||[x.description,x.counterparty,x.document,x.category].some(v=>v.toLowerCase().includes(search.toLowerCase())))&&(type==='all'||x.type===type)&&(status==='all'||x.status===status)&&(category==='all'||x.category===category)&&(!start||x.date>=start)&&(!end||x.date<=end)),[transactions,search,type,status,category,start,end])
 const pages=Math.max(1,Math.ceil(filtered.length/10)),items=filtered.slice((Math.min(page,pages)-1)*10,Math.min(page,pages)*10)
 const receipts=transactions.filter(x=>x.type==='receita'&&x.status==='pago').reduce((s,x)=>s+x.amount,0),expenses=transactions.filter(x=>x.type==='despesa'&&x.status==='pago').reduce((s,x)=>s+x.amount,0),receivable=transactions.filter(x=>x.type==='receita'&&x.status==='pendente').reduce((s,x)=>s+x.amount,0),payable=transactions.filter(x=>x.type==='despesa'&&x.status==='pendente').reduce((s,x)=>s+x.amount,0),profit=receipts-expenses
 const filtersActive=[search,type!=='all',status!=='all',category!=='all',start,end].filter(Boolean).length
 return <AdminShell area="finance" items={CRM_WORKSPACE_NAV} header={{title:'Financeiro',description:'Controle financeiro e fluxo de caixa'}} headerActions={[{label:'Importar OFX',variant:'secondary',icon:Upload,className:'finance-header-action',onClick:()=>ofxRef.current?.click()},{label:'Regras',variant:'secondary',icon:FileText,className:'finance-header-action',onClick:()=>navigate('/app/finance/rules')},{label:'Categorias Financeiras',variant:'secondary',icon:Tags,className:'finance-header-action',onClick:()=>navigate('/app/finance/categories')},{label:'Nova Transação',icon:Plus,className:'finance-header-action',onClick:()=>setEditing(null)}]}>
  <input ref={ofxRef} hidden type="file" accept=".ofx" onChange={e=>{if(e.target.files?.[0])alert(`Arquivo ${e.target.files[0].name} selecionado para conciliação.`);e.currentTarget.value=''}}/>
  <section className="finance-page">
   <div className="finance-kpis"><Kpi title="Receita Mensal" value={money(receipts)} detail="receitas pagas" icon={<TrendingUp/>}/><Kpi title="Despesas Mensais" value={money(-expenses)} detail="despesas pagas" icon={<TrendingDown/>}/><Kpi title="Lucro Líquido" value={money(profit)} detail={receipts?`margem ${Math.round(profit/receipts*100)}%`:'margem 0%'} icon={<DollarSign/>}/><Kpi title="Contas a Receber" value={money(receivable)} detail={`${transactions.filter(x=>x.type==='receita'&&x.status==='pendente').length} pendentes`} icon={<TrendingUp/>}/><Kpi title="Contas a Pagar" value={money(-payable)} detail={`${transactions.filter(x=>x.type==='despesa'&&x.status==='pendente').length} pendentes`} icon={<FileText/>}/></div>
   <div className="finance-filters"><input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(1)}}/><input type="date" value={end} onChange={e=>{setEnd(e.target.value);setPage(1)}}/><label className="finance-search"><Search size={15}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar transações…"/></label><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="all">Todos os tipos</option><option value="receita">Receita</option><option value="despesa">Despesa</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Todos os status</option><option value="pago">Pago</option><option value="pendente">Pendente</option><option value="vencido">Vencido</option><option value="cancelado">Cancelado</option></select><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="all">Todas as categorias</option>{Array.from(new Set(financeCategories.map(x=>x.category))).map(x=><option key={x}>{x}</option>)}</select>{filtersActive>0&&<button className="crm-btn secondary" onClick={()=>{setSearch('');setType('all');setStatus('all');setCategory('all');setStart('');setEnd('');setPage(1)}}>Limpar ({filtersActive})</button>}</div>
   <section className="finance-table-card"><header><div><h3>Transações</h3><p>Fluxo de receitas e despesas · {filtered.length} registro(s)</p></div>{selected.length>0&&<button className="crm-btn danger small" onClick={()=>{update(transactions.filter(x=>!selected.includes(x.id)));setSelected([])}}><Trash2 size={14}/>Excluir ({selected.length})</button>}</header><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th><input type="checkbox" checked={items.length>0&&items.every(x=>selected.includes(x.id))} onChange={e=>setSelected(e.target.checked?items.map(x=>x.id):[])}/></th><th>Tipo</th><th>Descrição</th><th>Categoria</th><th>Status</th><th>Data</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>setSelected(selected.includes(x.id)?selected.filter(id=>id!==x.id):[...selected,x.id])}/></td><td><span className={`finance-type ${x.type}`}>{x.type==='receita'?'Receita':'Despesa'}</span></td><td><button className="finance-link" onClick={()=>setViewing(x)}><strong>{x.description}</strong><small>{x.counterparty||'Sem contraparte'}</small></button></td><td>{x.category}<small className="finance-cell-sub">{x.subcategory}</small></td><td><span className={`finance-status ${x.status}`}>{statusText(x.status)}</span></td><td>{dateLabel(x.date)}</td><td className={x.type==='receita'?'positive':'negative'}>{money(x.type==='receita'?x.amount:-x.amount)}</td><td><RowMenu onView={()=>setViewing(x)} onEdit={()=>setEditing(x)} onDelete={()=>update(transactions.filter(item=>item.id!==x.id))}/></td></tr>)}</tbody></table></div><footer className="finance-pagination"><span>Página {Math.min(page,pages)} de {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></footer></section>
  </section>
  {editing!==undefined&&<TransactionModal initial={editing} onClose={()=>setEditing(undefined)} onSave={value=>{const stamp=new Date().toISOString();if(value.id)update(transactions.map(x=>x.id===value.id?{...value,updatedAt:stamp}:x));else update([{...value,id:uid('tx'),createdAt:stamp,updatedAt:stamp},...transactions]);setEditing(undefined)}}/>}
  {viewing&&<TransactionView value={viewing} onClose={()=>setViewing(null)} onEdit={()=>{setEditing(viewing);setViewing(null)}}/>}
 </AdminShell>
}

function TransactionModal({initial,onClose,onSave}:{initial:FinanceTransaction|null;onClose:()=>void;onSave:(x:FinanceTransaction)=>void}){
 const stamp=new Date().toISOString();const blank:FinanceTransaction={id:'',type:'receita',description:'',category:'',subcategory:'',status:'pendente',date:new Date().toISOString().slice(0,10),dueDate:'',amount:0,counterparty:'',document:'',paymentMethod:'pix',paymentType:'avista',installmentCount:2,installmentInterval:30,firstInstallmentDate:'',contractRef:'',contactRef:'',supplierRef:'',costCenter:'',competence:'',notes:'',attachmentName:'',attachmentDataUrl:'',createdAt:stamp,updatedAt:stamp}
 const [form,setForm]=useState(initial?{...blank,...initial}:blank),fileRef=useRef<HTMLInputElement>(null)
 const categories=financeCategories.filter(x=>x.type===form.type),paymentType=form.paymentType??'avista',installments=Math.max(1,form.installmentCount??1)
 const file=(e:ChangeEvent<HTMLInputElement>)=>{const item=e.target.files?.[0];if(!item)return;const reader=new FileReader();reader.onload=()=>setForm(x=>({...x,attachmentName:item.name,attachmentDataUrl:String(reader.result)}));reader.readAsDataURL(item)}
 const save=(e:FormEvent)=>{e.preventDefault();if(!form.description.trim()||!form.category||form.amount<=0)return;onSave(form)}
 return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="finance-modal wide finance-transaction-reference" role="dialog" aria-modal="true"><header><div><span>Financeiro</span><h2>{initial?'Editar Transação':'Nova Transação'}</h2></div><button className="crm-icon-btn" onClick={onClose}><X size={18}/></button></header><form onSubmit={save}><div className="finance-modal-body">
  <FormSection title="Classificação"><div className="finance-form-grid"><Select label="Tipo de Transação" value={form.type} onChange={v=>setForm(x=>({...x,type:v as FinanceTransactionType,category:'',subcategory:''}))} options={[['receita','Receita'],['despesa','Despesa']]}/><Field label={form.type==='receita'?'Receber de':'Pagar para'} value={form.counterparty} onChange={v=>setForm(x=>({...x,counterparty:v}))}/><Select label="Categoria" value={form.category} onChange={v=>setForm(x=>({...x,category:v,subcategory:''}))} options={Array.from(new Set(categories.map(x=>x.category))).map(x=>[x,x])}/><Select label="Subcategoria" value={form.subcategory} onChange={v=>setForm(x=>({...x,subcategory:v}))} options={categories.filter(x=>x.category===form.category).map(x=>[x.subcategory,x.subcategory])}/><Field label="Contrato Vinculado" value={form.contractRef} onChange={v=>setForm(x=>({...x,contractRef:v}))}/><Field label="Contato / Cliente" value={form.contactRef??''} onChange={v=>setForm(x=>({...x,contactRef:v}))}/><Field label="Fornecedor" value={form.supplierRef??''} onChange={v=>setForm(x=>({...x,supplierRef:v}))}/><Field label="Centro de Custo" value={form.costCenter} onChange={v=>setForm(x=>({...x,costCenter:v}))}/><Field label="Competência" value={form.competence} onChange={v=>setForm(x=>({...x,competence:v}))}/></div></FormSection>
  <FormSection title="Valores e Pagamento"><div className="finance-form-grid"><Field label="Valor (R$)" type="number" value={String(form.amount||'')} onChange={v=>setForm(x=>({...x,amount:Number(v)}))}/><Select label="Tipo de Pagamento" value={paymentType} onChange={v=>setForm(x=>({...x,paymentType:v as FinancePaymentType}))} options={[['avista','À vista'],['parcelado','Parcelado']]}/><Select label="Método de Pagamento" value={form.paymentMethod} onChange={v=>setForm(x=>({...x,paymentMethod:v}))} options={[['pix','Pix'],['boleto','Boleto'],['transferencia','Transferência'],['cartao','Cartão'],['dinheiro','Dinheiro'],['outro','Outro']]}/><Field label="Data da Transação" type="date" value={form.date} onChange={v=>setForm(x=>({...x,date:v}))}/><Select label="Status" value={form.status} onChange={v=>setForm(x=>({...x,status:v as FinanceStatus}))} options={[['pago','Pago'],['pendente','Pendente'],['vencido','Vencido'],['cancelado','Cancelado']]}/>{paymentType==='parcelado'&&<><Field label="Quantidade de Parcelas" type="number" value={String(installments)} onChange={v=>setForm(x=>({...x,installmentCount:Math.max(1,Number(v))}))}/><Field label="Intervalo entre Parcelas (dias)" type="number" value={String(form.installmentInterval??30)} onChange={v=>setForm(x=>({...x,installmentInterval:Number(v)}))}/><Field label="Data da 1ª Parcela" type="date" value={form.firstInstallmentDate??''} onChange={v=>setForm(x=>({...x,firstInstallmentDate:v}))}/><label className="finance-field"><span>Valor por Parcela</span><input readOnly value={money(form.amount/installments)}/></label></>}</div></FormSection>
  <FormSection title="Detalhes"><div className="finance-form-grid"><Field label="Descrição" value={form.description} onChange={v=>setForm(x=>({...x,description:v}))}/><Field label="Documento / Referência" value={form.document} onChange={v=>setForm(x=>({...x,document:v}))}/><Field label="Vencimento" type="date" value={form.dueDate} onChange={v=>setForm(x=>({...x,dueDate:v}))}/></div><label className="finance-field wide"><span>Observações</span><textarea rows={4} value={form.notes} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label><div className="finance-upload-row"><input ref={fileRef} hidden type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={file}/><button type="button" className="crm-btn secondary" onClick={()=>fileRef.current?.click()}><Upload size={14}/>Anexar Comprovante</button><span>{form.attachmentName||'PDF, JPG, PNG, DOC ou DOCX'}</span></div></FormSection>
 </div><div className="finance-modal-foot"><button type="button" className="crm-btn secondary" onClick={onClose}>Cancelar</button><button className="crm-btn primary" type="submit">{initial?'Salvar Alterações':'Criar Transação'}</button></div></form></section></div>
}

function TransactionView({value,onClose,onEdit}:{value:FinanceTransaction;onClose:()=>void;onEdit:()=>void}){return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="finance-modal finance-transaction-view-reference" role="dialog" aria-modal="true"><header><div><span>Financeiro</span><h2>Detalhes da Transação</h2></div><button className="crm-icon-btn" onClick={onClose}><X size={18}/></button></header><div className="finance-modal-body"><FormSection title="Informações principais"><ViewGrid items={[['Descrição',value.description],['Tipo',value.type==='receita'?'Receita':'Despesa'],['Categoria',`${value.category} / ${value.subcategory}`],['Status',statusText(value.status)]]}/></FormSection><FormSection title="Informações financeiras"><ViewGrid items={[['Valor',money(value.type==='receita'?value.amount:-value.amount)],['Data',dateLabel(value.date)],['Vencimento',dateLabel(value.dueDate)],['Competência',value.competence||'—']]}/></FormSection><FormSection title="Pagamento"><ViewGrid items={[['Tipo de pagamento',value.paymentType==='parcelado'?'Parcelado':'À vista'],['Método',value.paymentMethod||'—'],['Parcelas',value.paymentType==='parcelado'?String(value.installmentCount??1):'—'],['Documento',value.document||'—']]}/></FormSection><FormSection title="Relacionamentos"><ViewGrid items={[['Contraparte',value.counterparty||'—'],['Contrato',value.contractRef||'—'],['Contato / Cliente',value.contactRef||'—'],['Fornecedor',value.supplierRef||'—'],['Centro de custo',value.costCenter||'—']]}/></FormSection>{value.notes&&<FormSection title="Observações"><p className="finance-view-notes">{value.notes}</p></FormSection>}<FormSection title="Anexos"><p className="finance-view-notes">{value.attachmentName||'Nenhum anexo'}</p></FormSection><FormSection title="Auditoria / Metadados"><ViewGrid items={[['Criado em',new Date(value.createdAt).toLocaleString('pt-BR')],['Atualizado em',new Date(value.updatedAt).toLocaleString('pt-BR')],['ID',value.id]]}/></FormSection></div><div className="finance-modal-foot"><button className="crm-btn secondary" onClick={onClose}>Fechar</button><button className="crm-btn primary" onClick={onEdit}>Editar</button></div></section></div>}
function ViewGrid({items}:{items:[string,string][]}){return <div className="finance-view-grid">{items.map(([label,value])=><div className="finance-info" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
function FormSection({title,children}:{title:string;children:ReactNode}){return <section className="finance-form-section"><h3>{title}</h3>{children}</section>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="finance-field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="finance-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Selecione</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Kpi({title,value,detail,icon}:{title:string;value:string;detail:string;icon:ReactNode}){return <article className="finance-kpi"><div><span>{title}</span><strong>{value}</strong><small>{detail}</small></div><i>{icon}</i></article>}
function RowMenu({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);return <div className="crm-row-actions"><button className="crm-icon-btn" onClick={()=>setOpen(v=>!v)} aria-label="Ações"><MoreHorizontal size={16}/></button>{open&&<div className="crm-row-menu"><button onClick={()=>{setOpen(false);onView()}}>Ver</button><button onClick={()=>{setOpen(false);onEdit()}}>Editar</button><button className="danger" onClick={()=>{setOpen(false);onDelete()}}>Excluir</button></div>}</div>}
const statusText=(x:FinanceStatus)=>({pago:'Pago',pendente:'Pendente',vencido:'Vencido',cancelado:'Cancelado'}[x])