import {useState,type ReactNode} from 'react'
import {Paperclip,Trash2,X} from 'lucide-react'
import {contactCategoryOptions,contactProfiles,priorityOptions,type Contact} from './domain'
import {filesToAttachments} from './repository'
import {getContactSemanticLabels} from './semantics'
import {draftFromContact,type ContactDraft as Draft} from './contactDraft'

export function ContactFormModal(props:{open:boolean;contact?:Contact|null;onClose:()=>void;onSubmit:(draft:Draft,expectedUpdatedAt?:string)=>Promise<void>;busy:boolean}){
 if(!props.open)return null
 return <ContactFormContent key={props.contact?.id??'new-contact'} {...props}/>
}
function ContactFormContent({contact,onClose,onSubmit,busy}:{open:boolean;contact?:Contact|null;onClose:()=>void;onSubmit:(draft:Draft,expectedUpdatedAt?:string)=>Promise<void>;busy:boolean}){
 const [draft,setDraft]=useState<Draft>(()=>draftFromContact(contact));const [error,setError]=useState('')
 const set=<K extends keyof Draft>(k:K,v:Draft[K])=>setDraft(p=>({...p,[k]:v}));const profiles=contactProfiles[draft.entityType][draft.category]??['Outro'];const semantic=getContactSemanticLabels(draft.entityType)
 const submit=async()=>{if(!draft.name.trim()){setError('Nome é obrigatório.');return}try{setError('');await onSubmit(draft,contact?.updatedAt)}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o contato.')}}
 return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="crm-modal crm-modal-lg crm-modal-semantic crm-modal-form crm-contact-form" role="dialog" aria-modal="true" aria-label={contact?'Editar contato':'Novo contato'}><header className="crm-modal-head"><div><h2>{contact?'Editar Contato':'Novo Contato'}</h2><p>Relacionamento comercial ou institucional do Portal Lander.</p></div><button className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><div className="crm-modal-body">
 {error&&<div className="crm-error" role="alert">{error}</div>}
 <FormSection title="Tipo e Classificação"><div className="crm-form-grid crm-grid-3"><SelectField label="Tipo de contato" value={draft.entityType} options={[['pessoa_fisica','Pessoa Física'],['pessoa_juridica','Pessoa Jurídica']]} onChange={v=>{const t=v as Draft['entityType'];const nextProfile=contactProfiles[t][draft.category]?.[0]??'Outro';setDraft(p=>({...p,entityType:t,profile:nextProfile}))}}/><SelectField label="Categoria" value={draft.category} options={contactCategoryOptions} onChange={v=>{const c=v as Draft['category'];setDraft(p=>({...p,category:c,profile:contactProfiles[p.entityType][c]?.[0]??'Outro'}))}}/><SelectField label="Perfil" value={draft.profile} options={profiles.map(x=>[x,x] as const)} onChange={v=>set('profile',v)}/></div></FormSection>
 <FormSection title="Identificação"><div className="crm-form-grid crm-contact-identification-grid"><Field label={semantic.name}><input value={draft.name} onChange={e=>set('name',e.target.value)}/></Field><Field label={semantic.document}><input value={draft.document} onChange={e=>set('document',e.target.value)}/></Field><Field label={semantic.company}><input value={draft.company} onChange={e=>set('company',e.target.value)}/></Field></div></FormSection>
 <FormSection title="Contato e Presença Digital"><div className="crm-form-grid crm-grid-2"><Field label="Email"><input type="email" value={draft.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Telefone"><input value={draft.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label="WhatsApp"><input value={draft.whatsapp} onChange={e=>set('whatsapp',e.target.value)}/></Field><Field label="Instagram"><input value={draft.instagram} onChange={e=>set('instagram',e.target.value)}/></Field><Field label="Website"><input value={draft.website} onChange={e=>set('website',e.target.value)}/></Field></div></FormSection>
 <FormSection title="Localização"><div className="crm-form-grid crm-grid-2"><Field label="Cidade"><input value={draft.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="Estado"><input maxLength={2} value={draft.state} onChange={e=>set('state',e.target.value.toUpperCase())}/></Field></div></FormSection>
 <FormSection title="Relacionamento"><div className="crm-form-grid crm-contact-relationship-grid"><SelectField label="Prioridade" value={draft.priority} options={priorityOptions} onChange={v=>set('priority',v as Draft['priority'])}/><SelectField label="Status" value={draft.status} options={[['ativo','Ativo'],['inativo','Inativo']]} onChange={v=>set('status',v as Draft['status'])}/><Field label="Tags"><input value={draft.tags.join(', ')} onChange={e=>set('tags',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="Cliente Recorrente, Assessoria, Marca..."/></Field></div></FormSection>
 <FormSection title="Observações"><div className="crm-form-grid crm-grid-1"><Field label="Observações" wide><textarea rows={4} value={draft.notes} onChange={e=>set('notes',e.target.value)}/></Field></div></FormSection>
 <FormSection title="Anexos"><label className="crm-upload"><Paperclip size={16}/><span>Adicionar documento ou material (até 2 MB)</span><input type="file" multiple onChange={async e=>{if(!e.target.files)return;try{const files=await filesToAttachments(e.target.files);set('attachments',[...draft.attachments,...files])}catch(err){setError(err instanceof Error?err.message:'Falha no upload.')}}}/></label>{draft.attachments.length>0&&<div className="crm-attachment-list">{draft.attachments.map(a=><div key={a.id}><span>{a.name}</span><button type="button" onClick={()=>set('attachments',draft.attachments.filter(x=>x.id!==a.id))} aria-label={`Remover ${a.name}`}><Trash2 size={14}/></button></div>)}</div>}</FormSection>
 </div><footer className="crm-modal-foot"><button className="crm-btn secondary" onClick={onClose}>Cancelar</button><button className="crm-btn primary" disabled={busy} onClick={submit}>{busy?'Salvando...':contact?'Salvar alterações':'Criar contato'}</button></footer></section></div>
}
function FormSection({title,children}:{title:string;children:ReactNode}){return <section className="crm-form-section crm-semantic-section"><h3>{title}</h3>{children}</section>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`crm-field${wide?' wide':''}`}><span>{label}</span>{children}</label>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:readonly (readonly [string,string])[];onChange:(v:string)=>void}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>}
