import {useEffect,useMemo,useState,type ReactNode} from 'react'
import {BriefcaseBusiness,CheckCircle2,Eye,Filter,Flame,MoreHorizontal,Plus,Search,Trash2,UserRound,UsersRound} from 'lucide-react'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {contactCategoryOptions,label,leadStatusOptions,leadTypeOptions,originOptions,priorityOptions,serviceOptions,temperatureOptions,type Contact,type ContactFilters,type Lead,type LeadFilters,type LeadStatus} from './domain'
import {useBulkDeleteContacts,useBulkDeleteLeads,useBulkLeadStatus,useContacts,useCreateContact,useCreateLead,useDeleteContact,useDeleteLead,useLeads,useUpdateContact,useUpdateLead} from './hooks'
import {LeadFormModal} from './LeadFormModal'
import {LeadViewModal} from './LeadViewModal'
import {ContactFormModal} from './ContactFormModal'
import {ContactViewModal} from './ContactViewModal'

const emptyLeadFilters:LeadFilters={search:'',status:'all',type:'all',service:'all',origin:'all',priority:'all',temperature:'all'}
const emptyContactFilters:ContactFilters={search:'',entityType:'all',category:'all',profile:'all',status:'all',priority:'all'}
const NO_LEADS:Lead[]=[]
const NO_CONTACTS:Contact[]=[]

export default function CrmPage({view}:{view:'leads'|'contacts'}){
 const leadsQ=useLeads(),contactsQ=useContacts()
 const [leadFilters,setLeadFilters]=usePersistentState('portal-lander:crm:lead-filters',emptyLeadFilters)
 const [contactFilters,setContactFilters]=usePersistentState('portal-lander:crm:contact-filters',emptyContactFilters)
 const [leadPage,setLeadPage]=useState(1),[contactPage,setContactPage]=useState(1);const pageSize=20
 const [selectedLeadIds,setSelectedLeadIds]=useState<string[]>([]),[selectedContactIds,setSelectedContactIds]=useState<string[]>([])
 const [leadForm,setLeadForm]=useState<Lead|null|undefined>(undefined),[leadView,setLeadView]=useState<Lead|null>(null),[contactForm,setContactForm]=useState<Contact|null|undefined>(undefined),[contactView,setContactView]=useState<Contact|null>(null)
 const createLead=useCreateLead(),updateLead=useUpdateLead(),deleteLead=useDeleteLead(),bulkDeleteLeads=useBulkDeleteLeads(),bulkStatus=useBulkLeadStatus(),createContact=useCreateContact(),updateContact=useUpdateContact(),deleteContact=useDeleteContact(),bulkDeleteContacts=useBulkDeleteContacts()
 const leads=leadsQ.data??NO_LEADS,contacts=contactsQ.data??NO_CONTACTS
 const changeLeadFilters=(update:(current:LeadFilters)=>LeadFilters)=>{setLeadFilters(update);setLeadPage(1)}
 const changeContactFilters=(update:(current:ContactFilters)=>ContactFilters)=>{setContactFilters(update);setContactPage(1)}
 const filteredLeads=useMemo(()=>leads.filter(l=>{const q=leadFilters.search.trim().toLowerCase();return(!q||[l.name,l.company,l.email,l.phone,l.instagram].some(v=>v.toLowerCase().includes(q)))&&(leadFilters.status==='all'||l.status===leadFilters.status)&&(leadFilters.type==='all'||l.type===leadFilters.type)&&(leadFilters.service==='all'||l.service===leadFilters.service)&&(leadFilters.origin==='all'||l.origin===leadFilters.origin)&&(leadFilters.priority==='all'||l.priority===leadFilters.priority)&&(leadFilters.temperature==='all'||l.temperature===leadFilters.temperature)}),[leads,leadFilters])
 const filteredContacts=useMemo(()=>contacts.filter(c=>{const q=contactFilters.search.trim().toLowerCase();return(!q||[c.name,c.company,c.email,c.phone,c.whatsapp,c.document].some(v=>v.toLowerCase().includes(q)))&&(contactFilters.entityType==='all'||c.entityType===contactFilters.entityType)&&(contactFilters.category==='all'||c.category===contactFilters.category)&&(contactFilters.profile==='all'||c.profile===contactFilters.profile)&&(contactFilters.status==='all'||c.status===contactFilters.status)&&(contactFilters.priority==='all'||c.priority===contactFilters.priority)}),[contacts,contactFilters])
 const leadPageCount=Math.max(1,Math.ceil(filteredLeads.length/pageSize)),contactPageCount=Math.max(1,Math.ceil(filteredContacts.length/pageSize));const pagedLeads=filteredLeads.slice((leadPage-1)*pageSize,leadPage*pageSize),pagedContacts=filteredContacts.slice((contactPage-1)*pageSize,contactPage*pageSize)
 const leadMetrics={total:leads.length,new:leads.filter(x=>x.status==='novo').length,proposal:leads.filter(x=>x.status==='proposta').length,negotiation:leads.filter(x=>x.status==='negociacao').length,closed:leads.filter(x=>x.status==='fechado').length}
 const contactMetrics={total:contacts.length,clients:contacts.filter(x=>x.category==='cliente').length,advertisers:contacts.filter(x=>x.category==='anunciante').length,partners:contacts.filter(x=>x.category==='parceiro').length,sources:contacts.filter(x=>x.category==='fonte_editorial').length}
 const isLoading=leadsQ.isLoading||contactsQ.isLoading
 return <AdminShell area="crm" items={CRM_WORKSPACE_NAV} header={{title:view==='leads'?'Leads':'Contatos',description:view==='leads'?'Pipeline comercial e oportunidades':'Relacionamentos comerciais e institucionais'}}>
  <section className="crm-page">
   <div className="crm-page-toolbar"><div><span className="crm-eyebrow">CRM</span><h2>{view==='leads'?'Pipeline Comercial':'Rede de Relacionamentos'}</h2><p>{view==='leads'?'Prospecção, qualificação, follow-up, propostas e fechamento.':'Clientes, anunciantes, parceiros, assessorias, fornecedores e fontes.'}</p></div><button className="crm-btn primary" onClick={()=>view==='leads'?setLeadForm(null):setContactForm(null)}><Plus size={16}/>{view==='leads'?'Novo lead':'Novo contato'}</button></div>
   {view==='leads'?<>
    <div className="crm-kpis"><Kpi label="Total de Leads" value={leadMetrics.total} icon={<UsersRound size={17}/>}/><Kpi label="Novos" value={leadMetrics.new} icon={<Plus size={17}/>}/><Kpi label="Propostas" value={leadMetrics.proposal} icon={<BriefcaseBusiness size={17}/>}/><Kpi label="Em Negociação" value={leadMetrics.negotiation} icon={<Flame size={17}/>}/><Kpi label="Fechados" value={leadMetrics.closed} icon={<CheckCircle2 size={17}/>}/></div>
    <FilterBar search={leadFilters.search} setSearch={v=>changeLeadFilters(f=>({...f,search:v}))}><Select value={leadFilters.status} options={[['all','Todos os status'],...leadStatusOptions]} onChange={v=>changeLeadFilters(f=>({...f,status:v}))}/><Select value={leadFilters.type} options={[['all','Todos os tipos'],...leadTypeOptions]} onChange={v=>changeLeadFilters(f=>({...f,type:v}))}/><Select value={leadFilters.service} options={[['all','Todos os serviços'],...serviceOptions]} onChange={v=>changeLeadFilters(f=>({...f,service:v}))}/><Select value={leadFilters.origin} options={[['all','Todas as origens'],...originOptions]} onChange={v=>changeLeadFilters(f=>({...f,origin:v}))}/><Select value={leadFilters.priority} options={[['all','Todas as prioridades'],...priorityOptions]} onChange={v=>changeLeadFilters(f=>({...f,priority:v}))}/><Select value={leadFilters.temperature} options={[['all','Todas as temperaturas'],...temperatureOptions]} onChange={v=>changeLeadFilters(f=>({...f,temperature:v}))}/></FilterBar>
    <section className="crm-table-card"><TableHeader title="Lista de Leads" description="Acompanhe oportunidades, status, origem, valor e próximos follow-ups" selected={selectedLeadIds.length}>{selectedLeadIds.length>0&&<><select className="crm-inline-select" defaultValue="" onChange={e=>{if(e.target.value)bulkStatus.mutate({ids:selectedLeadIds,status:e.target.value as LeadStatus});e.currentTarget.value=''}}><option value="">Alterar status...</option>{leadStatusOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="crm-btn danger small" onClick={()=>{if(confirm(`Excluir ${selectedLeadIds.length} lead(s)?`)){bulkDeleteLeads.mutate(selectedLeadIds);setSelectedLeadIds([])}}}><Trash2 size={14}/>Excluir</button></>}</TableHeader>{isLoading?<Loading/>:filteredLeads.length===0?<Empty text="Nenhum lead encontrado para os filtros atuais."/>:<><LeadTable leads={pagedLeads} selected={selectedLeadIds} onSelected={setSelectedLeadIds} onView={setLeadView} onEdit={l=>setLeadForm(l)} onDelete={l=>{if(confirm(`Excluir o lead ${l.name}?`))deleteLead.mutate(l.id)}}/><Pagination page={Math.min(leadPage,leadPageCount)} pages={leadPageCount} total={filteredLeads.length} onPage={setLeadPage}/></>}</section>
   </>:<>
    <div className="crm-kpis"><Kpi label="Total de Contatos" value={contactMetrics.total} icon={<UsersRound size={17}/>}/><Kpi label="Clientes" value={contactMetrics.clients} icon={<UserRound size={17}/>}/><Kpi label="Anunciantes" value={contactMetrics.advertisers} icon={<BriefcaseBusiness size={17}/>}/><Kpi label="Parceiros" value={contactMetrics.partners} icon={<UsersRound size={17}/>}/><Kpi label="Fontes Editoriais" value={contactMetrics.sources} icon={<UserRound size={17}/>}/></div>
    <FilterBar search={contactFilters.search} setSearch={v=>changeContactFilters(f=>({...f,search:v}))}><Select value={contactFilters.entityType} options={[['all','Pessoa Física / Jurídica'],['pessoa_fisica','Pessoa Física'],['pessoa_juridica','Pessoa Jurídica']]} onChange={v=>changeContactFilters(f=>({...f,entityType:v}))}/><Select value={contactFilters.category} options={[['all','Todas as categorias'],...contactCategoryOptions]} onChange={v=>changeContactFilters(f=>({...f,category:v}))}/><Select value={contactFilters.status} options={[['all','Todos os status'],['ativo','Ativo'],['inativo','Inativo']]} onChange={v=>changeContactFilters(f=>({...f,status:v}))}/><Select value={contactFilters.priority} options={[['all','Todas as prioridades'],...priorityOptions]} onChange={v=>changeContactFilters(f=>({...f,priority:v}))}/></FilterBar>
    <section className="crm-table-card"><TableHeader title="Lista de Contatos" description="Relacionamentos consolidados do Portal Lander" selected={selectedContactIds.length}>{selectedContactIds.length>0&&<button className="crm-btn danger small" onClick={()=>{if(confirm(`Excluir ${selectedContactIds.length} contato(s)?`)){bulkDeleteContacts.mutate(selectedContactIds);setSelectedContactIds([])}}}><Trash2 size={14}/>Excluir</button>}</TableHeader>{isLoading?<Loading/>:filteredContacts.length===0?<Empty text="Nenhum contato encontrado para os filtros atuais."/>:<><ContactTable contacts={pagedContacts} selected={selectedContactIds} onSelected={setSelectedContactIds} onView={setContactView} onEdit={c=>setContactForm(c)} onDelete={c=>{if(confirm(`Excluir o contato ${c.name}?`))deleteContact.mutate(c.id)}}/><Pagination page={Math.min(contactPage,contactPageCount)} pages={contactPageCount} total={filteredContacts.length} onPage={setContactPage}/></>}</section>
   </>}
  </section>
  <LeadFormModal open={leadForm!==undefined} lead={leadForm} onClose={()=>setLeadForm(undefined)} busy={createLead.isPending||updateLead.isPending} onSubmit={async(d,expected)=>{if(leadForm){await updateLead.mutateAsync({id:leadForm.id,patch:d,expectedUpdatedAt:expected})}else await createLead.mutateAsync(d);setLeadForm(undefined)}}/>
  <LeadViewModal open={Boolean(leadView)} lead={leadView} onClose={()=>setLeadView(null)} onEdit={()=>{const l=leadView;setLeadView(null);setLeadForm(l)}}/>
  <ContactFormModal open={contactForm!==undefined} contact={contactForm} onClose={()=>setContactForm(undefined)} busy={createContact.isPending||updateContact.isPending} onSubmit={async(d,expected)=>{if(contactForm){await updateContact.mutateAsync({id:contactForm.id,patch:d,expectedUpdatedAt:expected})}else await createContact.mutateAsync(d);setContactForm(undefined)}}/>
  <ContactViewModal open={Boolean(contactView)} contact={contactView} onClose={()=>setContactView(null)} onEdit={()=>{const c=contactView;setContactView(null);setContactForm(c)}}/>
 </AdminShell>
}
function Kpi({label:lab,value,icon}:{label:string;value:number;icon:ReactNode}){return <article className="crm-kpi"><div><span>{lab}</span><strong>{value}</strong></div><i>{icon}</i></article>}
function FilterBar({search,setSearch,children}:{search:string;setSearch:(v:string)=>void;children:ReactNode}){return <div className="crm-filters"><label className="crm-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, empresa, email, telefone..."/></label><div className="crm-filter-selects"><Filter size={14}/>{children}</div></div>}
function Select({value,options,onChange}:{value:string;options:readonly (readonly [string,string])[];onChange:(v:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function TableHeader({title,description,selected,children}:{title:string;description:string;selected:number;children?:ReactNode}){return <header className="crm-table-head"><div><h3>{title}</h3><p>{description}</p></div><div>{selected>0&&<span className="crm-selection-count">{selected} selecionado(s)</span>}{children}</div></header>}
function Loading(){return <div className="crm-loading"><span/><span/><span/></div>}
function Empty({text}:{text:string}){return <div className="crm-empty"><UsersRound size={28}/><strong>Nenhum registro</strong><p>{text}</p></div>}
function LeadTable({leads,selected,onSelected,onView,onEdit,onDelete}:{leads:Lead[];selected:string[];onSelected:(ids:string[])=>void;onView:(l:Lead)=>void;onEdit:(l:Lead)=>void;onDelete:(l:Lead)=>void}){const all=leads.length>0&&leads.every(l=>selected.includes(l.id));return <div className="crm-table-wrap"><table className="crm-table"><thead><tr><th><input type="checkbox" checked={all} onChange={()=>onSelected(all?[]:leads.map(l=>l.id))}/></th><th>Lead</th><th>Serviço</th><th>Status</th><th>Origem</th><th>Valor estimado</th><th>Follow-up</th><th>Prioridade</th><th></th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><input type="checkbox" checked={selected.includes(l.id)} onChange={()=>onSelected(selected.includes(l.id)?selected.filter(x=>x!==l.id):[...selected,l.id])}/></td><td><button className="crm-link" onClick={()=>onView(l)}><strong>{l.name}</strong><small>{l.company||l.email||'Sem empresa'}</small></button></td><td>{label(serviceOptions,l.service)}</td><td><span className={`crm-badge status-${l.status}`}>{label(leadStatusOptions,l.status)}</span></td><td>{label(originOptions,l.origin)}</td><td>{typeof l.estimatedValue==='number'?l.estimatedValue.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}</td><td>{l.nextFollowUp?new Date(l.nextFollowUp).toLocaleDateString('pt-BR'):'—'}</td><td>{label(priorityOptions,l.priority)}</td><td><RowActions onView={()=>onView(l)} onEdit={()=>onEdit(l)} onDelete={()=>onDelete(l)}/></td></tr>)}</tbody></table></div>}
function ContactTable({contacts,selected,onSelected,onView,onEdit,onDelete}:{contacts:Contact[];selected:string[];onSelected:(ids:string[])=>void;onView:(c:Contact)=>void;onEdit:(c:Contact)=>void;onDelete:(c:Contact)=>void}){const all=contacts.length>0&&contacts.every(c=>selected.includes(c.id));return <div className="crm-table-wrap"><table className="crm-table"><thead><tr><th><input type="checkbox" checked={all} onChange={()=>onSelected(all?[]:contacts.map(c=>c.id))}/></th><th>Contato</th><th>Tipo</th><th>Categoria</th><th>Perfil</th><th>Cidade/UF</th><th>Prioridade</th><th>Status</th><th></th></tr></thead><tbody>{contacts.map(c=><tr key={c.id}><td><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>onSelected(selected.includes(c.id)?selected.filter(x=>x!==c.id):[...selected,c.id])}/></td><td><button className="crm-link" onClick={()=>onView(c)}><strong>{c.name}</strong><small>{c.company||c.email||'Sem empresa'}</small></button></td><td>{c.entityType==='pessoa_fisica'?'Pessoa Física':'Pessoa Jurídica'}</td><td>{label(contactCategoryOptions,c.category)}</td><td>{c.profile}</td><td>{[c.city,c.state].filter(Boolean).join('/')||'—'}</td><td>{label(priorityOptions,c.priority)}</td><td><span className={`crm-badge ${c.status==='ativo'?'status-fechado':'muted'}`}>{c.status==='ativo'?'Ativo':'Inativo'}</span></td><td><RowActions onView={()=>onView(c)} onEdit={()=>onEdit(c)} onDelete={()=>onDelete(c)}/></td></tr>)}</tbody></table></div>}
function RowActions({onView,onEdit,onDelete}:{onView:()=>void;onEdit:()=>void;onDelete:()=>void}){const [open,setOpen]=useState(false);return <div className="crm-row-actions"><button className="crm-icon-btn" onClick={()=>setOpen(v=>!v)} aria-label="Ações"><MoreHorizontal size={16}/></button>{open&&<div className="crm-row-menu"><button onClick={()=>{setOpen(false);onView()}}><Eye size={14}/>Visualizar</button><button onClick={()=>{setOpen(false);onEdit()}}>Editar</button><button className="danger" onClick={()=>{setOpen(false);onDelete()}}><Trash2 size={14}/>Excluir</button></div>}</div>}
function Pagination({page,pages,total,onPage}:{page:number;pages:number;total:number;onPage:(p:number)=>void}){return <div className="crm-pagination"><span>{total} registro(s) · Página {page} de {pages}</span><div><button disabled={page<=1} onClick={()=>onPage(page-1)}>Anterior</button><button disabled={page>=pages} onClick={()=>onPage(page+1)}>Próxima</button></div></div>}
function usePersistentState<T>(key:string,initial:T){const [value,setValue]=useState<T>(()=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:initial}catch{return initial}});useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(value))}catch(error){void error}},[key,value]);return [value,setValue] as const}
