import {useState,type ReactNode} from 'react'
import {Download,Edit3,ExternalLink,FileText,MessageSquare,UserRound,X} from 'lucide-react'
import {interactionOptions,label,leadStatusOptions,leadTypeOptions,originOptions,priorityOptions,serviceOptions,temperatureOptions,type InteractionType,type Lead} from './domain'
import {useAddLeadInteraction,useConvertLead} from './hooks'
import {getServiceDetailLabel} from './semantics'

export function LeadViewModal({open,lead,onClose,onEdit}:{open:boolean;lead:Lead|null;onClose:()=>void;onEdit:()=>void}){
 const [type,setType]=useState<InteractionType>('nota');const [notes,setNotes]=useState('');const [responsible,setResponsible]=useState('');const add=useAddLeadInteraction();const convert=useConvertLead();if(!open||!lead)return null
 return <div className="crm-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="crm-modal crm-modal-lg crm-modal-semantic crm-modal-view" role="dialog" aria-modal="true" aria-label="Visualizar lead"><header className="crm-modal-head"><div><div className="crm-badge-row"><span className={`crm-badge status-${lead.status}`}>{label(leadStatusOptions,lead.status)}</span><span className="crm-badge muted">{label(priorityOptions,lead.priority)}</span><span className="crm-badge muted">{label(leadTypeOptions,lead.type)}</span></div><h2>{lead.name}</h2><p>{lead.company||'Sem empresa informada'}</p></div><button className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><div className="crm-modal-body crm-view-grid">
  <Info title="Identificação"><Row k="Cargo / Função" v={lead.role}/></Info>
  <Info title="Contato"><Row k="Email" v={lead.email}/><Row k="Telefone / WhatsApp" v={lead.phone}/></Info>
  <Info title="Presença Digital"><Row k="Instagram" v={lead.instagram}/><Row k="Website" v={lead.website}/></Info>
  <Info title="Localização"><Row k="Cidade / UF" v={[lead.city,lead.state].filter(Boolean).join(' / ')}/></Info>
  <Info title="Qualificação"><Row k="Origem" v={label(originOptions,lead.origin)}/><Row k="Temperatura" v={label(temperatureOptions,lead.temperature)}/></Info>
  <Info title="Interesse Comercial"><Row k="Serviço / Interesse" v={label(serviceOptions,lead.service)}/><div className="crm-info-block"><span>Descrição da necessidade</span><p className="crm-long-text">{lead.description||'—'}</p></div></Info>
  {Object.entries(lead.serviceDetails).some(([,value])=>Boolean(value))&&<Info title="Detalhes do Serviço">{Object.entries(lead.serviceDetails).filter(([,value])=>value).map(([key,value])=><Row key={key} k={getServiceDetailLabel(lead.service,key)} v={value}/>)}</Info>}
  <Info title="Gestão Comercial"><Row k="Responsável" v={lead.responsible}/><Row k="Campanha de origem" v={lead.campaign}/><Row k="Valor estimado" v={typeof lead.estimatedValue==='number'?lead.estimatedValue.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):''}/><Row k="Tags" v={lead.tags.join(', ')}/></Info>
  <Info title="Follow-up"><Row k="Próximo follow-up" v={lead.nextFollowUp?new Date(lead.nextFollowUp).toLocaleString('pt-BR'):''}/></Info>
  <Info title="Observações Internas"><div className="crm-info-block"><span>Observações internas</span><p className="crm-long-text">{lead.notes||'—'}</p></div></Info>
  <section className="crm-view-section crm-semantic-view-section wide"><div className="crm-section-title"><h3>Interações da equipe</h3><MessageSquare size={16}/></div><div className="crm-interaction-form"><select value={type} onChange={e=>setType(e.target.value as InteractionType)}>{interactionOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input placeholder="Responsável" value={responsible} onChange={e=>setResponsible(e.target.value)}/><input className="grow" placeholder="Registrar observação da interação" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="crm-btn primary" disabled={!notes.trim()||add.isPending} onClick={async()=>{await add.mutateAsync({leadId:lead.id,type,notes,responsible});setNotes('')}}>Adicionar</button></div><div className="crm-timeline">{lead.interactions.length===0?<div className="crm-empty-mini">Nenhuma interação registrada.</div>:lead.interactions.map(i=><article key={i.id}><span className="crm-timeline-dot"/><div><strong>{label(interactionOptions,i.type)}</strong><p>{i.notes}</p><small>{i.responsible&&`${i.responsible} · `}{new Date(i.createdAt).toLocaleString('pt-BR')}</small></div></article>)}</div></section>
  <section className="crm-view-section crm-semantic-view-section wide"><div className="crm-section-title"><h3>Anexos</h3><FileText size={16}/></div>{lead.attachments.length===0?<div className="crm-empty-mini">Nenhum anexo.</div>:<div className="crm-file-grid">{lead.attachments.map(a=><a key={a.id} href={a.dataUrl} download={a.name}><FileText size={16}/><span>{a.name}</span><Download size={14}/></a>)}</div>}</section>
  {(lead.status==='fechado'||lead.convertedContactId)&&<section className="crm-view-section crm-semantic-view-section wide"><h3>Conversão</h3>{lead.status==='fechado'&&!lead.convertedContactId?<div className="crm-conversion-panel"><div><strong>Lead fechado</strong><span>Converta este lead em contato/cliente mantendo a operação existente.</span></div><button className="crm-btn success" disabled={convert.isPending} onClick={async()=>{await convert.mutateAsync(lead.id)}}><UserRound size={15}/> Converter em contato/cliente</button></div>:<div className="crm-converted"><ExternalLink size={14}/> Lead convertido em contato/cliente</div>}</section>}
  <Info title="Metadados"><Row k="Criado em" v={new Date(lead.createdAt).toLocaleString('pt-BR')}/><Row k="Atualizado em" v={new Date(lead.updatedAt).toLocaleString('pt-BR')}/></Info>
 </div><footer className="crm-modal-foot"><button className="crm-btn secondary" onClick={onClose}>Fechar</button><button className="crm-btn primary" onClick={onEdit}><Edit3 size={15}/> Editar</button></footer></section></div>
}
function Info({title,children}:{title:string;children:ReactNode}){return <section className="crm-view-section crm-semantic-view-section"><h3>{title}</h3>{children}</section>}
function Row({k,v}:{k:string;v?:string}){return <div className="crm-info-row"><span>{k}</span><strong>{v||'—'}</strong></div>}
