import {useState,type ReactNode} from 'react'
import {Paperclip,Trash2,X} from 'lucide-react'
import {emptyLead,leadStatusOptions,leadTypeOptions,originOptions,priorityOptions,serviceDetailFields,serviceOptions,temperatureOptions,type Attachment,type Lead} from './domain'
import {filesToAttachments} from './repository'

type Draft=ReturnType<typeof emptyLead>&{attachments:Attachment[]}
const draftFromLead=(lead?:Lead|null):Draft=>lead?{name:lead.name,company:lead.company,email:lead.email,phone:lead.phone,city:lead.city,state:lead.state,role:lead.role,website:lead.website,instagram:lead.instagram,type:lead.type,service:lead.service,description:lead.description,origin:lead.origin,status:lead.status,priority:lead.priority,responsible:lead.responsible,campaign:lead.campaign,nextFollowUp:lead.nextFollowUp,estimatedValue:lead.estimatedValue,temperature:lead.temperature,serviceDetails:{...lead.serviceDetails},notes:lead.notes,tags:[...lead.tags],attachments:[...lead.attachments]}:{...emptyLead(),attachments:[]}

export function LeadFormModal(props:{open:boolean;lead?:Lead|null;onClose:()=>void;onSubmit:(draft:Draft,expectedUpdatedAt?:string)=>Promise<void>;busy:boolean}){
 if(!props.open)return null
 return <LeadFormContent key={props.lead?.id??'new-lead'} {...props}/>
}
function LeadFormContent({lead,onClose,onSubmit,busy}:{open:boolean;lead?:Lead|null;onClose:()=>void;onSubmit:(draft:Draft,expectedUpdatedAt?:string)=>Promise<void>;busy:boolean}){
 const [draft,setDraft]=useState<Draft>(()=>draftFromLead(lead));const [error,setError]=useState('')
 const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(prev=>({...prev,[key]:value}))
 const submit=async()=>{if(!draft.name.trim()||!draft.phone.trim()){setError('Nome e telefone/WhatsApp são obrigatórios.');return}try{setError('');await onSubmit(draft,lead?.updatedAt)}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o lead.')}}
 const detailFields=serviceDetailFields[draft.service]??[]
 return <div className="crm-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="crm-modal crm-modal-lg" role="dialog" aria-modal="true" aria-label={lead?'Editar lead':'Novo lead'}>
  <header className="crm-modal-head"><div><h2>{lead?'Editar Lead':'Novo Lead'}</h2><p>Qualificação comercial, serviço, follow-up e contexto operacional.</p></div><button className="crm-icon-btn" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header>
  <div className="crm-modal-body">
   {error&&<div className="crm-error" role="alert">{error}</div>}
   <FormSection title="Identificação"><div className="crm-form-grid"><Field label="Nome do contato *"><input value={draft.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Empresa / Marca"><input value={draft.company} onChange={e=>set('company',e.target.value)}/></Field><Field label="Email"><input type="email" value={draft.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Telefone / WhatsApp *"><input value={draft.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Cargo / Função"><input value={draft.role} onChange={e=>set('role',e.target.value)}/></Field><Field label="Instagram"><input value={draft.instagram} onChange={e=>set('instagram',e.target.value)}/></Field><Field label="Website"><input value={draft.website} onChange={e=>set('website',e.target.value)}/></Field><Field label="Cidade"><input value={draft.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="Estado"><input maxLength={2} value={draft.state} onChange={e=>set('state',e.target.value.toUpperCase())}/></Field></div></FormSection>
   <FormSection title="Interesse comercial"><div className="crm-form-grid"><SelectField label="Tipo de lead" value={draft.type} options={leadTypeOptions} onChange={v=>set('type',v as Draft['type'])}/><SelectField label="Serviço / interesse" value={draft.service} options={serviceOptions} onChange={v=>set('service',v as Draft['service'])}/><Field label="Descrição" wide><textarea rows={3} value={draft.description} onChange={e=>set('description',e.target.value)}/></Field>{detailFields.map(f=><Field key={f.key} label={f.label}><input type={f.type??'text'} value={draft.serviceDetails[f.key]??''} onChange={e=>set('serviceDetails',{...draft.serviceDetails,[f.key]:e.target.value})}/></Field>)}</div></FormSection>
   <FormSection title="Dados internos do CRM"><div className="crm-form-grid"><SelectField label="Origem" value={draft.origin} options={originOptions} onChange={v=>set('origin',v as Draft['origin'])}/><SelectField label="Status" value={draft.status} options={leadStatusOptions} onChange={v=>set('status',v as Draft['status'])}/><SelectField label="Prioridade" value={draft.priority} options={priorityOptions} onChange={v=>set('priority',v as Draft['priority'])}/><SelectField label="Temperatura" value={draft.temperature} options={temperatureOptions} onChange={v=>set('temperature',v as Draft['temperature'])}/><Field label="Responsável"><input value={draft.responsible} onChange={e=>set('responsible',e.target.value)}/></Field><Field label="Campanha de origem"><input value={draft.campaign} onChange={e=>set('campaign',e.target.value)}/></Field><Field label="Próximo follow-up"><input type="datetime-local" value={draft.nextFollowUp} onChange={e=>set('nextFollowUp',e.target.value)}/></Field><Field label="Valor estimado"><input type="number" min="0" step="0.01" value={draft.estimatedValue} onChange={e=>set('estimatedValue',e.target.value===''?'':Number(e.target.value))}/></Field><Field label="Tags" wide><input value={draft.tags.join(', ')} onChange={e=>set('tags',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="VIP, Anunciante, Agência..."/></Field><Field label="Observações" wide><textarea rows={4} value={draft.notes} onChange={e=>set('notes',e.target.value)}/></Field></div></FormSection>
   <FormSection title="Anexos"><label className="crm-upload"><Paperclip size={16}/><span>Adicionar briefing, proposta ou material (até 2 MB por arquivo)</span><input type="file" multiple onChange={async e=>{if(!e.target.files)return;try{const files=await filesToAttachments(e.target.files);set('attachments',[...draft.attachments,...files])}catch(err){setError(err instanceof Error?err.message:'Falha no upload.')}}}/></label>{draft.attachments.length>0&&<div className="crm-attachment-list">{draft.attachments.map(a=><div key={a.id}><span>{a.name}</span><button type="button" onClick={()=>set('attachments',draft.attachments.filter(x=>x.id!==a.id))} aria-label={`Remover ${a.name}`}><Trash2 size={14}/></button></div>)}</div>}</FormSection>
  </div>
  <footer className="crm-modal-foot"><button className="crm-btn secondary" onClick={onClose}>Cancelar</button><button className="crm-btn primary" disabled={busy} onClick={submit}>{busy?'Salvando...':lead?'Salvar alterações':'Criar lead'}</button></footer>
 </section></div>
}
function FormSection({title,children}:{title:string;children:ReactNode}){return <section className="crm-form-section"><h3>{title}</h3>{children}</section>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`crm-field${wide?' wide':''}`}><span>{label}</span>{children}</label>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:readonly (readonly [string,string])[];onChange:(v:string)=>void}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>}
