import { Routes, Route, Navigate, NavLink, Link } from 'react-router-dom'
import { ArrowRight, Bell, BriefcaseBusiness, Building2, CalendarDays, ChevronDown, CircleDollarSign, FileText, Gauge, Globe2, Images, LayoutDashboard, Newspaper, Search, Settings, Tags, Users } from 'lucide-react'
import { portalLogo } from './brandAsset'
import { EditorialContentsAdmin, EditorialPagesAdmin } from '../features/editorial/components/EditorialAdmin'

const contacts = [
  { name: 'Marina Costa', company: 'Norte Produções', status: 'Lead', owner: 'Comercial', value: 'R$ 18.000' },
  { name: 'Rafael Alves', company: 'Estúdio Horizonte', status: 'Cliente', owner: 'Deyvisson', value: 'R$ 32.500' },
  { name: 'Camila Rocha', company: 'Aurora Music', status: 'Negociação', owner: 'Comercial', value: 'R$ 24.000' },
  { name: 'Bruno Lima', company: 'BL Eventos', status: 'Contato', owner: 'Equipe', value: 'R$ 7.500' },
]

const crmNav = [['Visão geral',LayoutDashboard,'/app/crm'],['Contatos',Users,'/app/crm/contatos'],['Pipeline',BriefcaseBusiness,'/app/crm/pipeline'],['Atividades',CalendarDays,'/app/crm/atividades'],['Financeiro',CircleDollarSign,'/app/crm/financeiro']] as const
const cmsNav = [['Visão geral',LayoutDashboard,'/app/site'],['Conteúdos',FileText,'/app/site/conteudos'],['Páginas',Globe2,'/app/site/paginas'],['Mídia',Images,'/app/site/midia'],['Categorias',Tags,'/app/site/categorias'],['Mídia Kit',Newspaper,'/app/site/midia-kit'],['Configurações',Settings,'/app/site/configuracoes']] as const

function Brand(){return <Link to="/" className="brand"><img src={portalLogo} alt="Portal Lander" style={{height:32}}/></Link>}
function AppShell({area,children}:{area:'crm'|'cms',children:React.ReactNode}) { const items=area==='crm'?crmNav:cmsNav; return <div className="app-shell"><aside className="sidebar"><div className="sidebar-head"><Brand/><span>{area==='crm'?'CRM':'SITE'}</span></div><nav>{items.map(([label,Icon,to])=><NavLink key={to} end={to==='/app/crm'||to==='/app/site'} to={to}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/app"><Building2 size={18}/><span>Trocar workspace</span></NavLink></div></aside><div className="workspace"><header className="workspace-top"><div><span className="workspace-name">Portal Lander</span><span className="workspace-context">{area==='crm'?'CRM':'Gerenciador do Site'}</span></div><div className="workspace-actions"><button className="icon-button"><Bell size={18}/></button><button className="account-button"><span>DL</span><div><b>Deyvisson</b><small>Administrador</small></div><ChevronDown size={15}/></button></div></header><main className="workspace-main">{children}</main></div></div> }
function PageHeader({eyebrow,title,action}:{eyebrow:string,title:string,action?:string}) { return <div className="page-header"><div><span>{eyebrow}</span><h1>{title}</h1></div>{action&&<button className="button dark">{action}</button>}</div> }
function Metric({label,value,detail}:{label:string,value:string,detail:string}) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }

function WorkspaceHome() { return <div className="workspace-picker"><div className="picker-copy"><span className="kicker">Portal Lander</span><h1>Escolha onde trabalhar</h1><p>Operação comercial e gerenciamento editorial permanecem separados por responsabilidade.</p></div><div className="workspace-cards"><Link to="/app/crm" className="workspace-card"><div className="workspace-icon"><BriefcaseBusiness/></div><span>Operação</span><h2>CRM</h2><p>Contatos, oportunidades, atividades e visão financeira.</p><ArrowRight/></Link><Link to="/app/site" className="workspace-card"><div className="workspace-icon"><Globe2/></div><span>Conteúdo</span><h2>Gerenciador do Site</h2><p>Fonte administrativa oficial para páginas e conteúdos editoriais.</p><ArrowRight/></Link></div><Link className="back-site" to="/">← Voltar ao site público</Link></div> }
function CrmDashboard() { return <AppShell area="crm"><PageHeader eyebrow="CRM" title="Visão geral" action="Novo contato"/><div className="metrics-grid"><Metric label="Contatos" value="248" detail="+18 este mês"/><Metric label="Leads" value="42" detail="12 qualificados"/><Metric label="Clientes" value="31" detail="5 ativos agora"/></div></AppShell> }
function Contacts() { return <AppShell area="crm"><PageHeader eyebrow="CRM / Contatos" title="Contatos" action="Novo contato"/><div className="toolbar"><div className="searchbox"><Search size={17}/><input placeholder="Buscar contatos..."/></div></div><section className="table-card"><table><thead><tr><th>Contato</th><th>Empresa</th><th>Status</th><th>Responsável</th><th>Valor relacionado</th></tr></thead><tbody>{contacts.map(c=><tr key={c.name}><td><b>{c.name}</b></td><td>{c.company}</td><td><span className="status">{c.status}</span></td><td>{c.owner}</td><td><strong>{c.value}</strong></td></tr>)}</tbody></table></section></AppShell> }
function CmsDashboard() { return <AppShell area="cms"><PageHeader eyebrow="Gerenciador do Site" title="Visão geral"/><div className="panel"><div className="panel-head"><div><span>Arquitetura editorial consolidada</span><h2>Um único fluxo oficial</h2></div></div><p>Páginas e conteúdos usam o mesmo modelo editorial e o mesmo contrato de repositório. A persistência compartilhada permanece bloqueada até existir backend/banco/API real.</p><div style={{display:'flex',gap:12,marginTop:18}}><Link className="button dark" to="/app/site/paginas">Gerenciar páginas</Link><Link className="button outline" to="/app/site/conteudos">Gerenciar conteúdos</Link></div></div></AppShell> }
function CmsPages(){return <AppShell area="cms"><EditorialPagesAdmin/></AppShell>}
function CmsContents(){return <AppShell area="cms"><EditorialContentsAdmin/></AppShell>}
function Placeholder({area,title}:{area:'crm'|'cms',title:string}) { return <AppShell area={area}><PageHeader eyebrow={area==='crm'?'CRM':'Gerenciador do Site'} title={title}/><div className="empty-state"><div><Gauge/></div><h2>Estrutura existente preservada</h2><p>Este módulo não faz parte da consolidação editorial desta etapa.</p></div></AppShell> }

export default function LegacyApp() { return <Routes><Route path="/app" element={<WorkspaceHome/>}/><Route path="/app/crm" element={<CrmDashboard/>}/><Route path="/app/crm/contatos" element={<Contacts/>}/><Route path="/app/crm/pipeline" element={<Placeholder area="crm" title="Pipeline comercial"/>}/><Route path="/app/crm/atividades" element={<Placeholder area="crm" title="Atividades"/>}/><Route path="/app/crm/financeiro" element={<Placeholder area="crm" title="Financeiro"/>}/><Route path="/app/site" element={<CmsDashboard/>}/><Route path="/app/site/conteudos" element={<CmsContents/>}/><Route path="/app/site/paginas" element={<CmsPages/>}/>{['midia','categorias','midia-kit','configuracoes'].map(p=><Route key={p} path={`/app/site/${p}`} element={<Placeholder area="cms" title={({midia:'Media Manager',categorias:'Categorias','midia-kit':'Mídia Kit',configuracoes:'Configurações'} as Record<string,string>)[p]}/>}/>)}<Route path="*" element={<Navigate to="/app" replace/>}/></Routes> }
