import type { ReactNode } from 'react'
import { Routes, Route, Navigate, NavLink, Link } from 'react-router-dom'
import { ArrowRight, Bell, BriefcaseBusiness, Building2, CalendarDays, ChevronDown, CircleDollarSign, FileText, Gauge, Globe2, Images, LayoutDashboard, Newspaper, Search, Settings, Tags, TrendingUp, UserPlus, Users } from 'lucide-react'
import { portalLogo } from './brandAsset'
import { EditorialContentsAdmin, EditorialPagesAdmin } from '../features/editorial/components/EditorialAdmin'
import { editorialReadModel } from '../features/editorial/repository'

const contacts = [
  { name: 'Marina Costa', company: 'Norte Produções', status: 'Lead', owner: 'Comercial', value: 'R$ 18.000' },
  { name: 'Rafael Alves', company: 'Estúdio Horizonte', status: 'Cliente', owner: 'Deyvisson', value: 'R$ 32.500' },
  { name: 'Camila Rocha', company: 'Aurora Music', status: 'Negociação', owner: 'Comercial', value: 'R$ 24.000' },
  { name: 'Bruno Lima', company: 'BL Eventos', status: 'Contato', owner: 'Equipe', value: 'R$ 7.500' },
]

const crmNav = [['Visão geral',LayoutDashboard,'/app/crm'],['Contatos',Users,'/app/crm/contatos'],['Pipeline',BriefcaseBusiness,'/app/crm/pipeline'],['Atividades',CalendarDays,'/app/crm/atividades'],['Financeiro',CircleDollarSign,'/app/crm/financeiro']] as const
const cmsNav = [['Visão geral',LayoutDashboard,'/app/site'],['Conteúdos',FileText,'/app/site/conteudos'],['Páginas',Globe2,'/app/site/paginas'],['Mídia',Images,'/app/site/midia'],['Categorias',Tags,'/app/site/categorias'],['Mídia Kit',Newspaper,'/app/site/midia-kit'],['Configurações',Settings,'/app/site/configuracoes']] as const

function Brand(){return <Link to="/" className="brand"><img src={portalLogo} alt="Portal Lander"/></Link>}
function AppShell({area,children}:{area:'crm'|'cms',children:ReactNode}) {
  const items=area==='crm'?crmNav:cmsNav
  return <div className="app-shell"><aside className="sidebar"><div className="sidebar-head"><Brand/><span>{area==='crm'?'CRM':'SITE'}</span></div><nav>{items.map(([label,Icon,to])=><NavLink key={to} end={to==='/app/crm'||to==='/app/site'} to={to}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/app"><Building2 size={18}/><span>Trocar workspace</span></NavLink></div></aside><div className="workspace"><header className="workspace-top"><div className="workspace-identity"><span className="workspace-name">Portal Lander</span><span className="workspace-divider"/><span className="workspace-context">{area==='crm'?'CRM':'Gerenciador do Site'}</span></div><div className="workspace-actions"><button className="icon-button" type="button" aria-label="Notificações"><Bell size={18}/></button><button className="account-button" type="button"><span>DL</span><div><b>Deyvisson</b><small>Administrador</small></div><ChevronDown size={15}/></button></div></header><main className="workspace-main">{children}</main></div></div>
}
function PageHeader({eyebrow,title,description,action,disabled=false}:{eyebrow:string,title:string,description?:string,action?:string,disabled?:boolean}) { return <div className="admin-page-header"><div className="admin-page-header-copy"><span className="admin-breadcrumb">{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="admin-header-actions"><button className="button dark" disabled={disabled}>{action}</button></div>}</div> }
function Kpi({label,value,detail,icon}:{label:string,value:string,detail:string,icon:ReactNode}) { return <div className="admin-kpi"><div className="admin-kpi-top"><span className="admin-kpi-label">{label}</span><span className="admin-kpi-icon">{icon}</span></div><strong>{value}</strong><small>{detail}</small></div> }
function EmptyModule({title,description}:{title:string,description:string}){return <div className="admin-empty"><div className="admin-empty-icon"><Gauge/></div><h2>{title}</h2><p>{description}</p></div>}

function WorkspaceHome() { return <div className="workspace-picker"><div className="picker-copy"><span className="kicker">Portal Lander · Área interna</span><h1>Escolha onde trabalhar</h1><p>CRM para relacionamento e operação comercial. Gerenciador do Site para conteúdo, páginas e estrutura editorial.</p></div><div className="workspace-cards"><Link to="/app/crm" className="workspace-card"><div className="workspace-icon"><BriefcaseBusiness/></div><span>Relacionamento e vendas</span><h2>CRM</h2><p>Contatos, leads, clientes, pipeline, atividades e visão financeira em um único workspace.</p><ArrowRight/></Link><Link to="/app/site" className="workspace-card"><div className="workspace-icon"><Globe2/></div><span>Conteúdo e publicação</span><h2>Gerenciador do Site</h2><p>Fonte administrativa oficial para páginas, conteúdos e evolução editorial do Portal Lander.</p><ArrowRight/></Link></div><Link className="back-site" to="/">← Voltar ao site público</Link></div> }
function CrmDashboard() { return <AppShell area="crm"><PageHeader eyebrow="CRM / Visão geral" title="Visão geral" description="Acompanhe relacionamento, oportunidades e movimentação comercial do portal." action="Novo contato"/><div className="admin-kpi-grid"><Kpi label="Contatos" value="248" detail="+18 neste mês" icon={<Users size={16}/>}/><Kpi label="Leads" value="42" detail="12 qualificados" icon={<UserPlus size={16}/>}/><Kpi label="Clientes" value="31" detail="5 em atividade" icon={<BriefcaseBusiness size={16}/>}/><Kpi label="Pipeline" value="R$ 82k" detail="Valor em negociação" icon={<TrendingUp size={16}/>}/></div><div className="admin-grid"><section className="admin-card"><div className="admin-card-head"><div><span>Relacionamentos</span><h2>Contatos recentes</h2></div><Link to="/app/crm/contatos" className="button outline">Ver contatos</Link></div>{contacts.map(contact=><div className="compact-row" key={contact.name}><div className="table-avatar">{contact.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</div><div className="grow"><b>{contact.name}</b><small>{contact.company} · {contact.owner}</small></div><span className={`status ${contact.status.toLowerCase().replace('ç','c').replace('ã','a')}`}>{contact.status}</span><strong>{contact.value}</strong></div>)}</section><section className="admin-card"><div className="admin-card-head"><div><span>Próximos passos</span><h2>Atividades</h2></div></div>{['Retornar proposta — Aurora Music','Reunião — Norte Produções','Follow-up — BL Eventos'].map((item,index)=><div className="activity-row" key={item}><span>{['10:30','14:00','16:15'][index]}</span><div><b>{item}</b><small>{['Ligação','Reunião','WhatsApp'][index]}</small></div></div>)}</section></div></AppShell> }
function Contacts() { return <AppShell area="crm"><PageHeader eyebrow="CRM / Contatos" title="Contatos" description="Pessoas e empresas relacionadas comercial ou institucionalmente ao portal." action="Novo contato"/><div className="admin-toolbar"><div className="admin-toolbar-group"><div className="searchbox"><Search size={17}/><input placeholder="Buscar por nome, empresa ou responsável..."/></div><button className="admin-filter" type="button">Todos os status</button></div><span className="admin-breadcrumb">{contacts.length} contatos exibidos</span></div><section className="table-card"><table><thead><tr><th>Contato</th><th>Empresa</th><th>Status</th><th>Responsável</th><th>Valor relacionado</th></tr></thead><tbody>{contacts.map(c=><tr key={c.name}><td><div className="table-primary"><span className="table-avatar">{c.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</span><div><b>{c.name}</b><small>Contato comercial</small></div></div></td><td>{c.company}</td><td><span className={`status ${c.status.toLowerCase().replace('ç','c').replace('ã','a')}`}>{c.status}</span></td><td>{c.owner}</td><td><strong>{c.value}</strong></td></tr>)}</tbody></table></section></AppShell> }
function CmsDashboard() {
  const pages=editorialReadModel.pages
  const contents=editorialReadModel.contents
  const published=contents.filter(item=>item.status==='published'&&item.active).length
  return <AppShell area="cms"><PageHeader eyebrow="Gerenciador do Site / Visão geral" title="Visão geral" description="Gerencie a arquitetura editorial e acompanhe o conteúdo que alimenta o portal público."/><div className="admin-kpi-grid"><Kpi label="Páginas" value={String(pages.length)} detail="Estruturas cadastradas" icon={<Globe2 size={16}/>}/><Kpi label="Conteúdos" value={String(contents.length)} detail="Itens no catálogo atual" icon={<FileText size={16}/>}/><Kpi label="Publicados" value={String(published)} detail="Visíveis no portal" icon={<Newspaper size={16}/>}/><Kpi label="No menu" value={String(pages.filter(page=>page.showInMainMenu).length)} detail="Entradas editoriais" icon={<LayoutDashboard size={16}/>} /></div><div className="admin-grid"><section className="admin-card"><div className="admin-card-head"><div><span>Arquitetura editorial</span><h2>Fonte administrativa consolidada</h2></div></div><p>Páginas e conteúdos utilizam o mesmo modelo e o mesmo contrato de repositório. A estrutura pública já consome essa fonte editorial única.</p><div className="admin-actions-row"><Link className="button dark" to="/app/site/paginas">Gerenciar páginas</Link><Link className="button outline" to="/app/site/conteudos">Gerenciar conteúdos</Link></div></section><section className="admin-card"><div className="admin-card-head"><div><span>Infraestrutura</span><h2>Persistência</h2></div></div><p>O repositório ainda não possui backend, banco ou API editorial. Escritas permanecem bloqueadas para não simular persistência.</p></section></div></AppShell>
}
function CmsPages(){return <AppShell area="cms"><EditorialPagesAdmin/></AppShell>}
function CmsContents(){return <AppShell area="cms"><EditorialContentsAdmin/></AppShell>}
function Placeholder({area,title}:{area:'crm'|'cms',title:string}) { return <AppShell area={area}><PageHeader eyebrow={area==='crm'?`CRM / ${title}`:`Gerenciador do Site / ${title}`} title={title} description="A estrutura desta área foi preservada e será implementada sobre o mesmo sistema visual e arquitetural."/><EmptyModule title={`${title} ainda não implementado`} description="Nenhuma funcionalidade falsa foi adicionada. Este módulo será conectado à infraestrutura real quando sua implementação funcional entrar no escopo."/></AppShell> }

export default function LegacyApp() { return <Routes><Route path="/app" element={<WorkspaceHome/>}/><Route path="/app/crm" element={<CrmDashboard/>}/><Route path="/app/crm/contatos" element={<Contacts/>}/><Route path="/app/crm/pipeline" element={<Placeholder area="crm" title="Pipeline comercial"/>}/><Route path="/app/crm/atividades" element={<Placeholder area="crm" title="Atividades"/>}/><Route path="/app/crm/financeiro" element={<Placeholder area="crm" title="Financeiro"/>}/><Route path="/app/site" element={<CmsDashboard/>}/><Route path="/app/site/conteudos" element={<CmsContents/>}/><Route path="/app/site/paginas" element={<CmsPages/>}/>{['midia','categorias','midia-kit','configuracoes'].map(p=><Route key={p} path={`/app/site/${p}`} element={<Placeholder area="cms" title={({midia:'Media Manager',categorias:'Categorias','midia-kit':'Mídia Kit',configuracoes:'Configurações'} as Record<string,string>)[p]}/>}/>)}<Route path="*" element={<Navigate to="/app" replace/>}/></Routes> }
