import {AlertTriangle,CheckCircle2,Database,Download,Loader2,Upload,X} from 'lucide-react'
import {useMemo,useRef,useState} from 'react'
import {AdminShell} from '../../shared/internal/AdminUi'
import {CRM_WORKSPACE_NAV} from '../../shared/internal/adminNavigation'
import {useModalA11y} from '../../shared/internal/useModalA11y'
import type {ImportPreview,ReportDefinition,ReportEntity} from './domain'
import {reportsRepository} from './repository'
import './reports.css'

const XLSX_MIME='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

export default function ReportsPage(){
 const [seed]=useState(()=>reportsRepository.snapshot()),[selected,setSelected]=useState<ReportDefinition|null>(null),[exporting,setExporting]=useState<string|null>(null),[notice,setNotice]=useState('')
 const definitions=useMemo(()=>new Map(seed.definitions.map(x=>[x.tableName,x])),[seed.definitions])
 const entities=seed.entities.filter(x=>x.reportable)
 const runExport=(entity:ReportEntity)=>{const def=definitions.get(entity.tableName);if(!def?.supportsExport)return;setExporting(entity.tableName);window.setTimeout(()=>{const rows=[def.exportableColumns.join('\t'),def.exportableColumns.map(column=>entity.columns.find(x=>x.name===column)?.label??column).join('\t')].join('\n');const blob=new Blob([rows],{type:XLSX_MIME});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${entity.tableName}.xlsx`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setExporting(null);setNotice('Exportação concluída.')},260)}
 return <AdminShell area="reports" items={CRM_WORKSPACE_NAV} header={{title:'Relatórios',description:'Exportação e importação por entidade — dirigido pelo backend'}}><section className="reports-page">
  {notice&&<div className="reports-notice" role="status"><CheckCircle2 size={14}/><span>{notice}</span><button type="button" onClick={()=>setNotice('')} aria-label="Fechar"><X size={14}/></button></div>}
  {entities.length===0?<div className="reports-empty">Nenhuma entidade reportável disponível.</div>:<div className="reports-entity-list">{entities.map(entity=>{const def=definitions.get(entity.tableName),unavailable=!def;return <article className="reports-entity-row" key={entity.tableName} data-testid={`entity-row-${entity.tableName}`}><div className="reports-entity-icon"><Database size={14}/></div><div className="reports-entity-copy"><strong>{entity.label||entity.tableName}</strong>{unavailable&&<small data-testid={`unavailable-${entity.tableName}`}>Temporariamente indisponível</small>}</div><div className="reports-entity-actions"><button type="button" className="reports-outline" disabled={!def?.supportsImport} onClick={()=>def&&setSelected(def)}><Upload size={13}/>Importar</button><button type="button" className="reports-outline" disabled={!def?.supportsExport||exporting===entity.tableName} onClick={()=>runExport(entity)}>{exporting===entity.tableName?<Loader2 className="reports-spin" size={13}/>:<Download size={13}/>}Exportar</button></div></article>})}</div>}
  {selected&&<ImportDialog definition={selected} previewSeed={seed.importPreview[selected.tableName]} onClose={()=>setSelected(null)} onImported={()=>{setNotice('Importação concluída.');setSelected(null)}}/>}
 </section></AdminShell>
}

function ImportDialog({definition,previewSeed,onClose,onImported}:{definition:ReportDefinition;previewSeed?:ImportPreview;onClose:()=>void;onImported:()=>void}){
 const fileRef=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<ImportPreview|null>(null),[validating,setValidating]=useState(false),[committing,setCommitting]=useState(false),[downloading,setDownloading]=useState(false),[error,setError]=useState('')
 const dialogRef=useModalA11y(onClose)
 const canCommit=Boolean(preview&&preview.invalidRows===0&&preview.errors.length===0&&preview.validRows>0)
 const downloadTemplate=()=>{setDownloading(true);window.setTimeout(()=>{const content=definition.importableColumns.join('\t');const blob=new Blob([content],{type:XLSX_MIME}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${definition.tableName}_template.xlsx`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setDownloading(false)},220)}
 const validate=()=>{if(!file)return;setError('');if(!/\.xlsx$/i.test(file.name)){setError('Apenas arquivos .xlsx são aceitos.');return}setValidating(true);window.setTimeout(()=>{setPreview(previewSeed??{totalRows:1,validRows:1,invalidRows:0,errors:[],warnings:[]});setValidating(false)},320)}
 const commit=()=>{if(!canCommit)return;setCommitting(true);window.setTimeout(()=>{setCommitting(false);onImported()},320)}
 return <div className="reports-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section ref={dialogRef} tabIndex={-1} className="reports-import-dialog" role="dialog" aria-modal="true" aria-labelledby="reports-import-title"><header><div><h2 id="reports-import-title"><Upload size={16}/>Importar {definition.entityName}</h2></div><button type="button" className="reports-icon" onClick={onClose} aria-label="Fechar"><X size={17}/></button></header><div className="reports-import-body"><div className="reports-template-row"><button type="button" onClick={downloadTemplate} disabled={downloading}>{downloading?<Loader2 className="reports-spin" size={14}/>:<Download size={14}/>}Baixar template</button></div><button type="button" className="reports-dropzone" onClick={()=>fileRef.current?.click()} aria-describedby="reports-file-help"><Upload size={28}/><strong>{file?file.name:'Clique para selecionar o arquivo'}</strong><small id="reports-file-help">XLSX</small></button><input ref={fileRef} type="file" accept=".xlsx" hidden onChange={e=>{const next=e.target.files?.[0]??null;if(next&&!/\.xlsx$/i.test(next.name)){setError('Apenas arquivos .xlsx são aceitos.');e.target.value='';return}setFile(next);setPreview(null);setError('')}}/>{error&&<div className="reports-inline-error" role="alert"><AlertTriangle size={13}/>{error}</div>}{preview&&<div className="reports-preview"><div className="reports-preview-counts"><span>Total: <b>{preview.totalRows}</b></span><span className="ok">Válidas: <b>{preview.validRows}</b></span><span className="bad">Inválidas: <b>{preview.invalidRows}</b></span></div>{preview.errors.map((item,i)=><p className="bad" key={`e-${i}`}><AlertTriangle size={12}/>{item}</p>)}{preview.warnings.map((item,i)=><p className="warn" key={`w-${i}`}>⚠ {item}</p>)}</div>}</div><footer><button type="button" className="reports-outline" onClick={onClose}>Cancelar</button><button type="button" className="reports-outline" onClick={validate} disabled={!file||validating}>{validating&&<Loader2 className="reports-spin" size={13}/>}Validar</button><button type="button" className="reports-primary" onClick={commit} disabled={!canCommit||committing}>{committing?<Loader2 className="reports-spin" size={13}/>:<CheckCircle2 size={13}/>}Importar</button></footer></section></div>
}
