import { Copy, Download, Pencil, Search, Trash2, Upload, X } from 'lucide-react'
import { useMemo, useRef, useState, type ChangeEvent } from 'react'
import * as XLSX from 'xlsx'
import { CRM_NAV } from '../../../shared/internal/adminNavigation'
import { AdminShell } from '../../../shared/internal/AdminUi'

type Variable={id:string;name:string;alias:string;internalName:string;field:string;placeholder:string}
const INITIAL:Variable[]=[
  {id:'var-001',name:'Razão Social da Empresa',alias:'Empresa',internalName:'EMPRESA',field:'RAZAO_SOCIAL',placeholder:'{{EMPRESA.RAZAO_SOCIAL}}'},
  {id:'var-002',name:'Nome do Cliente',alias:'Cliente',internalName:'CLIENTE',field:'NOME',placeholder:'{{CLIENTE.NOME}}'},
  {id:'var-003',name:'Número do Contrato',alias:'Contrato',internalName:'CONTRATO',field:'NUMERO',placeholder:'{{CONTRATO.NUMERO}}'},
  {id:'var-004',name:'Valor do Contrato',alias:'Contrato',internalName:'CONTRATO',field:'VALOR',placeholder:'{{CONTRATO.VALOR}}'},
]
const PAGE_SIZE=10

export function ContractVariablesPage(){
  const [variables,setVariables]=useState(INITIAL)
  const [query,setQuery]=useState('')
  const [page,setPage]=useState(0)
  const [selected,setSelected]=useState<string[]>([])
  const [editing,setEditing]=useState<Variable|null>(null)
  const [creating,setCreating]=useState(false)
  const [draft,setDraft]=useState({name:'',alias:'',internalName:'',field:''})
  const inputRef=useRef<HTMLInputElement>(null)
  const filtered=useMemo(()=>variables.filter(variable=>`${variable.name} ${variable.alias} ${variable.internalName} ${variable.field} ${variable.placeholder}`.toLowerCase().includes(query.toLowerCase())),[variables,query])
  const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const safePage=Math.min(page,pageCount-1);const pageItems=filtered.slice(safePage*PAGE_SIZE,safePage*PAGE_SIZE+PAGE_SIZE)
  const allSelected=pageItems.length>0&&pageItems.every(variable=>selected.includes(variable.id))
  const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'')
  const save=()=>{const internalName=normalize(draft.internalName||draft.alias||'VARIAVEL');const field=normalize(draft.field||draft.name);const variable={id:editing?.id??`var-${Date.now()}`,name:draft.name||field,alias:draft.alias||internalName,internalName,field,placeholder:`{{${internalName}.${field}}}`};setVariables(items=>editing?items.map(item=>item.id===editing.id?variable:item):[variable,...items]);setEditing(null);setCreating(false);setDraft({name:'',alias:'',internalName:'',field:''})}
  const exportXlsx=()=>{const data=variables.map(variable=>({Nome:variable.name,Alias:variable.alias,'Nomenclatura Interna':variable.internalName,Campo:variable.field,Placeholder:variable.placeholder}));const sheet=XLSX.utils.json_to_sheet(data);const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Variaveis');XLSX.writeFile(book,'variaveis-contratos.xlsx')}
  const importXlsx=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const buffer=await file.arrayBuffer();const workbook=XLSX.read(buffer);const sheet=workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,string>>(sheet);const imported=rows.map((row,index)=>{const name=row.Nome||row.name||`Variável ${index+1}`;const alias=row.Alias||row.alias||'VARIAVEL';const internalName=normalize(row['Nomenclatura Interna']||row.internalName||alias);const field=normalize(row.Campo||row.field||name);return{id:`var-import-${Date.now()}-${index}`,name,alias,internalName,field,placeholder:row.Placeholder||`{{${internalName}.${field}}}`}});setVariables(items=>[...imported,...items]);event.target.value=''}
  return <AdminShell area="crm" items={CRM_NAV} header={{title:'Variáveis de Template',description:'Crie, organize e reutilize placeholders em qualquer contrato'}} headerAction={{label:'Nova Variável',onClick:()=>{setCreating(true);setEditing(null);setDraft({name:'',alias:'',internalName:'',field:''})}}}>
    <div className="zip-stack contracts-variable-registry">
      <div className="contracts-category-toolbar"><label className="zip-search"><Search size={14}/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}} placeholder="Pesquisar variáveis..."/></label><div className="contracts-inline-actions"><input ref={inputRef} hidden type="file" accept=".xlsx,.xls" onChange={importXlsx}/><button className="zip-button secondary" type="button" onClick={()=>inputRef.current?.click()}><Upload size={14}/> Importar</button><button className="zip-button secondary" type="button" onClick={exportXlsx}><Download size={14}/> Exportar</button></div></div>
      <section className="zip-panel"><header className="zip-panel-head"><div><h2>Lista de Variáveis</h2><p>{filtered.length} variável(is) cadastrada(s)</p></div>{selected.length>0&&<button className="zip-button danger" type="button" onClick={()=>{setVariables(items=>items.filter(variable=>!selected.includes(variable.id)));setSelected([])}}><Trash2 size={14}/> Excluir ({selected.length})</button>}</header><div className="zip-table-wrap"><table className="zip-table"><thead><tr><th><input type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?selected.filter(id=>!pageItems.some(variable=>variable.id===id)):[...new Set([...selected,...pageItems.map(variable=>variable.id)])])}/></th><th>Nome</th><th>Alias</th><th>Nomenclatura Interna</th><th>Campo</th><th>Placeholder</th><th className="actions-col">Ações</th></tr></thead><tbody>{pageItems.length?pageItems.map(variable=><tr key={variable.id}><td><input type="checkbox" checked={selected.includes(variable.id)} onChange={()=>setSelected(ids=>ids.includes(variable.id)?ids.filter(id=>id!==variable.id):[...ids,variable.id])}/></td><td><strong>{variable.name}</strong></td><td>{variable.alias}</td><td><code>{variable.internalName}</code></td><td><code>{variable.field}</code></td><td><code>{variable.placeholder}</code></td><td className="actions-col"><div className="contracts-row-inline-actions"><button type="button" title="Copiar placeholder" onClick={()=>navigator.clipboard?.writeText(variable.placeholder)}><Copy size={14}/></button><button type="button" title="Editar" onClick={()=>{setEditing(variable);setCreating(true);setDraft({name:variable.name,alias:variable.alias,internalName:variable.internalName,field:variable.field})}}><Pencil size={14}/></button><button type="button" title="Excluir" onClick={()=>setVariables(items=>items.filter(item=>item.id!==variable.id))}><Trash2 size={14}/></button></div></td></tr>):<tr><td colSpan={7} className="contracts-empty-row">Nenhuma variável encontrada.</td></tr>}</tbody></table></div>{filtered.length>0&&<footer className="contracts-pagination"><span>Página {safePage+1} de {pageCount}</span><button className="zip-button secondary" type="button" disabled={safePage===0} onClick={()=>setPage(value=>Math.max(0,value-1))}>Anterior</button><button className="zip-button secondary" type="button" disabled={safePage>=pageCount-1} onClick={()=>setPage(value=>Math.min(pageCount-1,value+1))}>Próxima</button></footer>}</section>
    </div>
    {creating&&<div className="reference-modal-backdrop"><section className="reference-modal"><header className="reference-modal-head"><div><span>VARIÁVEIS</span><h2>{editing?'Editar Variável':'Nova Variável'}</h2></div><button className="reference-modal-close" type="button" onClick={()=>{setCreating(false);setEditing(null)}}><X size={17}/></button></header><div className="reference-modal-body reference-form"><div className="reference-form-grid"><label><span>Nome *</span><input value={draft.name} onChange={event=>setDraft(value=>({...value,name:event.target.value}))}/></label><label><span>Alias</span><input value={draft.alias} onChange={event=>setDraft(value=>({...value,alias:event.target.value}))}/></label><label><span>Nomenclatura Interna</span><input value={draft.internalName} onChange={event=>setDraft(value=>({...value,internalName:event.target.value}))}/></label><label><span>Campo</span><input value={draft.field} onChange={event=>setDraft(value=>({...value,field:event.target.value}))}/></label></div></div><footer className="reference-modal-footer"><button className="zip-button secondary" type="button" onClick={()=>{setCreating(false);setEditing(null)}}>Cancelar</button><button className="zip-button" type="button" onClick={save}>Salvar</button></footer></section></div>}
  </AdminShell>
}
