import { Building2, Check, ChevronLeft, ChevronRight, ClipboardList, Eye, FileText, Music, PenLine, Plus, Trash2, User, UserPlus, Users, Variable, X } from 'lucide-react'
import { useState } from 'react'
import { ContractA4Preview } from './ContractA4Preview'

export type ContractWizardPayload={title:string;client:string;type:string;platform:string;status:string;start:string;end:string;value:number;signers:{name:string;email:string;order:number;platform:string}[]}

type Party={tipo:'pf'|'pj'|'artista';nome:string;email:string;documento:string}
type Signer={name:string;email:string;order:number;platform:string}
const STEPS=[['Template','Escolha o modelo',FileText],['Partes','Defina contratantes',Users],['Variáveis','Preencha os campos',Variable],['Documento','Revise o conteúdo',Eye],['Signatários','Configure assinaturas',UserPlus],['Revisão','Finalize o contrato',ClipboardList]] as const

export function ContratoWizard({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(payload:ContractWizardPayload)=>void}){
  const [step,setStep]=useState(1)
  const [template,setTemplate]=useState('Contrato de Prestação de Serviços')
  const [category,setCategory]=useState('Agenciamento')
  const [parties,setParties]=useState<Party[]>([{tipo:'pj',nome:'Portal Lander',email:'',documento:''},{tipo:'pf',nome:'',email:'',documento:''}])
  const [contractNumber,setContractNumber]=useState('CTR-2026-004')
  const [value,setValue]=useState('')
  const [content,setContent]=useState('')
  const [signers,setSigners]=useState<Signer[]>([{name:'',email:'',order:1,platform:'Autentique'}])
  const [title,setTitle]=useState('')
  const [start,setStart]=useState('')
  const [end,setEnd]=useState('')
  const [status,setStatus]=useState('Rascunho')
  const [notes,setNotes]=useState('')
  if(!open)return null
  const next=()=>setStep(v=>Math.min(6,v+1));const prev=()=>setStep(v=>Math.max(1,v-1))
  const addSigner=()=>setSigners(items=>[...items,{name:'',email:'',order:items.length+1,platform:'Autentique'}])
  const submit=()=>onSave({title:title||`${template} · ${parties[1]?.nome||'Novo cliente'}`,client:parties[1]?.nome||'—',type:category,platform:signers[0]?.platform||'Sem plataforma',status,start:start||'2026-08-29',end:end||'2026-08-29',value:Number(value||0),signers})
  return <div className="reference-modal-backdrop"><section className="reference-modal contracts-wizard-modal"><header className="reference-modal-head"><div><span>CONTRATOS</span><h2>Novo Contrato</h2></div><button className="reference-modal-close" type="button" onClick={onClose}><X size={17}/></button></header><div className="contracts-wizard-layout"><aside className="contracts-wizard-steps">{STEPS.map(([label,description,Icon],index)=><button key={label} className={step===index+1?'active':''} type="button" onClick={()=>setStep(index+1)}><span>{step>index+1?<Check size={12}/>:index+1}</span><div><strong><Icon size={12}/> {label}</strong><small>{description}</small></div></button>)}</aside><div className="reference-modal-body reference-form contracts-wizard-content">
    {step===1&&<section className="reference-form-section"><h3>Escolha um Template</h3><div className="contracts-template-choice"><button className="active" type="button" onClick={()=>setTemplate('Contrato de Prestação de Serviços')}><FileText size={18}/><strong>Contrato de Prestação de Serviços</strong><small>Modelo padrão para serviços e projetos</small></button><button type="button" onClick={()=>setTemplate('Contrato de Licenciamento')}><Music size={18}/><strong>Contrato de Licenciamento</strong><small>Licenciamento de conteúdo e direitos</small></button></div><div className="reference-form-grid"><label><span>Categoria</span><select value={category} onChange={e=>setCategory(e.target.value)}><option>Agenciamento</option><option>Distribuição</option><option>Licenciamento</option><option>Edição</option></select></label><label><span>Número do contrato</span><input value={contractNumber} onChange={e=>setContractNumber(e.target.value)}/></label></div></section>}
    {step===2&&<section className="reference-form-section"><h3>Partes do Contrato</h3>{parties.map((party,index)=><div className="contracts-party-card" key={index}><div className="contracts-party-title"><span>{party.tipo==='pj'?<Building2 size={15}/>:party.tipo==='artista'?<Music size={15}/>:<User size={15}/>}</span><strong>{index===0?'CONTRATANTE':'CONTRATADO'}</strong></div><div className="reference-form-grid"><label><span>Tipo</span><select value={party.tipo} onChange={e=>setParties(items=>items.map((p,i)=>i===index?{...p,tipo:e.target.value as Party['tipo']}:p))}><option value="pf">Pessoa Física</option><option value="pj">Pessoa Jurídica</option><option value="artista">Artista</option></select></label><label><span>Nome / Razão Social</span><input value={party.nome} onChange={e=>setParties(items=>items.map((p,i)=>i===index?{...p,nome:e.target.value}:p))}/></label><label><span>E-mail</span><input value={party.email} onChange={e=>setParties(items=>items.map((p,i)=>i===index?{...p,email:e.target.value}:p))}/></label><label><span>CPF / CNPJ</span><input value={party.documento} onChange={e=>setParties(items=>items.map((p,i)=>i===index?{...p,documento:e.target.value}:p))}/></label></div></div>)}</section>}
    {step===3&&<section className="reference-form-section"><h3>Variáveis do Contrato</h3><div className="reference-form-grid"><label><span>CONTRATO.NUMERO</span><input value={contractNumber} onChange={e=>setContractNumber(e.target.value)}/></label><label><span>CONTRATO.VALOR</span><input type="number" value={value} onChange={e=>setValue(e.target.value)}/></label><label className="wide"><span>CONTRATANTE.NOME</span><input value={parties[0]?.nome||''} readOnly/></label><label className="wide"><span>CONTRATADO.NOME</span><input value={parties[1]?.nome||''} readOnly/></label></div></section>}
    {step===4&&<section className="reference-form-section"><h3>Documento</h3><label><span>Conteúdo do Contrato</span><textarea rows={14} value={content} onChange={e=>setContent(e.target.value)} placeholder="Edite o conteúdo do contrato ou mantenha o conteúdo do template..."/></label><ContractA4Preview title={title||template}><p>{content||`Contrato ${contractNumber} celebrado entre ${parties[0]?.nome||'CONTRATANTE'} e ${parties[1]?.nome||'CONTRATADO'}.`}</p></ContractA4Preview></section>}
    {step===5&&<section className="reference-form-section"><div className="contracts-section-heading"><div><h3>Signatários</h3><p>Configure quem deve assinar e em qual ordem.</p></div><button className="zip-button secondary" type="button" onClick={addSigner}><Plus size={14}/> Adicionar Signatário</button></div>{signers.map((signer,index)=><div className="contracts-signer-card" key={index}><div className="reference-form-grid"><label><span>Nome</span><input value={signer.name} onChange={e=>setSigners(items=>items.map((s,i)=>i===index?{...s,name:e.target.value}:s))}/></label><label><span>E-mail</span><input value={signer.email} onChange={e=>setSigners(items=>items.map((s,i)=>i===index?{...s,email:e.target.value}:s))}/></label><label><span>Ordem</span><input type="number" min={1} value={signer.order} onChange={e=>setSigners(items=>items.map((s,i)=>i===index?{...s,order:Number(e.target.value)}:s))}/></label><label><span>Plataforma</span><select value={signer.platform} onChange={e=>setSigners(items=>items.map((s,i)=>i===index?{...s,platform:e.target.value}:s))}><option>Sem plataforma</option><option>Autentique</option><option>Clicksign</option><option>DocuSign</option></select></label></div>{signers.length>1&&<button className="zip-button danger" type="button" onClick={()=>setSigners(items=>items.filter((_,i)=>i!==index))}><Trash2 size={13}/> Remover</button>}</div>)}</section>}
    {step===6&&<section className="reference-form-section"><h3>Revisão</h3><div className="reference-form-grid"><label className="wide"><span>Título do Contrato *</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Contrato de Agenciamento · Artista"/></label><label><span>Data de Início *</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><span>Data de Término</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option>Rascunho</option><option>Pendente</option><option>Aguardando Assinatura</option><option>Assinado</option><option>Vigente</option></select></label><label className="wide"><span>Observações</span><textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><ContractA4Preview title={title||template}><p><strong>{contractNumber}</strong></p><p>Partes: {parties.map(p=>p.nome||'Não informado').join(' × ')}</p><p>Valor: {value?Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Não informado'}</p><p>{content||'Conteúdo do template selecionado.'}</p></ContractA4Preview></section>}
  </div></div><footer className="reference-modal-footer"><button className="zip-button secondary" type="button" onClick={onClose}>Cancelar</button><span className="contracts-wizard-footer-spacer"/>{step>1&&<button className="zip-button secondary" type="button" onClick={prev}><ChevronLeft size={14}/> Voltar</button>}{step<6?<button className="zip-button" type="button" onClick={next}>Continuar <ChevronRight size={14}/></button>:<><button className="zip-button secondary" type="button" onClick={submit}><FileText size={14}/> Salvar Rascunho</button><button className="zip-button" type="button" onClick={submit}><PenLine size={14}/> Criar Contrato</button></>}</footer></section></div>
}
