import { Calendar, DollarSign, Download, Eye, FileText, History, PenLine, Send, Users, X } from 'lucide-react'
import { useState } from 'react'
import { ContractA4Preview } from './ContractA4Preview'
import { DocumentTimeline } from './DocumentTimeline'
import { SigningPlatformBadge } from './SigningPlatformBadge'
import { SendForSigningDialog } from './SendForSigningDialog'

export type ViewContract={id:string;title:string;client:string;type:string;platform:string;status:string;start:string;end:string;value:number;signers?:{name:string;email:string;order:number;platform:string}[]}

const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const date=(value:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—'

export function ContratoViewModal({open,contract,onClose,onEdit,onSigningUpdate}:{open:boolean;contract:ViewContract|null;onClose:()=>void;onEdit:()=>void;onSigningUpdate:(provider:string)=>void}){
  const [tab,setTab]=useState<'resumo'|'assinatura'|'documento'|'historico'>('resumo')
  const [signing,setSigning]=useState(false)
  if(!open||!contract)return null
  const signers=contract.signers?.length?contract.signers:[{name:contract.client,email:'',order:1,platform:contract.platform}]
  return <><div className="reference-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="reference-modal contracts-view-modal"><header className="reference-modal-head"><div><span>CONTRATO</span><h2>{contract.title}</h2><div className="contracts-view-head-meta"><span className="zip-badge">{contract.type}</span><span className={`zip-badge ${['Vigente','Ativo','Assinado'].includes(contract.status)?'zip-badge-success':contract.status==='Aguardando Assinatura'?'zip-badge-warning':''}`}>{contract.status}</span><SigningPlatformBadge platform={contract.platform}/></div></div><button className="reference-modal-close" type="button" onClick={onClose}><X size={17}/></button></header><div className="zip-tabs contracts-view-tabs"><button className={tab==='resumo'?'active':''} onClick={()=>setTab('resumo')}><Eye size={14}/> Resumo</button><button className={tab==='assinatura'?'active':''} onClick={()=>setTab('assinatura')}><PenLine size={14}/> Assinatura</button><button className={tab==='documento'?'active':''} onClick={()=>setTab('documento')}><FileText size={14}/> Documento</button><button className={tab==='historico'?'active':''} onClick={()=>setTab('historico')}><History size={14}/> Histórico</button></div><div className="reference-modal-body contracts-view-body">
    {tab==='resumo'&&<div className="contracts-view-summary"><section className="contracts-detail-grid"><article><Calendar size={16}/><span>Período</span><strong>{date(contract.start)} — {date(contract.end)}</strong></article><article><DollarSign size={16}/><span>Valor</span><strong>{contract.value?money(contract.value):'—'}</strong></article><article><Users size={16}/><span>Cliente / Artista</span><strong>{contract.client}</strong></article><article><FileText size={16}/><span>Tipo</span><strong>{contract.type}</strong></article></section><section className="reference-form-section"><h3>Informações do Contrato</h3><div className="reference-form-grid contracts-readonly-grid"><label><span>Título</span><div>{contract.title}</div></label><label><span>Status</span><div>{contract.status}</div></label><label><span>Plataforma</span><div>{contract.platform}</div></label><label><span>Identificador</span><div>{contract.id}</div></label></div></section></div>}
    {tab==='assinatura'&&<div className="contracts-signature-view"><section className="reference-form-section"><div className="contracts-section-heading"><div><h3>Processo de Assinatura</h3><p>Acompanhe plataforma, signatários e andamento.</p></div><button className="zip-button" type="button" onClick={()=>setSigning(true)}><Send size={14}/> Enviar para Assinatura</button></div><div className="contracts-signing-status"><div><span>Plataforma</span><SigningPlatformBadge platform={contract.platform}/></div><div><span>Status</span><strong>{contract.status}</strong></div></div></section><section className="reference-form-section"><h3>Signatários</h3><div className="contracts-signers-review">{signers.map((signer,index)=><div key={`${signer.email}-${index}`}><span>{signer.order}</span><div><strong>{signer.name||'Sem nome'}</strong><small>{signer.email||'E-mail não informado'} · {signer.platform}</small></div></div>)}</div></section><section className="reference-form-section"><h3>Linha do Tempo</h3><DocumentTimeline/></section></div>}
    {tab==='documento'&&<div><div className="contracts-document-actions"><button className="zip-button secondary" type="button"><Download size={14}/> Baixar Documento</button></div><ContractA4Preview title={contract.title}><p>CONTRATO Nº {contract.id.toUpperCase()}</p><p>Entre <strong>Portal Lander</strong> e <strong>{contract.client}</strong>, fica estabelecido o presente contrato de {contract.type.toLowerCase()}.</p><h2>CLÁUSULA PRIMEIRA — DO OBJETO</h2><p>O objeto deste contrato segue os termos acordados entre as partes e as informações registradas no sistema.</p><h2>CLÁUSULA SEGUNDA — DA VIGÊNCIA</h2><p>Vigência de {date(contract.start)} até {date(contract.end)}, pelo valor de {contract.value?money(contract.value):'valor a definir'}.</p></ContractA4Preview></div>}
    {tab==='historico'&&<section className="reference-form-section"><h3>Histórico do Documento</h3><DocumentTimeline items={[{label:'Contrato criado',detail:'Registro criado no módulo Contratos',date:'Sistema',state:'done'},{label:'Última atualização',detail:`Status atual: ${contract.status}`,date:'Atual',state:'done'},{label:'Assinatura',detail:contract.status==='Assinado'?'Processo concluído':'Processo ainda não concluído',state:contract.status==='Assinado'?'done':'pending'}]}/></section>}
  </div><footer className="reference-modal-footer"><button className="zip-button secondary" type="button" onClick={onClose}>Fechar</button><button className="zip-button" type="button" onClick={onEdit}>Editar Contrato</button></footer></section></div><SendForSigningDialog open={signing} title={contract.title} signers={signers} onClose={()=>setSigning(false)} onSend={provider=>{onSigningUpdate(provider);setSigning(false)}}/></>
}
