import { FileText, MoreHorizontal, Plus, Save, Search, Sparkles, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { CRM_NAV } from '../../../shared/internal/adminNavigation'
import { AdminShell } from '../../../shared/internal/AdminUi'

type Template={id:string;name:string;description:string;type:'semantico'|'padrao';active:boolean;variables:number;createdAt:string;content?:string;category?:string}
const INITIAL:Template[]=[
  {id:'tpl-1',name:'Contrato de Publicidade',description:'Modelo para campanhas e entregas publicitárias.',type:'semantico',active:true,variables:12,createdAt:'2026-08-20',category:'Comercial'},
  {id:'tpl-2',name:'Prestação de Serviços',description:'Modelo padrão para prestação de serviços.',type:'padrao',active:true,variables:8,createdAt:'2026-08-18',category:'Prestação de Serviços'},
  {id:'tpl-3',name:'Parceria Comercial',description:'Modelo para parcerias e permutas.',type:'semantico',active:false,variables:10,createdAt:'2026-08-11',category:'Comercial'},
]
const VARS=['{{EMPRESA.RAZAO_SOCIAL}}','{{EMPRESA.CNPJ}}','{{CLIENTE.NOME}}','{{CLIENTE.DOCUMENTO}}','{{CONTRATO.NUMERO}}','{{CONTRATO.VALOR}}']

export function TemplatesContractsPage(){
  const [templates,setTemplates]=useState<Template[]>(INITIAL)
  const [query,setQuery]=useState('')
  const [type,setType]=useState<'all'|'semantico'|'padrao'>('all')
  const [status,setStatus]=useState<'all'|'ativo'|'inativo'>('all')
  const [workspace,setWorkspace]=useState(false)
  const [activeTab,setActiveTab]=useState<'template'|'variaveis'|'categorias'|'preview'>('template')
  const [draft,setDraft]=useState({name:'',category:'',content:'',headerImage:'',footerImage:''})
  const [varSearch,setVarSearch]=useState('')
  const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('pt-BR');return templates.filter(t=>(!q||`${t.name} ${t.description}`.toLocaleLowerCase('pt-BR').includes(q))&&(type==='all'||t.type===type)&&(status==='all'||(status==='ativo'?t.active:!t.active)))},[templates,query,type,status])
  const semanticCount=templates.filter(t=>t.type==='semantico').length
  const activeCount=templates.filter(t=>t.active).length
  const mapped=templates.reduce((sum,t)=>sum+t.variables,0)
  const openWorkspace=()=>{setDraft({name:'',category:'',content:'',headerImage:'',footerImage:''});setActiveTab('template');setWorkspace(true)}
  const insertVar=(value:string)=>setDraft(v=>({...v,content:`${v.content}${v.content&&!v.content.endsWith(' ')?' ':''}${value}`}))
  const save=()=>{if(!draft.name.trim())return;setTemplates(items=>[{id:`tpl-${Date.now()}`,name:draft.name.trim(),description:'Template criado no workspace contratual.',type:'semantico',active:true,variables:VARS.filter(v=>draft.content.includes(v)).length,createdAt:new Date().toISOString(),content:draft.content,category:draft.category||'Comercial'},...items]);setWorkspace(false)}
  return <AdminShell area="crm" items={CRM_NAV} header={{title:'Templates de Contrato',description:'Motor semântico de templates contratuais'}}>
    <div className="zip-stack contracts-page">
      <div className="zip-kpi-grid four"><article className="zip-metric"><div className="zip-metric-icon"><FileText size={18}/></div><div><span>Total de Templates</span><strong>{templates.length}</strong><small>todos os tipos</small></div></article><article className="zip-metric"><div className="zip-metric-icon"><Sparkles size={18}/></div><div><span>Semânticos (IA)</span><strong>{semanticCount}</strong><small>gerados por IA</small></div></article><article className="zip-metric"><div className="zip-metric-icon"><FileText size={18}/></div><div><span>Ativos</span><strong>{activeCount}</strong><small>disponíveis</small></div></article><article className="zip-metric"><div className="zip-metric-icon"><Sparkles size={18}/></div><div><span>Variáveis Mapeadas</span><strong>{mapped}</strong><small>em todos os templates</small></div></article></div>
      <div className="zip-toolbar contracts-toolbar"><label className="zip-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome ou descrição..."/></label><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">Todos os tipos</option><option value="semantico">Semântico (IA)</option><option value="padrao">Padrão</option></select><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Todos</option><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select><button type="button" className="zip-button" onClick={openWorkspace}><Plus size={14}/> Novo Template</button></div>
      <section className="zip-panel contracts-table-panel"><header className="zip-panel-head"><div><h2>Lista de Templates</h2><p>{filtered.length} template(s)</p></div></header><div className="zip-table-wrap"><table className="zip-table"><thead><tr><th></th><th>Nome</th><th>Categoria</th><th>Status</th><th>Data de Criação</th><th>Ações</th></tr></thead><tbody>{filtered.length?filtered.map(t=><tr key={t.id}><td><input type="checkbox"/></td><td><strong>{t.name}</strong></td><td>{t.category||'—'}</td><td><span className={`zip-badge ${t.active?'zip-badge-success':''}`}>{t.active?'Ativo':'Inativo'}</span></td><td>{new Date(t.createdAt).toLocaleDateString('pt-BR')}</td><td><button type="button" className="zip-icon" title="Ações"><MoreHorizontal size={15}/></button></td></tr>):<tr><td colSpan={6} className="contracts-empty-row">Nenhum template encontrado.</td></tr>}</tbody></table></div></section>
    </div>
    {workspace&&<div className="reference-modal-backdrop"><section className="reference-modal reference-modal-xl contracts-template-workspace"><header className="reference-modal-head"><div><span>TEMPLATE CONTRATUAL</span><h2>{draft.name||'Novo Template'}</h2></div><button className="reference-modal-close" onClick={()=>setWorkspace(false)}><X size={17}/></button></header><div className="zip-tabs">{[['template','Template'],['variaveis','Variáveis'],['categorias','Categorias'],['preview','Preview']].map(([key,label])=><button key={key} className={activeTab===key?'active':''} onClick={()=>setActiveTab(key as typeof activeTab)}>{label}</button>)}</div>
      {activeTab==='template'&&<div className="contracts-template-editor"><div className="contracts-template-main"><div className="contracts-template-meta"><div><span>Informações Básicas</span><label><small>Nome do Template</small><input value={draft.name} onChange={e=>setDraft(v=>({...v,name:e.target.value}))} placeholder="Ex: Contrato de Gravação — Exclusivo"/></label><label><small>Categoria do Template</small><select value={draft.category} onChange={e=>setDraft(v=>({...v,category:e.target.value}))}><option value="">Selecionar categoria…</option><option>Comercial</option><option>Prestação de Serviços</option><option>Eventos</option><option>Licenciamento</option></select></label></div><div><span>Identidade Visual do Documento</span><label><small>Imagem de Cabeçalho</small><input type="file" accept="image/*"/></label><label><small>Imagem de Rodapé</small><input type="file" accept="image/*"/></label></div></div><div className="contracts-template-content"><div><span>Conteúdo do Contrato</span><button className="zip-button secondary" type="button"><Sparkles size={14}/> Analisar com IA</button></div><textarea value={draft.content} onChange={e=>setDraft(v=>({...v,content:e.target.value}))} placeholder={'Escreva o conteúdo do contrato…\n\nUse {{GRUPO.CAMPO}} para inserir variáveis dinâmicas.'}/></div></div><aside className="contracts-template-vars"><div><strong>Variáveis do Registo</strong><input value={varSearch} onChange={e=>setVarSearch(e.target.value)} placeholder="Pesquisar variáveis…"/></div>{VARS.filter(v=>v.toLowerCase().includes(varSearch.toLowerCase())).map(v=><button key={v} onClick={()=>insertVar(v)}><code>{v}</code><Plus size={13}/></button>)}</aside></div>}
      {activeTab==='variaveis'&&<div className="reference-modal-body"><section className="zip-panel"><header className="zip-panel-head"><div><h2>Variáveis de Template</h2><p>Placeholders disponíveis no registro</p></div></header><div className="reference-entity-list">{VARS.map(v=><div className="reference-entity-row" key={v}><div className="reference-entity-copy"><strong>{v}</strong><span>Variável reutilizável</span></div><button className="zip-button secondary" onClick={()=>{insertVar(v);setActiveTab('template')}}>Inserir</button></div>)}</div></section></div>}
      {activeTab==='categorias'&&<div className="reference-modal-body"><section className="zip-panel"><header className="zip-panel-head"><div><h2>Categorias</h2><p>Classificação disponível para templates</p></div></header><div className="reference-entity-list">{['Comercial','Prestação de Serviços','Eventos','Licenciamento'].map(v=><div className="reference-entity-row" key={v}><div className="reference-entity-copy"><strong>{v}</strong><span>{v.toLowerCase().replaceAll(' ','_')}</span></div></div>)}</div></section></div>}
      {activeTab==='preview'&&<div className="reference-modal-body"><div className="reference-contract-preview"><div className="reference-a4"><h1>{draft.name||'TEMPLATE CONTRATUAL'}</h1><p>{draft.content||'Pré-visualização do conteúdo do template.'}</p></div></div></div>}
      <footer className="reference-modal-footer"><span className="contracts-autosave-note">Alterações salvas automaticamente</span><button className="zip-button secondary" onClick={()=>setWorkspace(false)}>Cancelar</button><button className="zip-button" onClick={save}><Save size={14}/> Salvar Template</button></footer></section></div>}
  </AdminShell>
}
