import {randomUUID} from 'node:crypto'
import {getPool,withTransaction} from './db.js'
import {HttpError} from './editorialService.js'
import {integrationRuntimeStatus,whatsappProvider} from './integrationProviderService.js'

const SUPPORT_STATUS=new Set(['nova','aguardando_atendimento','em_atendimento','aguardando_cliente','resolvida','arquivada'])
const text=value=>value===undefined||value===null?'':String(value).trim()
const now=()=>new Date().toISOString()
const uid=prefix=>`${prefix}_${randomUUID()}`
const clone=value=>structuredClone(value)
const emptyAutomation=()=>({enabled:false,welcomeMessage:'',mainMenuMessage:'',menuOptions:[],templates:[],requiredFields:[],optionalFields:[],invalidOptionMessage:'',absenceMessage:'',outOfHoursMessage:'',closingMessage:'',returnToMenuRule:{enabled:false,commands:[]},escalationRules:[],notificationChannels:{in_app:true,whatsapp:false,sms:false},supervisorUserId:null,managerUserId:null,updatedAt:''})
const emptyState=()=>({supportConversations:[],supportMessages:[],internalConversations:[],internalMessages:[],quickReplies:[],automation:emptyAutomation()})
const ensureState=value=>{const state=value&&typeof value==='object'&&!Array.isArray(value)?value:{};return {supportConversations:Array.isArray(state.supportConversations)?state.supportConversations:[],supportMessages:Array.isArray(state.supportMessages)?state.supportMessages:[],internalConversations:Array.isArray(state.internalConversations)?state.internalConversations:[],internalMessages:Array.isArray(state.internalMessages)?state.internalMessages:[],quickReplies:Array.isArray(state.quickReplies)?state.quickReplies:[],automation:{...emptyAutomation(),...(state.automation&&typeof state.automation==='object'?state.automation:{})}}}

async function actor(userId){const {rows}=await getPool().query('select id,email,display_name from admin_users where id=$1 and active=true',[userId]);if(!rows[0])throw new HttpError(401,'Usuário administrativo inválido.','CHAT_AUTH_USER_INVALID');return {id:rows[0].id,email:rows[0].email,name:text(rows[0].display_name)||rows[0].email}}
async function members(){const {rows}=await getPool().query("select id,email,display_name from admin_users where active=true and role in ('owner','admin','editor') order by created_at asc,id asc");return rows.map(row=>({authUserId:row.id,fullName:text(row.display_name)||null,email:row.email}))}
async function load(client,{lock=false,userId=null}={}){await client.query("insert into chat_admin_state(id,payload,created_by,updated_by) values('primary',$1,$2,$2) on conflict (id) do nothing",[JSON.stringify(emptyState()),userId]);const {rows}=await client.query(`select payload,version,updated_at from chat_admin_state where id='primary'${lock?' for update':''}`);return {state:ensureState(rows[0]?.payload),version:Number(rows[0]?.version||1),updatedAt:rows[0]?.updated_at?new Date(rows[0].updated_at).toISOString():''}}
async function persist(client,state,userId){const {rows}=await client.query("update chat_admin_state set payload=$1,version=version+1,updated_by=$2 where id='primary' returning version,updated_at",[JSON.stringify(state),userId]);return {state,version:Number(rows[0].version),updatedAt:new Date(rows[0].updated_at).toISOString()}}
function findConversation(state,id){const item=state.supportConversations.find(value=>value.id===id);if(!item)throw new HttpError(404,'Conversa de atendimento não encontrada.','CHAT_CONVERSATION_NOT_FOUND');return item}
function audit(conversation,message){conversation.auditTrail=Array.from(new Set([...(Array.isArray(conversation.auditTrail)?conversation.auditTrail:[]),message]));conversation.updatedAt=now()}
function updateLast(conversation,message){conversation.lastMessage=message.body;conversation.lastMessageAt=new Date(message.createdAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});conversation.lastReplyAt=new Date(message.createdAt).toLocaleString('pt-BR');conversation.unread=0;conversation.updatedAt=message.createdAt}
async function currentState(){const snapshot=await load(getPool());return {...snapshot.state,internalMembers:await members(),runtime:{whatsapp:integrationRuntimeStatus().whatsapp,attachments:{configured:false},audioRecording:{configured:false},escalation:{configured:false}},meta:{version:snapshot.version,updatedAt:snapshot.updatedAt}}}

async function mutate(userId,work){return withTransaction(async client=>{const loaded=await load(client,{lock:true,userId}),state=loaded.state,result=await work(state,client);const saved=await persist(client,state,userId);return {saved,result}})}

export const chatService={
  async state(){return currentState()},
  async createSupport(input,userId){const who=await actor(userId);const customer=text(input?.customer),phone=text(input?.phone);if(!customer&&!phone)throw new HttpError(400,'Informe cliente ou telefone.','CHAT_CUSTOMER_REQUIRED');const created=await mutate(userId,state=>{const stamp=now(),id=uid('chat_sup'),conversation={id,customer:customer||phone,handle:phone,phone,instagram:'',email:'',originLabel:phone?'WhatsApp':'Atendimento interno',channel:phone?'whatsapp':'custom',queue:'Atendimento',sector:'Triagem',status:'nova',assignee:who.name,protocol:id.replace(/\W/g,'').slice(-8).toUpperCase(),sla:100,remainingTimeLabel:'4h',deadlineState:'on_track',tags:[],lastMessage:'Conversa criada.',lastMessageAt:new Date(stamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),createdAt:new Date(stamp).toLocaleString('pt-BR'),lastReplyAt:'—',unread:0,value:'',crmSummary:{existingCustomer:false,lead:'',openDeal:'',stage:''},auditTrail:[`Conversa criada por ${who.name}`],updatedAt:stamp};state.supportConversations.unshift(conversation);return conversation});return {conversation:clone(created.result),state:await currentState()}},
  async sendSupport(conversationId,input,userId){const who=await actor(userId),body=text(input?.body),internalNote=Boolean(input?.internalNote),attachments=Array.isArray(input?.attachments)?input.attachments:[];if(attachments.length)throw new HttpError(409,'Upload de anexos do Chat ainda não possui pipeline persistente configurado.','CHAT_ATTACHMENTS_UNAVAILABLE');if(!body)throw new HttpError(400,'Mensagem vazia.','CHAT_MESSAGE_REQUIRED');const prepared=await mutate(userId,state=>{const conversation=findConversation(state,conversationId);if(['resolvida','arquivada'].includes(conversation.status))throw new HttpError(409,'Reabra a conversa antes de enviar mensagens.','CHAT_CONVERSATION_CLOSED');let deliveryStatus='unavailable';if(internalNote)deliveryStatus='internal_only';else if(conversation.channel==='whatsapp')deliveryStatus=whatsappProvider.configured()?'sending':'unavailable';const stamp=now(),message={id:uid('chat_msg'),conversationId,sender:'agent',author:who.name,body,time:new Date(stamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),createdAt:stamp,deliveryStatus,internalNote};state.supportMessages.push(message);updateLast(conversation,message);return {messageId:message.id,phone:conversation.phone,deliveryStatus}});if(prepared.result.deliveryStatus==='sending'){let status='sent',error='',externalId='';try{const result=await whatsappProvider.sendText({to:prepared.result.phone,text:body});externalId=result.messageId}catch(cause){status='failed';error=cause instanceof Error?cause.message:'Falha no envio externo.'}await mutate(userId,state=>{const message=state.supportMessages.find(item=>item.id===prepared.result.messageId);if(message){message.deliveryStatus=status;message.deliveryError=error||undefined;message.externalId=externalId||undefined}})}return currentState()},
  async setStatus(id,statusValue,userId){const who=await actor(userId),status=text(statusValue);if(!SUPPORT_STATUS.has(status))throw new HttpError(400,'Status do Chat inválido.','CHAT_STATUS_INVALID');await mutate(userId,state=>{const conversation=findConversation(state,id);conversation.status=status;audit(conversation,`Status alterado para ${status} por ${who.name}`)});return currentState()},
  async transfer(id,assignee,userId){const who=await actor(userId),value=text(assignee);if(!value)throw new HttpError(400,'Responsável obrigatório.','CHAT_ASSIGNEE_REQUIRED');await mutate(userId,state=>{const conversation=findConversation(state,id);conversation.assignee=value;conversation.status='em_atendimento';audit(conversation,`Transferido para ${value} por ${who.name}`)});return currentState()},
  async addTag(id,tag,userId){const value=text(tag);if(!value)throw new HttpError(400,'Tag vazia.','CHAT_TAG_REQUIRED');await mutate(userId,state=>{const conversation=findConversation(state,id);conversation.tags=Array.from(new Set([...(conversation.tags||[]),value]));conversation.updatedAt=now()});return currentState()},
  async markCrm(id,patch,userId){await mutate(userId,state=>{const conversation=findConversation(state,id);conversation.crmSummary={...conversation.crmSummary,existingCustomer:Boolean(patch?.existingCustomer??conversation.crmSummary?.existingCustomer),lead:text(patch?.lead??conversation.crmSummary?.lead),openDeal:text(patch?.openDeal??conversation.crmSummary?.openDeal),stage:text(patch?.stage??conversation.crmSummary?.stage)};conversation.updatedAt=now()});return currentState()},
  async createInternal(participantIds,userId){const who=await actor(userId),all=await members(),ids=Array.isArray(participantIds)?participantIds.map(String):[],selected=all.filter(member=>ids.includes(member.authUserId)&&member.authUserId!==userId);if(!selected.length)throw new HttpError(400,'Selecione ao menos um participante.','CHAT_PARTICIPANT_REQUIRED');await mutate(userId,state=>{const stamp=now(),participants=[{authUserId:who.id,fullName:who.name,email:who.email},...selected].map(member=>({...member,lastReadAt:stamp}));state.internalConversations.unshift({id:uid('internal'),type:participants.length>2?'group':'direct',name:participants.length>2?selected.map(item=>item.fullName||item.email).join(', '):null,createdBy:userId,createdAt:stamp,updatedAt:stamp,participants})});return currentState()},
  async sendInternal(conversationId,bodyValue,userId){const body=text(bodyValue);if(!body)throw new HttpError(400,'Mensagem vazia.','CHAT_MESSAGE_REQUIRED');await mutate(userId,state=>{const conversation=state.internalConversations.find(item=>item.id===conversationId);if(!conversation||!conversation.participants?.some(item=>item.authUserId===userId))throw new HttpError(403,'Você não participa desta conversa.','CHAT_INTERNAL_FORBIDDEN');const stamp=now();state.internalMessages.push({id:uid('im'),conversationId,senderAuthUserId:userId,body,createdAt:stamp,editedAt:null});conversation.updatedAt=stamp});return currentState()},
  async saveAutomation(input,userId){const value=input&&typeof input==='object'?input:{};await mutate(userId,state=>{state.automation={...emptyAutomation(),...value,enabled:false,updatedAt:now()}});return currentState()},
}
