import assert from 'node:assert/strict'
import test from 'node:test'
import {assertSafeExternalUrl,classifyCandidate,createSafeExternalFetcher,fetchYouTubeItems,likelySameStory,normalizeExternalUrl,parseSyndicationFeed,scoreCandidate,titleSimilarity} from './contentIngestionCore.js'

const rss=`<?xml version="1.0"?><rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/"><channel><title>Portal Test</title><item><guid>news-1</guid><title>Mercado musical brasileiro cresce com streaming</title><link>https://example.com/news/1?utm_source=rss</link><description><![CDATA[<p>Gravadoras e artistas ampliam receitas.</p>]]></description><pubDate>Fri, 04 Sep 2026 12:00:00 GMT</pubDate><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Redação</dc:creator><media:thumbnail url="https://example.com/image.jpg"/></item></channel></rss>`
const atom=`<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom"><title>Atom</title><entry><id>tag:example.com,2026:2</id><title>Spotify anuncia ferramenta para artistas no Brasil</title><link rel="alternate" href="https://example.com/atom/2"/><summary>Novidade para o mercado musical.</summary><published>2026-09-04T13:00:00Z</published><author><name>Equipe</name></author></entry></feed>`

test('RSS 2.0 normaliza item, data, autor e mídia sem copiar matéria completa',()=>{const [item]=parseSyndicationFeed(rss,{feedUrl:'https://example.com/feed.xml',sourceName:'Test'});assert.equal(item.externalId,'news-1');assert.equal(item.title,'Mercado musical brasileiro cresce com streaming');assert.equal(item.description,'Gravadoras e artistas ampliam receitas.');assert.equal(item.author,'Redação');assert.equal(item.publishedAt,'2026-09-04T12:00:00.000Z');assert.equal(item.imageUrl,'https://example.com/image.jpg')})
test('Atom normaliza id, link e publicação',()=>{const [item]=parseSyndicationFeed(atom,{feedUrl:'https://example.com/atom.xml'});assert.equal(item.externalId,'tag:example.com,2026:2');assert.equal(item.canonicalUrl,'https://example.com/atom/2');assert.equal(item.author,'Equipe');assert.equal(item.publishedAt,'2026-09-04T13:00:00.000Z')})
test('XML inválido é rejeitado',()=>assert.throws(()=>parseSyndicationFeed('<html>no feed</html>'),error=>error?.code==='FEED_XML_INVALID'))
test('URL canônica remove parâmetros de tracking',()=>assert.equal(normalizeExternalUrl('https://EXAMPLE.com/news/1/?utm_source=x&x=1#fragment'),'https://example.com/news/1?x=1'))
test('similaridade exige narrativa realmente próxima',()=>{assert.ok(titleSimilarity('Spotify lança recurso para artistas brasileiros','Spotify lança novo recurso para artistas brasileiros')>.88);assert.equal(likelySameStory({title:'Spotify lança recurso para artistas brasileiros',publishedAt:'2026-09-04T12:00:00Z'},{title:'Festival brasileiro anuncia shows de rap e funk',publishedAt:'2026-09-04T13:00:00Z'}),false)})
test('classificação e relevância são determinísticas e explicáveis',()=>{const input={provider:'official_source',sourceType:'official_news',country:'BR',language:'pt-BR',title:'ECAD divulga novos dados de direitos autorais e royalties no Brasil',description:'Mercado musical brasileiro',publishedAt:new Date().toISOString()};assert.equal(classifyCandidate(input),'Direitos Autorais');const result=scoreCandidate(input);assert.ok(result.score>=50);assert.ok(result.score<=100);assert.ok(result.reasons.includes('official-source:15'));assert.ok(result.reasons.includes('brazil-relevance:15'))})
test('popularidade YouTube é apenas sinal relativo limitado',()=>{const result=scoreCandidate({provider:'youtube',country:'BR',language:'pt',title:'Novo single de artista brasileiro',statistics:{viewCount:100000000},publishedAt:new Date().toISOString()});const reason=result.reasons.find(item=>item.startsWith('youtube-relative-signal:'));assert.ok(reason);assert.ok(Number(reason.split(':')[1])<=20)})
test('YouTube exige credencial backend',async()=>{await assert.rejects(()=>fetchYouTubeItems({},''),error=>error?.code==='YOUTUBE_NOT_CONFIGURED')})
test('SSRF bloqueia protocolos e destinos privados',async()=>{await assert.rejects(()=>assertSafeExternalUrl('file:///etc/passwd'),error=>error?.code==='EXTERNAL_URL_PROTOCOL_INVALID');await assert.rejects(()=>assertSafeExternalUrl('http://127.0.0.1/feed'),error=>error?.code==='EXTERNAL_URL_PRIVATE_DESTINATION');await assert.rejects(()=>assertSafeExternalUrl('http://metadata.internal/feed'),error=>error?.code==='EXTERNAL_URL_PRIVATE_DESTINATION')})
test('SSRF bloqueia host público que resolve para IP privado',async()=>{await assert.rejects(()=>assertSafeExternalUrl('https://example.test/feed',{lookup:async()=>[{address:'10.0.0.5',family:4}]}),error=>error?.code==='EXTERNAL_URL_PRIVATE_DESTINATION')})
test('fetch seguro trata feed offline',async()=>{const fetcher=createSafeExternalFetcher({lookup:async()=>[{address:'93.184.216.34',family:4}],fetchImpl:async()=>{throw new TypeError('offline')}});await assert.rejects(()=>fetcher('https://example.com/feed.xml'),error=>error?.code==='EXTERNAL_FETCH_NETWORK_ERROR')})
test('fetch seguro trata timeout',async()=>{const keepAlive=setTimeout(()=>{},1000);try{const fetcher=createSafeExternalFetcher({lookup:async()=>[{address:'93.184.216.34',family:4}],fetchImpl:async(_url,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true}))});await assert.rejects(()=>fetcher('https://example.com/feed.xml',{timeoutMs:10}),error=>error?.code==='EXTERNAL_FETCH_TIMEOUT')}finally{clearTimeout(keepAlive)}})
test('fetch seguro revalida redirect contra SSRF',async()=>{const fetcher=createSafeExternalFetcher({lookup:async host=>host==='example.com'?[{address:'93.184.216.34',family:4}]:[{address:'127.0.0.1',family:4}],fetchImpl:async()=>new Response('',{status:302,headers:{location:'http://evil.test/private'}})});await assert.rejects(()=>fetcher('https://example.com/feed.xml'),error=>error?.code==='EXTERNAL_URL_PRIVATE_DESTINATION')})
