import {randomUUID} from 'node:crypto'
import {getPool,withTransaction} from './db.js'
import {HttpError} from './editorialService.js'

const LEAD_STATUS=new Set(['novo','contato_realizado','qualificado','proposta','negociacao','fechado','perdido'])
const LEAD_TYPE=new Set(['empresa_marca','agencia_publicidade','assessoria_imprensa','agencia_comunicacao','anunciante','patrocinador','produtora','organizador_evento','artista_personalidade','criador_influenciador','parceiro_comercial','prestador_servico','instituicao','outro'])
const LEAD_SERVICE=new Set(['publieditorial','materia_patrocinada','publicacao_comercial','banner_publicitario','campanha_publicitaria','divulgacao_evento','divulgacao_lancamento','cobertura_evento','entrevista','producao_conteudo','patrocinio','parceria_comercial','design','marketing','desenvolvimento_web','consultoria','outro'])
const LEAD_ORIGIN=new Set(['site','formulario_portal','whatsapp','email','instagram','facebook','linkedin','indicacao','prospeccao_ativa','evento','parceiro','campanha','google','outro'])
const PRIORITY=new Set(['baixa','media','alta','estrategica'])
const TEMPERATURE=new Set(['frio','morno','quente'])
const INTERACTION_TYPE=new Set(['reuniao','email','whatsapp','ligacao','follow_up','proposta','contrato','nota'])
const CONTACT_ENTITY=new Set(['pessoa_fisica','pessoa_juridica'])
const CONTACT_CATEGORY=new Set(['cliente','anunciante','parceiro','fornecedor','prestador_servico','assessoria_agencia','fonte_editorial','patrocinador','instituicao','investidor','outro'])
const CONTACT_STATUS=new Set(['ativo','inativo'])
const MAX_JSON_STATE_BYTES=5*1024*1024

const text=value=>value===undefined||value===null?'':String(value).trim()
const array=value=>Array.isArray(value)?value:[]
const object=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{}
const enumValue=(set,value,fallback)=>set.has(text(value))?text(value):fallback
const iso=value=>value?new Date(value).toISOString():''
const jsonState=(value,label)=>{
  const normalized=array(value)
  if(Buffer.byteLength(JSON.stringify(normalized),'utf8')>MAX_JSON_STATE_BYTES)throw new HttpError(413,`${label} excede o limite permitido.`,'CRM_STATE_TOO_LARGE',{field:label})
  return normalized
}
const conflict=(actual,expected)=>{if(expected&&new Date(actual).toISOString()!==new Date(expected).toISOString())throw new HttpError(409,'Este registro foi alterado em outra sessão. Reabra o registro antes de salvar.','CRM_CONFLICT')}
const requireName=value=>{const name=text(value);if(!name)throw new HttpError(400,'Nome é obrigatório.','CRM_NAME_REQUIRED');return name}
const normalizePhone=value=>text(value).replace(/\D/g,'')

function mapLead(row){return {
  id:row.id,name:row.name,company:row.company,email:row.email,phone:row.phone,city:row.city,state:row.state,role:row.role,website:row.website,instagram:row.instagram,
  type:row.lead_type,service:row.service,description:row.description,origin:row.origin,status:row.status,priority:row.priority,responsible:row.responsible,campaign:row.campaign,
  nextFollowUp:row.next_follow_up?row.next_follow_up.toISOString?.()||String(row.next_follow_up):'',estimatedValue:row.estimated_value===null?'':Number(row.estimated_value),temperature:row.temperature,
  serviceDetails:object(row.service_details),notes:row.notes,tags:array(row.tags),attachments:array(row.attachments),interactions:array(row.interactions),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),
  ...(row.converted_contact_id?{convertedContactId:row.converted_contact_id}:{}),...(row.source_submission_id?{sourceSubmissionId:String(row.source_submission_id)}:{}),
}}
function mapContact(row){return {
  id:row.id,entityType:row.entity_type,category:row.category,profile:row.profile,name:row.name,company:row.company,role:row.role,email:row.email,phone:row.phone,whatsapp:row.whatsapp,
  city:row.city,state:row.state,document:row.document,website:row.website,instagram:row.instagram,priority:row.priority,status:row.status,tags:array(row.tags),notes:row.notes,
  attachments:array(row.attachments),timeline:array(row.timeline),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),...(row.source_lead_id?{sourceLeadId:row.source_lead_id}:{}),
}}
function normalizeLead(input,current={}){return {
  name:requireName(input.name??current.name),company:text(input.company??current.company),email:text(input.email??current.email),phone:text(input.phone??current.phone),city:text(input.city??current.city),state:text(input.state??current.state),role:text(input.role??current.role),website:text(input.website??current.website),instagram:text(input.instagram??current.instagram),
  type:enumValue(LEAD_TYPE,input.type??current.type,'outro'),service:enumValue(LEAD_SERVICE,input.service??current.service,'outro'),description:text(input.description??current.description),origin:enumValue(LEAD_ORIGIN,input.origin??current.origin,'outro'),status:enumValue(LEAD_STATUS,input.status??current.status,'novo'),priority:enumValue(PRIORITY,input.priority??current.priority,'media'),responsible:text(input.responsible??current.responsible),campaign:text(input.campaign??current.campaign),
  nextFollowUp:text(input.nextFollowUp??current.nextFollowUp),estimatedValue:input.estimatedValue===''||input.estimatedValue===null||input.estimatedValue===undefined?(current.estimatedValue===''?null:current.estimatedValue??null):Number(input.estimatedValue),temperature:enumValue(TEMPERATURE,input.temperature??current.temperature,'morno'),serviceDetails:object(input.serviceDetails??current.serviceDetails),notes:text(input.notes??current.notes),tags:array(input.tags??current.tags).map(String).filter(Boolean),attachments:jsonState(input.attachments??current.attachments??[],'attachments'),interactions:jsonState(input.interactions??current.interactions??[],'interactions'),
}}
function normalizeContact(input,current={}){return {
  entityType:enumValue(CONTACT_ENTITY,input.entityType??current.entityType,'pessoa_juridica'),category:enumValue(CONTACT_CATEGORY,input.category??current.category,'outro'),profile:text(input.profile??current.profile),name:requireName(input.name??current.name),company:text(input.company??current.company),role:text(input.role??current.role),email:text(input.email??current.email),phone:text(input.phone??current.phone),whatsapp:text(input.whatsapp??current.whatsapp),city:text(input.city??current.city),state:text(input.state??current.state),document:text(input.document??current.document),website:text(input.website??current.website),instagram:text(input.instagram??current.instagram),priority:enumValue(PRIORITY,input.priority??current.priority,'media'),status:enumValue(CONTACT_STATUS,input.status??current.status,'ativo'),tags:array(input.tags??current.tags).map(String).filter(Boolean),notes:text(input.notes??current.notes),attachments:jsonState(input.attachments??current.attachments??[],'attachments'),timeline:jsonState(input.timeline??current.timeline??[],'timeline'),sourceLeadId:text(input.sourceLeadId??current.sourceLeadId)||null,
}}

async function selectLead(client,id,{lock=false}={}){const {rows}=await client.query(`select * from crm_leads where id=$1${lock?' for update':''}`,[id]);if(!rows[0])throw new HttpError(404,'Lead não encontrado.','CRM_LEAD_NOT_FOUND');return rows[0]}
async function selectContact(client,id,{lock=false}={}){const {rows}=await client.query(`select * from crm_contacts where id=$1${lock?' for update':''}`,[id]);if(!rows[0])throw new HttpError(404,'Contato não encontrado.','CRM_CONTACT_NOT_FOUND');return rows[0]}

export const crmService={
  async listLeads(){const {rows}=await getPool().query('select * from crm_leads order by created_at desc');return rows.map(mapLead)},
  async listContacts(){const {rows}=await getPool().query('select * from crm_contacts order by created_at desc');return rows.map(mapContact)},
  async createLead(input){const value=normalizeLead(input);const id=`lead_${randomUUID()}`;const {rows}=await getPool().query(`insert into crm_leads(id,name,company,email,phone,city,state,role,website,instagram,lead_type,service,description,origin,status,priority,responsible,campaign,next_follow_up,estimated_value,temperature,service_details,notes,tags,attachments,interactions) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26) returning *`,[id,value.name,value.company,value.email,value.phone,value.city,value.state,value.role,value.website,value.instagram,value.type,value.service,value.description,value.origin,value.status,value.priority,value.responsible,value.campaign,value.nextFollowUp||null,value.estimatedValue,value.temperature,JSON.stringify(value.serviceDetails),value.notes,value.tags,JSON.stringify(value.attachments),JSON.stringify(value.interactions)]);return mapLead(rows[0])},
  async updateLead(id,patch,expectedUpdatedAt){return withTransaction(async client=>{const currentRow=await selectLead(client,id,{lock:true});const current=mapLead(currentRow);conflict(current.updatedAt,expectedUpdatedAt);const value=normalizeLead(patch,current);const {rows}=await client.query(`update crm_leads set name=$2,company=$3,email=$4,phone=$5,city=$6,state=$7,role=$8,website=$9,instagram=$10,lead_type=$11,service=$12,description=$13,origin=$14,status=$15,priority=$16,responsible=$17,campaign=$18,next_follow_up=$19,estimated_value=$20,temperature=$21,service_details=$22,notes=$23,tags=$24,attachments=$25,interactions=$26 where id=$1 returning *`,[id,value.name,value.company,value.email,value.phone,value.city,value.state,value.role,value.website,value.instagram,value.type,value.service,value.description,value.origin,value.status,value.priority,value.responsible,value.campaign,value.nextFollowUp||null,value.estimatedValue,value.temperature,JSON.stringify(value.serviceDetails),value.notes,value.tags,JSON.stringify(value.attachments),JSON.stringify(value.interactions)]);return mapLead(rows[0])})},
  async deleteLead(id){const result=await getPool().query('delete from crm_leads where id=$1',[id]);if(!result.rowCount)throw new HttpError(404,'Lead não encontrado.','CRM_LEAD_NOT_FOUND')},
  async bulkDeleteLeads(ids){const normalized=[...new Set(array(ids).map(String).filter(Boolean))];if(!normalized.length)return;await getPool().query('delete from crm_leads where id=any($1::text[])',[normalized])},
  async bulkStatus(ids,status){const normalized=[...new Set(array(ids).map(String).filter(Boolean))],next=enumValue(LEAD_STATUS,status,'');if(!next)throw new HttpError(400,'Status de lead inválido.','CRM_LEAD_STATUS_INVALID');if(!normalized.length)return;await getPool().query('update crm_leads set status=$2 where id=any($1::text[])',[normalized,next])},
  async addInteraction(id,input){return withTransaction(async client=>{const row=await selectLead(client,id,{lock:true});const items=array(row.interactions);const type=enumValue(INTERACTION_TYPE,input.type,'');if(!type)throw new HttpError(400,'Tipo de interação inválido.','CRM_INTERACTION_TYPE_INVALID');const interaction={id:`interaction_${randomUUID()}`,type,notes:text(input.notes),responsible:text(input.responsible),createdAt:new Date().toISOString()};items.unshift(interaction);jsonState(items,'interactions');await client.query('update crm_leads set interactions=$2 where id=$1',[id,JSON.stringify(items)]);return interaction})},
  async createContact(input){const value=normalizeContact(input),stamp=new Date().toISOString(),id=`contact_${randomUUID()}`;if(!value.timeline.length)value.timeline=[{id:`timeline_${randomUUID()}`,type:'created',description:'Contato criado no CRM',createdAt:stamp}];const {rows}=await getPool().query(`insert into crm_contacts(id,entity_type,category,profile,name,company,role,email,phone,whatsapp,city,state,document,website,instagram,priority,status,tags,notes,attachments,timeline,source_lead_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22) returning *`,[id,value.entityType,value.category,value.profile,value.name,value.company,value.role,value.email,value.phone,value.whatsapp,value.city,value.state,value.document,value.website,value.instagram,value.priority,value.status,value.tags,value.notes,JSON.stringify(value.attachments),JSON.stringify(value.timeline),value.sourceLeadId]);return mapContact(rows[0])},
  async updateContact(id,patch,expectedUpdatedAt){return withTransaction(async client=>{const currentRow=await selectContact(client,id,{lock:true}),current=mapContact(currentRow);conflict(current.updatedAt,expectedUpdatedAt);const value=normalizeContact(patch,current),stamp=new Date().toISOString();value.timeline=[{id:`timeline_${randomUUID()}`,type:'updated',description:'Dados do contato atualizados',createdAt:stamp},...value.timeline];jsonState(value.timeline,'timeline');const {rows}=await client.query(`update crm_contacts set entity_type=$2,category=$3,profile=$4,name=$5,company=$6,role=$7,email=$8,phone=$9,whatsapp=$10,city=$11,state=$12,document=$13,website=$14,instagram=$15,priority=$16,status=$17,tags=$18,notes=$19,attachments=$20,timeline=$21,source_lead_id=$22 where id=$1 returning *`,[id,value.entityType,value.category,value.profile,value.name,value.company,value.role,value.email,value.phone,value.whatsapp,value.city,value.state,value.document,value.website,value.instagram,value.priority,value.status,value.tags,value.notes,JSON.stringify(value.attachments),JSON.stringify(value.timeline),value.sourceLeadId]);return mapContact(rows[0])})},
  async deleteContact(id){const result=await getPool().query('delete from crm_contacts where id=$1',[id]);if(!result.rowCount)throw new HttpError(404,'Contato não encontrado.','CRM_CONTACT_NOT_FOUND')},
  async bulkDeleteContacts(ids){const normalized=[...new Set(array(ids).map(String).filter(Boolean))];if(!normalized.length)return;await getPool().query('delete from crm_contacts where id=any($1::text[])',[normalized])},
  async addTimeline(id,input){return withTransaction(async client=>{const row=await selectContact(client,id,{lock:true}),items=array(row.timeline);const entry={id:`timeline_${randomUUID()}`,type:text(input.type)||'note',description:text(input.description),createdAt:new Date().toISOString()};items.unshift(entry);jsonState(items,'timeline');await client.query('update crm_contacts set timeline=$2 where id=$1',[id,JSON.stringify(items)]);return entry})},
  async convertLead(id){return withTransaction(async client=>{const leadRow=await selectLead(client,id,{lock:true});if(leadRow.converted_contact_id)return mapContact(await selectContact(client,leadRow.converted_contact_id));const email=text(leadRow.email).toLowerCase(),phone=normalizePhone(leadRow.phone);const params=[],conditions=[];if(email){params.push(email);conditions.push(`lower(email)=$${params.length}`)}if(phone){params.push(phone);conditions.push(`regexp_replace(coalesce(phone,''),'\\D','','g')=$${params.length}`);conditions.push(`regexp_replace(coalesce(whatsapp,''),'\\D','','g')=$${params.length}`)}let contactRow=null;if(conditions.length){const {rows}=await client.query(`select * from crm_contacts where ${conditions.join(' or ')} order by created_at desc limit 1`,params);contactRow=rows[0]||null}if(!contactRow){const contactId=`contact_${randomUUID()}`,stamp=new Date().toISOString(),timeline=[{id:`timeline_${randomUUID()}`,type:'conversion',description:`Convertido do lead ${leadRow.name}`,createdAt:stamp}];const {rows}=await client.query(`insert into crm_contacts(id,entity_type,category,profile,name,company,role,email,phone,whatsapp,city,state,document,website,instagram,priority,status,tags,notes,attachments,timeline,source_lead_id) values($1,$2,'cliente',$3,$4,$5,$6,$7,$8,$8,$9,$10,'',$11,$12,$13,'ativo',$14,$15,$16,$17,$18) returning *`,[contactId,leadRow.company?'pessoa_juridica':'pessoa_fisica',leadRow.company?'Empresa':'Cliente individual',leadRow.name,leadRow.company,leadRow.role,leadRow.email,leadRow.phone,leadRow.city,leadRow.state,leadRow.website,leadRow.instagram,leadRow.priority,leadRow.tags,leadRow.notes,JSON.stringify(array(leadRow.attachments)),JSON.stringify(timeline),leadRow.id]);contactRow=rows[0]}await client.query("update crm_leads set converted_contact_id=$2,status='fechado' where id=$1",[id,contactRow.id]);return mapContact(contactRow)})},
}
