import {randomUUID} from 'node:crypto'
import {getPool,withTransaction} from './db.js'
import {HttpError} from './editorialService.js'

const TRANSACTION_TYPES=new Set(['receita','despesa'])
const TRANSACTION_STATUS=new Set(['pago','pendente','vencido','cancelado'])
const PAYMENT_TYPES=new Set(['avista','parcelado'])
const INVOICE_TYPES=new Set(['entrada','saida'])
const INVOICE_STATUS=new Set(['emitida','pendente','paga','cancelada'])
const RULE_EVENTS=new Set(['transaction.created','transaction.paid','invoice.due','contract.signed'])

const text=value=>value===undefined||value===null?'':String(value).trim()
const optionalText=value=>{const normalized=text(value);return normalized||null}
const enumValue=(value,allowed,label)=>{const normalized=text(value);if(!allowed.has(normalized))throw new HttpError(400,`${label} inválido.`,'FINANCE_ENUM_INVALID',{field:label});return normalized}
const requiredText=(value,label)=>{const normalized=text(value);if(!normalized)throw new HttpError(400,`${label} é obrigatório.`,'FINANCE_REQUIRED',{field:label});return normalized}
const dateValue=(value,label,{required=false}={})=>{const normalized=text(value);if(!normalized){if(required)throw new HttpError(400,`${label} é obrigatória.`,'FINANCE_DATE_REQUIRED',{field:label});return null}if(!/^\d{4}-\d{2}-\d{2}$/.test(normalized)||Number.isNaN(new Date(`${normalized}T00:00:00Z`).getTime()))throw new HttpError(400,`${label} inválida.`,'FINANCE_DATE_INVALID',{field:label});return normalized}
const numberValue=(value,label,{required=false}={})=>{if(value===undefined||value===null||value===''){if(required)throw new HttpError(400,`${label} é obrigatório.`,'FINANCE_NUMBER_REQUIRED',{field:label});return null}const normalized=Number(value);if(!Number.isFinite(normalized)||normalized<0)throw new HttpError(400,`${label} inválido.`,'FINANCE_NUMBER_INVALID',{field:label});return normalized}
const integerValue=(value,label)=>{const normalized=numberValue(value,label);if(normalized===null)return null;if(!Number.isInteger(normalized))throw new HttpError(400,`${label} inválido.`,'FINANCE_NUMBER_INVALID',{field:label});return normalized}
const iso=value=>value?new Date(value).toISOString():''
const conflict=(actual,expected)=>{if(expected&&new Date(actual).toISOString()!==new Date(expected).toISOString())throw new HttpError(409,'Este registro financeiro foi alterado em outra sessão. Reabra o registro antes de salvar.','FINANCE_CONFLICT')}

const mapTransaction=row=>({
  id:row.id,type:row.transaction_type,description:row.description,category:row.category,subcategory:row.subcategory,status:row.status,date:String(row.transaction_date),dueDate:row.due_date?String(row.due_date):'',amount:Number(row.amount),counterparty:row.counterparty,document:row.document,paymentMethod:row.payment_method,paymentType:row.payment_type,
  ...(row.installment_count!==null?{installmentCount:Number(row.installment_count)}:{}),...(row.installment_interval!==null?{installmentInterval:Number(row.installment_interval)}:{}),...(row.first_installment_date?{firstInstallmentDate:String(row.first_installment_date)}:{}),
  contractRef:row.contract_ref,...(row.contact_ref?{contactRef:row.contact_ref}:{}),...(row.supplier_ref?{supplierRef:row.supplier_ref}:{}),costCenter:row.cost_center,competence:row.competence,notes:row.notes,...(row.attachment_name?{attachmentName:row.attachment_name}:{}),...(row.attachment_data_url?{attachmentDataUrl:row.attachment_data_url}:{}),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),
})
const normalizeTransaction=(input,current={})=>{
  const paymentType=enumValue(input.paymentType??current.paymentType??'avista',PAYMENT_TYPES,'paymentType')
  const installmentCount=integerValue(input.installmentCount??current.installmentCount,'installmentCount')
  const installmentInterval=integerValue(input.installmentInterval??current.installmentInterval,'installmentInterval')
  if(paymentType==='parcelado'&&(installmentCount===null||installmentCount<1))throw new HttpError(400,'Quantidade de parcelas inválida.','FINANCE_INSTALLMENTS_INVALID')
  return {
    type:enumValue(input.type??current.type,TRANSACTION_TYPES,'type'),description:requiredText(input.description??current.description,'description'),category:text(input.category??current.category),subcategory:text(input.subcategory??current.subcategory),status:enumValue(input.status??current.status??'pendente',TRANSACTION_STATUS,'status'),date:dateValue(input.date??current.date,'date',{required:true}),dueDate:dateValue(input.dueDate??current.dueDate,'dueDate'),amount:numberValue(input.amount??current.amount,'amount',{required:true}),counterparty:text(input.counterparty??current.counterparty),document:text(input.document??current.document),paymentMethod:text(input.paymentMethod??current.paymentMethod),paymentType,
    installmentCount:paymentType==='parcelado'?installmentCount:null,installmentInterval:paymentType==='parcelado'?installmentInterval:null,firstInstallmentDate:paymentType==='parcelado'?dateValue(input.firstInstallmentDate??current.firstInstallmentDate,'firstInstallmentDate'):null,
    contractRef:text(input.contractRef??current.contractRef),contactRef:optionalText(input.contactRef??current.contactRef),supplierRef:optionalText(input.supplierRef??current.supplierRef),costCenter:text(input.costCenter??current.costCenter),competence:text(input.competence??current.competence),notes:text(input.notes??current.notes),attachmentName:optionalText(input.attachmentName??current.attachmentName),attachmentDataUrl:optionalText(input.attachmentDataUrl??current.attachmentDataUrl),
  }
}

const mapInvoice=row=>({
  id:row.id,number:row.invoice_number,series:row.series,type:row.invoice_type,party:row.party,document:row.document,issueDate:String(row.issue_date),dueDate:row.due_date?String(row.due_date):'',amount:Number(row.amount),status:row.status,description:row.description,pdfUrl:row.pdf_url,
  ...(row.model?{model:row.model}:{}),...(row.access_key?{accessKey:row.access_key}:{}),...(row.operation_nature?{operationNature:row.operation_nature}:{}),...(row.cfop?{cfop:row.cfop}:{}),...(row.entry_exit_date?{entryExitDate:String(row.entry_exit_date)}:{}),...(row.state_registration?{stateRegistration:row.state_registration}:{}),...(row.municipal_registration?{municipalRegistration:row.municipal_registration}:{}),...(row.email?{email:row.email}:{}),...(row.phone?{phone:row.phone}:{}),...(row.address?{address:row.address}:{}),...(row.city?{city:row.city}:{}),...(row.state?{state:row.state}:{}),...(row.zip_code?{zipCode:row.zip_code}:{}),
  ...(row.products_amount!==null?{productsAmount:Number(row.products_amount)}:{}),...(row.freight_amount!==null?{freightAmount:Number(row.freight_amount)}:{}),...(row.insurance_amount!==null?{insuranceAmount:Number(row.insurance_amount)}:{}),...(row.discount_amount!==null?{discountAmount:Number(row.discount_amount)}:{}),...(row.other_expenses!==null?{otherExpenses:Number(row.other_expenses)}:{}),...(row.icms_base!==null?{icmsBase:Number(row.icms_base)}:{}),...(row.icms_amount!==null?{icmsAmount:Number(row.icms_amount)}:{}),...(row.ipi_amount!==null?{ipiAmount:Number(row.ipi_amount)}:{}),...(row.pis_amount!==null?{pisAmount:Number(row.pis_amount)}:{}),...(row.cofins_amount!==null?{cofinsAmount:Number(row.cofins_amount)}:{}),...(row.iss_amount!==null?{issAmount:Number(row.iss_amount)}:{}),
  ...(row.payment_method?{paymentMethod:row.payment_method}:{}),...(row.payment_condition?{paymentCondition:row.payment_condition}:{}),...(row.xml_url?{xmlUrl:row.xml_url}:{}),...(row.additional_info?{additionalInfo:row.additional_info}:{}),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),
})
const normalizeInvoice=(input,current={})=>({
  number:requiredText(input.number??current.number,'number'),series:text(input.series??current.series)||'001',type:enumValue(input.type??current.type,INVOICE_TYPES,'type'),party:requiredText(input.party??current.party,'party'),document:text(input.document??current.document),issueDate:dateValue(input.issueDate??current.issueDate,'issueDate',{required:true}),dueDate:dateValue(input.dueDate??current.dueDate,'dueDate'),amount:numberValue(input.amount??current.amount,'amount',{required:true}),status:enumValue(input.status??current.status??'pendente',INVOICE_STATUS,'status'),description:text(input.description??current.description),pdfUrl:text(input.pdfUrl??current.pdfUrl),model:optionalText(input.model??current.model),accessKey:optionalText(input.accessKey??current.accessKey),operationNature:optionalText(input.operationNature??current.operationNature),cfop:optionalText(input.cfop??current.cfop),entryExitDate:dateValue(input.entryExitDate??current.entryExitDate,'entryExitDate'),stateRegistration:optionalText(input.stateRegistration??current.stateRegistration),municipalRegistration:optionalText(input.municipalRegistration??current.municipalRegistration),email:optionalText(input.email??current.email),phone:optionalText(input.phone??current.phone),address:optionalText(input.address??current.address),city:optionalText(input.city??current.city),state:optionalText(input.state??current.state),zipCode:optionalText(input.zipCode??current.zipCode),productsAmount:numberValue(input.productsAmount??current.productsAmount,'productsAmount'),freightAmount:numberValue(input.freightAmount??current.freightAmount,'freightAmount'),insuranceAmount:numberValue(input.insuranceAmount??current.insuranceAmount,'insuranceAmount'),discountAmount:numberValue(input.discountAmount??current.discountAmount,'discountAmount'),otherExpenses:numberValue(input.otherExpenses??current.otherExpenses,'otherExpenses'),icmsBase:numberValue(input.icmsBase??current.icmsBase,'icmsBase'),icmsAmount:numberValue(input.icmsAmount??current.icmsAmount,'icmsAmount'),ipiAmount:numberValue(input.ipiAmount??current.ipiAmount,'ipiAmount'),pisAmount:numberValue(input.pisAmount??current.pisAmount,'pisAmount'),cofinsAmount:numberValue(input.cofinsAmount??current.cofinsAmount,'cofinsAmount'),issAmount:numberValue(input.issAmount??current.issAmount,'issAmount'),paymentMethod:optionalText(input.paymentMethod??current.paymentMethod),paymentCondition:optionalText(input.paymentCondition??current.paymentCondition),xmlUrl:optionalText(input.xmlUrl??current.xmlUrl),additionalInfo:optionalText(input.additionalInfo??current.additionalInfo),
})

const mapCategory=row=>({id:row.id,category:row.category,subcategory:row.subcategory,type:row.transaction_type,counterparty:row.counterparty,active:Boolean(row.active)})
const normalizeCategory=(input,current={})=>({category:requiredText(input.category??current.category,'category'),subcategory:requiredText(input.subcategory??current.subcategory,'subcategory'),type:enumValue(input.type??current.type,TRANSACTION_TYPES,'type'),counterparty:text(input.counterparty??current.counterparty),active:input.active===undefined?(current.active??true):Boolean(input.active)})
const mapRule=row=>({id:row.id,name:row.name,event:row.event_type,condition:row.condition_text,action:row.action_text,active:Boolean(row.active)})
const normalizeRule=(input,current={})=>({name:requiredText(input.name??current.name,'name'),event:enumValue(input.event??current.event,RULE_EVENTS,'event'),condition:requiredText(input.condition??current.condition,'condition'),action:requiredText(input.action??current.action,'action'),active:input.active===undefined?(current.active??true):Boolean(input.active)})

async function selectOne(client,table,id,{lock=false}={}){const allowed=new Set(['finance_transactions','finance_invoices','finance_categories','finance_rules']);if(!allowed.has(table))throw new Error('Invalid finance table');const {rows}=await client.query(`select * from ${table} where id=$1${lock?' for update':''}`,[id]);if(!rows[0])throw new HttpError(404,'Registro financeiro não encontrado.','FINANCE_NOT_FOUND');return rows[0]}

export const financeService={
  async listTransactions(){const {rows}=await getPool().query('select * from finance_transactions order by transaction_date desc,created_at desc');return rows.map(mapTransaction)},
  async createTransaction(input,userId=null){const v=normalizeTransaction(input);const id=`finance_tx_${randomUUID()}`;const {rows}=await getPool().query(`insert into finance_transactions(id,transaction_type,description,category,subcategory,status,transaction_date,due_date,amount,counterparty,document,payment_method,payment_type,installment_count,installment_interval,first_installment_date,contract_ref,contact_ref,supplier_ref,cost_center,competence,notes,attachment_name,attachment_data_url,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$25) returning *`,[id,v.type,v.description,v.category,v.subcategory,v.status,v.date,v.dueDate,v.amount,v.counterparty,v.document,v.paymentMethod,v.paymentType,v.installmentCount,v.installmentInterval,v.firstInstallmentDate,v.contractRef,v.contactRef,v.supplierRef,v.costCenter,v.competence,v.notes,v.attachmentName,v.attachmentDataUrl,userId]);return mapTransaction(rows[0])},
  async updateTransaction(id,patch,expectedUpdatedAt,userId=null){return withTransaction(async client=>{const row=await selectOne(client,'finance_transactions',id,{lock:true}),current=mapTransaction(row);conflict(current.updatedAt,expectedUpdatedAt);const v=normalizeTransaction(patch,current);const {rows}=await client.query(`update finance_transactions set transaction_type=$2,description=$3,category=$4,subcategory=$5,status=$6,transaction_date=$7,due_date=$8,amount=$9,counterparty=$10,document=$11,payment_method=$12,payment_type=$13,installment_count=$14,installment_interval=$15,first_installment_date=$16,contract_ref=$17,contact_ref=$18,supplier_ref=$19,cost_center=$20,competence=$21,notes=$22,attachment_name=$23,attachment_data_url=$24,updated_by=$25 where id=$1 returning *`,[id,v.type,v.description,v.category,v.subcategory,v.status,v.date,v.dueDate,v.amount,v.counterparty,v.document,v.paymentMethod,v.paymentType,v.installmentCount,v.installmentInterval,v.firstInstallmentDate,v.contractRef,v.contactRef,v.supplierRef,v.costCenter,v.competence,v.notes,v.attachmentName,v.attachmentDataUrl,userId]);return mapTransaction(rows[0])})},
  async removeTransaction(id){const result=await getPool().query('delete from finance_transactions where id=$1',[id]);if(!result.rowCount)throw new HttpError(404,'Transação não encontrada.','FINANCE_TRANSACTION_NOT_FOUND')},

  async listInvoices(){const {rows}=await getPool().query('select * from finance_invoices order by issue_date desc,created_at desc');return rows.map(mapInvoice)},
  async createInvoice(input,userId=null){const v=normalizeInvoice(input);const id=`finance_nf_${randomUUID()}`;const {rows}=await getPool().query(`insert into finance_invoices(id,invoice_number,series,invoice_type,party,document,issue_date,due_date,amount,status,description,pdf_url,model,access_key,operation_nature,cfop,entry_exit_date,state_registration,municipal_registration,email,phone,address,city,state,zip_code,products_amount,freight_amount,insurance_amount,discount_amount,other_expenses,icms_base,icms_amount,ipi_amount,pis_amount,cofins_amount,iss_amount,payment_method,payment_condition,xml_url,additional_info,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$41) returning *`,[id,v.number,v.series,v.type,v.party,v.document,v.issueDate,v.dueDate,v.amount,v.status,v.description,v.pdfUrl,v.model,v.accessKey,v.operationNature,v.cfop,v.entryExitDate,v.stateRegistration,v.municipalRegistration,v.email,v.phone,v.address,v.city,v.state,v.zipCode,v.productsAmount,v.freightAmount,v.insuranceAmount,v.discountAmount,v.otherExpenses,v.icmsBase,v.icmsAmount,v.ipiAmount,v.pisAmount,v.cofinsAmount,v.issAmount,v.paymentMethod,v.paymentCondition,v.xmlUrl,v.additionalInfo,userId]);return mapInvoice(rows[0])},
  async updateInvoice(id,patch,expectedUpdatedAt,userId=null){return withTransaction(async client=>{const row=await selectOne(client,'finance_invoices',id,{lock:true}),current=mapInvoice(row);conflict(current.updatedAt,expectedUpdatedAt);const v=normalizeInvoice(patch,current);const {rows}=await client.query(`update finance_invoices set invoice_number=$2,series=$3,invoice_type=$4,party=$5,document=$6,issue_date=$7,due_date=$8,amount=$9,status=$10,description=$11,pdf_url=$12,model=$13,access_key=$14,operation_nature=$15,cfop=$16,entry_exit_date=$17,state_registration=$18,municipal_registration=$19,email=$20,phone=$21,address=$22,city=$23,state=$24,zip_code=$25,products_amount=$26,freight_amount=$27,insurance_amount=$28,discount_amount=$29,other_expenses=$30,icms_base=$31,icms_amount=$32,ipi_amount=$33,pis_amount=$34,cofins_amount=$35,iss_amount=$36,payment_method=$37,payment_condition=$38,xml_url=$39,additional_info=$40,updated_by=$41 where id=$1 returning *`,[id,v.number,v.series,v.type,v.party,v.document,v.issueDate,v.dueDate,v.amount,v.status,v.description,v.pdfUrl,v.model,v.accessKey,v.operationNature,v.cfop,v.entryExitDate,v.stateRegistration,v.municipalRegistration,v.email,v.phone,v.address,v.city,v.state,v.zipCode,v.productsAmount,v.freightAmount,v.insuranceAmount,v.discountAmount,v.otherExpenses,v.icmsBase,v.icmsAmount,v.ipiAmount,v.pisAmount,v.cofinsAmount,v.issAmount,v.paymentMethod,v.paymentCondition,v.xmlUrl,v.additionalInfo,userId]);return mapInvoice(rows[0])})},
  async removeInvoice(id){const result=await getPool().query('delete from finance_invoices where id=$1',[id]);if(!result.rowCount)throw new HttpError(404,'Nota fiscal não encontrada.','FINANCE_INVOICE_NOT_FOUND')},

  async listCategories(){const {rows}=await getPool().query('select * from finance_categories order by category asc,subcategory asc');return rows.map(mapCategory)},
  async createCategory(input,userId=null){const v=normalizeCategory(input),id=`finance_category_${randomUUID()}`;const {rows}=await getPool().query('insert into finance_categories(id,category,subcategory,transaction_type,counterparty,active,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$7) returning *',[id,v.category,v.subcategory,v.type,v.counterparty,v.active,userId]);return mapCategory(rows[0])},
  async updateCategory(id,patch,userId=null){return withTransaction(async client=>{const current=mapCategory(await selectOne(client,'finance_categories',id,{lock:true})),v=normalizeCategory(patch,current);const {rows}=await client.query('update finance_categories set category=$2,subcategory=$3,transaction_type=$4,counterparty=$5,active=$6,updated_by=$7 where id=$1 returning *',[id,v.category,v.subcategory,v.type,v.counterparty,v.active,userId]);return mapCategory(rows[0])})},
  async removeCategory(id){const result=await getPool().query('delete from finance_categories where id=$1',[id]);if(!result.rowCount)throw new HttpError(404,'Categoria financeira não encontrada.','FINANCE_CATEGORY_NOT_FOUND')},

  async listRules(){const {rows}=await getPool().query('select * from finance_rules order by created_at desc');return rows.map(mapRule)},
  async createRule(input,userId=null){const v=normalizeRule(input),id=`finance_rule_${randomUUID()}`;const {rows}=await getPool().query('insert into finance_rules(id,name,event_type,condition_text,action_text,active,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$7) returning *',[id,v.name,v.event,v.condition,v.action,v.active,userId]);return mapRule(rows[0])},
  async updateRule(id,patch,userId=null){return withTransaction(async client=>{const current=mapRule(await selectOne(client,'finance_rules',id,{lock:true})),v=normalizeRule(patch,current);const {rows}=await client.query('update finance_rules set name=$2,event_type=$3,condition_text=$4,action_text=$5,active=$6,updated_by=$7 where id=$1 returning *',[id,v.name,v.event,v.condition,v.action,v.active,userId]);return mapRule(rows[0])})},
  async removeRule(id){const result=await getPool().query('delete from finance_rules where id=$1',[id]);if(!result.rowCount)throw new HttpError(404,'Regra financeira não encontrada.','FINANCE_RULE_NOT_FOUND')},
}
