import {randomUUID} from 'node:crypto'
import {getPool,withTransaction} from './db.js'
import {HttpError} from './editorialService.js'

const EMPLOYEE_STATUS=new Set(['ativo','inativo','férias','afastado','desligado'])
const CONTRACT_TYPES=new Set(['CLT','PJ','Estágio','Temporário','Autônomo'])
const PAYROLL_STATUS=new Set(['pendente','processado','pago','cancelado'])
const LEAVE_STATUS=new Set(['pendente','aprovado','rejeitado','em andamento','concluído'])
const LOOKUPS={departments:['Administrativo','Comercial','Financeiro','Marketing','Operações','Tecnologia'],documentTypes:['Contrato de Trabalho','Documento Pessoal','Atestado','Comprovante','Certificado','Outro'],leaveTypes:['férias','atestado','licença médica','licença maternidade/paternidade','falta justificada','afastamento']}
const text=value=>value===undefined||value===null?'':String(value).trim()
const number=value=>{const result=Number(value);return Number.isFinite(result)?result:0}
const now=()=>new Date().toISOString()
const uid=prefix=>`${prefix}_${randomUUID()}`
const clone=value=>structuredClone(value)
const daysBetween=(start,end)=>{if(!start||!end)return 0;const a=new Date(`${start}T00:00:00Z`).getTime(),b=new Date(`${end}T00:00:00Z`).getTime();return Number.isFinite(a)&&Number.isFinite(b)?Math.max(0,Math.round((b-a)/86400000)+1):0}
const emptyState=()=>({employees:[],payroll:[],leaves:[],documents:[],...LOOKUPS})
const ensureState=value=>{const state=value&&typeof value==='object'&&!Array.isArray(value)?value:{};return {employees:Array.isArray(state.employees)?state.employees:[],payroll:Array.isArray(state.payroll)?state.payroll:[],leaves:Array.isArray(state.leaves)?state.leaves:[],documents:Array.isArray(state.documents)?state.documents:[],...LOOKUPS}}
const required=(value,message,code)=>{const result=text(value);if(!result)throw new HttpError(400,message,code);return result}
const validateDate=(value,{requiredValue=false,code='RH_DATE_INVALID'}={})=>{const result=text(value);if(!result&&!requiredValue)return'';if(!/^\d{4}-\d{2}-\d{2}$/.test(result))throw new HttpError(400,'Data deve usar YYYY-MM-DD.',code);return result}
const validateMonth=value=>{const result=required(value,'Mês de referência obrigatório.','RH_REFERENCE_MONTH_REQUIRED');if(!/^\d{4}-\d{2}$/.test(result))throw new HttpError(400,'Mês de referência deve usar YYYY-MM.','RH_REFERENCE_MONTH_INVALID');return result}

async function actor(userId,client=getPool()){const {rows}=await client.query('select id,email,display_name from admin_users where id=$1 and active=true',[userId]);if(!rows[0])throw new HttpError(401,'Usuário administrativo inválido.','RH_AUTH_USER_INVALID');return {id:rows[0].id,email:rows[0].email,name:text(rows[0].display_name)||rows[0].email}}
async function load(client,{lock=false,userId=null}={}){await client.query("insert into rh_admin_state(id,payload,created_by,updated_by) values('primary',$1,$2,$2) on conflict (id) do nothing",[JSON.stringify(emptyState()),userId]);const {rows}=await client.query(`select payload,version,updated_at from rh_admin_state where id='primary'${lock?' for update':''}`);return {state:ensureState(rows[0]?.payload),version:Number(rows[0]?.version||1),updatedAt:rows[0]?.updated_at?new Date(rows[0].updated_at).toISOString():''}}
async function persist(client,state,userId){const {rows}=await client.query("update rh_admin_state set payload=$1,version=version+1,created_by=coalesce(created_by,$2),updated_by=$2 where id='primary' returning version,updated_at",[JSON.stringify(state),userId]);return {state,version:Number(rows[0].version),updatedAt:new Date(rows[0].updated_at).toISOString()}}
async function mutate(userId,work){return withTransaction(async client=>{const loaded=await load(client,{lock:true,userId}),result=await work(loaded.state,client);const saved=await persist(client,loaded.state,userId);return {saved,result}})}
const withRuntime=snapshot=>({...clone(snapshot.state),runtime:{documentUpload:{configured:false}},meta:{version:snapshot.version,updatedAt:snapshot.updatedAt}})
async function currentState(){return withRuntime(await load(getPool()))}
function requireEmployee(state,id){const employee=state.employees.find(item=>item.id===id);if(!employee)throw new HttpError(404,'Funcionário não encontrado.','RH_EMPLOYEE_NOT_FOUND');return employee}
function employeeInput(input){const status=text(input?.status)||'ativo',contractType=text(input?.contractType)||'CLT';if(!EMPLOYEE_STATUS.has(status))throw new HttpError(400,'Status de funcionário inválido.','RH_EMPLOYEE_STATUS_INVALID');if(!CONTRACT_TYPES.has(contractType))throw new HttpError(400,'Tipo de contrato inválido.','RH_CONTRACT_TYPE_INVALID');return {name:required(input?.name,'Nome do funcionário obrigatório.','RH_EMPLOYEE_NAME_REQUIRED'),email:text(input?.email),cpf:text(input?.cpf),rg:text(input?.rg),birthDate:validateDate(input?.birthDate),phone:text(input?.phone),address:text(input?.address),role:text(input?.role),department:text(input?.department),contractType,admissionDate:validateDate(input?.admissionDate),baseSalary:Math.max(0,number(input?.baseSalary)),status,linkedUser:text(input?.linkedUser),notes:text(input?.notes)}}
function payrollInput(input){const status=text(input?.status)||'pendente';if(!PAYROLL_STATUS.has(status))throw new HttpError(400,'Status da folha inválido.','RH_PAYROLL_STATUS_INVALID');const grossSalary=Math.max(0,number(input?.grossSalary)),discounts=Math.max(0,number(input?.discounts)),bonus=Math.max(0,number(input?.bonus));return {employeeId:required(input?.employeeId,'Funcionário obrigatório.','RH_PAYROLL_EMPLOYEE_REQUIRED'),referenceMonth:validateMonth(input?.referenceMonth),grossSalary,discounts,bonus,netSalary:Math.max(0,grossSalary-discounts+bonus),paymentDate:validateDate(input?.paymentDate),status,notes:text(input?.notes)}}
function leaveInput(input){const status=text(input?.status)||'pendente',startDate=validateDate(input?.startDate,{requiredValue:true}),endDate=validateDate(input?.endDate,{requiredValue:true});if(!LEAVE_STATUS.has(status))throw new HttpError(400,'Status de ausência inválido.','RH_LEAVE_STATUS_INVALID');if(endDate<startDate)throw new HttpError(400,'Data final deve ser igual ou posterior à inicial.','RH_LEAVE_RANGE_INVALID');return {employeeId:required(input?.employeeId,'Funcionário obrigatório.','RH_LEAVE_EMPLOYEE_REQUIRED'),type:required(input?.type,'Tipo de ausência obrigatório.','RH_LEAVE_TYPE_REQUIRED'),startDate,endDate,days:daysBetween(startDate,endDate),status,notes:text(input?.notes)}}
function approvalFields(status,who,existing={}){if(status!=='aprovado')return {approvedBy:'',approvedByUserId:null,approvedByDisplayName:'',approvedAt:null};if(existing.status==='aprovado'&&existing.approvedByUserId)return {approvedBy:existing.approvedByDisplayName||existing.approvedBy||who.name,approvedByUserId:existing.approvedByUserId,approvedByDisplayName:existing.approvedByDisplayName||existing.approvedBy||who.name,approvedAt:existing.approvedAt||now()};const at=now();return {approvedBy:who.name,approvedByUserId:who.id,approvedByDisplayName:who.name,approvedAt:at}}

export const rhService={
 async state(){return currentState()},
 async saveEmployee(input,id,userId){const result=await mutate(userId,state=>{const value=employeeInput(input),stamp=now();if(id){const existing=requireEmployee(state,id),next={...existing,...value,updatedAt:stamp};state.employees=state.employees.map(item=>item.id===id?next:item);return next}const created={...value,id:uid('emp'),createdAt:stamp,updatedAt:stamp};state.employees.unshift(created);return created});return {item:clone(result.result),state:await currentState()}},
 async deleteEmployees(ids,userId){const list=Array.isArray(ids)?ids.map(String).filter(Boolean):[];if(!list.length)throw new HttpError(400,'Selecione ao menos um funcionário.','RH_EMPLOYEE_IDS_REQUIRED');await mutate(userId,state=>{const set=new Set(list);state.employees=state.employees.filter(item=>!set.has(item.id));state.payroll=state.payroll.filter(item=>!set.has(item.employeeId));state.leaves=state.leaves.filter(item=>!set.has(item.employeeId));state.documents=state.documents.filter(item=>!set.has(item.employeeId))});return currentState()},
 async savePayroll(input,id,userId){const result=await mutate(userId,state=>{const value=payrollInput(input);requireEmployee(state,value.employeeId);const stamp=now();if(id){const existing=state.payroll.find(item=>item.id===id);if(!existing)throw new HttpError(404,'Registro de pagamento não encontrado.','RH_PAYROLL_NOT_FOUND');const next={...existing,...value,updatedAt:stamp};state.payroll=state.payroll.map(item=>item.id===id?next:item);return next}const created={...value,id:uid('pay'),createdAt:stamp,updatedAt:stamp};state.payroll.unshift(created);return created});return {item:clone(result.result),state:await currentState()}},
 async deletePayroll(ids,userId){const list=Array.isArray(ids)?ids.map(String).filter(Boolean):[];if(!list.length)throw new HttpError(400,'Selecione ao menos um registro.','RH_PAYROLL_IDS_REQUIRED');await mutate(userId,state=>{const set=new Set(list);state.payroll=state.payroll.filter(item=>!set.has(item.id))});return currentState()},
 async saveLeave(input,id,userId){const result=await mutate(userId,async(state,client)=>{const value=leaveInput(input);requireEmployee(state,value.employeeId);const who=await actor(userId,client),stamp=now();if(id){const existing=state.leaves.find(item=>item.id===id);if(!existing)throw new HttpError(404,'Férias/ausência não encontrada.','RH_LEAVE_NOT_FOUND');const next={...existing,...value,...approvalFields(value.status,who,existing),updatedAt:stamp};state.leaves=state.leaves.map(item=>item.id===id?next:item);return next}const created={...value,...approvalFields(value.status,who),id:uid('leave'),createdAt:stamp,updatedAt:stamp};state.leaves.unshift(created);return created});return {item:clone(result.result),state:await currentState()}},
 async deleteLeaves(ids,userId){const list=Array.isArray(ids)?ids.map(String).filter(Boolean):[];if(!list.length)throw new HttpError(400,'Selecione ao menos um registro.','RH_LEAVE_IDS_REQUIRED');await mutate(userId,state=>{const set=new Set(list);state.leaves=state.leaves.filter(item=>!set.has(item.id))});return currentState()},
 async deleteDocument(id,userId){await mutate(userId,state=>{const before=state.documents.length;state.documents=state.documents.filter(item=>item.id!==id);if(state.documents.length===before)throw new HttpError(404,'Documento não encontrado.','RH_DOCUMENT_NOT_FOUND')});return currentState()},
 async assertDocumentUploadUnavailable(){throw new HttpError(409,'Upload de documentos ainda não possui storage persistente configurado.','RH_DOCUMENT_UPLOAD_UNAVAILABLE')},
}
