import {RotateCcw} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {AdminNotice,AdminShell} from '../../../shared/internal/AdminUi'
import {SITE_MANAGER_NAV} from '../../../shared/internal/adminNavigation'
import {HomePagePreviewFrame} from '../components/HomePagePreviewFrame'
import {SectionEditorField as Field,SectionEditorSaveBar,SectionEditorSummaryCard,SectionEditorTabButton as Tab,SectionViewportSwitch,type SectionEditorTabId as EditorTab} from '../components/SectionEditorUi'
import {SectionMediaField} from '../components/SectionMediaField'
import {advertisingViewportLayout,withAdvertisingSectionLayout,type AdvertisingAlignment,type AdvertisingSectionConfiguration} from '../advertisingSectionLayout'
import {loadAdminHomeSection,saveHomeSection} from '../homeSectionConfigRepository'
import {defaultSectionConfiguration,type SectionHeroViewport} from '../sectionConfiguration'
import '../../../styles/section-configuration-editor.css'
import '../../../styles/section-editor-workbench.css'
import '../../../styles/home-advertising-editor.css'

type AdvertisingSectionId='publicidade-lateral'|'anuncie-aqui'
const labels:Record<AdvertisingSectionId,{name:string;summary:string}>={
  'publicidade-lateral':{name:'Publicidade Lateral',summary:'Publicidade lateral da Página Inicial; em Tablet/Mobile migra para o fluxo principal.'},
  'anuncie-aqui':{name:'Anuncie Aqui',summary:'Banner comercial da Página Inicial com arte, clique e adaptação responsiva.'},
}
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value))
const viewportLabel=(viewport:SectionHeroViewport)=>viewport==='desktop'?'Desktop':viewport==='tablet'?'Tablet':'Mobile'

export function HomeAdvertisingSectionPage({sectionId}:{sectionId:AdvertisingSectionId}){
  const meta=labels[sectionId]
  const initial=()=>withAdvertisingSectionLayout(defaultSectionConfiguration(sectionId,meta.name),sectionId)
  const [config,setConfig]=useState<AdvertisingSectionConfiguration>(initial)
  const [persisted,setPersisted]=useState<AdvertisingSectionConfiguration>(initial)
  const [viewport,setViewport]=useState<SectionHeroViewport>('desktop')
  const [tab,setTab]=useState<EditorTab>('content')
  const [loading,setLoading]=useState(true)
  const [saving,setSaving]=useState(false)
  const [message,setMessage]=useState('')
  const [error,setError]=useState('')
  const dirty=JSON.stringify(config)!==JSON.stringify(persisted)
  const title=useMemo(()=>`Configurar seção: ${meta.name}`,[meta.name])
  const isSidebar=sectionId==='publicidade-lateral'
  useEffect(()=>{let active=true;void loadAdminHomeSection(sectionId,meta.name).then(value=>{if(!active)return;const normalized=withAdvertisingSectionLayout(value,sectionId);setConfig(normalized);setPersisted(normalized)}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:'Falha ao carregar a configuração persistida.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[sectionId,meta.name])
  const patch=(next:Partial<AdvertisingSectionConfiguration>)=>{setConfig(current=>({...current,...next}));setMessage('');setError('')}
  const reset=()=>{setConfig(withAdvertisingSectionLayout(defaultSectionConfiguration(sectionId,meta.name),sectionId));setMessage('');setError('')}
  const discard=()=>{setConfig(persisted);setMessage('');setError('')}
  const save=async()=>{if(saving)return;setSaving(true);setMessage('');setError('');try{const saved=withAdvertisingSectionLayout(await saveHomeSection(sectionId,meta.name,config),sectionId);setConfig(saved);setPersisted(saved);setMessage('Configuração persistida com sucesso.')}catch(caught){setConfig(persisted);setError(caught instanceof Error?`${caught.message} A publicidade publicada anteriormente foi preservada.`:'Falha ao salvar. O estado publicado anterior foi preservado.')}finally{setSaving(false)}}
  const desktop=advertisingViewportLayout(config,'desktop')
  return <AdminShell area="cms" items={SITE_MANAGER_NAV} header={{title,description:`Configure ${meta.name} no painel rolável à esquerda e acompanhe a Página Inicial completa no preview fixo à direita.`,backTo:'/app/site/paginas',backLabel:'Páginas'}}>
    {loading&&<AdminNotice title={`Sincronizando ${meta.name}`} description="Carregando a configuração persistida antes de abrir o editor."/>}{error&&<AdminNotice title="Falha na configuração" description={error}/>} 
    {!loading&&<div className="section-editor-workbench"><div className="section-editor-rail" aria-label={`Configurações da seção ${meta.name}`}><SectionEditorSummaryCard eyebrow={meta.name.toUpperCase()} description={meta.summary} active={config.active} onActiveChange={active=>patch({active})}/><div className="section-editor-tabs"><Tab active={tab==='content'} label="Conteúdo" onClick={()=>setTab('content')}/><Tab active={tab==='appearance'} label="Aparência" onClick={()=>setTab('appearance')}/><Tab active={tab==='behavior'} label="Comportamento" onClick={()=>setTab('behavior')}/></div><section className="section-editor-card section-editor-detail">
      {tab==='content'&&<><div className="section-editor-card-head"><h3>Conteúdo</h3><p>Gerencie a arte, o conteúdo alternativo e o destino clicável.</p></div><div className="section-config-fields"><SectionMediaField value={config.imageUrl} onChange={imageUrl=>patch({imageUrl})} label="Imagem do anúncio"/><Field label="Texto alternativo da imagem"><input value={config.adImageAlt} onChange={event=>patch({adImageAlt:event.target.value})} placeholder={`Publicidade ${meta.name}`}/></Field><div className="home-advertising-copy-card"><strong>Conteúdo exibido quando não houver imagem</strong><Field label="Chamada superior"><input value={config.eyebrow} onChange={event=>patch({eyebrow:event.target.value})}/></Field><Field label="Título principal"><input value={config.title} onChange={event=>patch({title:event.target.value})}/></Field><Field label="Descrição"><textarea rows={3} value={config.description} onChange={event=>patch({description:event.target.value})}/></Field><Field label="Texto do botão"><input value={config.linkLabel} onChange={event=>patch({linkLabel:event.target.value})}/></Field></div><div className="home-advertising-link-card"><label className="section-config-switch"><input type="checkbox" checked={config.adLinkEnabled} onChange={event=>patch({adLinkEnabled:event.target.checked})}/><span>Área inteira clicável</span></label><div className="section-config-two"><Field label="URL de destino"><input value={config.linkUrl} onChange={event=>patch({linkUrl:event.target.value})} placeholder="https://... ou /pagina"/></Field><Field label="Abrir link"><select value={config.adLinkTarget} onChange={event=>patch({adLinkTarget:event.target.value as AdvertisingSectionConfiguration['adLinkTarget']})}><option value="same">Na mesma aba</option><option value="new">Em nova aba</option></select></Field></div></div></div></>}
      {tab==='appearance'&&<><div className="section-editor-card-head"><h3>Aparência</h3><p>Ajuste a apresentação da arte sem alterar o padrão do editor.</p></div><div className="section-config-fields"><Field label="Ajuste da imagem"><select value={config.adImageFit} onChange={event=>patch({adImageFit:event.target.value as AdvertisingSectionConfiguration['adImageFit']})}><option value="contain">Conter inteira — preserva toda a arte</option><option value="cover">Preencher — corte proporcional quando necessário</option></select></Field><div className="section-config-colors"><Field label="Fundo"><input type="color" value={config.background} onChange={event=>patch({background:event.target.value})}/></Field><Field label="Texto"><input type="color" value={config.textColor} onChange={event=>patch({textColor:event.target.value})}/></Field><Field label="Destaque"><input type="color" value={config.accentColor} onChange={event=>patch({accentColor:event.target.value})}/></Field></div></div></>}
      {tab==='behavior'&&<><div className="section-editor-card-head"><h3>Comportamento</h3><p>Configure dimensões e alinhamento preservando a responsividade pública.</p></div><div className="section-config-fields"><div className="section-editor-rule"><strong>Comportamento responsivo</strong><p>{isSidebar?'No Desktop permanece lateral; em Tablet/Mobile migra para o fluxo principal sem deformar a arte.':'O banner responde ao viewport real de Desktop, Tablet e Mobile sem duplicar conteúdo.'}</p><span className="section-editor-device-badge">{viewportLabel(viewport)}</span></div><div className="home-advertising-device-card"><div className="home-advertising-device-card-head"><strong>Layout Desktop de referência</strong><span>Tablet e Mobile são derivados automaticamente deste componente.</span></div><div className="section-config-two"><Field label={`Largura · ${desktop.width||'100%'}${desktop.width?'px':''}`}><input type="number" min="0" max="1920" value={desktop.width} onChange={event=>patch({adWidthDesktop:clamp(Number(event.target.value)||0,0,1920)})}/></Field><Field label={`Altura · ${desktop.height||'automática'}${desktop.height?'px':''}`}><input type="number" min="0" max="1600" value={desktop.height} onChange={event=>patch({adHeightDesktop:clamp(Number(event.target.value)||0,0,1600)})}/></Field></div><Field label="Alinhamento Desktop"><select value={desktop.align} onChange={event=>patch({adAlignDesktop:event.target.value as AdvertisingAlignment})}><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></Field></div></div></>}
    </section><div className="section-editor-actions"><button type="button" className="button outline" disabled={saving} onClick={reset}><RotateCcw size={15}/> Restaurar padrão</button></div>{message&&<div className="section-config-success" role="status">{message}</div>}</div><section className="section-editor-preview"><div className="section-editor-preview-head"><div><h2>Preview da página inteira</h2><p>{viewportLabel(viewport)} · edição em tempo real · alterações refletidas antes de salvar.</p></div><SectionViewportSwitch viewport={viewport} onChange={setViewport}/></div><div className="section-editor-preview-canvas"><HomePagePreviewFrame sectionId={sectionId} configuration={config} viewport={viewport}/></div></section></div>}
    {!loading&&<SectionEditorSaveBar dirty={dirty} saving={saving} onDiscard={discard} onSave={()=>void save()} dirtyText="O preview já mostra o rascunho; a Home pública só muda após salvar." cleanText="O estado salvo continua sendo usado pela Home."/>}
  </AdminShell>
}
