import { FileText, Globe2, Images, Newspaper } from 'lucide-react'
import { AdminEmpty, AdminKpi, AdminPageHeader, AdminShell } from '../../shared/internal/AdminUi'
import { SITE_MANAGER_NAV } from '../../shared/internal/adminNavigation'
import { editorialReadModel } from '../editorial/repository'

function ReadOnlyNotice(){return <div className="admin-notice"><div><strong>Configuração em modo leitura</strong><p>Sem backend ou banco conectado, esta área apresenta somente a estrutura prevista. Alterações permanecem desabilitadas para não simular persistência.</p></div></div>}

export function MediaKitPage(){
  const published=editorialReadModel.contents.filter(content=>content.status==='published'&&content.active).length
  const pages=editorialReadModel.pages.filter(page=>page.active).length
  return <AdminShell area="cms" items={SITE_MANAGER_NAV}><AdminPageHeader eyebrow="Gerenciador do Site / Mídia Kit" title="Mídia Kit" description="Estrutura administrativa para materiais comerciais, audiência e apresentação institucional." action="Editar mídia kit" disabled/><ReadOnlyNotice/><div className="admin-kpi-grid"><AdminKpi label="Páginas ativas" value={String(pages)} detail="Estrutura editorial atual" icon={<Globe2 size={16}/>}/><AdminKpi label="Publicados" value={String(published)} detail="Conteúdos públicos" icon={<Newspaper size={16}/>}/><AdminKpi label="Assets" value="—" detail="Aguardando biblioteca persistente" icon={<Images size={16}/>}/><AdminKpi label="Versão" value="Rascunho" detail="Sem persistência habilitada" icon={<FileText size={16}/>}/></div><div className="admin-grid"><section className="admin-card"><div className="admin-card-head"><div><span>Comercial</span><h2>Estrutura prevista</h2></div></div><div className="settings-list"><div><b>Apresentação institucional</b><small>Resumo do Portal Lander, posicionamento e proposta comercial.</small></div><div><b>Formatos publicitários</b><small>Inventário de espaços, formatos e especificações.</small></div><div><b>Audiência e métricas</b><small>Indicadores reais deverão vir da camada de analytics quando conectada.</small></div><div><b>Contato comercial</b><small>Responsáveis, canais e informações de atendimento.</small></div></div></section><section className="admin-card"><div className="admin-card-head"><div><span>Estado atual</span><h2>Sem publicação automática</h2></div></div><p>O mídia kit ainda não possui uma fonte persistente própria. Esta tela define a arquitetura visual e os blocos necessários sem criar conteúdo comercial fictício.</p></section></div></AdminShell>
}

export function SiteSettingsPage(){return <AdminShell area="cms" items={SITE_MANAGER_NAV}><AdminPageHeader eyebrow="Gerenciador do Site / Configurações" title="Configurações" description="Parâmetros editoriais, navegação e comportamento administrativo do portal." action="Salvar alterações" disabled/><ReadOnlyNotice/><div className="admin-grid"><section className="admin-card"><div className="admin-card-head"><div><span>Editorial</span><h2>Publicação e navegação</h2></div></div><div className="settings-list"><div><b>Menu principal</b><small>Controlado pelos campos de página e ordem editorial existentes.</small><span className="status published">Estruturado</span></div><div><b>SEO por página/conteúdo</b><small>Meta title, description, canonical e Open Graph já fazem parte do modelo.</small><span className="status published">Estruturado</span></div><div><b>Persistência</b><small>Backend e banco ainda não conectados.</small><span className="status draft">Pendente</span></div></div></section><section className="admin-card"><div className="admin-card-head"><div><span>Sistema</span><h2>Recursos administrativos</h2></div></div><div className="settings-list"><div><b>Autenticação administrativa</b><small>Necessita camada real de autenticação e autorização antes de produção.</small></div><div><b>Biblioteca de mídia</b><small>Necessita armazenamento persistente e política de upload.</small></div><div><b>Auditoria</b><small>Necessita registro persistente de alterações e responsáveis.</small></div></div></section></div></AdminShell>}

export function SiteOperationsFallback(){return <AdminShell area="cms" items={SITE_MANAGER_NAV}><AdminEmpty title="Área não disponível" description="A rota solicitada ainda não possui uma implementação administrativa."/></AdminShell>}
