import { CircleDollarSign, FileText, Plus, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { CRM_NAV } from '../../shared/internal/adminNavigation'
import { AdminPageHeader, AdminShell } from '../../shared/internal/AdminUi'

type Section='financeiro'|'contabilidade'|'notas'|'categorias'|'financial-rules'|'transaction-rules'
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)
const rows=[['Publicidade Portal Lander','Receita','Publicidade','Recebido',8500],['Cobertura Festival Órbita','Receita','Eventos','Previsto',12000],['Ferramentas SaaS','Despesa','Software','Pago',-2480],['Produção editorial','Despesa','Produção','Pago',-3200]] as const
const meta:Record<Section,[string,string]>={financeiro:['Financeiro','Gestão de transações, receitas, despesas e fluxo financeiro.'],contabilidade:['Contabilidade','Demonstrativos, P&L e visão contábil.'],notas:['Notas Fiscais','Emissão, consulta e gerenciamento de notas fiscais.'],categorias:['Categorias Financeiras','Categorias e subcategorias utilizadas nas transações.'],'financial-rules':['Automações Financeiras','Regras automáticas e fluxos de automação financeira.'],'transaction-rules':['Regras de Categorização Financeira','Regras aplicadas à categorização automática das transações.']}
function Metric({title,value,detail}:{title:string;value:string;detail:string}){return <article className="zip-metric"><div className="zip-metric-icon"><CircleDollarSign size={18}/></div><div><span>{title}</span><strong>{value}</strong><small>{detail}</small></div></article>}
function Panel({children}:{children:React.ReactNode}){return <section className="zip-panel">{children}</section>}
export function AccountingSectionPage({section}:{section:Section}){const [query,setQuery]=useState('');const filtered=useMemo(()=>rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase())),[query]);const [title,description]=meta[section]
return <AdminShell area="crm" items={CRM_NAV}><AdminPageHeader eyebrow="CRM / FINANCEIRO" title={title} description={description}/><div className="zip-stack">
{section==='financeiro'&&<><div className="zip-kpi-grid five"><Metric title="Receita Mensal" value="R$ 20.500" detail="no período"/><Metric title="Despesas Mensais" value="R$ 5.680" detail="no período"/><Metric title="Lucro Líquido" value="R$ 14.820" detail="resultado"/><Metric title="Contas a Receber" value="R$ 12.000" detail="previstas"/><Metric title="Contas a Pagar" value="R$ 2.480" detail="pendentes"/></div><div className="zip-toolbar"><input type="date"/><input type="date"/><label className="zip-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar transações…"/></label><select><option>Tipo</option><option>Receita</option><option>Despesa</option></select><select><option>Status</option></select><select><option>Categoria</option></select><button className="zip-button"><Plus size={14}/> Nova Transação</button></div><Panel><header className="zip-panel-head"><div><h2>Transações</h2><p>{filtered.length} registros</p></div></header><div className="zip-table-wrap"><table className="zip-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Categoria</th><th>Status</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{filtered.map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td>{money(r[4])}</td><td><button className="zip-button secondary">Ver</button></td></tr>)}</tbody></table></div></Panel></>}
{section==='contabilidade'&&<><div className="zip-kpi-grid four"><Metric title="Receita Total" value="R$ 20.500" detail="receitas no período"/><Metric title="Despesa Total" value="R$ 5.680" detail="despesas no período"/><Metric title="Lucro Líquido" value="R$ 14.820" detail="resultado consolidado"/><Metric title="Margem Líquida" value="72%" detail="sobre receita"/></div><div className="zip-segmented four"><button className="active">Todos</button><button>P&L Empresa</button><button>P&L Projetos</button><button>P&L Artistas</button></div><Panel><header className="zip-panel-head"><div><h2>Demonstrativo de Resultado (P&L)</h2><p>Receitas, despesas e resultado</p></div></header><div className="zip-table-wrap"><table className="zip-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Status</th><th>Valor</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[3]}</td><td>{money(r[4])}</td></tr>)}</tbody></table></div></Panel></>}
{section==='notas'&&<><div className="zip-toolbar"><input type="date"/><input type="date"/><label className="zip-search"><Search size={14}/><input placeholder="Buscar por número, cliente ou fornecedor…"/></label><select><option>Tipo</option><option>NFS-e</option><option>NF-e</option></select><select><option>Status</option></select><button className="zip-button"><Plus size={14}/> Nova Nota</button></div><Panel><header className="zip-panel-head"><div><h2>Lista de Notas Fiscais</h2><p>Documentos fiscais</p></div></header><div className="reference-entity-row"><span className="reference-entity-icon"><FileText size={15}/></span><div className="reference-entity-copy"><strong>NFS-e #00018</strong><span>Norte Produções · R$ 8.500</span><small>29/08/2026 · Emitida</small></div><button className="zip-button secondary">Ver</button></div></Panel></>}
{section==='categorias'&&<Panel><header className="zip-panel-head"><div><h2>Lista de Categorias Financeiras</h2><p>Categorias e subcategorias</p></div><button className="zip-button"><Plus size={14}/> Nova Categoria</button></header>{['Publicidade','Eventos','Produção','Software','Administrativo'].map(x=><div className="reference-entity-row" key={x}><span className="reference-entity-icon"><CircleDollarSign size={15}/></span><div className="reference-entity-copy"><strong>{x}</strong><span>Receita / Despesa</span><small>Categoria ativa</small></div><button className="zip-button secondary">Editar</button></div>)}</Panel>}
{section==='financial-rules'&&<><div className="zip-toolbar"><label className="zip-search"><Search size={14}/><input placeholder="Buscar por palavra-chave ou categoria"/></label><select><option>Tipo</option></select><select><option>Origem</option></select><select><option>Status</option></select><button className="zip-button"><Plus size={14}/> Nova Regra</button></div><Panel><header className="zip-panel-head"><div><h2>Regras de Automação</h2><p>Automação e classificação financeira</p></div></header>{['Software → Software/SaaS','Meta Ads → Publicidade','PIX recebido → Receita'].map(x=><div className="reference-entity-row" key={x}><div className="reference-entity-copy"><strong>{x}</strong><span>Regra automática</span><small>Ativa</small></div><button className="zip-button secondary">Editar</button></div>)}</Panel></>}
{section==='transaction-rules'&&<><div className="zip-toolbar"><label className="zip-search"><Search size={14}/><input placeholder="Buscar regras de categorização"/></label><select><option>Origem/Destino</option></select><select><option>Produto/Sistema</option></select><select><option>Categoria</option></select><button className="zip-button"><Plus size={14}/> Nova Regra</button></div><Panel><header className="zip-panel-head"><div><h2>Regras de Categorização</h2><p>Origem, destino, produto/sistema e categoria</p></div></header><div className="zip-table-wrap"><table className="zip-table"><thead><tr><th>Regra</th><th>Origem/Destino</th><th>Produto/Sistema</th><th>Categoria</th><th>Status</th></tr></thead><tbody><tr><td>Recebimentos comerciais</td><td>Cliente</td><td>Portal Lander</td><td>Publicidade</td><td>Ativa</td></tr><tr><td>Despesas de software</td><td>Fornecedor</td><td>SaaS</td><td>Software</td><td>Ativa</td></tr></tbody></table></div></Panel></>}
</div></AdminShell>}
