import { CheckCircle2, ClipboardList, FileEdit, ListChecks, Megaphone, Search } from 'lucide-react'
import { useMemo, useState, type ReactNode } from 'react'
import { useParams } from 'react-router-dom'
import { CRM_NAV } from '../../shared/internal/adminNavigation'
import { AdminPageHeader, AdminShell } from '../../shared/internal/AdminUi'
import { TableViewPagination, type TablePageSize } from '../../shared/internal/TableViewPagination'
import { MarketingPage as LegacyMarketingPage } from './OperationsPage'

type Tone='neutral'|'success'|'warning'|'danger'|'accent'|'info'
const Badge=({children,tone='neutral'}:{children:ReactNode;tone?:Tone})=><span className={`zip-badge zip-badge-${tone}`}>{children}</span>
const Metric=({title,value,description,icon,tone='neutral'}:{title:string;value:string;description:string;icon:ReactNode;tone?:Tone})=><article className={`zip-metric zip-metric-${tone}`}><div className="zip-metric-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{description}</small></div></article>

function TableView({headers,rows}:{headers:string[];rows:ReactNode[][]}){
  const [page,setPage]=useState(1)
  const [pageSize,setPageSize]=useState<TablePageSize>(5)
  const totalPages=Math.max(1,Math.ceil(rows.length/pageSize));const safePage=Math.min(page,totalPages);const visible=rows.slice((safePage-1)*pageSize,safePage*pageSize)
  return <><div className="zip-table-wrap"><table className="zip-table"><thead><tr>{headers.map((header,index)=><th key={header} className={index===headers.length-1?'right':''}>{header}</th>)}</tr></thead><tbody>{visible.map((row,index)=><tr key={`${safePage}-${index}`}>{row.map((cell,cellIndex)=><td key={cellIndex} className={cellIndex===row.length-1?'right':''}>{cell}</td>)}</tr>)}</tbody></table></div><TableViewPagination page={safePage} totalPages={totalPages} totalRecords={rows.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={size=>{setPageSize(size);setPage(1)}}/></>
}

const campaignRows=[['Portal Lander Institucional','Meta + Google','Ativa','Aquisição','R$ 8.000','78%'],['Mídia Kit Comercial','Meta','Planejada','Anunciantes','R$ 5.400','42%'],['Festival Órbita','Instagram','Ativa','Cobertura','R$ 5.000','63%'],['Radar Funk','Instagram','Ativa','Audiência','R$ 3.200','69%'],['Lançamentos da Semana','Meta','Planejada','Tráfego','R$ 2.400','31%'],['Especial Bastidores','YouTube','Planejada','Visualização','R$ 4.100','18%'],['Portal Lander News','Google','Ativa','Aquisição','R$ 6.700','74%'],['Mídia Kit Setembro','Meta','Rascunho','Anunciantes','R$ 3.900','12%'],['Entrevistas Premium','Instagram','Ativa','Engajamento','R$ 2.800','81%'],['Cobertura Regional','Meta + Google','Planejada','Cobertura','R$ 7.200','27%']]
const briefingRows=[['Festival Órbita 2026','Cobertura e awareness','Público urbano 18–34','Aprovado','6'],['Mídia Kit Comercial','Captação de anunciantes','Marcas e agências','Em elaboração','4'],['Portal Lander Institucional','Fortalecimento de marca','Mercado da música','Rascunho','4'],['Radar Funk','Audiência recorrente','Fãs de funk','Aprovado','5'],['Bastidores Premium','Engajamento','Público editorial','Em elaboração','3'],['Newsletter Semanal','Retenção','Leitores recorrentes','Aprovado','4'],['Cobertura Regional','Autoridade','Produtores locais','Rascunho','6'],['Entrevistas Premium','Posicionamento','Artistas e equipes','Aprovado','5']]
const taskRows=[['Fechar mídia kit setembro','Comercial','Marketing','30/08','Em andamento'],['Revisar peças Festival Órbita','Criativo','Editorial','31/08','Revisão'],['Programar posts da semana','Conteúdo','Social','01/09','A fazer'],['Revisar campanha Radar Funk','Campanha','Marketing','01/09','A fazer'],['Montar pauta semanal','Editorial','Editorial','02/09','Em andamento'],['Validar criativos Meta','Criativo','Design','02/09','Revisão'],['Atualizar briefing institucional','Briefing','Marketing','03/09','A fazer'],['Fechar relatório mensal','Métricas','Marketing','04/09','A fazer'],['Organizar calendário setembro','Calendário','Social','05/09','Concluída'],['Revisar CTAs do mídia kit','Comercial','Marketing','05/09','Em andamento']]

function SearchableTablePage({kind}:{kind:'campaigns'|'briefing'|'tasks'}){
  const [query,setQuery]=useState('')
  const source=kind==='campaigns'?campaignRows:kind==='briefing'?briefingRows:taskRows
  const rows=useMemo(()=>source.filter(row=>!query||row.join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))),[query,source])
  const config=kind==='campaigns'?{eyebrow:'CRM / MARKETING / CAMPANHAS',title:'Campanhas',description:'Campanhas, canais, orçamento, status e desempenho.',headers:['Campanha','Canal','Status','Objetivo','Orçamento','Desempenho']} : kind==='briefing'?{eyebrow:'CRM / MARKETING / BRIEFING',title:'Briefing',description:'Estratégia, público, objetivos, mensagens e entregáveis.',headers:['Briefing','Objetivo','Público','Status','Entregáveis']}:{eyebrow:'CRM / MARKETING / TAREFAS',title:'Tarefas',description:'Prioridades, responsáveis, prazos e andamento operacional.',headers:['Tarefa','Tipo','Responsável','Prazo','Status']}
  const rendered=rows.map(row=>row.map((cell,index)=>index===0?<strong>{cell}</strong>:((kind==='campaigns'&&index===2)||(kind==='briefing'&&index===3)||(kind==='tasks'&&index===4))?<Badge tone={cell==='Ativa'||cell==='Aprovado'||cell==='Concluída'?'success':cell==='Revisão'?'danger':'warning'}>{cell}</Badge>:cell))
  return <AdminShell area="crm" items={CRM_NAV}><AdminPageHeader eyebrow={config.eyebrow} title={config.title} description={config.description}/><div className="zip-stack"><div className="zip-kpi-grid four"><Metric title="Registros" value={String(source.length)} description="na base" icon={kind==='campaigns'?<Megaphone size={18}/>:kind==='briefing'?<ClipboardList size={18}/>:<ListChecks size={18}/>} tone="accent"/><Metric title="Ativos" value={String(Math.max(1,Math.floor(source.length/2)))} description="em andamento" icon={<CheckCircle2 size={18}/>} tone="success"/><Metric title="Pendentes" value={String(Math.max(1,Math.ceil(source.length/3)))} description="aguardando ação" icon={<FileEdit size={18}/>} tone="warning"/><Metric title="Filtrados" value={String(rows.length)} description="resultado atual" icon={<Search size={18}/>} /></div><div className="zip-toolbar"><label className="zip-search"><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={`Buscar em ${config.title.toLocaleLowerCase('pt-BR')}…`}/></label></div><section className="zip-panel"><header className="zip-panel-head"><div><h2>{config.title}</h2><p>{rows.length} registros encontrados</p></div></header><TableView headers={config.headers} rows={rendered}/></section></div></AdminShell>
}

export function PaginatedMarketingPage(){const {sectionKey='visao-geral'}=useParams();if(sectionKey==='campanhas')return <SearchableTablePage kind="campaigns"/>;if(sectionKey==='briefing')return <SearchableTablePage kind="briefing"/>;if(sectionKey==='tarefas')return <SearchableTablePage kind="tasks"/>;return <LegacyMarketingPage/>}
