import {Clock,Search,X} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {AGENDA_ARTIST_RELATED_TYPES,AGENDA_CRM_LOCATION_TYPES,AGENDA_EVENT_TYPES,AGENDA_STATUS_OPTIONS} from '../constants'
import {dateISO,fromDateAndTime,timeHHMM} from '../date'
import type {AgendaEvent,AgendaEventDraft,AgendaLocation,AgendaParticipant,AgendaEventStatus} from '../domain'

type Props={open:boolean;mode:'create'|'edit';event?:AgendaEvent;participants:AgendaParticipant[];locations:AgendaLocation[];locationCatalogAvailable?:boolean;onClose:()=>void;onSave:(draft:AgendaEventDraft)=>void}
type FormState={title:string;type:string;status:AgendaEventStatus;participantIds:string[];startDate:string;startTime:string;endDate:string;endTime:string;location:string;locationId:string;address:string;venueContact:string;venuePhone:string;venueEmail:string;capacity:string;fee:string;expectedAudience:string;description:string;notes:string}
const emptyState=():FormState=>({title:'',type:'',status:'agendado',participantIds:[],startDate:dateISO(new Date()),startTime:'09:00',endDate:'',endTime:'',location:'',locationId:'',address:'',venueContact:'',venuePhone:'',venueEmail:'',capacity:'',fee:'',expectedAudience:'',description:'',notes:''})
const stateFromEvent=(event?:AgendaEvent):FormState=>{if(!event)return emptyState();const start=new Date(event.startsAt),end=event.endsAt?new Date(event.endsAt):null;return{title:event.title,type:event.type,status:event.status,participantIds:[...event.participantIds],startDate:dateISO(start),startTime:timeHHMM(start),endDate:end?dateISO(end):'',endTime:end?timeHHMM(end):'',location:event.location,locationId:event.locationId??'',address:event.address??'',venueContact:event.venueContact??'',venuePhone:event.venuePhone??'',venueEmail:event.venueEmail??'',capacity:event.capacity?.toString()??'',fee:event.fee?.toString()??'',expectedAudience:event.expectedAudience?.toString()??'',description:event.description,notes:event.notes}}
const numeric=(value:string)=>{if(!value.trim())return undefined;const number=Number(value);return Number.isFinite(number)?number:undefined}

export default function AgendaFormModal({open,mode,event,participants,locations,locationCatalogAvailable=true,onClose,onSave}:Props){
 const [form,setForm]=useState<FormState>(()=>stateFromEvent(event)),[errors,setErrors]=useState<Record<string,string>>({}),[participantOpen,setParticipantOpen]=useState(false),[participantSearch,setParticipantSearch]=useState('')
 useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[open,onClose])
 const filteredParticipants=useMemo(()=>participants.filter(item=>!participantSearch||`${item.label} ${item.category}`.toLowerCase().includes(participantSearch.toLowerCase())),[participants,participantSearch])
 const selectedSummary=form.participantIds.map(id=>participants.find(item=>item.id===id)?.label).filter(Boolean).join(', ')
 const isArtistRelated=AGENDA_ARTIST_RELATED_TYPES.has(form.type),showLocation=isArtistRelated||form.type==='reunioes',catalogLocationType=AGENDA_CRM_LOCATION_TYPES.has(form.type),useLocationCatalog=catalogLocationType&&locationCatalogAvailable,isShow=form.type==='shows'
 if(!open)return null
 const update=<K extends keyof FormState>(key:K,value:FormState[K])=>setForm(current=>({...current,[key]:value}))
 const selectLocation=(id:string)=>{const location=locations.find(item=>item.id===id);if(!location){update('locationId',id);return}setForm(current=>({...current,locationId:id,location:location.name,address:location.address,venueContact:location.contact,venuePhone:location.phone??''}))}
 const updateManualLocation=(key:'location'|'address'|'venueContact'|'venuePhone',value:string)=>setForm(current=>({...current,[key]:value,locationId:''}))
 const toggleParticipant=(id:string)=>update('participantIds',form.participantIds.includes(id)?form.participantIds.filter(item=>item!==id):[...form.participantIds,id])
 const submit=(e:React.FormEvent)=>{e.preventDefault();const nextErrors:Record<string,string>={};if(!form.title.trim())nextErrors.title='Título do evento é obrigatório';if(!form.type)nextErrors.type='Tipo de evento é obrigatório';if(!form.startDate)nextErrors.startDate='Data de início é obrigatória';setErrors(nextErrors);if(Object.keys(nextErrors).length)return;const startsAt=fromDateAndTime(form.startDate,form.startTime),endsAt=form.endDate?fromDateAndTime(form.endDate,form.endTime):undefined;if(!startsAt)return;onSave({title:form.title.trim(),type:form.type,status:form.status,participantIds:form.participantIds,startsAt,endsAt:endsAt||undefined,location:form.location,locationId:form.locationId||undefined,address:form.address||undefined,venueContact:form.venueContact||undefined,venuePhone:form.venuePhone||undefined,venueEmail:form.venueEmail||undefined,capacity:numeric(form.capacity),fee:numeric(form.fee),expectedAudience:numeric(form.expectedAudience),description:form.description,notes:form.notes,checklist:event?.checklist??[]})}
 return <div className="agenda-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="agenda-modal agenda-form-modal" role="dialog" aria-modal="true" aria-labelledby="agenda-form-title">
  <header><div><span>AGENDA</span><h2 id="agenda-form-title">{mode==='create'?'Novo Evento na Agenda':'Editar Evento'}</h2></div><button className="agenda-icon-button" type="button" onClick={onClose} aria-label="Fechar"><X size={17}/></button></header>
  <form onSubmit={submit}><div className="agenda-modal-body agenda-form-body">
   <section className="agenda-form-section"><h3>Dados do evento</h3><div className="agenda-form-grid two">
    <label className="agenda-field wide"><span>Título do Evento *</span><input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Digite o título do evento"/>{errors.title&&<small>{errors.title}</small>}</label>
    <label className="agenda-field"><span>Tipo de Evento *</span><select value={form.type} onChange={e=>update('type',e.target.value)}><option value="">Selecione o tipo</option>{AGENDA_EVENT_TYPES.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select>{errors.type&&<small>{errors.type}</small>}</label>
    <div className="agenda-field agenda-participant-field"><span>Participantes do Evento</span><button type="button" className="agenda-select-like" onClick={()=>setParticipantOpen(value=>!value)}><span className={selectedSummary?'':'muted'}>{selectedSummary||'Selecione participantes'}</span><span>⌄</span></button>{participantOpen&&<div className="agenda-participant-menu"><label><Search size={14}/><input value={participantSearch} onChange={e=>setParticipantSearch(e.target.value)} onKeyDown={e=>e.stopPropagation()} placeholder="Buscar artista ou funcionário…"/></label>{filteredParticipants.length===0?<p>Nenhum participante encontrado</p>:filteredParticipants.map(item=><button type="button" key={item.id} onClick={()=>toggleParticipant(item.id)} className={form.participantIds.includes(item.id)?'selected':''}><span className="agenda-checkmark">{form.participantIds.includes(item.id)?'✓':''}</span><span>{item.label}<small>{item.category}</small></span></button>)}</div>}</div>
    <label className="agenda-field"><span>Status</span><select value={form.status} onChange={e=>update('status',e.target.value as AgendaEventStatus)}>{AGENDA_STATUS_OPTIONS.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
   </div></section>
   <section className="agenda-form-section"><h3>Data e horário</h3><div className="agenda-form-grid two">
    <label className="agenda-field"><span>Data de Início *</span><input type="date" value={form.startDate} onChange={e=>update('startDate',e.target.value)}/>{errors.startDate&&<small>{errors.startDate}</small>}</label>
    <label className="agenda-field"><span>Horário de Início</span><div className="agenda-time-input"><Clock size={14}/><input type="time" value={form.startTime} onChange={e=>update('startTime',e.target.value)}/></div></label>
    <label className="agenda-field"><span>Data de Fim</span><input type="date" value={form.endDate} onChange={e=>update('endDate',e.target.value)}/></label>
    <label className="agenda-field"><span>Horário de Fim</span><div className="agenda-time-input"><Clock size={14}/><input type="time" value={form.endTime} onChange={e=>update('endTime',e.target.value)}/></div></label>
   </div></section>
   {showLocation&&<section className="agenda-form-section"><h3>Local</h3>{catalogLocationType&&!locationCatalogAvailable&&<p role="status">Catálogo de locais não configurado neste ambiente. Os dados do local serão registrados manualmente neste evento.</p>}<div className="agenda-form-grid two">
    <label className="agenda-field"><span>Nome do Local</span>{useLocationCatalog?<select value={form.locationId} onChange={e=>selectLocation(e.target.value)}><option value="">Selecione o local (CRM)</option>{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:<input value={form.location} onChange={e=>updateManualLocation('location',e.target.value)} placeholder={form.type==='reunioes'?'Nome do local da reunião':'Nome do venue / casa de show'}/>}</label>
    <label className="agenda-field"><span>Contato do Local</span><input value={form.venueContact} onChange={e=>useLocationCatalog?undefined:updateManualLocation('venueContact',e.target.value)} placeholder="Responsável no local" readOnly={useLocationCatalog}/></label>
    <label className="agenda-field"><span>Telefone do Local</span><input value={form.venuePhone} onChange={e=>useLocationCatalog?undefined:updateManualLocation('venuePhone',e.target.value)} placeholder="Telefone / WhatsApp" readOnly={useLocationCatalog}/></label>
    <label className="agenda-field wide"><span>Endereço Completo</span><input value={form.address} onChange={e=>useLocationCatalog?undefined:updateManualLocation('address',e.target.value)} placeholder="Endereço completo do local" readOnly={useLocationCatalog}/></label>
   </div></section>}
   {isShow&&<section className="agenda-form-section"><h3>Detalhes do show</h3><div className="agenda-form-grid three">
    <label className="agenda-field"><span>Capacidade do Público</span><input type="number" min="0" value={form.capacity} onChange={e=>update('capacity',e.target.value)} placeholder="Capacidade máxima do local"/></label>
    <label className="agenda-field"><span>Valor do Cachê</span><div className="agenda-money-input"><span>R$</span><input type="number" min="0" step="0.01" value={form.fee} onChange={e=>update('fee',e.target.value)} placeholder="0,00"/></div></label>
    <label className="agenda-field"><span>Público Esperado</span><input type="number" min="0" value={form.expectedAudience} onChange={e=>update('expectedAudience',e.target.value)} placeholder="Quantidade de pessoas esperadas"/></label>
   </div></section>}
   <section className="agenda-form-section"><h3>Informações complementares</h3><div className="agenda-form-grid two"><label className="agenda-field"><span>Descrição</span><textarea rows={4} value={form.description} onChange={e=>update('description',e.target.value)} placeholder="Descrição do evento"/></label><label className="agenda-field"><span>Observações</span><textarea rows={4} value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Observações sobre o evento"/></label></div></section>
  </div><footer><button className="button outline" type="button" onClick={onClose}>Cancelar</button><button className="button dark" type="submit">Salvar Evento</button></footer></form>
 </section></div>
}
