import { Routes, Route, Navigate, NavLink, Link } from 'react-router-dom'
import { ArrowRight, Bell, BriefcaseBusiness, Building2, CalendarDays, ChevronDown, CircleDollarSign, FileText, Gauge, Globe2, Images, LayoutDashboard, Menu, Newspaper, Search, Settings, Sparkles, Tags, Users, WandSparkles, X } from 'lucide-react'
import { useState } from 'react'

const stories = [
  { category: 'Música', title: 'Novos sons, novas histórias e a cultura que movimenta a cena', excerpt: 'Curadoria editorial com lançamentos, entrevistas e bastidores em uma experiência direta e visual.', meta: '6 min de leitura' },
  { category: 'Entrevistas', title: 'Conversas com quem está construindo o próximo capítulo da música', excerpt: 'Artistas, produtores e criadores falando de processo, carreira e visão de futuro.', meta: '12 min de leitura' },
  { category: 'Mercado', title: 'O que muda quando conteúdo, comunidade e negócio passam a operar juntos', excerpt: 'Uma leitura prática sobre mídia, audiência e novas formas de criar valor.', meta: '8 min de leitura' },
]

const contacts = [
  { name: 'Marina Costa', company: 'Norte Produções', status: 'Lead', owner: 'Comercial', value: 'R$ 18.000' },
  { name: 'Rafael Alves', company: 'Estúdio Horizonte', status: 'Cliente', owner: 'Deyvisson', value: 'R$ 32.500' },
  { name: 'Camila Rocha', company: 'Aurora Music', status: 'Negociação', owner: 'Comercial', value: 'R$ 24.000' },
  { name: 'Bruno Lima', company: 'BL Eventos', status: 'Contato', owner: 'Equipe', value: 'R$ 7.500' },
]

const contentRows = [
  { title: 'A nova fase da cena independente', type: 'Notícia', status: 'Publicado', updated: 'Hoje, 14:32' },
  { title: 'Entrevista: criação sem fórmula', type: 'Entrevista', status: 'Em revisão', updated: 'Hoje, 11:18' },
  { title: 'Radar de lançamentos — Agosto', type: 'Lançamento', status: 'Rascunho', updated: 'Ontem, 19:41' },
  { title: 'Mercado e audiência em 2026', type: 'Artigo', status: 'Agendado', updated: 'Ontem, 16:08' },
]

function Brand({ compact = false }: { compact?: boolean }) {
  return <Link to="/" className="brand"><span className="brand-mark">L</span>{!compact && <span>PORTAL <b>LANDER</b></span>}</Link>
}

function PublicHeader() {
  const [open, setOpen] = useState(false)
  return <header className="public-header"><div className="public-nav shell"><Brand/><nav className={open ? 'public-links open' : 'public-links'}><NavLink to="/noticias">Notícias</NavLink><a href="#cultura">Cultura</a><a href="#lancamentos">Lançamentos</a><a href="#entrevistas">Entrevistas</a><NavLink to="/colabore">Colabore</NavLink></nav><div className="nav-actions"><button className="icon-button" aria-label="Buscar"><Search size={18}/></button><Link className="button ghost" to="/app">Área interna</Link><button className="icon-button menu-button" onClick={()=>setOpen(!open)} aria-label="Abrir menu">{open?<X/>:<Menu/>}</button></div></div></header>
}

function Home() {
  return <div className="public-page"><PublicHeader/><main><section className="hero shell"><div className="eyebrow"><Sparkles size={15}/> Conteúdo, cultura e movimento</div><h1>Histórias que<br/>movem a <em>cena.</em></h1><p>O Portal Lander conecta música, cultura, entretenimento e mercado com curadoria editorial e linguagem própria.</p><div className="hero-actions"><Link className="button primary" to="/noticias">Explorar conteúdo <ArrowRight size={17}/></Link><a className="text-link" href="#destaques">Ver destaques</a></div><div className="hero-visual" aria-hidden="true"><div className="orb orb-one"/><div className="orb orb-two"/><span>PL</span></div></section><section id="destaques" className="editorial-section shell"><div className="section-heading"><div><span className="kicker">Em destaque</span><h2>Agora no Portal</h2></div><Link to="/noticias" className="text-link">Ver tudo <ArrowRight size={15}/></Link></div><div className="story-grid">{stories.map((story,i)=><article className={i===0?'story-card featured':'story-card'} key={story.title}><div className="story-art"><span>0{i+1}</span></div><div className="story-copy"><span className="category">{story.category}</span><h3>{story.title}</h3><p>{story.excerpt}</p><small>{story.meta}</small></div></article>)}</div></section><section className="manifesto"><div className="shell manifesto-inner"><span className="kicker">Portal Lander</span><h2>Mais do que publicar.<br/>Criar contexto.</h2><p>Uma plataforma editorial construída para reunir conteúdo, presença digital e oportunidades em um mesmo ecossistema.</p></div></section></main><footer className="public-footer"><div className="shell footer-grid"><Brand/><p>Conteúdo, música, cultura e mídia.</p><span>© 2026 Portal Lander</span></div></footer></div>
}

function Noticias() { return <div className="public-page"><PublicHeader/><main className="shell listing-page"><span className="kicker">Editorial</span><h1>Notícias</h1><p className="page-lead">Atualizações, histórias e movimentos que merecem contexto.</p><div className="filter-row"><button className="chip active">Todos</button><button className="chip">Música</button><button className="chip">Cultura</button><button className="chip">Mercado</button></div><div className="news-list">{[...stories,...stories].map((s,i)=><article key={i} className="news-row"><div className="news-index">{String(i+1).padStart(2,'0')}</div><div><span className="category">{s.category}</span><h2>{s.title}</h2><p>{s.excerpt}</p></div><ArrowRight/></article>)}</div></main></div> }

function Colabore() { return <div className="public-page"><PublicHeader/><main className="shell form-page"><div className="form-intro"><span className="kicker">Colabore</span><h1>Tem uma história que deveria estar aqui?</h1><p>Envie pautas, lançamentos, projetos e sugestões para nossa equipe editorial.</p></div><form className="public-form" onSubmit={e=>e.preventDefault()}><label>Nome<input placeholder="Seu nome"/></label><label>Email<input type="email" placeholder="voce@email.com"/></label><label>Tipo<select defaultValue=""><option value="" disabled>Selecione</option><option>Pauta</option><option>Lançamento</option><option>Evento</option><option>Outro</option></select></label><label>Título<input placeholder="Resumo da sugestão"/></label><label className="full">Descrição<textarea rows={6} placeholder="Conte os detalhes..."/></label><div className="form-note full">Frontend de demonstração — envio definitivo será conectado ao backend posteriormente.</div><button className="button primary" type="submit">Preparar envio <ArrowRight size={17}/></button></form></main></div> }

const crmNav = [['Visão geral',LayoutDashboard,'/app/crm'],['Contatos',Users,'/app/crm/contatos'],['Pipeline',BriefcaseBusiness,'/app/crm/pipeline'],['Atividades',CalendarDays,'/app/crm/atividades'],['Financeiro',CircleDollarSign,'/app/crm/financeiro']] as const
const cmsNav = [['Visão geral',LayoutDashboard,'/app/site'],['Conteúdos',FileText,'/app/site/conteudos'],['Páginas',Globe2,'/app/site/paginas'],['Mídia',Images,'/app/site/midia'],['Categorias',Tags,'/app/site/categorias'],['Mídia Kit',Newspaper,'/app/site/midia-kit'],['Configurações',Settings,'/app/site/configuracoes']] as const

function AppShell({area,children}:{area:'crm'|'cms',children:React.ReactNode}) { const items=area==='crm'?crmNav:cmsNav; return <div className="app-shell"><aside className="sidebar"><div className="sidebar-head"><Brand compact/><span>{area==='crm'?'CRM':'SITE'}</span></div><nav>{items.map(([label,Icon,to])=><NavLink key={to} end={to==='/app/crm'||to==='/app/site'} to={to}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/app"><Building2 size={18}/><span>Trocar workspace</span></NavLink></div></aside><div className="workspace"><header className="workspace-top"><div><span className="workspace-name">Portal Lander</span><span className="workspace-context">{area==='crm'?'CRM':'Gerenciador do Site'}</span></div><div className="workspace-actions"><button className="icon-button"><Bell size={18}/></button><button className="account-button"><span>DL</span><div><b>Deyvisson</b><small>Administrador</small></div><ChevronDown size={15}/></button></div></header><main className="workspace-main">{children}</main></div></div> }

function WorkspaceHome() { return <div className="workspace-picker"><div className="picker-copy"><span className="kicker">Portal Lander</span><h1>Escolha onde trabalhar</h1><p>O frontend interno é dividido em áreas claras para evitar misturar operação comercial com gerenciamento editorial.</p></div><div className="workspace-cards"><Link to="/app/crm" className="workspace-card"><div className="workspace-icon"><BriefcaseBusiness/></div><span>Operação</span><h2>CRM</h2><p>Contatos, oportunidades, atividades e visão financeira.</p><ArrowRight/></Link><Link to="/app/site" className="workspace-card"><div className="workspace-icon"><WandSparkles/></div><span>Conteúdo</span><h2>Gerenciador do Site</h2><p>Conteúdos, páginas, mídia, SEO e configurações do portal.</p><ArrowRight/></Link></div><Link className="back-site" to="/">← Voltar ao site público</Link></div> }

function PageHeader({eyebrow,title,action}:{eyebrow:string,title:string,action?:string}) { return <div className="page-header"><div><span>{eyebrow}</span><h1>{title}</h1></div>{action&&<button className="button dark">{action}</button>}</div> }
function Metric({label,value,detail}:{label:string,value:string,detail:string}) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }

function CrmDashboard() { return <AppShell area="crm"><PageHeader eyebrow="CRM" title="Visão geral" action="Novo contato"/><div className="metrics-grid"><Metric label="Contatos" value="248" detail="+18 este mês"/><Metric label="Leads" value="42" detail="12 qualificados"/><Metric label="Clientes" value="31" detail="5 ativos agora"/><Metric label="Receitas" value="R$ 84,2k" detail="Este mês"/><Metric label="Despesas" value="R$ 26,8k" detail="Este mês"/><Metric label="Resultado" value="R$ 57,4k" detail="Margem operacional"/></div><div className="panel-grid"><section className="panel"><div className="panel-head"><div><span>Pipeline</span><h2>Oportunidades recentes</h2></div><button className="text-button">Ver pipeline</button></div>{contacts.slice(0,3).map(c=><div className="compact-row" key={c.name}><div className="avatar">{c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="grow"><b>{c.company}</b><small>{c.name}</small></div><span className="status">{c.status}</span><strong>{c.value}</strong></div>)}</section><section className="panel"><div className="panel-head"><div><span>Hoje</span><h2>Próximas atividades</h2></div></div>{['Retornar proposta — Aurora Music','Reunião — Norte Produções','Follow-up — BL Eventos'].map((x,i)=><div className="activity-row" key={x}><span>{['10:30','14:00','16:15'][i]}</span><div><b>{x}</b><small>{['Ligação','Reunião','WhatsApp'][i]}</small></div></div>)}</section></div></AppShell> }

function Contacts() { return <AppShell area="crm"><PageHeader eyebrow="CRM / Contatos" title="Contatos" action="Novo contato"/><div className="toolbar"><div className="searchbox"><Search size={17}/><input placeholder="Buscar contatos..."/></div><button className="button outline">Filtros</button></div><section className="table-card"><table><thead><tr><th>Contato</th><th>Empresa</th><th>Status</th><th>Responsável</th><th>Valor relacionado</th></tr></thead><tbody>{contacts.map(c=><tr key={c.name}><td><b>{c.name}</b></td><td>{c.company}</td><td><span className="status">{c.status}</span></td><td>{c.owner}</td><td><strong>{c.value}</strong></td></tr>)}</tbody></table></section></AppShell> }

function CmsDashboard() { return <AppShell area="cms"><PageHeader eyebrow="Gerenciador do Site" title="Visão geral" action="Novo conteúdo"/><div className="metrics-grid four"><Metric label="Publicados" value="126" detail="Conteúdos ativos"/><Metric label="Rascunhos" value="14" detail="Aguardando edição"/><Metric label="Em revisão" value="7" detail="Precisam de atenção"/><Metric label="Agendados" value="5" detail="Próximas publicações"/></div><section className="panel"><div className="panel-head"><div><span>Conteúdo</span><h2>Atualizações recentes</h2></div><Link to="/app/site/conteudos" className="text-button">Ver todos</Link></div>{contentRows.map(r=><div className="content-row" key={r.title}><div className="content-icon"><FileText size={17}/></div><div className="grow"><b>{r.title}</b><small>{r.type} · {r.updated}</small></div><span className="status">{r.status}</span><button className="icon-button">•••</button></div>)}</section></AppShell> }

function Contents() { return <AppShell area="cms"><PageHeader eyebrow="Gerenciador do Site / Conteúdos" title="Conteúdos" action="Novo conteúdo"/><div className="toolbar"><div className="searchbox"><Search size={17}/><input placeholder="Buscar conteúdos..."/></div><div className="tabbar"><button className="active">Todos</button><button>Publicados</button><button>Rascunhos</button><button>Em revisão</button></div></div><section className="table-card"><table><thead><tr><th>Título</th><th>Tipo</th><th>Status</th><th>Atualizado</th></tr></thead><tbody>{contentRows.map(r=><tr key={r.title}><td><b>{r.title}</b></td><td>{r.type}</td><td><span className="status">{r.status}</span></td><td>{r.updated}</td></tr>)}</tbody></table></section></AppShell> }

function Placeholder({area,title}:{area:'crm'|'cms',title:string}) { return <AppShell area={area}><PageHeader eyebrow={area==='crm'?'CRM':'Gerenciador do Site'} title={title}/><div className="empty-state"><div><Gauge/></div><h2>Estrutura preparada</h2><p>Este módulo entra na próxima etapa de implementação do frontend. A navegação e a arquitetura já estão reservadas sem fingir funcionalidade inexistente.</p></div></AppShell> }
function NotFound() { return <div className="not-found"><Brand/><span>404</span><h1>Página não encontrada</h1><Link className="button primary" to="/">Voltar ao início</Link></div> }

export default function App() { return <Routes><Route path="/" element={<Home/>}/><Route path="/noticias" element={<Noticias/>}/><Route path="/colabore" element={<Colabore/>}/><Route path="/app" element={<WorkspaceHome/>}/><Route path="/app/crm" element={<CrmDashboard/>}/><Route path="/app/crm/contatos" element={<Contacts/>}/><Route path="/app/crm/pipeline" element={<Placeholder area="crm" title="Pipeline comercial"/>}/><Route path="/app/crm/atividades" element={<Placeholder area="crm" title="Atividades"/>}/><Route path="/app/crm/financeiro" element={<Placeholder area="crm" title="Financeiro"/>}/><Route path="/app/site" element={<CmsDashboard/>}/><Route path="/app/site/conteudos" element={<Contents/>}/>{['paginas','midia','categorias','midia-kit','configuracoes'].map(p=><Route key={p} path={`/app/site/${p}`} element={<Placeholder area="cms" title={({paginas:'Páginas',midia:'Media Manager',categorias:'Categorias','midia-kit':'Mídia Kit',configuracoes:'Configurações'} as Record<string,string>)[p]}/>}/>)}<Route path="/home" element={<Navigate to="/" replace/>}/><Route path="*" element={<NotFound/>}/></Routes> }
