import {ExternalLink,RefreshCw} from 'lucide-react'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {listAdminEditorialPages} from '../../editorial/adminClient'
import type {EditorialPage} from '../../editorial/model'
import {contentIngestionClient,type ImportCandidate} from '../../editorial/contentIngestionClient'
import {AdminNotice} from '../../../shared/internal/AdminUi'

export function ImportCandidatesPanel({enabled}:{enabled:boolean}){
 const [candidates,setCandidates]=useState<ImportCandidate[]>([]),[pages,setPages]=useState<EditorialPage[]>([]),[destinationByCandidate,setDestinationByCandidate]=useState<Record<string,string>>({}),[busy,setBusy]=useState(''),[error,setError]=useState('')
 const reconcileDestinations=useCallback((candidateRows:ImportCandidate[],editorial:EditorialPage[])=>setDestinationByCandidate(current=>Object.fromEntries(Object.entries(current).filter(([candidateId,pageId])=>candidateRows.some(candidate=>candidate.id===candidateId&&candidate.status==='approved')&&editorial.some(page=>page.id===pageId)))),[])
 const load=async()=>{if(!enabled)return;setError('');try{const [candidateRows,pageRows]=await Promise.all([contentIngestionClient.listCandidates({limit:100}),listAdminEditorialPages()]);setCandidates(candidateRows);const editorial=pageRows.filter(page=>page.type==='editorial');setPages(editorial);reconcileDestinations(candidateRows,editorial)}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível carregar candidatos editoriais.')}}
 useEffect(()=>{if(!enabled)return;let active=true;void Promise.all([contentIngestionClient.listCandidates({limit:100}),listAdminEditorialPages()]).then(([candidateRows,pageRows])=>{if(!active)return;setCandidates(candidateRows);const editorial=pageRows.filter(page=>page.type==='editorial');setPages(editorial);reconcileDestinations(candidateRows,editorial)}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:'Não foi possível carregar candidatos editoriais.')});return()=>{active=false}},[enabled,reconcileDestinations])
 const pending=useMemo(()=>candidates.filter(item=>!['rejected','ignored'].includes(item.status)),[candidates])
 const clearDestination=(candidateId:string)=>setDestinationByCandidate(current=>{const next={...current};delete next[candidateId];return next})
 const action=async(candidate:ImportCandidate,kind:'review'|'approve'|'reject'|'ignore'|'convert')=>{setBusy(`${candidate.id}:${kind}`);setError('');try{if(kind==='review')await contentIngestionClient.reviewCandidate(candidate.id);else if(kind==='approve')await contentIngestionClient.approveCandidate(candidate.id);else if(kind==='reject')await contentIngestionClient.rejectCandidate(candidate.id);else if(kind==='ignore')await contentIngestionClient.ignoreCandidate(candidate.id);else{const pageId=destinationByCandidate[candidate.id]||'';if(!pageId)throw new Error('Selecione uma página editorial de destino.');await contentIngestionClient.convertCandidate(candidate.id,pageId)}clearDestination(candidate.id);await load()}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível concluir a curadoria.')}finally{setBusy('')}}
 if(!enabled)return <AdminNotice title="Candidatos editoriais" description="A curadoria de fontes externas usa somente o caminho autenticado da API. No modo local de desenvolvimento ela permanece desativada para não simular produção."/>
 return <section aria-label="Candidatos editoriais">
  <div className="admin-toolbar"><div className="admin-toolbar-group"><button type="button" className="button outline" onClick={()=>void load()}><RefreshCw size={15}/>Atualizar candidatos</button></div></div>
  <AdminNotice title="Curadoria editorial" description="Itens externos são referências de pauta. Aprovar não publica: a conversão cria somente um rascunho no CMS, sem importar automaticamente imagens de terceiros. Cada candidato exige sua própria escolha explícita de página editorial de destino antes da conversão."/>
  {error&&<AdminNotice title="Falha na curadoria" description={error}/>} 
  <div className="tableview-surface cms-tableview-surface"><section className="table-card"><table><thead><tr><th>Candidato</th><th>Fonte</th><th>Categoria</th><th>Relevância</th><th>Status</th><th>Data</th><th>Ações</th></tr></thead><tbody>{pending.map(candidate=><tr key={candidate.id}><td><div className="table-primary"><div><b>{candidate.title}</b><small>{candidate.description||'Sem snippet disponível'}</small></div></div></td><td><div><b>{candidate.sourceName}</b><small>{candidate.provider}</small></div></td><td>{candidate.suggestedCategory||'—'}</td><td>{candidate.relevanceScore}/100</td><td><span className={`status ${candidate.status}`}>{candidate.status}</span></td><td>{candidate.publishedAt?new Date(candidate.publishedAt).toLocaleDateString('pt-BR'):'—'}</td><td><div className="admin-toolbar-group"><a className="button outline" href={candidate.canonicalUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>Fonte</a>{candidate.status==='new'&&<button type="button" className="button outline" disabled={Boolean(busy)} onClick={()=>void action(candidate,'review')}>Revisar</button>}{['new','reviewing','rejected'].includes(candidate.status)&&<button type="button" className="button" disabled={Boolean(busy)} onClick={()=>void action(candidate,'approve')}>Aprovar</button>}{['new','reviewing','approved'].includes(candidate.status)&&<button type="button" className="button outline" disabled={Boolean(busy)} onClick={()=>void action(candidate,'reject')}>Rejeitar</button>}{candidate.status!=='converted'&&<button type="button" className="button outline" disabled={Boolean(busy)} onClick={()=>void action(candidate,'ignore')}>Ignorar</button>}{candidate.status==='approved'&&<><label><span className="sr-only">Página de destino do rascunho para {candidate.title}</span><select aria-label={`Página de destino do rascunho para ${candidate.title}`} value={destinationByCandidate[candidate.id]||''} onChange={e=>setDestinationByCandidate(current=>({...current,[candidate.id]:e.target.value}))}><option value="">Selecione a página de destino</option>{pages.map(page=><option key={page.id} value={page.id}>{page.title}</option>)}</select></label><button type="button" className="button" disabled={!destinationByCandidate[candidate.id]||Boolean(busy)} onClick={()=>void action(candidate,'convert')}>Criar rascunho</button></>}{candidate.status==='converted'&&candidate.editorialContentId&&<a className="button" href={`#/app/site/conteudos/${candidate.editorialContentId}`}>Abrir rascunho</a>}</div></td></tr>)}</tbody></table>{!pending.length&&<p className="empty-state">Nenhum candidato pendente de curadoria.</p>}</section></div>
 </section>
}
